### ISSUE TITLE
SPIKE, As a Researcher, I want to evaluate "Please allow up to an hour to complete this form. This session cannot be saved.", so that we know if it's understandable.

### ISSUE THREAD

**Issue by lisamcmichael** [USDAForestService/fs-open-forest-platform#1003]
## Notes

- Will applicants know what a "session" means? 
- Should "form" be replaced with "application"?
- Would applicants like a friendlier message?
- I'm proposing a "test" of different variations of _"Please allow up to an hour to complete this form. This session cannot be saved_." with up to 10 employees at TechTrend, possibly some of our team as well. 

**See #532** 

## Acceptance Criteria
- [x] PO reviews/approves research approach 

## Tasks
- [x] Create research methodology/approach
- [x] Mock up instruction variations
- [x] Review with UX design lead/Lisa
- [x] Review w/ PO
- [x] PO approves, modifies or declines the research

## Definition of Done
- [x] Test is either launched or put on hold/canceled

**Comment by lisamcmichael** [comment]
![Variations 1003](https://user-images.githubusercontent.com/52501060/68034278-c660ba80-fc97-11e9-96a3-35fcad59ce2b.jpg)

**Comment by lisamcmichael** [comment]
@lisaredux Take a look at the variations on the instructions. Let me know what you think. I have time later to meet and discuss, after standup. Also, the approach is to setup a "survey" with these options, and test them w/ TechTrend employees, to see which one is most understandable.

**Comment by lisaredux** [comment]
Thanks @lisamcmichael — looks good. As far as the variations, my first thought is that A or B are better for brevity. 

Also, something to note about this form is that Login.gov won't time them out, I believe. So they could possibly come back to it if they leave if they don't sign out or close their browser. Something to confirm with DEV, but I think with well-crafted verbiage, we can create that space between setting up expectations with caution so that the applicant doesn't go into panic-mode, ideally.

**Comment by lisamcmichael** [comment]
@lisaredux this is good food for thought and helped me think of yet another variation:
4th option:
**Please give yourself up to an hour to complete the application. And, it will not be saved until it's submitted.**

**Comment by lisamcmichael** [comment]
_Another set to consider (made small changes here and there). Added a 4th message._
![Variations 1003](https://user-images.githubusercontent.com/52501060/68042498-6bd05a00-fca9-11e9-8aba-2e15e9955612.jpg)

**Comment by lisamcmichael** [comment]
@ASprinkle and @lisaredux I'm proposing a "test" of different variations of __"Please allow up to an hour to complete this form. This session cannot be saved."_ with up to 10 employees at TechTrend and/or w/in our team members. Joe's comment didn't surprise me; so, it was somewhat the incentive to create additional approaches.

**https://ows.io/qs/5pn4x34v**

**Comment by ASprinkle** [comment]
Thanks @lisamcmichael I provided some suggestions as well...
https://6x8hlxq8.optimalworkshop.com/questions/uy6e0333-0

**Comment by lisamcmichael** [comment]
Hi, @ASprinkle and @lisaredux _I've updated the messaging options, and enhanced the "getting started" section:_

**Getting started...**
Imagine you're applying for a Special Use permit. In addition to taking about an hour to complete the application, you'll need to have several documents on hand. Also, at this time you cannot save your application and come back to finish it later.

To make the experience better for you, we will include one of these messages, we're just not sure which one to include. That's where your help comes in! Take a look at these 4 messages, then pick one that makes the most sense to you (A, B, C or D), and tell us which one you picked and why in the comment box (see below).

Should you decide you prefer part of one message and part of another message, that's okay! Please share that with us by writing it in the comment box below.

Message A: Please allow up to an hour to complete the application. The information you enter cannot be saved to be completed later.

Message B: Please allow up to an hour to complete the application. Have all of your required documents ready. This application cannot be saved until it is submitted.

Message C: We suggest giving yourself up to an hour to complete the application. The information you enter cannot be saved and completed later. Plan to have all your required documents ready, and finish in one session.

Message D: Please give yourself up to an hour to complete the application. The information you enter will not be saved until it's submitted.

**Comment by ASprinkle** [comment]
@lisamcmichael looks good to me. Let's ID who we're going to sample this with and launch it. I see our meeting for this morning for a touch base, awesome!

**Comment by lisamcmichael** [comment]
going to Mt Hood, MBS and Jon

**Comment by lisamcmichael** [comment]
Sending Amber a link to the survey

- launched survey
- amber sending it out to a select set of participants, including Jon

**Comment by lisamcmichael** [comment]
@ASprinkle _Here is the link to the Survey_

**https://ows.io/qs/c142v8nt**

**Comment by lisamcmichael** [comment]
@ASprinkle We have **2 responses to the survey** so far. When we meet, we can go over those.

**Comment by ASprinkle** [comment]
ok, thanks. one of those was mine... not to be a skew but i tested it before sending. I commented "keep it short and sweet" :)

**Comment by lisamcmichael** [comment]
@ASprinkle How many survey invitations did you send out? Thx.

**Comment by ASprinkle** [comment]
@lisamcmichael I sent the invite to 6 individuals.

**Comment by lisamcmichael** [comment]
@ASprinkle I created a duplicate of our survey, and shared it w/ Dylan, Rebekah and Eric. It will be interesting  to see how their responses compare/contrast to actual Open Forest personnel. I'll put a meeting on our calendar for tomorrow to 'sync up' and review.
