### ISSUE TITLE
As a public user, I would like to see the give feedback link displayed correctly on mobile

### ISSUE THREAD

**Issue by mtlaney** [USDAForestService/fs-open-forest-platform#1004]
## Notes
* Currently the give feedback button has some overlapping on mobile displays *

## Acceptance Criteria
- [x] Give Feedback Link displays correctly on mobile

## Tasks
- [x] Update CSS to fix display issues
- [x] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by lisaredux** [comment]
@mtlaney — let me know if I can help with some CSS troubleshooting on this

**Comment by mtlaney** [comment]
@lisaredux Thanks Lisa, I should have it corrected now on staging, but if you see anything please let me know~!

**Comment by ASprinkle** [comment]
This looks great for mobile!!
![image](https://user-images.githubusercontent.com/33435621/68054082-bef6dc80-fcaa-11e9-8345-4eb55bdc6231.png)
![image](https://user-images.githubusercontent.com/33435621/68054088-c5855400-fcaa-11e9-9bc3-62a810075fff.png)
