### ISSUE TITLE
As an Oka-Wen Admin I would like to have the English and Spanish info brochures updated for 2019, so that people have the most updated info.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1006]
## Notes
* What are things we should consider when making this story *

There is currently 2018 information brochures on the Okan-Wen page under contact us.
The Forest recently sent 2019 brochure information, and anticipated the link for the brochures to take the user back to the FS website.
![image.png](https://images.zenhubusercontent.com/5a00e34b8a75884b90864b6f/1f25bf75-afe8-489b-8d87-e4e0af800bee)

## Acceptance Criteria
- [ ] people are informed that there is a downloadable Christmas tree info brochure for this forest.
- [x] By hyperlinking to the Oka-Wen page, the Open Forest team doesn't have to ensure updated documents/info each year.

## Tasks
- [x] Remove the PDF links for Enlish and Spanish brochures, and provide a hyperlink that takes the user to the Oka-Wen FS website.
- [x] Change the text to read: "Downloadable versions of Christmas tree cutting information in English or Spanish are also available by clicking here." and make "clicking here" a hyper link to: https://www.fs.usda.gov/detail/okawen/passes-permits/?cid=fsbdev3_053596
- [x] PO approved

## Definition of Done
- [x] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
This looks like it's working in staging...
![image](https://user-images.githubusercontent.com/33435621/68046113-4dae2e00-fc98-11e9-8f65-d9280c3e759b.png)
![image](https://user-images.githubusercontent.com/33435621/68046120-50a91e80-fc98-11e9-9ff2-10ad4e15ffe6.png)
