### ISSUE TITLE
As an Oka-Wen tree cutter I want to be informed that I can dig up my tree so that I know what's allowed.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1011]
## Notes
* What are things we should consider when making this story *

Add information about being able to dig up a tree.

## Acceptance Criteria
- [x] Christmas tree transplant information is specified in the How to Cut your tree section.
- [x] Rules are updated to reflect transplanting a Christmas tree.

## Tasks
- [x] Underneath the tree topping prohibited text/icon, insert the following text: "Your tree may be cut, or dug up and removed as a transplant. The ground can start freezing in early November. Remember to fill in the hole created when digging up a live tree."
- [x] Add to the Rules and Guidelines: "If you dug up your tree, fill in the hole that was created when digging it up."
- [x] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
![image](https://user-images.githubusercontent.com/33435621/68161178-23fc3d80-ff0a-11e9-85ff-7e221c7fd3d2.png)
![image](https://user-images.githubusercontent.com/33435621/68161181-265e9780-ff0a-11e9-94a2-b8636776d069.png)
