### ISSUE TITLE
As a Christmas tree user I want to be informed about having to print my permit before I enter my info so that I know what's expected.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1016]
## Notes
* What are things we should consider when making this story *
![PrintPermitPaymentPhasetext.png](https://images.zenhubusercontent.com/5a00e34b8a75884b90864b6f/0d9746f6-1e1c-4a88-a695-06bf7b2702f1)

## Acceptance Criteria
- [x] The text is added to the Buy a Christmas tree permit page (at the beginning of the "payment" phase)

## Tasks
- [x] Below the information about Christmas tree permit cost, and before Permit Holder Information add the following in **bold** text: "Your permit must be printed to be valid and cannot be stored on a mobile device.
- [x] PO approved

## Definition of Done
- [x] Pull requests meet technical definition of done
- [x] Compare finished design with mockup

**Comment by carlsonem** [comment]
Need to make this change to every forest page

**Comment by ASprinkle** [comment]
@mtlaney I checked this afternoon, and i don't see it updated in staging yet.

**Comment by ASprinkle** [comment]
![image](https://user-images.githubusercontent.com/33435621/68771169-511cb000-05dc-11ea-935b-fd866aa8a253.png)
looks good to me!
