### ISSUE TITLE
As a Fre-Win admin i would like to see the stump height and diameter updated so that tree cutters do the right thing.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1017]
## Notes
* What are things we should consider when making this story *

I received this message from our POC on the Fre-Win: "So sorry to ask….but an error was pointed out to me and I don’t know if we can correct it now or not.......We have a 15 foot with a 6” diameter base, not stump height…the stump height is less than 12”….

## Acceptance Criteria
- [x] Stump height is shown as 12 inches maximum
- [x] Stump diameter shows as 6 inches maximum

## Tasks
- [x] Update the How to Cut Your Tree section: Stump Height: 12 inches maximum
- [x]  Update the How to Cut your Tree section: Stump Diameter: 6 inches maximum
- [x] Update the Rules and Guidelines section to reflect the 12 inch max stump height, and 6 inch max stump diameter
- [x]  Update the printed permit to to reflect the 12 inch max stump height, and 6 inch max stump diameter
- [x] PO approved

## Definition of Done
- [x] Pull requests meet technical definition of done
- [x] A/C and Tasks are completed.

**Comment by ASprinkle** [comment]
The printed permit looks great!
Can we add the stump diameter icon and 6 inch max to the How to cut your tree section, and also update the rules and guidelines with the stump diameter info?
![image](https://user-images.githubusercontent.com/33435621/68234667-90347b00-ffb6-11e9-90da-aa49e69f018c.png)

![image](https://user-images.githubusercontent.com/33435621/68234792-e3a6c900-ffb6-11e9-8fd3-a7b6b2d2b6f7.png)

![image](https://user-images.githubusercontent.com/33435621/68234841-fae5b680-ffb6-11e9-899e-274851a77905.png)

**Comment by ASprinkle** [comment]
![image](https://user-images.githubusercontent.com/33435621/68247682-30e36480-ffd0-11e9-8677-0aceb4ea4e09.png)
![image](https://user-images.githubusercontent.com/33435621/68247689-33de5500-ffd0-11e9-9989-8c79e09b1f10.png)
![image](https://user-images.githubusercontent.com/33435621/68247693-3640af00-ffd0-11e9-9a9a-347fdecabcf3.png)
