### ISSUE TITLE
As an Open Forest User, I'd like to be able to input my email address with upper-case characters

### ISSUE THREAD

**Issue by Dmac26** [USDAForestService/fs-open-forest-platform#1019]
## Notes
A customer emailed the support team stating that they were unable to buy a permit because the email address field in the "buy permit" section was telling them they had an invalid address. Upon further investigation it was determined that the customer was using upper-case letters in their address. When we input the address with lower-case letters, everything functioned as normal.

![image](https://user-images.githubusercontent.com/33435621/68224040-c405a580-ffa2-11e9-83a8-e282e2c6b74e.png)

![image](https://user-images.githubusercontent.com/33435621/68224181-f9aa8e80-ffa2-11e9-89de-0e9982dc31d2.png)

## Acceptance Criteria
- [x] User can enter their email address with upper and lowercase characters without error.
- [x] Validation match is successful.

## Tasks
- [x] Test to see if issue can be replicated
- [x] Update code to handle upper-case inputs
- [x] PO approved

## Definition of Done
- [ ] The email field accepts inputs of upper and lower-case letters

**Comment by ASprinkle** [comment]
Looks good!
![image](https://user-images.githubusercontent.com/33435621/68315410-95540180-006c-11ea-9138-85192b0b0d35.png)
