### ISSUE TITLE
SPIKE, As a Researcher, I want to share survey findings from story #1003", so that Special Permit application "instructions" are understandable..

### ISSUE THREAD

**Issue by lisamcmichael** [USDAForestService/fs-open-forest-platform#1024]
## Notes
**See story #1003 and #532**

## Acceptance Criteria
- [x] PO approves new language/content (Special Permit application)  #532

## Tasks
- [x] Researcher launches launches survey
- [x] Researcher and PO review survey findings and decider on "go live" content for pilot

## Definition of Done
- [x] Story #532 is updated.

**Comment by lisamcmichael** [comment]
@ASprinkle If you think this isn't needed, feel free to close the story.

**Comment by ASprinkle** [comment]
Based on the results of the survey, this will be the language we use: 

**"It may take a while to complete the application. To save time, have all of your documents ready.  You won’t be able to save the application to complete it later. The application will be saved once it’s submitted."**
