### ISSUE TITLE
As an admin for multiple forests I want to see my forests listed so that I can do admin things.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1031]
## Notes
* What are things we should consider when making this story *

We recently found that Admins who are in charge of multiple forests cannot see any forests listed in the Admin Generate Reports or Change Season Dates tabs.
Reference story #749 and #839 

![AdminNoForests.png](https://images.zenhubusercontent.com/5a00e34b8a75884b90864b6f/d9d4b42a-be4b-454f-adef-524adfdab469)

![L_3E14 tmp](https://user-images.githubusercontent.com/33435621/68407421-64d99980-0138-11ea-8160-aee5d95640c3.png)

## Acceptance Criteria
- [ ] Admins who need access to generate reports or change season dates for multiple forests have the access.

## Tasks
- [x] Edit admin roles for the following people so that they can see their forests
- Brian Tandy (Deschutes, Ochoco) brian.tandy@usda.gov
- Charlotte Kennymore (Arapaho and Roosevelt, Shoshone - i.e., Region 2) charlotte.kennymore@usda.gov
- Dana Croll (all Region 6 forests) dcroll@fs.fed.us
- Krystal Fleeger (all Region 6 forests) krystal.fleeger@usda.gov
- [x] Confirm with Brian that access to admin functions works
- [x] Confirm with Charlotte that access to admin functions works
- [x] Confirm with Krystal that access to admin functions works
- [x] Confirm with Dana that access to admin functions works
- [x] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by abdul1234e** [comment]
This is completed. i followed with Charlotte, she can access admin privileges both on staging and prod. 

Need to follow-up with other folks.

**Comment by ASprinkle** [comment]
Thank  you @abdul1234e  I sent an email to everyone confirming. Will update when we hear back from them. Will move to Awaiting Acceptance in the meantime.

**Comment by ASprinkle** [comment]
@abdul1234e Brian informed me that you called him and that we'll check in on his admin access again tomorrow. I was able to confirm with Dana and Krystal that they can see all forests.

**Comment by ASprinkle** [comment]
Brian confirmed access.
