### ISSUE TITLE
As a Christmas tree cutter on the WIL NF, I want to be informed about prohibited tree species.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1033]
## Notes
* What are things we should consider when making this story *

## Acceptance Criteria
- [x] Prohibited species are updated to show Western White Pine and Whitebark Pine.  Pacific yew is kept.
![WIL_prohibitedspecies.JPG](https://images.zenhubusercontent.com/5a00e34b8a75884b90864b6f/f6b7513e-6a75-45a0-a2a6-5098319cfc30)
## Tasks
- [x] Do not Remove Pacific Yew photo and text from the Identifying Tree Species section
- [x] Do not Remove Pacific Yew text from the Rules and Guidelines section
- [x] Add Western white pine text and photo to the Identifying Tree Species section
- [x] Add Whitebakr Pine text and photo to the Identifying Tree Species section
- [x] Add the following text to the Rules and Guidelines section for Christmas tree Cutting: "Do not cut five-needle pine trees."
- [x] PO approved

## Definition of Done
- [x] Pull requests meet technical definition of done
- [x] Compare finished design with mockup

**Comment by ASprinkle** [comment]
Thumbs Up
![image](https://user-images.githubusercontent.com/33435621/68443486-d6413880-0188-11ea-8f9c-745f79baca3d.png)
![image](https://user-images.githubusercontent.com/33435621/68443491-d8a39280-0188-11ea-8502-cee66b491a12.png)
