### ISSUE TITLE
As someone providing feedback, I would like to be informed that no one will be responding to me so that I know what to expect.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1036]
## Notes
* What are things we should consider when making this story *

We have heard from a few people that when someone submits "feedback" they may expect a response from the team.  We will need to add some informational text to the feedback page so that people know that submitting feedback does not result in a response, and that if they have a question, they should contact customer support.

## Acceptance Criteria
- [ ]  Users are informed that their feedback submission will not result in a response from the team.
- [ ] Users are informed that if they need help, or have technical questions, they will need to contact customer support.

## Tasks
- [ ] Determine informative language to add to the Feedback pages.
- [ ] Mock the design
- [ ] Add the text
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
Updated story #984 with this information. closed this story.
