### ISSUE TITLE
As a xmas tree cutter i don't want to be confused by seeing code factor in the ARP rules and guidelines when I print them.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1038]
## Notes
* What are things we should consider when making this story *

![image](https://user-images.githubusercontent.com/33435621/68488642-6075b500-01fa-11ea-957f-790440aa77f1.png)

![image.png](https://images.zenhubusercontent.com/5a00e34b8a75884b90864b6f/ece58cbd-0b44-4d59-bcee-64d69140b6c9)

## Acceptance Criteria
- [x] There is no code factor in the ARP printed rules and guidelines.

## Tasks
- [x] remove code factor in the printed ARP rules and guidelines, so that it shows the date it is referencing.
- [x] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup

**Comment by ASprinkle** [comment]
Update from stand up @briandavidson will to a preemptive push to staging to verify the solution is working.

**Comment by ASprinkle** [comment]
Success! the updates are working in staging! @briandavidson 
![image](https://user-images.githubusercontent.com/33435621/69271987-b4818180-0b8a-11ea-8ede-568556fe2f6d.png)
![image](https://user-images.githubusercontent.com/33435621/69271994-b77c7200-0b8a-11ea-9048-b8b071f48b5b.png)
