### ISSUE TITLE
SPIKE 404 error when printing from confirmation page

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1040]
## Notes
* What are things we should consider when making this story *
[404whenPrintingConfirm.docx](https://github.com/USDAForestService/fs-open-forest-platform/files/3837867/404whenPrintingConfirm.docx)

## Acceptance Criteria
- [x] We understand why the 404 error is populating at this stage
- [x] We can print permits from the confirmation page without a 404 error,

## Tasks
- [x] Research 404 error
- [x] Fix bug
- [x] PO approved

## Definition of Done
- [x] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [x] Usability tested

**Comment by ASprinkle** [comment]
Here is a screen shot flow that I was able to capture from a purchase I made on my cell phone: 
![Screenshot_20191115-150919_Chrome](https://user-images.githubusercontent.com/33435621/68983149-8f71c500-07be-11ea-9bb4-f100801d4c60.jpg)
![Screenshot_20191115-150931_Chrome](https://user-images.githubusercontent.com/33435621/68983155-94cf0f80-07be-11ea-9f26-c820e26ce8e8.jpg)
![Screenshot_20191115-150943_Print Spooler](https://user-images.githubusercontent.com/33435621/68983162-9bf61d80-07be-11ea-87c9-f9de391e837d.jpg)

**Comment by ASprinkle** [comment]
@briandavidson looks great! no 404!
![image](https://user-images.githubusercontent.com/33435621/69666268-d5d9e600-1040-11ea-81b5-0dc391e77e06.png)
![image](https://user-images.githubusercontent.com/33435621/69666283-db373080-1040-11ea-95ec-c34e3bcaad48.png)
![image](https://user-images.githubusercontent.com/33435621/69666292-decab780-1040-11ea-9f00-d4ad6c2c195e.png)
