### ISSUE TITLE
As an Open Forest Admin I want to make sure the right people have access so that the forest can do admin things.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1042]
## Notes
* What are things we should consider when making this story *
Remove Seana Lammers as an Open Forest Admin. She is no longer working for the Fre-Win/Forest Service.

## Acceptance Criteria
- [x] Seana Lammers no longer has administrative access to Open Forest 
- [x] Angie Forbes is granted access in place of Seana for the Fremont-Winema
- [x] We've confirmed that Rebecca Busscher has access to the Mt. Baker Snoqualmie 
- [x] We've confirmed that Chamise Kramer has access to the Rogue River-Siskiyou 
- [x] We've confirmed that Terri Jump has access to the Okanogan-Wenatchee
- [x] We've confirmed that Leo Silva has access to the Okanogan-Wenatchee
- [x] We've confirmed that Cara Lewis has access to the Mt. Hood
- [x] We've reviewed and confirmed that all Open Forest admins information is correct in the system and should be functioning normally.

## Tasks
- [x] Remove Seana Lammers from Open Forest as an admin. seanamlammers@usda.gov
- [x] Add Angie Forbes as an Admin for the Fremont-Winema angie.forbes@usda.gov
- [x] Confirm that Angie is able to access Open Forest as an Admin
- [x] Confirm that Rebecca Busscher rebecca.busscher@usda.gov has Admin Access to the Mt. Baker Snoqualmie (#749 ) 
- [x] Confirm that Chamise Kramer chamise.kramer@usda.gov has Admin Access to the Rogue River-Siskiyou (#839 )
- [x] Confirm that Terri Jump terri.jump@usda.gov has Admin Access to the Okanogan-Wenatchee (#749  ) 
- [x] Confirm that Leo Silva leonardo.silva@usda.gov has Admin Access to the Okanogan-Wenatchee (#839  )
- [x] Add Cara Lewis Cara.Lewis@usda.gov to Mt. Hood (a recently new employee to Mt. Hood in SFP role)
- [x] Review and confirm all admins access is correct in the system
- [x] Amber to Schedule a Demo with Angie.
- [x] PO approved

## Definition of Done
- [] Pull requests meet technical definition of done

**Comment by abdul1234e** [comment]
Amber, I got to restart prod with this environment variables update. We will update later tonight or your recommend time suggested.

**Comment by ASprinkle** [comment]
@abdul1234e I updated this to include an admin check on Rebecca Busscher for the Mt. Baker-Snoqualmie based on a  recent customer support issue that @Rebekah-Hernandez and Dylan received

**Comment by ASprinkle** [comment]
> Amber, I got to restart prod with this environment variables update. We will update later tonight or your recommend time suggested.

We confirmed at stand up today that the recommended time for a prod restart would be 0800 Eastern (0500 PST), and not during the nightly resets.

**Comment by abdul1234e** [comment]
removed seana and added angie.

{
          "admin_username": "ANGIE_FORBES",
          "forests": [
            "fremontwinema"
          ]
        },

confirmed access to rebekah.

{
          "admin_username": "REBECCA_BUSSCHER",
          "forests": [
            "mtbakersnoqualmie"
          ]
        },

**Comment by ASprinkle** [comment]
@abdul1234e more admin access issues for folks.  It would  be good for you to go back and check all of our admins as a proactive approach to id any potential issues with access. I will make a list for you to work from and update the story in a bit.

**Comment by ASprinkle** [comment]
I created a workbook called "All Forests DatesCodesAdmins" there is a tab for Admins in this workbook that you can use to cross check access.  I think I captured all of them. I am curious to know if I missed any that are in our system. https://usfs.box.com/s/6n8130crzvivssgrqt4jpn569vwam0mu

**Comment by abdul1234e** [comment]
@ASprinkle @mwreiss  thanks for list you share. I did some testing in staging with forest 

Fremont-Winema National Forest
Rogue River-Siskiyou National Forest
Mt. Baker-Snoqualmie National Forest
Okanogan-Wenatchee National Forest

they all are having issues in portal giving blank forest. 

![image](https://user-images.githubusercontent.com/31516419/68804657-3c6a0780-0630-11ea-8733-58a4877b823f.png)

I have updated my credentials from All to okanogan in staging. I get the same error and also verified with above users.

{
          "admin_username": "ABDUL_QURESHI",
          "forests": [
            "okanogan-wenatchee"
          ]
        }

**Comment by ASprinkle** [comment]
@abdul1234e thanks for this update. Where do we go from here for individuals that only need (should have) access to a single forest?  I think it is interesting that this appears to be associated with our only hyphenated forests.  are there any issues with the  "Arapaho and Roosevelt" which is one forest in our system.

**Comment by abdul1234e** [comment]
there is no issues with arp forest name. Its sound like only issue with hyphenated forest names.

I have verified with kristie. 

![image](https://user-images.githubusercontent.com/31516419/68805767-776d3a80-0632-11ea-9a7d-35dd75d11694.png)

{
          "admin_username": "KRISTIE_SALZMANN",
          "forests": [
            "shoshone"
          ]
        },
or {
          "admin_username": "JODI_KING",
          "forests": [
            "arp"
          ]
        },

**Comment by ASprinkle** [comment]
We verified that Tammy Williams on the ARP cannot access the generate reports function, she sees no forests listed. I have asked her for a screen shot of what she sees. Interesting that the "Arapaho and Roosevelt" is shown as "arp" in the code, and other forests are written out. is there perhaps a bug related to that?

**Comment by mwreiss** [comment]
@abdul1234e  Are you sure that all the users trying are Level 2 assurance in eAuth?  The issue seems inconsistent if some are working but others are not within the same forest.  Is that reasonable to think or is the issue unrelated?

Do we have a baseline who is working and who is not for each?

**Comment by ASprinkle** [comment]
@mwreiss Not a solid baseline I have asked for everyone to check their permissions. I started tracking it in a spreadsheet in pinyon https://usfs.box.com/s/6n8130crzvivssgrqt4jpn569vwam0mu

**Comment by abdul1234e** [comment]
I have confirmed with rebecca and silva. they both can see one forest in the production site.

need to check with others. 

I will work check with eauth again for Tammy wiliams. it could be first and last name might be differ.

**Comment by ASprinkle** [comment]
@abdul1234e that is GREAT news!

**Comment by abdul1234e** [comment]
Confirmed with angie. She can access fremont-winema.

**Comment by mwreiss** [comment]
@abdul1234e  Thanks Abdul!

**Comment by mwreiss** [comment]
@ASprinkle @abdul1234e  sounds like this was due to an inconsistency in code vs whitelist.  Do we need to validate for future forest additions?  Side note: This will be resolved in the future with the EEMS roll out for role management.

**Comment by abdul1234e** [comment]
Confirmed with terri jump. she can see one forest Okanogan-Wenatchee in her portal.  I still need to confirm with two more users and it should be good to done.

**Comment by abdul1234e** [comment]
Confirmed with cara that she can access her forest.

**Comment by ASprinkle** [comment]
Thanks @abdul1234e  great work on getting this done!  It's a lot to round all this stuff up and make sure it's working. I am glad you were able to get a hold of everyone in timely manner :)
