### ISSUE TITLE
SPIKE: Demo the special uses application process for the team

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1043]
## Notes
* What are things we should consider when making this story *

## Acceptance Criteria
- [x] the team has an understanding of the workflow for both applications on the MBS special uses platform.

## Tasks
- [x] Schedule demo for team
- [x] Special uses non-commercial group use applicant workflow/process demo.
- [x] Special uses non-commercial group use admin workflow/process demo.
- [x] Special uses temporary outfitting and guiding applicant workflow/process demo.
- [x] Special uses temporary outfitting and guiding admin workflow/process demo.
- [x] SUDS integration demo.
- [x] Schedule follow ups if needed.
- [x] Schedule an Adobe recording prep session with Eric Carlson
- [x] PO approved

## Definition of Done
- [x] A/C and Tasks are completed.

**Comment by ASprinkle** [comment]
Demo scheduled 11/13 @ 0630 PST

**Comment by ASprinkle** [comment]
Adobe prep session scheduled with Eric 11/18

**Comment by ASprinkle** [comment]
Demo follow ups won't be scheduled right now. Plan: record demo, and offer demo of portions of the SU site during sprint reviews.
