### ISSUE TITLE
(MVP) As an MBS SU Admin I would like to know that the platform has been successfully tested in PROD prior to launch so that I can feel good about being ready.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1044]
## Notes

We want to run some end to end tests for special uses in PROD to verify it is working in PROD in prep for launch. (we especially want to test email correspondence and links, and make sure that when we accept to SUDS, that it goes there in PROD).

## Acceptance Criteria
- [x] Testing passed successfully and is ready for "real" customers to use the module

## Tasks
- [x] Develop testing scenario (Lisa M.)
- [x] Assign testers (@ASprinkle and @Rebekah-Hernandez)
- [x] Inform the forest that we are testing the application in production
- [x] Assure testers have the correct role in SUDS
- [x] Test the application in prod
- [x] Test Case Scenario 1 - NCGU application & Accept to SUDS
- [x] Test Case Scenario 2 - NCGU application & Reject
- [x] Test Case Scenario 3 - NCGU application & Hold, request info, update, and reject.
- [x] Test Case Scenario 4 - NCGU application & Applicant cancels their own application
- [x] Test Case Scenario 5 - TOG application & Accept to SUDS
- [x] Test Case Scenario 6 - TOG application & Reject
- [x] Test Case Scenario 7 - TOG application & Hold, request info, update, and reject.
- [x] Test Case Scenario 8 - TOG application & Applicant cancels their own application
- [x] Test Case Scenario 9 - Mobile View - -NCGU application and Admin Rejects
- [x] Test Case Scenario 10 - Mobile View - TOG application and Admin Rejects
- [x] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by lisamcmichael** [comment]
**@ASprinkle or @carlsonem I will need access to the Admin screens to create a "test script". Thx!**

**Comment by ASprinkle** [comment]
@lisamcmichael I can share my screen with you during our meeting tomorrow, and give you control to click through. not sure how long it will take to get you added to the admin screens in staging. That is not something that i know how to do. I'll include @abdul1234e @mwreiss here too

**Comment by lisamcmichael** [comment]
> @lisamcmichael I can share my screen with you during our meeting tomorrow, and give you control to click through. not sure how long it will take to get you added to the admin screens in staging. That is not something that i know how to do. I'll include @abdul1234e @mwreiss here too

@ASprinkle That might work. Together, we can identify the major user flows (task flows) as test scenarios.  I'll find time on your calendar.

**Comment by lisamcmichael** [comment]
@ASprinkle Abdul is granting access to MBS on staging. 

I started **baseline user journeys** for consideration:
_Log in, Log out_
_Generate a report_
  Search 
  Select criteria
_Request content changes
Grant access_ 
  Add user
_Edit access_ 
  Search
  Remove user
  Select criteria
_Request help (customer support)
Request access 
Feedback_

**Comment by lisamcmichael** [comment]
@ASprinkle **I have access to MBS on Staging** ... _thx to @abdul1234e ._

**Comment by lisamcmichael** [comment]
@Rebekah-Hernandez I met w/ Amber this morning. She will be a tester, and would like you to test as well. I have the test scenarios. I am cleaning them up, and then I'll share with you both.

**Comment by Rebekah-Hernandez** [comment]
I'm not exactly sure what being a tester entails. Is that similar to the videos with the front liners where they go through the website with your prompts? Is there anything I need to do to prepare? @lisamcmichael

**Comment by lisamcmichael** [comment]
> I'm not exactly sure what being a tester entails. Is that similar to the videos with the front liners where they go through the website with your prompts? Is there anything I need to do to prepare? @lisamcmichael

It's simple really, you'll use the test scenarios to test the Special Use MBS site in production, to ensure it works as intended (no bugs or miscues). We'll grab time w/ Amber to sync on this.

**Comment by lisamcmichael** [comment]
@ASprinkle and @Rebekah-Hernandez, **Test Scenarios are now on Pinyon.**  

**https://usfs.box.com/s/ypjzny3htvxodjy4webzld3av6x3brwb**

**Comment by ASprinkle** [comment]
@mwreiss is working on SUDS access for testers. We won't be able to fully execute test case scenarios 1 or 5 until we can confirm SUDS access.

**Comment by ASprinkle** [comment]
@carlsonem and @ASprinkle paired on testing Login.gov function in prod for a new customer. We completed test case scenario 3 in that process.

@Rebekah-Hernandez and Amber have time scheduled to pair on tests 12/11/2019

**Comment by ASprinkle** [comment]
@lisamcmichael thanks for putting together that great test scenario write up! that will be very helpful!

**Comment by mwreiss** [comment]
@ASprinkle  I filled out request forms for you, @Rebekah-Hernandez and I yesterday afternoon.  I haven't received a reply from Anne Hansen about the request.

**Comment by ASprinkle** [comment]
Rebekah and Amber paired and Tested case scenarios 2,  4, 6, 7, 8, 9, 10.  Notes here:  https://usfs.box.com/s/p8tqn011wp07lg81jsiy09bgtxnot4er

Testing Accepting to SUDS will take place after current Ready for Master stories are pushed to PROD.

**Comment by ASprinkle** [comment]
12/17: TCScenario 1 - "Apply" button (no login.gov language), routed to login.gov, upon logging in, routed to Christmas tree page. Cleared cache and tried again, SU main page showed login.gov language, routed to login.gov, routed to application page correctly.

**Comment by ASprinkle** [comment]
Email:  Short term, Abdul will add the MBS POC to whitelist for email today, not adding them to the actual shared mailbox.
