### ISSUE TITLE
As an Open Forest customer, I'd like an initial landing page research completed to ensure that I can find what I need easily and efficiently.

### ISSUE THREAD

**Issue by lisamcmichael** [USDAForestService/fs-open-forest-platform#1051]
## Notes
See EPIC #604

## Acceptance Criteria
- [x] We have an understanding of what would be important to users when they arrive at a future Open Forest landing page.
- [x] We have the information documented in an easy to find location.

## Tasks
- [x] Define research approach(s)
     - [x] Pick research approach (researcher, designer and PO) see #604 "Bargain UX"
- [x] Create interview questions
      - [x] give to 18F to include in their field study first week in Dec.
      - [x] give to PO / Designer
      - [x] modify questions if needed
- [x] Synthesize 18F research findings 
- [x] Share research findings with PO and designer
- [x] Determine path for initial landing page wireframe
- [x] PO approved

## Definition of Done
- [x] Tasks and A/C are completed.

**Comment by lisamcmichael** [comment]
@ASprinkle I have updated tasks so that I can present two options for our research approach. After today's call, we may need to revise tasks and/or story #604.

**Comment by ASprinkle** [comment]
@lisamcmichael  I added "Determine interview questions - goals/outcomes from interviews"

**Comment by ASprinkle** [comment]
@lisamcmichael copying these notes here... too :)

Meeting with Aaron/Amber/Lisa S to discuss research approach to take:

Bargain UX most feasible due to budget constraints
Lisa S: she needs to know the scope of information to design prototype
Aaron/Amber: design a landing page that is going to work for the next 2 yrs.? Then it will be revisited.
Amber: Also considering an in-person Retro w/pilot forests, to help align w/ Gifford-Pinchot (program increment)
Look at Aaron's questions for user interview ideas
MVP could be mid to high-fi (depends on where we are in the process).

**Comment by lisamcmichael** [comment]
Updated tasks to match tasks in "Bargain UX" approach

Removed these tasks:
- [ ] Identify users to conduct interviews with
- [ ] Schedule the interviews
- [ ] Complete interviews (one-on-one/"in person" preference vs. survey/email)

**Comment by lisamcmichael** [comment]
_Here is v1 of interview questions for 18F's field research that starts next week._ 
https://usfs.box.com/s/jah2pl0ur52a8e0p481j5ibzjlgk53km

**Comment by lisamcmichael** [comment]
@lisaredux I added you so we can continue to collaborate on what research findings make its way into the wireframe.

**Comment by lisamcmichael** [comment]
**Research questions to hand off to 18F
https://usfs.app.box.com/file/566822961291**

**Comment by lisamcmichael** [comment]
@ASprinkle 
@lisaredux and I met with Mark and Christine (18F); their field research coming up is with LEOs. They know what we're looking for, even though LEOs are not our primary target. On the upside, Christine will be running remote moderated sessions with the public later this month. I've asked if we can be a fly on the wall for some of those.

**Comment by ASprinkle** [comment]
@lisamcmichael  I am looking at the questions in box now... is it an assumption that 18F will be doing the research to inform Open Forest main landing page? or is that what is confirmed happening? I guess I thought 18F was working on firewood product research.  and that we were doing the work for a main landing page.

**Comment by lisamcmichael** [comment]
> @lisamcmichael I am looking at the questions in box now... is it an assumption that 18F will be doing the research to inform Open Forest main landing page? or is that what is confirmed happening? I guess I thought 18F was working on firewood product research. and that we were doing the work for a main landing page.
> 
> I added comments and track changes.

Hi @ASprinkle - we are piggy backing on 18F research because we're taking the "budget" approach, vs. having user interviews now. With that in mind, whatever we can glean from their research (talking to LEOs, the public and front liners) will help @lisaredux wire-up an initial prototype. After we have a prototype, we'll run usability research and collect input.

Also, Mark and Christine have a solid idea of what we need to know. The research they're doing this weekend with LEOs may not give us anything useful; however, they're sharing those findings with us, and we can comb through them and hopefully come up w/ something useful for the landing page. 

We have the meeting on Monday to hash some of this out. I'll look at your comments/thx!

**Comment by lisamcmichael** [comment]
@lisaredux and @ASprinkle I'm drafting a synopsis of 18F's research shared w/ us from their field research w/ "FLs", and the public. Before we meet on Monday, I'll post it.

**Comment by lisamcmichael** [comment]
> @lisaredux and @ASprinkle I'm drafting a synopsis of 18F's research shared w/ us from their field research w/ "FLs", and the public. Before we meet on Monday, I'll post it.

@ASprinkle, yesterday Lisa and I met to talk about next steps based on _using the "second hand" 18F research_. Monday, we'll demo the Balsamiq collaborative tool, and go over the research findings/insights I've pulled out of their 2 recently completed studies. **Here is the synopsis:

**![image](https://user-images.githubusercontent.com/52501060/70339590-18f44000-181d-11ea-9c43-3e242f6b4751.png)****

PS: Lisa, the research synopsis includes more details.

**Comment by lisamcmichael** [comment]
@Rebekah-Hernandez  - see above "Open Forest - Research Insights...". I'll share that on our call, and we'll also create next steps.
