### ISSUE TITLE
As an Open Forest customer, I want to have clickable wireframe design to test later so that I feel good about the main landing page approach. 

### ISSUE THREAD

**Issue by lisamcmichael** [USDAForestService/fs-open-forest-platform#1052]
## Notes
See Epic #604 
Depending on what we learn in user interviews #1051, a card sort activity may be needed to inform wires.

## Acceptance Criteria
- [x] We have a completed landing page wireframe ready for testing with users.

## Tasks
- [x] Review synthesized results from #1051 
- [x] Wireframe a design based on those results.
- [x] Review the wireframe with dev for feasibility considerations, and make adjustments as needed.
- [x] Wireframe is ready for testing.
- [ ] PO approved

## Definition of Done
- [ ] Compare finished design with mockup/wireframe
- [ ] Usability tests are scheduled.

**Comment by lisaredux** [comment]
@Rebekah-Hernandez here's the PDF in progress 
[OpenForestLanding-604.pdf](https://github.com/USDAForestService/fs-open-forest-platform/files/4003472/OpenForestLanding-604.pdf)

**Comment by lisaredux** [comment]
[OpenForestLanding-1052-clickable.pdf](https://github.com/USDAForestService/fs-open-forest-platform/files/4013034/OpenForestLanding-1052-clickable.pdf)
@Rebekah-Hernandez This is the current one to be discussed in a meeting now.

Meeting with Amber and Rebekah later today to comb through some more

**Comment by lisaredux** [comment]
@ASprinkle @Rebekah-Hernandez here's the updated prototype that we'll look at in the 
 meeting [OpenForestLanding-1052-updated-12-31-2019.pdf](https://github.com/USDAForestService/fs-open-forest-platform/files/4013431/OpenForestLanding-1052-updated-12-31-2019.pdf)

**Comment by mwreiss** [comment]
Hi @lisaredux  and @Rebekah-Hernandez  are you ready to do a demo/review with the team before this moves to dev?

**Comment by ASprinkle** [comment]
@mwreiss we've planned a meeting with Aaron and Eric tomorrow to identify any other sideboards before finalizing the wireframe for wireframe testing. Before we test the wireframe we want to meet with Dev to make sure we're not setting up an unattainable expectation with it. There is still quite a bit of work to do before it gets moved to Dev for staging which would be story #1123  The sequence of events is lined out in the story box of epic #604

**Comment by mwreiss** [comment]
@ASprinkle  Thanks Amber, that sounds great.  I wanted to be sure @smahmudFS , @JonathanLerner54  and I were able to do a review before moving to dev. to cover architecture, security and general infrastructure changes (ie. database, etc..).  I know this is a large add on and want to be sure all basis are covered on this end.  Thank you!

**Comment by ASprinkle** [comment]
Ahh ok! I will forward the invite for tomorrow on to you all :)

**Comment by lisaredux** [comment]
Hi everyone, this is the clickable protoptype we will discuss — [OpenForestLanding-1052-01032020.pdf](https://github.com/USDAForestService/fs-open-forest-platform/files/4020123/OpenForestLanding-1052-01032020.pdf)

I'm making a few updates, so if you see anything that needs updating or if you have questions, be sure to let me know during the meeting today. Thanks

**Comment by lisaredux** [comment]
Updated PDF with breadcrumbs [OpenForestLanding-1052-01032020-UPDATED.pdf](https://github.com/USDAForestService/fs-open-forest-platform/files/4020186/OpenForestLanding-1052-01032020-UPDATED.pdf)

**Comment by lisaredux** [comment]
@ASprinkle @Rebekah-Hernandez This is updated since our meeting. I'm still combing for bad links. If you see something wrong, let me know and I'll update it.

[OpenForestLanding-1052-01062020-UPDATED.pdf](https://github.com/USDAForestService/fs-open-forest-platform/files/4028289/OpenForestLanding-1052-01062020-UPDATED.pdf)

**Comment by lisaredux** [comment]
@ASprinkle @Rebekah-Hernandez Here's the latest prototype: some minor updates especially with breadcrumbs, links and profile workflow (1130):
[OpenForestLanding-1052-01072020.pdf](https://github.com/USDAForestService/fs-open-forest-platform/files/4031574/OpenForestLanding-1052-01072020.pdf)

**Comment by ASprinkle** [comment]
will upload updated one shortly after stand up. Next step: #1122

**Comment by lisaredux** [comment]
Here's the latest for your review @ASprinkle.  [OpenForestLanding-1052-01102020.pdf](https://github.com/USDAForestService/fs-open-forest-platform/files/4048183/OpenForestLanding-1052-01102020.pdf)

I'll be handing off the Balsamiq files to Rebekah via Pinyon shortly

**Comment by ASprinkle** [comment]
Thanks @lisaredux     @Rebekah-Hernandez where in pinyon is it saved?

**Comment by lisaredux** [comment]
Good call @ASprinkle Here it is https://usfs.box.com/s/ss00de9vj5066etmiiflj0qts7gmjown

**Comment by ASprinkle** [comment]
@lisaredux I tried opening it in pinyon and It doesn't look like I have the appropriate permissions for the type of document that it is...

**Comment by Rebekah-Hernandez** [comment]
It's a type of file that works in the balsamiq app. I don't know how else it can be opened @ASprinkle

**Comment by ASprinkle** [comment]
@Rebekah-Hernandez can you save the latest version as a PDF so that we have a snap shot of it finalized? We should be able to save it as a downloadable PDF, I think.

**Comment by Rebekah-Hernandez** [comment]
@lisaredux @ASprinkle I think the final is saved right above it. I see the pdf was uploaded on Friday, the same as the .bmpr file. If that's not right, i will get that saved and put on pinyon soon.

**Comment by lisaredux** [comment]
@Rebekah-Hernandez thanks for clarifying. That is correct. I'll upload the latest PDF to Pinyon as well here labeled Story1052 https://usfs.app.box.com/folder/99990407599
