### ISSUE TITLE
As an Open Forest customer, I want an Open Forest landing page that is well designed and functions properly.

### ISSUE THREAD

**Issue by lisamcmichael** [USDAForestService/fs-open-forest-platform#1054]
## Notes
* What are things we should consider when making this story *

## Acceptance Criteria
- [ ]

## Tasks
- [ ] Finalize mock design
Build mock up
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
Rebekah and Aquib are meeting later today to go over wire frame refinements

**Comment by aQuib** [comment]
@ASprinkle - I made two small changes to this ticket tasks to incorporate making high-fidelity mockup (versus just updating the lofi wireframe), but the effort remains unchanged for this ticket.

**Comment by ASprinkle** [comment]
@aQuib @Rebekah-Hernandez  I uploaded some of my comments to the main page PDF that Rebekah sent me:  it's in pinyon https://usfs.box.com/s/ww1ncclbiwarfg70cf7nertfa8h01x6l and I uploaded it here 
[Main Page wireframe Sprinkcomments.pdf](https://github.com/USDAForestService/fs-open-forest-platform/files/4252391/Main.Page.wireframe.Sprinkcomments.pdf)

**Comment by aQuib** [comment]
Here are update hifi mockup (only thing yet to added it official imagery for banners ![image](https://user-images.githubusercontent.com/2117062/75567323-57b22480-5a1f-11ea-8da1-981d43d9325a.png)

**Comment by ASprinkle** [comment]
Need to schedule one more hand-off meeting with Dev as a refresher.

**Comment by carlsonem** [comment]
@ishanashams The mockup for the map is in aquib's comment above.

**Comment by aQuib** [comment]
Here is update hifi mockups with the 
[OF Landing Page v1.60 (sm).pdf](https://github.com/USDAForestService/fs-open-forest-platform/files/4294620/OF.Landing.Page.v1.60.sm.pdf)
mobile, tablet, and desktop screen sizes.

**Comment by ishanashams** [comment]
@aQuib - thanks

**Comment by mtlaney** [comment]
@aQuib any chance you can drop the images used in here?

**Comment by aQuib** [comment]
![thumbnail_product_firewood_desktop](https://user-images.githubusercontent.com/2117062/76627529-919c2400-6511-11ea-9fa0-730ec6f098ce.png)
![thumbnail_product_firewood_mobile](https://user-images.githubusercontent.com/2117062/76627530-9234ba80-6511-11ea-8f28-61c1cdab26c5.png)
![thumbnail_product_firewood_tablet](https://user-images.githubusercontent.com/2117062/76627531-9234ba80-6511-11ea-81cc-7cdf0eacd7c8.png)
![thumbnail_product_huckleberry_desktop](https://user-images.githubusercontent.com/2117062/76627532-9234ba80-6511-11ea-99da-545aa688425d.png)
![thumbnail_product_huckleberry_mobile](https://user-images.githubusercontent.com/2117062/76627535-92cd5100-6511-11ea-86ec-966aaaa6a252.png)
![thumbnail_product_huckleberry_tablet](https://user-images.githubusercontent.com/2117062/76627538-92cd5100-6511-11ea-826e-88a573202ef6.png)
![thumbnail_product_mushroom_desktop](https://user-images.githubusercontent.com/2117062/76627539-9365e780-6511-11ea-9268-8145a5c78b65.png)
![thumbnail_product_mushroom_tablet](https://user-images.githubusercontent.com/2117062/76627540-9365e780-6511-11ea-8d71-d7701f7d3477.png)
![thumbnail_product_mushroom_tablet@2x](https://user-images.githubusercontent.com/2117062/76627541-9365e780-6511-11ea-84ff-234e477a8ce9.png)
![thumbnail_product_xmas_desktop](https://user-images.githubusercontent.com/2117062/76627542-9365e780-6511-11ea-83e3-581994384d58.png)
![thumbnail_product_xmas_mobile](https://user-images.githubusercontent.com/2117062/76627543-93fe7e00-6511-11ea-8b6c-d64f23f98581.png)
![thumbnail_product_xmas_tablet](https://user-images.githubusercontent.com/2117062/76627544-93fe7e00-6511-11ea-83bc-4411531ff9e8.png)
![thumbnail_specialuse_non_desktop](https://user-images.githubusercontent.com/2117062/76627545-93fe7e00-6511-11ea-9a0a-fb7856f72753.png)
![thumbnail_specialuse_non_tablet](https://user-images.githubusercontent.com/2117062/76627549-93fe7e00-6511-11ea-916e-b819fbece52c.png)
![thumbnail_specialuse_temp_desktop](https://user-images.githubusercontent.com/2117062/76627550-94971480-6511-11ea-8cf1-a11cf255097e.png)
![thumbnail_specialuse_temp_tablet](https://user-images.githubusercontent.com/2117062/76627551-94971480-6511-11ea-8726-d5cc5ae889a4.png)

**Comment by aQuib** [comment]
@mtlaney  - I have attached images for you here (different sizes based on screen size).
