### ISSUE TITLE
As an MBS Admin I would like to see updated maps and rules and guidelines to restrict research areas so that people don't get trees there.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1056]
## Notes
* What are things we should consider when making this story *

## Acceptance Criteria
- [x] The Skagit Area map is updated
- [x] The Where to cut your tree section is updated
- [x] The Rules and Guidelines page is updated
- [x] The emailed rules and guidelines have the updated information.

## Tasks
- [x] Replace the current Skagit Area map (Revised 11/2013) on the website with the one attached here. Use the same alt text.
[Christmastree-BakerLake_Map_2019 2.pdf](https://github.com/USDAForestService/fs-open-forest-platform/files/3848985/Christmastree-BakerLake_Map_2019.2.pdf)
- [x] Add a bullet to the 'Prohibited Areas and Restrictions', 'No cutting or removing trees within' list that reads: "Research natural areas."
- [x] Add a bullet in the Rules and Guidelines page, under the 'Do not cut trees within' list that reads: "Research natural areas."
- [x] PO approved

## Definition of Done
- [x] Pull requests meet technical definition of done
- [ ] AC and tasks are met.

**Comment by ASprinkle** [comment]
This story is blocked waiting on a final update from the MBS for another potential change.

**Comment by ASprinkle** [comment]
Unblocking - I confirmed with Rebecca on the MBS that there won't be any more update requests to the MBS page.

**Comment by ASprinkle** [comment]
These updates look good @mtlaney 
![image](https://user-images.githubusercontent.com/33435621/69271555-e7774580-0b89-11ea-8cf6-bb788057e63d.png)
![image](https://user-images.githubusercontent.com/33435621/69271562-ea723600-0b89-11ea-9dca-e4617f4c0ac5.png)
![image](https://user-images.githubusercontent.com/33435621/69271577-ee05bd00-0b89-11ea-96fa-bb417040b07c.png)
![image](https://user-images.githubusercontent.com/33435621/69271585-f1994400-0b89-11ea-8187-eb04578e7c9a.png)
