### ISSUE TITLE
As an MBS SU customer I want to know that the site has been reviewed for consistency and plain language so that I can understand what I am readingfollow up

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1057]
## Notes
* What are things we should consider when making this story *

All notes from this review are housed here: https://usfs.box.com/s/r8ov6bksk35oedbtydy5mq7t6sip50ry

## Acceptance Criteria
- [x] We have an understanding of what's needed to reach MVP
- [x] We have an understanding of what's needed to enhance the site.

## Tasks
- [x]  Schedule time to review the SU customer experience
- [x] Review Temporary outfitter guide permit application
- [x] Review Noncommercial group use Learn More
- [x] Review Non commercial group use applicaiton
- [x] Review Non commercial group use applicaiton confirmation page
- [x] Review help me find a permit tool
- [x] Review landing page
- [x] Review Temporary Outfitting and Guiding Learn More
- [x] Review Temporary Outfitting and Guiding Applicant Confirmation Page
- [x] Review View Applications Page
- [x] Review Application Details Page
- [x]  Identify needs to address prior to MVP
- [x]  Create stories for MVP if needed.
- [x]  PO approved

## Definition of Done
- [x] A/C and Tasks are met

**Comment by ASprinkle** [comment]
First meeting is scheduled for Tuesday 11/19

**Comment by ASprinkle** [comment]
@lisamcmichael I renamed this, removing the SPIKE note. this story will take a while to complete I think..

**Comment by ASprinkle** [comment]
Amber will pick this back up after the holiday weekend.

**Comment by ASprinkle** [comment]
https://usfs.box.com/s/r8ov6bksk35oedbtydy5mq7t6sip50ry
