### ISSUE TITLE
As an Admin for Umatilla, I would like the vendor information updated so that people know where else they can go to get permits.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1058]
## Notes
* What are things we should consider when making this story *

## Acceptance Criteria
- [x] The umatilla NF vendor link takes the user to the Umatilla NF Christmas Tree page where they can navigate to a brochure, or other information.

## Tasks
- [x] Update the "Local Vendors" link in the contact us section to take the user to this location:  https://www.fs.usda.gov/detail/umatilla/passes-permits/forestproducts/?cid=fsbdev7_016114
- [x] PO approved

## Definition of Done
- [x] Pull requests meet technical definition of done
- [x] Usability tested

**Comment by ASprinkle** [comment]
@briandavidson @mtlaney 
I merged the pull request for this story earlier today, and at stand up it was mentioned that I should be able to see it on staging... However, when I go to the staging site, this is what I see (window inset) when i click on the local vendors link for the Umatilla NF.

![image](https://user-images.githubusercontent.com/33435621/69105445-1bcef280-0a20-11ea-88af-7dc6de7b2c92.png)

Instead, I should be taken here:

**Comment by mtlaney** [comment]
@ASprinkle check again when you get a chance, when I log onto staging it's taking me to the correct URL.

**Comment by ASprinkle** [comment]
![image](https://user-images.githubusercontent.com/33435621/69170393-dd344900-0aae-11ea-9de7-bb92913e6b5c.png)

@mtlaney thanks, it's working! :)
