### ISSUE TITLE
As a permit administrator for the MBS I'd like special uses admin access in Open Forest so that I can review applications.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1060]
## Notes
We want to make sure MBS special uses admins are added to the system so that there is not a "one-person" bottleneck for application reviews. 
We also want to make sure that MBS special uses administrators can receive the email notifications when applications are submitted to the Open Forest system.

## Acceptance Criteria
- [x] We've confirmed that MBS administrators have access to the Open Forest admin site for special uses.
- [x] We also want to make sure that MBS special uses administrators can receive the email notifications when applications are submitted to the Open Forest system.

## Tasks
- [x] Identify who the special use admins are for the MBS
- [x] Grant those individuals admin access to MBS staging and MBS prod.
- [x] Identify which special use admins should receive automatic email notifications when applications are submitted through Open Forest
- [x] Confirm that FS admins can access areas they need access to.
- [x] Sue has access
- [x] Brian has access
- [x] Orlando has access
- [x] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Usability tested

**Comment by ASprinkle** [comment]
The following people who should have admin access for MBS special use permits. These people will also need to receive email notifications when applications are submitted.
sue.shermanbiery@usda.gov
orlando.garcia@usda.gov
brian.lee@usda.gov

The following people should have admin access to view PROD information in Open Forest for special uses, but should not be on an automatic email list for submitted applications
mike.schlafmann@usda.gov
anne.hansen@usda.gov
shawnee.hinman@usda.gov

**Comment by abdul1234e** [comment]
Can i move this to in progress? It will be nice to complete this over the holidays.

**Comment by ASprinkle** [comment]
@abdul1234e  yes - always good to check in with the team and see if there is any help you can provide for other in progress stories. If not, then having you pull this one in sounds good! thanks!!

**Comment by abdul1234e** [comment]
This is completed. lets validate with admin users and move this card further.

**Comment by abdul1234e** [comment]
confirmed with all 3 users they can get only staging and production.

**Comment by ASprinkle** [comment]
Ok, so all three MBS admins have access to the Admin functions with the special uses pages for both the staging site and the production site for the MBS?

**Comment by abdul1234e** [comment]
thats correct.

**Comment by ASprinkle** [comment]
> The following people who should have admin access for MBS special use permits. These people will also need to receive email notifications when applications are submitted.
> [sue.shermanbiery@usda.gov](mailto:sue.shermanbiery@usda.gov)
> [orlando.garcia@usda.gov](mailto:orlando.garcia@usda.gov)
> [brian.lee@usda.gov](mailto:brian.lee@usda.gov)

@JonathanLerner54  these are the FS admins at the MBS who would have Admin Access in Open Forest, and also Roles in SUDS.

**Comment by JonathanLerner54** [comment]
Per our conversation at today's working group, we will be establishing a tester role for the ePermits team members.
