### ISSUE TITLE
As a Regional FS Special Use Admin, I would like to be added to to see information, but would not like to receive email notification so that I am not overwhelmed with information.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1064]
## Notes
* What are things we should consider when making this story *
We also want to make sure that MBS special uses administrators can receive the email notifications when applications are submitted to the Open Forest system.

The following people should have admin access to view PROD information in Open Forest for special uses, but should not be on an automatic email list for submitted applications
mike.schlafmann@usda.gov
anne.hansen@usda.gov
shawnee.hinman@usda.gov

## Acceptance Criteria
- [x] We've confirmed that MBS administrators who want to receive email notifications are receiving those notifications, and those who do not want to receive notifications are not receiving them.
- [x] We know whether or not adding an admin to the Open Forest special uses site automatically results in the admin receiving emails (not all admins want to receive email notifications).

## Tasks
 - [x] Find out whether or not Admins in OF are attached automatically to email notifications, or if those can be separate.
- [x] Identify the individuals who should be added as admins, but not receive email notifications of applications submitted.
- [x] Confirm that these FS admins are not receiving email notifications
- [x] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by abdul-fs** [comment]
mike was already admin into mbs in prod. I have added anne and shawnee.

We still need to validate with anne and shawnee to see if they can get on prod without issues.

**Comment by abdul-fs** [comment]
Their admin access if granted and confirmed with users. 

Fyi: We have smtp email group added into prod whitelist file. we can review the list and add them into SM.FS.OpenFrstAdm@usda.gov so decided admin will received notifications.
@mwreiss 

"name": "smtp-service",
    "credentials": {
      "admins": [
        "SM.FS.OpenFrstAdm@usda.gov",
        "adsprinkle@fs.fed.us",
        "aaronburk@fs.fed.us"

**Comment by ASprinkle** [comment]
@mwreiss @abdul-fs Before we add names to a group email list, do we know what the scenarios are that would generate an email to the SM.FS.OpenFrstAdm@usda.gov inbox?
For example:
-Is an email is sent to SM.FS.OpenFrstAdm@usda.gov only when an application is submitted for review?
or,
-Is and email sent to SM.FS.OpenFrstAdm@usda.gov each time an action is taken on an application (i.e., submitted, on hold, edited/ready for review, rejected, cancelled, accepted to suds)?

**Comment by abdul-fs** [comment]
@ASprinkle @mwreiss I saw emails like submission and cancelled so far. I will review this with Matt Reiss and lets do further testing.

**Comment by ASprinkle** [comment]
When @Rebekah-Hernandez and I were testing in PROD we used the customer support email address as the "applicants" email address. You can see all of the scenarios we've tested in the Customer Support inbox under SUDS testing, which might help.

**Comment by ASprinkle** [comment]
@abdul-fs @mwreiss for researching the inboxes, we would want to be sure that the MBS Administrators at the Forest are indeed receiving updates for not only submitting or cancelled applications but also when someone has responded to an Admins HOLD requesting more information, which is captured in:
TCSencario3: Test Case Scenario 3 - NCGU application & Hold, admin request info, applicant uupdate, and admin reject.
TCScenario7: Test Case Scenario 7 - TOG application & Hold, admin request info, applicant update, and admin reject.

**Comment by ASprinkle** [comment]
Have we confirmed with Mike, or Shawnee, or Anne that they are not receiving emails when actions on applications occur?

**Comment by abdul-fs** [comment]
They are not part of smtp so they wont be getting any emails. I will also confirmed with them.

**Comment by abdul-fs** [comment]
Confirmed with anne. She is not receiving any emails from Forest Service online permits <do_not_reply_openforest@usda.gov>

**Comment by ASprinkle** [comment]
Thanks @abdul-fs I'll move this over to "done" :)
