### ISSUE TITLE
SPIKE As an applicant, I want to understand expectations if I think my activity will have less than 75 people.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1067]
## Notes

Currently, the non-commercial group use application process will not let the user submit an application if the total number of participants and spectators is less than 75.  

MBS states that they have some areas on their forest where they require people to get a NCGU permit even if their group is less than 75.

We want to make sure we have an understanding of the occurrences of permits for less than 75 people for the MBS and other possible future pilot forests.

![image](https://user-images.githubusercontent.com/33435621/69187585-bcc8b680-0acf-11ea-8296-1dbed9a19401.png)

## Acceptance Criteria
- [x] We have an understanding of what Open Forest should be able to offer to potential applicants that have an estimate of less than 75 people. 

## Tasks
- [x] Follow up with the MBS to gain clarity around the <75 people requirements
- [x] Research with other forests regarding their paths for NCGU applications with <75 people
- [x] Document findings
- [x] Create follow up stories if needed.  (we've solutioned for minor text changes) follow up story #1084 1084 created.

## Definition of Done
- [ ] Tasks and A/C are completed

**Comment by aaronburk** [comment]
this is interesting story because we have done a lot of work on this, I am curious of why that we can keel the general guidance of 75 people is likely a national policy.  This is also part of the early "How do I know if I need a permit" wizard part of the app.  They may also need reconsideration??   May need to discuss further with national rec??

**Comment by ASprinkle** [comment]
@aaronburk so, perhaps this is a case of the Forest is operating outside the boundaries of FS direction?  There are two areas on the MBS where they require NCGU permits no matter the group size.  Perhaps, we do not need to change this function on the site - and can address it differently, and see how the season goes.

**Comment by ASprinkle** [comment]
Amber and Aaron are pairing on this issue before prioritizing

**Comment by ASprinkle** [comment]
[EmailChain with MBS RE_ Less than 75 people.pdf](https://github.com/USDAForestService/fs-open-forest-platform/files/3881734/EmailChain.with.MBS.RE_.Less.than.75.people.pdf)
[Email Chain with MtHood and CRGNSA RE_Less than 75 people.pdf](https://github.com/USDAForestService/fs-open-forest-platform/files/3881736/Email.Chain.with.MtHood.and.CRGNSA.RE_Less.than.75.people.pdf)

**Comment by ASprinkle** [comment]
Scheduled a meeting with MBS for 11/25 @1300 PST to complete the follow up w/MBS task.

**Comment by ASprinkle** [comment]
**response from Brian Lee:**
_Currently, I already have 3 requests for Gold Creek Pond in 2020 – outside of the 180 day window SUDS allows. 

Last year, I had perhaps 15 requests between the 2. The numbers have been going up every year. 

Gold Creek Pond may be going back to the Okanogan-Wenatchee, but I haven’t seen the official letter stating that yet._

**Comment by ASprinkle** [comment]
![image](https://user-images.githubusercontent.com/33435621/69578722-eb3e0a00-0f85-11ea-9c4c-5806be2386e5.png)
Your activity may not require a permit. Contact your local forest office for details.

![image](https://user-images.githubusercontent.com/33435621/69578844-217b8980-0f86-11ea-9b5a-9d9deb9549e9.png)
something like this: "According to the regulation, permits are required for 75 or more people. However, some forest may have special considerations, contact your local forest if you have questions."

![image](https://user-images.githubusercontent.com/33435621/69578974-6a334280-0f86-11ea-8964-1b7d5964c95e.png)
something like "It appears you have entered fewer than 75 total attendees. For fewer than 75, you may not need a permit. Contact your local forest office."
