### ISSUE TITLE
As a visitor giving feedback, I want to be able return to the page that I was previously at if I choose to abandon submitting feedback, so that I can continue on my path.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1070]
## Notes
* What are things we should consider when making this story *

Users should be given the option to go to their previous page from the feedback screen, instead of the Return Home option, if they choose to abandon giving/submitting feedback.

## Acceptance Criteria
- [x] Users have the option of returning to their previous page from the give feedback screen without using their browser back button.

## Tasks
- [x] mock up redesign the Return Home option on the Give Feedback page. 
- [x] Build the "Return to previous page" option in the Give Feedback window that has been mocked up.
- [x] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
@lisaredux  Give Feedback Return to Previous Page Mock Up:

Redesign the Return Home option on the Give Feedback page
https://open-forest-staging.app.cloud.gov/feedback

<img width="742" alt="68979403-74f21880-07cb-11ea-8cf3-5dd00444ce82" src="https://user-images.githubusercontent.com/26801590/69186942-8bf47b80-0ae7-11ea-980c-3f42d9a191f4.png">

**Comment by ASprinkle** [comment]
@briandavidson the return to previous page in staging does not seem to work in all instances...
For example (I did not test all, but for the ones I did test), if a User is on the "Christmas tree cutting rules" page, clicks Give Feedback and then decides to abandon that and  "Return to previous page", they are not presented with the Rules information, instead they are taken to the "Buy a Christmas tree permit" page.  Perhaps this is because "information has to be saved" along the way...  or maybe something else? Here are screen shots of the flow I described: 
![image](https://user-images.githubusercontent.com/33435621/69463057-8a1cf900-0d2f-11ea-9aff-b8e55309a629.png)
![image](https://user-images.githubusercontent.com/33435621/69463069-8ee1ad00-0d2f-11ea-8eca-e5a4d5ad6033.png)
![image](https://user-images.githubusercontent.com/33435621/69463079-94d78e00-0d2f-11ea-8f04-74174e7a349e.png)

**Comment by briandavidson** [comment]
Ah okay, I see what's going on. It looks like it is going to the correct page but isn't remembering which section of the page you were viewing. Nice catch @ASprinkle ! I'll have this patched up asap.

**Comment by ASprinkle** [comment]
@briandavidson I went in and checked the interaction this morning. It looks like when I choose to give feedback on the Rules and Guidelines page, and then I select the "return to previous page" option, I am taken to the "Buy a Christmas tree permit" page where I will need to re-enter all of my tree info again, before I can view the rules and guidelines to proceed with my purchase.  I think this is the same general expectation if someone leaves the Special Use permit application screen to give feedback - the info they entered will not be saved.  If we don't think we can do this, we may need to create a different story to address communicating with the customer, a "caution note" or something perhaps.

**Comment by briandavidson** [comment]
@ASprinkle I don't know of any straightforward way to preserve the partially completed form data. I don't want to say it can't be done because I'm fairly sure it can, but it would take some pretty unconventional techniques and would be a much bigger undertaking than the initial scope of this ticket.

**Comment by ASprinkle** [comment]
Ok understood. saving data would be another story. let's keep moving with what we have for now, especially since we've got a good understanding of the interaction.  thanks Brian!

**Comment by ASprinkle** [comment]
@briandavidson @mtlaney 
When I review this story in prep to move it to done, It does not appear that the update made it to production.  Here is a screen shot of the feedback page on production
![image](https://user-images.githubusercontent.com/33435621/70182339-82971180-1698-11ea-8963-15069c298db9.png)

Here is a screen shot of it on the staging site
![image](https://user-images.githubusercontent.com/33435621/70182409-a3f7fd80-1698-11ea-8cda-745739070384.png)

**Comment by ASprinkle** [comment]
@briandavidson looks great!
![image](https://user-images.githubusercontent.com/33435621/70253552-45825c00-1738-11ea-90c2-823fe7e58d00.png)
