### ISSUE TITLE
As an Admin for MBS, I would like the vendor information updated so that people know where else they can go to get permits.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1071]
## Notes
* What are things we should consider when making this story *

## Acceptance Criteria
- [x] The MBS vendor link takes the user to the forest Christmas Tree page where they can navigate to a brochure, or other information.

## Tasks
- [x] Update the "Local Vendors" link in the contact us section to take the user to this location:  
https://www.fs.usda.gov/detail/mbs/passes-permits/forestproducts/?cid=fseprd602862
- [x] PO approved

## Definition of Done
- [x] Pull requests meet technical definition of done
- [x] Usability tested
