### ISSUE TITLE
SPIKE MBS special uses permits to SUDS timing restrictions

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1074]
## Notes
* What are things we should consider when making this story *

Brian Lee is asking: regarding the timeframe that applicants can apply. I know the minimum lead time is 3 days, but is there a maximum set? Last time I tried to issue a permit well in advance, I do not believe SUDS would let me go further than 6 months in advance. If we are to respond to applications within 48 hours and (if approved) issue the permit within 2 weeks, is it possible that a person could apply, get approval, and not be able to get the permit within that 2 week timeframe because SUDS won’t let us?
![NCGU Exceeds max term limit](https://user-images.githubusercontent.com/33435621/69286814-1b159800-0ba9-11ea-8581-111c6fd6f845.JPG)

Also, would changing the Authorization ID in SUDS affect the electronic application side of things?

## Acceptance Criteria
- [x] We are prepared to respond to Brian's questions brian.lee@usda.gov
- [x] We know what to follow up on.

## Tasks
- [x] Research/test SUDS to answer the timing restriction question
- [x] Research/test SUDS to answer the authorization ID question
- [x] PO approved

## Definition of Done
- [x] A response is sent to Brian

**Comment by ASprinkle** [comment]
[SUDS TimingRestriction Spike1074.docx](https://github.com/USDAForestService/fs-open-forest-platform/files/3881776/SUDS.TimingRestriction.Spike1074.docx)

[SUDS AuthID Spike1074.docx](https://github.com/USDAForestService/fs-open-forest-platform/files/3881819/SUDS.AuthID.Spike1074.docx)

**Comment by ASprinkle** [comment]
No follow up items needed or identified.
