### ISSUE TITLE
(MVP) As an SU Applicant, I'd like to be able to input my email address with upper-case characters

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1076]
## Notes

This is the same issue from story #1019 - where it appears the issue was resolved only on the Christmas tree platform.

It appears the same instance is occurring in the non-commercial group use and in the temporary outfitting and guiding application pages.
![image](https://user-images.githubusercontent.com/33435621/69388506-e0316400-0c7d-11ea-8efa-a7f8f0517637.png)

## Acceptance Criteria
- [x] Applicants can enter their email address with upper and lowercase characters without error
- [x] validation match is successful

## Tasks
- [x] Update code to handle upper and lower case inputs
- [x] PO approved

## Definition of Done
- [x] Pull requests meet technical definition of done
- [x] Usability tested

**Comment by carlsonem** [comment]
This has been resolved on Christmas Tree, would expect it to be similar work

**Comment by ASprinkle** [comment]
This looks great on staging. I am able to enter upper case and lower case letters and number without error.
![image](https://user-images.githubusercontent.com/33435621/70463907-ac727e80-1a72-11ea-899e-4d44dbd53291.png)
![image](https://user-images.githubusercontent.com/33435621/70463914-b0060580-1a72-11ea-9f1f-fbe9611c6924.png)
