### ISSUE TITLE
As an Open Forest visitor providing feedback I'd like to know what to expect when I submit my feedback so that I feel good about providing it.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1080]
## Notes
We have a design from Story #984 that is ready to implement.
https://github.com/USDAForestService/fs-open-forest-platform/issues/984#issuecomment-557649339

## Acceptance Criteria
- [x] Users can see on the feedback page that they if they want a response, they'll need to email the team
- [x] Users know their feedback is anonymous

## Tasks
- [x] Build the completed design for the feedback (introductory text and hint text.) https://github.com/USDAForestService/fs-open-forest-platform/issues/984#issuecomment-557649339
- [x] Build the completed design for the thank you banner that the user sees once they've submitted their feedback. https://github.com/USDAForestService/fs-open-forest-platform/issues/984#issuecomment-557649339
- [x] PO approved

## Definition of Done
- [x] Pull requests meet technical definition of done
- [x] Compare finished design with mockup
- [x] Usability tested

**Comment by ASprinkle** [comment]
Copied from #984 
Thanks for the meeting @Rebekah-Hernandez @ASprinkle @lisamcmichael. 
Here are the updates for review:

**FEEDBACK FORM**
https://open-forest-staging.app.cloud.gov/feedback

Modified h1-sub: _Tell us what you like about the website 
or what we can be doing better._

New hint text:  _Your feedback is anonymous. If you have questions, or would like a response, email us at SM.FS.OpnFrstCsSup@usda.gov._

![Screenshot 2019-11-22 13 34 24](https://user-images.githubusercontent.com/26801590/69451973-a53b3900-0d2e-11ea-943a-56a8293308a1.png)





**POST-FEEDBACK SECTION**
Modified usa-alert-info section: _Thank you for sharing your feedback. 
For help or technical questions, email us at SM.FS.OpnFrstCsSup@usda.gov._

![Screenshot 2019-11-22 13 40 17](https://user-images.githubusercontent.com/26801590/69452161-0c58ed80-0d2f-11ea-8b9b-0789571d44b4.png)

**Comment by briandavidson** [comment]
Hi @ASprinkle - this one's ready to go to awaiting acceptance but just wanted to check really quick.. do we maybe want to do something like this here since the email address is a little funky?

![image](https://user-images.githubusercontent.com/5187168/71201179-7b126380-2267-11ea-915f-eac26373bf40.png)

**Comment by ASprinkle** [comment]
@briandavidson let's keep it as is for now with the full email address.  We may make an improvement like that later. We discussed making a "here" link in the footer, but decided against it, i think because of browser popup limitations (?)...  The banner is looking really good in staging: 
![image](https://user-images.githubusercontent.com/33435621/71586737-0ee9f800-2ad0-11ea-901d-e987f841958d.png)

One tiny fix on the enter feedback screen, looks like an odd carry over - can we remove this extra line with the "."? - circled in the screen shot here: 
![image](https://user-images.githubusercontent.com/33435621/71586762-25904f00-2ad0-11ea-98a6-f144335169f9.png)

**Comment by briandavidson** [comment]
looks like an extra `.` snuck in there. i just addressed it and will create a PR in just a few.

**Comment by ASprinkle** [comment]
Looks good!
![image](https://user-images.githubusercontent.com/33435621/71634790-eba87100-2bd3-11ea-88a5-d7beb8b3db12.png)

**Comment by ASprinkle** [comment]
![image](https://user-images.githubusercontent.com/33435621/72013467-c4c0ef00-3212-11ea-9119-4b07f7aeffe3.png)
in Prod! :)
