### ISSUE TITLE
As a customer providing feedback I would like to know what my limitations are, and I would like to be able to provide more text so that I can give all my feedback.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1081]
## Notes
* What are things we should consider when making this story *
Currently the text box allows very few characters, and not enough to fill up the size of the text box provided.
![image](https://user-images.githubusercontent.com/33435621/69481713-6a85df00-0dc8-11ea-897b-ff3e5a6946ac.png)

## Acceptance Criteria
- [x]  The customer can enter many characters into the text box, filling up the size of the text box.
- [x] The customer knows when they've entered too many characters.

## Tasks
- [x] Determine appropriate character limit
- [x] Build to allow more characters
- [x] Research default mechanism for character limit for other parts of the application
- [x] Show error based on default mechanism "A maximum of [X number] characters are allowed"
- [x] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Usability tested

**Comment by ASprinkle** [comment]
As examples:
Temp Outfitting and guiding character error:
![image](https://user-images.githubusercontent.com/33435621/69481787-2ba45900-0dc9-11ea-8aad-fb124513190c.png)

Non-commercial group use character error: 
![image](https://user-images.githubusercontent.com/33435621/69481792-352dc100-0dc9-11ea-959b-60b587bda319.png)

**Comment by ASprinkle** [comment]
Discussion during refinement resulted in the decision for 1,000 character limit.

**Comment by ASprinkle** [comment]
@briandavidson I cleared my cache, and this was the result after I hit the "Submit" button.  Instead of getting the  thank you banner I was stuck on the give feedback screen, and the box was highlighted green.
![image](https://user-images.githubusercontent.com/33435621/70172936-aaeb3400-16c9-11ea-9d42-3c4ff0329143.png)

**Comment by briandavidson** [comment]
Hey @ASprinkle - our database has a default maximum length of 255 for text strings that I was unaware of. I just made some changes that should override this default and allow use to specify the 1000 character limit we want. It should be up on staging shortly.

**Comment by ASprinkle** [comment]
@briandavidson I checked it out in staging, and when I enter 255 characters or less, I am able to successfully submit feedback. However, when I enter greater than 255 characters, I remain stuck on the feedback screen without any error message.   So no matter what character limit we choose, is an error message being built in also, so that a customer know what to do if they enter too much? there is text in the tasks above for an error message.  
Do you think a design of the error message should be mocked up?

**Comment by briandavidson** [comment]
@ASprinkle I'm guessing the changes weren't deployed yet at the time you checked. Take another look when you get a chance, I think it's working the way you were expecting now.

**Comment by ASprinkle** [comment]
This is working really well! @briandavidson @Dmac26 :) 
![image](https://user-images.githubusercontent.com/33435621/70255544-da3a8900-173b-11ea-88a2-c5b1a7498b60.png)
![image](https://user-images.githubusercontent.com/33435621/70255553-dd357980-173b-11ea-8ae7-2c71f06354dc.png)

I was able to submit successfully with up to 1k characters.
