### ISSUE TITLE
SPIKE find out how "Cloning (Legacy Test and Development Environments)" may impact our SUDS tests/dev.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1083]
## Notes
We received and email: " Cloning  (Legacy Test and Development Environments) scheduled for December 2 through December 6, 2019 (system)"

## Acceptance Criteria
- [ ] We understand how this update may impact our dev/test environments as we continue building on the special uses platform.

## Tasks
- [ ] Research to find out how this cloning may impact our tests.
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
email from Matt: The last cloning didn’t affect the API, so we should be OK.
