### ISSUE TITLE
(MVP) As an SU applicant I'd like to know what to do if I'm in the NCGU application with less than 75 people, so that I don't feel lost.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1084]
## Notes
* What are things we should consider when making this story *
Spike #1067 provides more context and background to the development of this story.

## Acceptance Criteria
- [x] The applicant is informed that (per regulation) a permit is not required if they have less than 75 people. However, they should contact their local forest if they are planning a large group gathering so that their local forest can provide helpful information to them. 

## Tasks
- [x] Mock up the Updated the Learn More page text.
- [x] Mock up the Updated error text in the NCGU application.
- [x] Mock up the Updated Help me find a permit solution text.
- [x] Design Dev hand off meeting.
- [x] Build the updated Learn More page text.
- [x] Build the updated error text in the NCGU application.
- [x] Build the updated help me find a permit solution text.
- [x] PO approved

## Definition of Done
- [x] Pull requests meet technical definition of done
- [x] Compare finished design with mockup
- [x] Usability tested

**Comment by ASprinkle** [comment]
![image](https://user-images.githubusercontent.com/33435621/69578722-eb3e0a00-0f85-11ea-9c4c-5806be2386e5.png)
Something like: "Your activity does not require a permit (regulation citation link). However, it may be helpful if you have a large group, to contact your local office to find out about any special restrictions.

![image](https://user-images.githubusercontent.com/33435621/69578844-217b8980-0f86-11ea-9b5a-9d9deb9549e9.png)
something like this: "According to the regulation, permits are required for 75 or more people. However, some forest may have special considerations, contact your local forest if you have questions."

![image](https://user-images.githubusercontent.com/33435621/69578974-6a334280-0f86-11ea-8964-1b7d5964c95e.png)
something like "It appears you have entered fewer than 75 total attendees. For fewer than 75, a permit is not required. For large groups of less than 75 people, contact your local office."

**Comment by ASprinkle** [comment]
@mtlaney 
This is looking really great. we've got a small typo though, in the Learn More page: "According to the regulation, permits are required for 75 or more people. However, some forest may have special considerations, contact your local forest if you have questions." we need an "s" at the end of "forests" where it reads "However, some forest"s" may have..."  

This story is considered PO approved and Ready for Master, just need to fix the small typo. Thanks!
