### ISSUE TITLE
SPIKE Customer Service issues related to printing from confirmation page and customer receiving no emails (spam, junk, inbox).

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1087]
## Notes
* What are things we should consider when making this story *

## Acceptance Criteria
- [ ] We have an understanding of what's going on.
- [ ] We have an understanding of what's needed for next steps.

## Tasks
- [ ] Dev to meet with Customer Service team to gain understanding of customer issues related to printing and receiving emails.
- [ ] Reviewing customer issues related to printing.
- [ ] Review customer issues related to receiving emails.
- [ ] Document results.
- [ ] PO approved

## Definition of Done
- [ ] Tasks and A/C are complete.
- [ ] Follow up stories are created, if necessary.
- [ ] Results are documented.

**Comment by ASprinkle** [comment]
These customer service issues regarding email issued occurred at a time that overlapped a push to production uppercase and lower case inputs to email.  Printing issues were isolated/few,
