### ISSUE TITLE
As a customer who completed the christmas tree permit purchase process I'd like to be directed back to my confirmation page after I choose to give feedback so that I can print my permit after.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1098]
## Notes

If a customer chooses to give feedback before printing or saving their permit from the confirmation page, they will not be able to print/view their permit from confirmation page after giving feedback.
This screen shot shows what the customer sees when they return to their previous page after submitting feedback:
![image](https://user-images.githubusercontent.com/33435621/70254332-c2620580-1739-11ea-960e-025a8bb585b5.png)
This is a screen shot of what the customer sees when they select print as shows on ^ screen shot
![image](https://user-images.githubusercontent.com/33435621/70254752-7368a000-173a-11ea-9066-45c814f126f2.png)

## Acceptance Criteria
- [x] when returning to the confirmation page after giving feedback, the customer can view their order details.
- [x] when returning to the confirmation page after giving feedback, the customer can print their permit and rules if they choose to.
- [x] The customer knows their feedback has been successfully submitted.

## Tasks
- [ ] Needs Dev refinement.
- [x] PO approved

## Definition of Done
- [x] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [x] Usability tested

**Comment by ASprinkle** [comment]
More screen shots of feedback workflow from confirmation page:
![image](https://user-images.githubusercontent.com/33435621/70254851-a01cb780-173a-11ea-8862-9653977dce79.png)
![image](https://user-images.githubusercontent.com/33435621/70254858-a317a800-173a-11ea-9938-f3b52510a274.png)
![image](https://user-images.githubusercontent.com/33435621/70254907-b4f94b00-173a-11ea-86b0-b4cb2e2264ad.png)
![image](https://user-images.githubusercontent.com/33435621/70254916-b88cd200-173a-11ea-9e2c-e672bfb10362.png)
![image](https://user-images.githubusercontent.com/33435621/70254923-bc205900-173a-11ea-80a9-5156619d9520.png)

**Comment by ASprinkle** [comment]
@briandavidson 
I spent some time playing around with this one.  It looks like the return to the confirmation page is not fully functional.
Here are a series of screen shots:

Initial Confirmation page after completing purchase process:
![image](https://user-images.githubusercontent.com/33435621/73110590-de716000-3ebb-11ea-84a8-c0fdfe3bd64d.png)
![image](https://user-images.githubusercontent.com/33435621/73110592-e29d7d80-3ebb-11ea-9784-822db2b47eed.png)

Feedback page (admin portal since I logged in to change dates)
![image](https://user-images.githubusercontent.com/33435621/73110615-f5b04d80-3ebb-11ea-9195-7e2a6588e89b.png)

After hitting the submit button, I was directed back to a confirmation page, but it didn't look the same as my initial one:
![image](https://user-images.githubusercontent.com/33435621/73110645-11b3ef00-3ebc-11ea-9602-c4b711c88adc.png)

and when I selected Print, a window with no information popped up:
![image](https://user-images.githubusercontent.com/33435621/73110657-22646500-3ebc-11ea-92a4-626d827ca6ab.png)

**Comment by ASprinkle** [comment]
@briandavidson  I noticed that this story is not refined for Dev, is there some refinement that we can work on to identify tasks that would be helpful?

**Comment by ASprinkle** [comment]
I checked this, and this is what I see when I return to my confirmation page after submitting feedback 
![image](https://user-images.githubusercontent.com/33435621/73386255-6ae89d80-4283-11ea-9ada-5221dbd88418.png)

**Comment by ASprinkle** [comment]
Success!
![image](https://user-images.githubusercontent.com/33435621/73397921-6a302580-42dc-11ea-9c59-00a08d948093.png)
![image](https://user-images.githubusercontent.com/33435621/73397927-6c927f80-42dc-11ea-92c7-304cf9997f3b.png)
