### ISSUE TITLE
As a customer who requests a refund or an admin/support POC searching for info, I would like to have access to the information I need so that I can complete the refund process.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1099]
## Notes
During the 2019 Christmas tree season, we heard from customers who wanted refunds.
Refund requests were due to errors during payment process in pay.gov that resulted in multiple transactions from the customer, when they intended to be charged only 1 time.

The team met with ASC and CFO group to determine process for customers to obtain refunds.

Open Forest team does not issue refunds, but customers can work with ASC to obtain refunds if funds have indeed been settled.

## Acceptance Criteria
- [ ] Customers have access to know what their pay.gov tracking ID is for each purchase.
- [ ] Administrators can see pay.gov tracking ID associated with Christmas tree permit numbers when Generating Reports.

## Tasks
- [ ] Design a column for the generate reports table for a Pay.gov Tracking ID.
- [ ] Dev to research how to automate the pay.gov tracking ID into the customer confirmation page.
- [ ] Dev to research how to automate the pay.gov tracking ID into the confirmation email.
- [ ] Dev to research how to automate the pay.gov tracking ID into the generate reports table.
- [ ] Build based on results of research.
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
@Dmac26 @Rebekah-Hernandez  I created this story in the midst of working through the refund process.  When reviewing this, it seems we no longer need to have the pay.gov tracking ID populated within Open Forest given the steps that ASC group lined out for the refund process, correct?

**Comment by Rebekah-Hernandez** [comment]
Yes, that should be correct. We don't pull the pay.gov tracking ID, ASC is able to pull that out. We only need the information that Dylan included

**Comment by ASprinkle** [comment]
Closing. No work needed on behalf of Dev, no improvements to the site identified in order to issue refunds.
