### ISSUE TITLE
As a user I'd like to understand browser compatibility so that I can get my permit easily.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1102]
## Notes
 
As of 12/9/2019 there have been 15 instances in the Feedback report that are related to users not being able to continue to check out.

## Acceptance Criteria
- [ ] We have an understanding of customers browser compatibility issues.
- [ ] We know whether or not we will build in  a notification to non-compatible browser users.

## Tasks
- [ ] Research users response to notification to use correct browser.
- [ ] Understand quantity of issues received related to compatibility issues (audit log review 2019 season).
- [ ] Validate compatibility with Microsoft Edge.
- [ ] Mock design for notification language/banner
- [ ] PO approved.

## Definition of Done
- [ ] Completed mock up
- [ ] Usability tested

**Comment by ASprinkle** [comment]
IE new browser is called Edge.

**Comment by ASprinkle** [comment]
Closing this issue - we're going to implement the banner approach first (#1165 ) - platform wide.  We learned enough from the feedback tool and the Christmas tree season to know that the issue needs to be addressed.  We know we cannot build the system now to be compatible with all browsers, so communicating to customers up front ahead of time is preferred.
