### ISSUE TITLE
SPIKE Content Update Efficiency Research

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1103]
## Notes

This story is a design, UX related SPIKE - We want to learn more about what could be done to improve efficiencies related to content updates for Christmas trees.  What might be needed to achieve an improved efficiency here?

## Acceptance Criteria
- [x] We have an understanding of what is possible to improve efficiencies around content updates for Christmas trees for DEV.
- [x] We have an understanding of what is desired to improve efficiency around content updates for Christmas trees for FS Staff.
- [x] We have documented the information, and are ready to design some concepts around what we've learned.

_Research Topline summary: https://usfs.box.com/s/v803afbtq50ehqopbmtgitqu9ev9aoa8_

## Tasks
- [x] Meet with Dev to find out how efficiencies can be gained regarding Christmas tree content updates.
- [x] Select POCs/FS staff (Amber)
- [x] Invite 5 POCs/FS staff to interview
- [x] Create simple interview guide (Lisa)
- [x] Meet with some POC FS Staff from pilot forests (determine qty, 5?).
- [x] Document research results
- [x] Draft Topline Summary in Word/post to Pinyon
- [x] PO approved

## Definition of Done
- [x] A/C and Tasks are completed.
- [x] Documentation is in Pinyon, and linked to this story.

**Comment by lisamcmichael** [comment]
@ASprinkle Could you identify the 5 forest POCs? I can get the times set up to meet with each of them (sooner than later). 30 minutes should be enough. We could include Rebekah (mentoring).

**Comment by ASprinkle** [comment]
> @ASprinkle Could you identify the 5 forest POCs? I can get the times set up to meet with each of them (sooner than later). 30 minutes should be enough. We could include Rebekah (mentoring).

on it @lisamcmichael

**Comment by ASprinkle** [comment]
@lisamcmichael  
Christian on the Willamette NF christian.mercado@usda.gov (confirmed available)
Rebecca on the Mt. Baker Snoqualmie NF rebecca.busscher@usda.gov (confirmed available)
Laura on the Arapaho and Roosevelt NF laura.c.shaffer@usda.gov (confirmed, available next week)
Cara on the Mt. Hood NF Cara.Lewis@usda.gov (confirmed available)
Darcy on the Umatilla NF darcy.weseman@usda.gov (emailed a notification)

Others in the event there's a scheduling conflict for some:
Jeremy Fields, Deschutes/Ochoco jeremy.fields@usda.gov
Jodi King, Arapaho Roosevelt jodi.king@usda.gov
Leo Silva, Okanogan-Wenatchee leonardo.silva@usda.gov
Deb Gutierrez, Umatilla NF debra.gutierrez@usda.gov

**Comment by lisamcmichael** [comment]
@ASprinkle The interview guide w/ the Forests, should be a conversation starter. Here are some initial ideas:

- For next season, we want to remove "road blocks" to make it easier to update and manage content on your on your Open Forest site. What would you like to see changed so that it's easier to be a content editor?

- What Open Forest Xmas tree content are you managing and/or updating the most? Tell me about that in more detail.  How is that working for you? (Probe on answers to generate more ideas for improvement.)

- If we could only change one things to make it more efficient to manage/edit content on your Open Forest Xmas tree site, what would it be?

**Comment by lisamcmichael** [comment]
Notes from today's design/dev pairing:

**Developer input (Brian and Mike) 12.11.19**

- Key question: Not how, but "what" do we want to improve?
		○ Next: Forms (a page on the site to edit forms) a design similar to an application form
		○ Next: design w/ input fields populated (ex: costs, tree species details, cutting areas, etc.) and Admin can update it.
		○ Need: Version control needed (to prevent multiple editors to over write updates)
		○ Need: Auto upload maps (might be a big leap for Forests) - Forests will need guidelines to help improve the process.
		○ Another concern is prohibited tree species (Mike)
- Consideration: How would this impact the "new" admin management "platform"?
- Consideration: Security/privacy concerns? Brian - my hunch is "no" but check with John. 

Lisa S:
- Consideration: would the design have to be integrated or an external form? 
	• Mike:
		○ Tree height would be a dropdown (pre-determined)
Other content might or might not be integrated into the design (it depends on the content type).

**Comment by lisamcmichael** [comment]
@ASprinkle  I emailed 5 forests and "cc" @Rebekah-Hernandez to set up a time with each one. 

Christian on the Willamette NF christian.mercado@usda.gov (confirmed available)
Rebecca on the Mt. Baker Snoqualmie NF rebecca.busscher@usda.gov (confirmed available)
Laura on the Arapaho and Roosevelt NF laura.c.shaffer@usda.gov (confirmed, available next week)
Cara on the Mt. Hood NF Cara.Lewis@usda.gov (confirmed available)
Jeremy Fields, Deschutes/Ochoco jeremy.fields@usda.gov

Rebekah, I'll grab a few minutes with you this afternoon to 'sync' on the "interview" approach. Thx.

**Comment by lisamcmichael** [comment]
@ASprinkle Quick update...

Completed 2 retro sessions (Rebecca/MBS) and (Jeremy/D/O). Rebekah's notes are uploaded. I took paper notes during both calls, and I'll merge those w/ her notes. 

After we complete 5 sessions, we'll clean up notes and create a topline summary.

**Comment by lisamcmichael** [comment]
@ASprinkle and @Rebekah-Hernandez 

**I started the topline summary. See you soon.
https://usfs.app.box.com/notes/576450697151**

**Comment by lisamcmichael** [comment]
Hello @ASprinkle 
**The Topline Summary in Word: https://usfs.box.com/s/v803afbtq50ehqopbmtgitqu9ev9aoa8**

Cheers/happy holiday and Merry Christmas
Will keep in touch

**Comment by ASprinkle** [comment]
For awareness, I am deleting the "Notes" documents, and combining the final Topline summary and the discussion guide docs to minimize "like" documents in the list.
