### ISSUE TITLE
As a special use admin I do not want to be confused by the "cancel application" button when I am viewing application details so that I can easily make a decision.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1105]
## Notes
The "cancel application" button feature is a function that should only be available to the applicant who is viewing the details of the application they have submitted.  

Having the cancel application button available to the administrator creates some confusion between whether or not they should "cancel" or "reject" an application.  FS admins should only have the option to Accept, Hold, or Reject applications.

Currently, the cancel application button is present in admin view application details, and it routes the admin through this workflow, inappropriately routing them through login.gov.
![image](https://user-images.githubusercontent.com/33435621/70550557-c8395b80-1b2a-11ea-8216-8702c7cd65d4.png)
![image](https://user-images.githubusercontent.com/33435621/70550560-cb344c00-1b2a-11ea-8c4c-88f4ff24a8c1.png)
![image](https://user-images.githubusercontent.com/33435621/70550570-ce2f3c80-1b2a-11ea-8c06-8d247cc11a80.png)

## Acceptance Criteria
- [x] The cancel application button is not present for an FS admin view.
- [x] FS admins see Accept, Hold, and Reject as action options.
- [x] The cancel application button is still available for applicants who are viewing their application details.

## Tasks
- [x] Remove the cancel application button from FS admin view.
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
This looks great! @briandavidson 
![image](https://user-images.githubusercontent.com/33435621/71586206-45bf0e80-2ace-11ea-8b25-bdcf5dffd172.png)
