### ISSUE TITLE
As an potential applicant I want setting up a profile in login.gov to be tested in PROD so that I know it works.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1106]
## Notes
* What are things we should consider when making this story *

https://openforest.fs.usda.gov/mbs

## Acceptance Criteria
- [x] Applicants can successfully create a login.gov account, and be routed back to Open Forest application page upon completion of account set up.

## Tasks
- [x] test at least one instance.
- [x] PO approved

## Definition of Done
- [x] A/C and tasks are completed.

**Comment by ASprinkle** [comment]
Amber and Eric paired on this story today. Eric started at https://openforest.fs.usda.gov/mbs then was routed to login.gov to "Apply" for NCGU permit.  Eric successfully created an account, and upon completion was routed to the NCGU application page.
