### ISSUE TITLE
SPIKE special uses platform URL

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1108]
## Notes
currently the PROD url is: https://openforest.fs.usda.gov/mbs

It may make more sense to create this url so that it indicates the permit platform the user is on:
openforest.fs.usda.gov/special-uses/mbs

## Acceptance Criteria
- [x] We have an understanding of what it would take to update the URL

## Tasks
- [x] research URL update complexities between Open Forest and Login.gov redirects.
- [x] research URL update complexities for Open Forest auto generated emails with hyperlinks.
- [x] research URL update complexities for breadcrumbs.
- [x] research URL update complexities associated with SUDS
- [] if simple, make updates.
- [x] if complex, create story to address url update in the future.
- [x] document research for future story.
- [x] PO approved

## Definition of Done
- [x]  A/C met
- [x] Tasks completed

**Comment by ASprinkle** [comment]
@mtlaney I created this spike based on our chat. I took a stab at tasks and A/C.  @carlsonem FYI follow up from our chat yesterday.

**Comment by mtlaney** [comment]
@ASprinkle after initial research, I believe we can be in the clear to move forward on this. However it is a bit involved, likely an 8 or 13 just because of how many places that URL is going to touch. It will involve a quite a bit of testing before being ready for Prod. However I still think this is an issue we should capture in a story and get the work started.

**Comment by ASprinkle** [comment]
@mtlaney Thanks - I don't think we will start work on this right now. This may be a more appropriate piece of work once we start on the landing page.  Since we're planning launch the week of 12/15, I don't think it would be wise to introduce more testing and risk at this point, especially considering what we've got now for a url meets MVP.  @aaronburk  updating the url for special uses will need to be done, just not right now if we're planning launch this week.  Let's make a new issue for this to be prioritized.

**Comment by ASprinkle** [comment]
@mtlaney BTW great work researching that!

**Comment by ASprinkle** [comment]
I created story #1111 as a follow up to this SPIKE.
@mtlaney once you update the documentation task, this story can be moved to "done"

**Comment by mtlaney** [comment]
### Currently /mbs is the main route for special use permits (noncommercial and temp). 
#### Current nested child routes that would need re-routed listed below:
 - help me pick
 - non-commercial/learn more
 - temp-outfitters/learn more
 - applications
 - applications/noncommercial-group-use/new
 - applications/noncommercial-group-use/:id/edit
 - :type/submitted/:id
 - temp-outfitters/new
 - temp-outfitters/:id/edit

#### Would also need to rewrite our entire app.po.ts routes for testing. All of our redirects post login / logout in server files would need to be handled with the new routes.

**Comment by ASprinkle** [comment]
Thanks!
