### ISSUE TITLE
As a Fre-Win Christmas tree manager I'd like to be added as an admin so that I can run reports.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1109]
## Notes

Annette Shullanberger has been a POC for the Christmas tree program, and we should add Annettee as an administrator for the Fremont-Winema National Forest

## Acceptance Criteria
- [x] We've confirmed that Annette can access the administrator functions for Christmas trees in Open Forest

## Tasks
- [x] Add Annette as an administrator for the Fremont-Winema National Forest annette.shullanberger@usda.gov
- [x] Confirm with Annette that her access works.
- [x] PO approved

## Definition of Done
- [x] A/C met
- [x] Tasks Complete

**Comment by abdul-fs** [comment]
She is added in production and staging. lets validate with her.

**Comment by abdul-fs** [comment]
Confirmed with Annette she can get on prod and staging site with fremont forest.
