### ISSUE TITLE
As a public user I want an Open Forest URL that makes sense so that I can get to where I want to go.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1111]
## Notes
This is a follow on to SPIKE #1108
This story updates the URL for Christmas Trees and Special Uses, initiating a main landing page URL.
Currently Christmas Tree url is: https://openforest.fs.usda.gov/christmas-trees/forests 
and the Special Uses url is: https://openforest.fs.usda.gov/mbs

Currently when someone navigates to openforest.fs.usda.gov they are automatically routed to the Christmas tree page.

We want people to be able to navigate to openforest.fs.usda.gov and then choose their path.  Doing this would update the urls for both pagesl:

## Acceptance Criteria
- [ ] We have a main landing page url where people can choose their path.
- [ ] We have an updated url for special uses that matches the workflow from main landing page.
- [ ] We have an updated url for christmas trees that matches the workflow from main landing page.

## Tasks
- [ ] remove automatic re-reoute to Christmas tree landing page from openforest.fs.usda.gov
- [ ] update special uses URLs
- [ ] update Christmas trees URLs
- [ ] Validation of acceptance criteria completed
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
#604 #1123

**Comment by carlsonem** [comment]
OBE, change will automatically be implemented with changes to the code, no proxy change needed.
