### ISSUE TITLE
Add Eric Turbeville to staging site access as FS admin

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1112]
## Notes
Eric is SUDS redesign Product Owner
He would like access to Open Forest special uses admin functions in staging so that he has an idea of how the system works.

## Acceptance Criteria
- [x] Eric can access Special Uses staging sites
https://open-forest-staging.app.cloud.gov/mbs
 https://open-forest-staging.app.cloud.gov/admin/applications
- [x] Eric can accept applications to suds

## Tasks
- [x] Add Eric to staging eAuth whitelist
- [x] research Eric's Accept to SUDS error reasoning
- [x] resolve Eric's Accept to SUDS error
- [x] PO approved

## Definition of Done
- [x] A/C and Tasks are done

**Comment by ASprinkle** [comment]
![image](https://user-images.githubusercontent.com/33435621/71008822-1bb52780-209e-11ea-9f43-533ad9eb2e99.png)

**Comment by abdul-fs** [comment]
I have confirmed with him yesterday. He is able to get on staging without any issues.

**Comment by ASprinkle** [comment]
@abdul-fs  Moving back into In Progress - RE #259 notes when Eric tried to accept and application to SUDS he was presented with an error and has not been able to accept and application to SUDS in Staging.

**Comment by ASprinkle** [comment]
@abdul-fs are there additional tasks that you think would be helpful? I edited them a bit from our discussion at stand up.

**Comment by abdul-fs** [comment]
It looks like multiple application has been submitted with same contact. Lets replicate the same. we need to find out same contact can handle submitting two application at once.

@mwreiss do we have suds team we can follow up?

**Comment by ASprinkle** [comment]
Is the error a result of: 
a SUDS issue, 
a result of an Open Forest issue,
or a roles/privileges issue?

We completed research recently around SUDS contact information #679  - and we understood that there wasn't anything set up to keep people with the same names or addresses submitting an application

**Comment by abdul-fs** [comment]
@briandavidson @mtlaney @mwreiss is this a bug? can open forest mbs submits more application with same contact.

@mwreiss we need to check with suds team for roles/privileges.

**Comment by briandavidson** [comment]
@abdul-fs it looks like it's an issue with this user's roles and does not appear to be a bug.

**Comment by abdul-fs** [comment]
Thanks brian. yes its issue with user's role. Thanks Amber. we submitted Eric 2nd application having same details without any error.

**Comment by mwreiss** [comment]
@abdul-fs  Looks like you  and @ASprinkle  got this one figured out.  Thank you!

**Comment by abdul-fs** [comment]
Eric has submitted an request for his roles same as amber. Waiting on suds team.

**Comment by abdul-fs** [comment]
Team: Eric role is still pending. Is there any way we can expedite his NRM request. @mwreiss

**Comment by mwreiss** [comment]
@abdul-fs Pam Young would be the contact to expedite for staging/dev.  I noticed she was out over the past 2 weeks and just returned today, I'm guessing shes catching up on the backlog.  What role is he being added to, Forest Manager, ePermits role or something else?  I can send a follow up to Pam if needed.

**Comment by ASprinkle** [comment]
@mwreiss thanks.  Eric just needs access to our special uses staging environment to test interactions with accepting applications to SUDS. So he would need to be able to see admin stuff in our Open Forest staging environment, as well as see applications sent to SUDS for (0605 MBS) in NRM test/dev.  He's a Product Owner for the SUDS redesign team, and so is testing functions.

**Comment by mwreiss** [comment]
@ASprinkle Ok great!  Do you have an email or an initial request that was made to get access that I could reference with Pam?

**Comment by ASprinkle** [comment]
@mwreiss possibly...I'll see what I can find.

**Comment by abdul-fs** [comment]
@mwreiss I got this from Eric.  artf105106. if this helps.

**Comment by mwreiss** [comment]
@ASprinkle @abdul-fs  I still have access to the NRM teamforge site and noticed this ticket was completed 12/27.  In theory Eric should be good to go.  If he still has trouble we can ask Pam to look further.

![image](https://user-images.githubusercontent.com/50459930/71835129-72e36200-3076-11ea-96d0-61b6c01a153e.png)

**Comment by abdul-fs** [comment]
Eric is testing it again and will get back to us with results. if not we will have follow up meeting with him soon.

**Comment by ASprinkle** [comment]
![image](https://user-images.githubusercontent.com/33435621/72298574-51085300-3613-11ea-96df-406d8e6583c5.png)
Success @abdul-fs
