### ISSUE TITLE
As a user I do not want to be routed to the Christmas tree page when clicking apply

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1113]
## Notes
While testing in PROD:
Accessed the Open Forest special uses main page and the "Apply" button displayed with out the login.gov information on it. This is an expected occurrence when the user is already logged in.
![image](https://user-images.githubusercontent.com/33435621/71014935-9b93bf80-20a7-11ea-8ef4-5f83b6627e19.png)

Clicked on Apply, and it routed to login.gov, upon logging in, it then redirected to the Christmas tree page. 

We then cleared the cache and tried again. Upon this instance, the special uses main page showed the  login.gov language, routed to login.gov, routed to application page correctly.
If the user is not already logged in, the Apply button should say "Sign in with Login.gov" 
![image](https://user-images.githubusercontent.com/33435621/71015360-4f954a80-20a8-11ea-81d0-d66c5f6b523b.png)

## Acceptance Criteria
- [ ] We have an understanding of why the user might on occasion be redirected to the Christmas tree main page.

## Tasks
- [ ] Investigate
- [ ] Document investigation results in the comments of this story.
- [ ] PO approved

## Definition of Done
- [ ] A/C and Tasks are complete.

**Comment by ASprinkle** [comment]
![image](https://user-images.githubusercontent.com/33435621/71015457-7c496200-20a8-11ea-95a5-cfd1cee63524.png)
![image](https://user-images.githubusercontent.com/33435621/71015466-7f445280-20a8-11ea-8ccb-d3596a81b90a.png)
![image](https://user-images.githubusercontent.com/33435621/71015477-82d7d980-20a8-11ea-8aeb-99bfa7e20a3e.png)
![image](https://user-images.githubusercontent.com/33435621/71015483-866b6080-20a8-11ea-92d7-684933cf9f30.png)
![image](https://user-images.githubusercontent.com/33435621/71015492-89665100-20a8-11ea-8bcd-2b3750f2a27d.png)

**Comment by briandavidson** [comment]
🤔 It's odd that you were redirected to login.gov when the button read `Apply`, since it supposedly only displays that when you are already logged in.

**Comment by ASprinkle** [comment]
@briandavidson  yes - that is the expectation.  However in this scenario it had been some time between when the actual/original login happened, and when we revisited the page to test the site.

**Comment by ASprinkle** [comment]
@briandavidson the redirect to Christmas tree is an uncommon occurrence. it is infrequent and has been difficult to replicate.  It does not happen in every instance of selecting Apply after logging in. We think its some kind of cache issue, but we should not assume.

**Comment by mtlaney** [comment]
@ASprinkle @briandavidson here's what I can figure out on my end. It appears the login.gov and eauth are getting their wires crossed. So if you've logged into the application recently (and are currently logged into eAuth)

For instance see attached screen shot. The application recognizes me as an authorized admin user. However when I click Apply i'm re-directed to the login.gov page (since i'm not logged in thru login.gov, only eauth). This _shouldn't_ be an issue for the public, but I'm going to keep digging just to ensure. This is my pre-liminary diagnosis, and there could definitely be something else going on.

<img width="1352" alt="Screen Shot 2019-12-17 at 11 28 04 PM" src="https://user-images.githubusercontent.com/18233188/71055882-3da5bd00-2125-11ea-8e8d-3bd82d46f5d7.png">

**Comment by ASprinkle** [comment]
@mtlaney good update. Here's more info that I think supports the cross hairs you described between eAuth and Login.gov:

In this screen shot, when I selected my shortcut to visit MBS staging (not my MBS Admin staging) I was presented with this page, that shows I am logged in as an FS admin with the "Apply" buttons
![image](https://user-images.githubusercontent.com/33435621/71096101-9778a800-2162-11ea-9dae-a8a9cd7bba29.png)

When I hit "Apply" it routes me through Login.gov as it should since I was technically logged in as an Admin... although, when you do a true log in as an admin you do not see the MBS landing page...
![image](https://user-images.githubusercontent.com/33435621/71096200-c1ca6580-2162-11ea-8441-4a88bcf5908b.png)
![image](https://user-images.githubusercontent.com/33435621/71096213-c68f1980-2162-11ea-841b-559ca478ffac.png)

Once I finish the login.gov process, I am automatically routed to xmas tree page
![image](https://user-images.githubusercontent.com/33435621/71096283-d9a1e980-2162-11ea-8fe3-7d6d3bac7867.png)


Then when I select my shortcut for MBS special uses staging, I see the special uses page with the appropriate credentials in the upper right, showing that I am logged in as an applicant (no "admin" is shown) since I did go through login.gov - which is the applicants workflow.
![image](https://user-images.githubusercontent.com/33435621/71096372-05bd6a80-2163-11ea-9fb3-ae3ea0c1b638.png)

From there i was able to "Apply" normally.

I suppose I never "logged out" as an Admin yesterday.  So, this morning, when I selected my shortcut to MBS Staging (non-admin), the page shows me the crosshairs: FS Admin logged in credentials, with the applicant's page view.  

It seems like this instance could occur for an FS Admin if they do not log out, and then they try to view the main MBS landing page (applicant's page).

**Comment by mtlaney** [comment]
@ASprinkle the new changes should end a users session after 20 minutes of inactivity or after logging out. I don't believe we have a way to test this in staging however since it's tied to the eAuth session.

**Comment by ASprinkle** [comment]
ok. thanks Mike!
