### ISSUE TITLE
As a Christmas tree Admin for the Gifford Pinchot or Mt. Hood, I want to have the right people listed as admins so that we can do admin things

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1114]
## Notes
Robin Rose is retiring, last day Jan 3
Joe Gates is retiring, last day 12/20
Laura Pramuk Retired end of Dec

## Acceptance Criteria
- [x] Robin Rose no longer has admin access
- [x] Joe Gates no longer had admin access 
- [x] Laura Pramuk no longer had admin access
- [x] We have added new administrators to the system

## Tasks
- [x] Remove Robin Rose robin.rose@usda.gov
- [x] Remove Joe Gates joseph.gates2@usda.gov
- [x] Remove Laura Pramuk laura.pramuk@usda.gov
- [x] Find out who the new POC should be
- [x] Updated whitelist with new POC
- [x] Restage production and staging to take effect.
- [x] Add the new POC
- [x] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by abdul-fs** [comment]
Remove Robin Rose robin.rose@usda.gov
 Remove Joe Gates joseph.gates2@usda.gov
 Remove Laura Pramuk laura.pramuk@usda.gov 

has been removed from production and staging.

**Comment by ASprinkle** [comment]
@abdul-fs  I have a request out to the Gifford Pinchot, Dave Olson (who is the Natural Resources Staff Officer for the forest) to find out who our new POC should be for the Gifford Pinchot.

Heather Ibsen will be the new PAO point of contact for the Open Forest team, but we do not need to add her as an admin to the system, given the other Mt. Hood admins we already have.

**Comment by ASprinkle** [comment]
I moved this to blocked. We are waiting on FS GP response for new POC.

**Comment by ASprinkle** [comment]
[GP POC email.pdf](https://github.com/USDAForestService/fs-open-forest-platform/files/4068343/GP.POC.email.pdf)

**Comment by ASprinkle** [comment]
1/24 emailed again: Dave Olson and Tracy Calizon asking for GP POC names.

**Comment by ASprinkle** [comment]
New GP POC:

Phil Monsanto phil.monsanto@usda.gov (Acting Forest Silviculturist)
Sue Ripp susan.ripp@usda.gov (Public Affairs Officer)
Kyung Koh Willis  (Starting on 2/18/2020) Recreation Program Manager - not in the FS system yet.

**Comment by ASprinkle** [comment]
@abdul-fs  this one is ready now. I cc'd you on an email to them.  LMK if you have any questions. feel free to pull it into "in progress" whenever you're able.

**Comment by abdul-fs** [comment]
They both got added into production for forest giffordpinchot. I will reach out to them tomorrow.

Phil Monsanto phil.monsanto@usda.gov (Acting Forest Silviculturist)
Sue Ripp susan.ripp@usda.gov (Public Affairs Officer)

**Comment by ASprinkle** [comment]
@abdul-fs can we add Heather Ibsen in this story as well  heather.ibsen@usda.gov per the request email from Sue Ripp?

**Comment by abdul-fs** [comment]
Sure will add her.

**Comment by abdul-fs** [comment]
@ASprinkle @mwreiss This requires the services to be restarted in prod after hours. Can you approve it?

**Comment by mwreiss** [comment]
@ASprinkle its your call, but I'm ok with the services to be restarted after hours.
