### ISSUE TITLE
[Dec 20] Prepare Open Forest for potential government shutdown, Midnight (EST) Dec. 20.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1115]
## Notes
Potential exists for a government shut down Dec. 7 when funding is due to run out. As part of the shutdown process, we should prepare the site.
See also 2018 shutdown stories #476 (shutdown) and #480 (reinstate)

## Acceptance Criteria
- [ ] Forest visitors are not able to purchase a Christmas tree permit during the shutdown.
- [ ] Forest visitors are not able to "Apply" for a special use permit. the button is not actionable.
- [ ] The "buy permit" button is not available, nor is it accessible.
- [ ] There is information on the main Christmas tree page that explains why permits are not available, subsequent forest pages are not accessible.
- [ ] - [ ] There is information on the main special uses page that explains why permits are not available, subsequent forest pages are not accessible.

## Tasks
- [ ] Update the routes so that the main (openforest.fs.usda.gov) site doesn't redirect to Christmas trees, and so that it points to a shutdown page.
- [ ] Update routes so that (openforest.fs.usda.gov/mbs) points to a shut down page. 
- [ ] Create new shutdown page.
- [ ] Add the shutdown language to the site.

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
No shutdown Dec 2019.
