### ISSUE TITLE
Post-Government shutdown, reinstate the Open Forest site

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1116]
## Notes
If the government shuts down at midnight on Dec 20, the Open Forest site will not be available for the public.
See also stories from the 2018 shutdown #480 and #476 
When the potential government shut down ends, we would need to reinstate the Open Forest site so that: 
    - people are able to purchase Christmas tree tags if it is still Christmas tree season, or so that
    - people are able to learn about the Christmas tree program (without the buy permit button) if it is no longer 
Christmas tree season.
     - people are able to submit special use applications, and learn more.

## Acceptance Criteria
- [ ] The Open Forest Christmas tree site is accessible, and functioning.
- [ ]  Christmas tree season dates and "buy permit" button is correctly populated for each forest. 
- [ ]  The Open Forest special uses site is accessible and functioning.
- [ ]  Forest visitors can engage in the buy permit process if the Christmas tree season is still open.

## Tasks
- [ ] remove the redirects to the shutdown page.
- [ ] PO Approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
No shutdown Dec 2019.
