### ISSUE TITLE
As an applicant I want an automatic email to be sent to the FS administrator when I update my application so that I know my updates will be seen.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1118]
## Notes
When an applicant "saves" their application after updating it in response to an Admin's HOLD request, the Admin should receive an email notifying them that the application has been updated.
Currently, when the applicant saves the update to their application, the applicant receives an automated confirmation email that states "We are reviewing the additional information you provided", however, the FS administrator does not receive an email notification, and would not know there has been an update unless they log into Open Forest to review their pending applications list.

## Acceptance Criteria
- [x] FS administrators receive email notifications when applicants save an update to an application in response to a hold request.

## Tasks
- [x] Determine email notification to admins language (following existing schema).
- [x] Build in the feature to send an automated email to admins notifying admins of the updated "review" status.
- [x] PO approved

## Definition of Done
- [x] Pull requests meet technical definition of done
- [x] Compare finished design with mockup
- [x] Usability tested

**Comment by ASprinkle** [comment]
[New Application Submitted Email to Administrator.pdf](https://github.com/USDAForestService/fs-open-forest-platform/files/3975808/New.Application.Submitted.Email.to.Administrator.pdf)
[On Hold Status Email to Applicant.pdf](https://github.com/USDAForestService/fs-open-forest-platform/files/3975809/On.Hold.Status.Email.to.Applicant.pdf)
[Submitted for Review Email Notification to Applicant.pdf](https://github.com/USDAForestService/fs-open-forest-platform/files/3975810/Submitted.for.Review.Email.Notification.to.Applicant.pdf)
[Updated Application Under Review Email to Applicant.pdf](https://github.com/USDAForestService/fs-open-forest-platform/files/3975811/Updated.Application.Under.Review.Email.to.Applicant.pdf)

**Comment by ASprinkle** [comment]
@mtlaney I tested the email notifications and did not see that an administrator received an email once the applicant updated their application per the admin's hold and requested update.  Here are screen shots of the emails received to my inbox as the applicant, 
![image](https://user-images.githubusercontent.com/33435621/73105848-d8c14d80-3eae-11ea-9e50-da77b3a81539.png)

and to the Admin inbox for Admins:
![image](https://user-images.githubusercontent.com/33435621/73105857-dd860180-3eae-11ea-831b-2ccd9767907e.png)

In this story, we should see an email to the Admin inbox that notifies the admin that the applicant has updated their application, and that it's ready for further admin review.

**Comment by ASprinkle** [comment]
This is working really great, the admin is getting an email stating the application has been updated.
