### ISSUE TITLE
(MVP) As an MBS permit administrator I want to receive automatic emails when actions are taken in Open Forest for applications so that I know I need to do something..

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1119]
## Notes

We need to verify that MBS admins are receiving emails prior to launch.

## Acceptance Criteria
- [x] We have confirmed that MBS permit administrators receive automatic emails in all instances when emails are issued to FS admins.

## Tasks
- [x] Add sue.shermanbiery@usda.gov so that she receives automatic emails in all instances when emails are issued to FS admins.
- [x] Add orlando.garcia@usda.gov  so that he receives automatic emails in all instances when emails are issued to FS admins.
- [x] Add brian.lee@usda.gov so that he receives automatic emails in all instances when emails are issued to FS admins.
- [x] Verify (in production) with available administrator(s) on the MBS that they are receiving the system generated emails for applications.
- [x] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [x] Usability tested

**Comment by ASprinkle** [comment]
Comment from Abdul in Teams: [Yesterday 7:51 PM] Qureshi, Abdul - FS
    

they are added into production smtp list.                                                                                                                                                            "name": "smtp-service",    "credentials": {
      "admins": [
        "SM.FS.OpenFrstAdm@usda.gov",
        "adsprinkle@fs.fed.us",
        "aaronburk@fs.fed.us",
        "sue.shermanbiery@usda.gov",
        "orlando.garcia@usda.gov",
        "brian.lee@usda.gov"

**Comment by ASprinkle** [comment]
Testing email instances with Test Case Scenario 11 NCGU Application that I will also Cancel as an applicant. I'll use the customer support email inbox as the applicant's email address...

**Comment by ASprinkle** [comment]
@abdul-fs Success!! I was able to also verify with Sue Shermanbiery this morning over chat that she received automatic emails from my tests in PROD.
Here are screen shots
![image](https://user-images.githubusercontent.com/33435621/71095329-42886200-2161-11ea-8cad-f06e828cae5f.png)
![image](https://user-images.githubusercontent.com/33435621/71095341-49af7000-2161-11ea-9b8b-f26d6561baf5.png)
![image](https://user-images.githubusercontent.com/33435621/71095403-6481e480-2161-11ea-9f08-45c2bf98c0f7.png)
