### ISSUE TITLE
As an Open Forest customer, I want to be scheduled to provide input on an initial landing page wireframe design.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1122]
## Notes
See Epic #604 
dependent on #1052

## Acceptance Criteria
- [x] We know when testing will occur.
- [x] We know what we'll be testing

## Tasks
- [x] Draft a research plan for testing the main landing page wireframe with users.
- [x] Approve research plan.
- [x] Identify testing pool.
- [x] Update wireframe, and review with team
- [x] Research allowable video/screen share platform for testing with public users.
- [x] Schedule tests with users.
- [x] PO approved

## Definition of Done
- [x] Tests are scheduled.
- [x] Research plan is finalized.

**Comment by lisaredux** [comment]
@ASprinkle I move this to in progress since Rebekah and I began discussing today. 
Here's the research plan in progress if you'd like to weigh in. 
https://usfs.app.box.com/notes/595079817566

I'll put something on our calendars for early next week to discuss

**Comment by ASprinkle** [comment]
Sent email to FS POCs.  I bcc'd them in the email, so I have saved the sent version of it as a PDF here so that you can see who it was sent to: https://usfs.box.com/s/xnzzklit69xf5vtkkuru8vl4rtv4e1nu

**Comment by lisaredux** [comment]
Thanks @ASprinkle @Rebekah-Hernandez — I just made a wiki page for the research plan and it lives here https://github.com/USDAForestService/fs-open-forest/wiki/Research-plan---Landing-page-(story-1122)

**Comment by Rebekah-Hernandez** [comment]
@ASprinkle We've come up with the test script draft and it's ready for you to take a look at when you get a minute - https://usfs.app.box.com/notes/597239653158

**Comment by lisaredux** [comment]
@ASprinkle @Rebekah-Hernandez I created a new Pinyon folder called _Recruiting resources_ in _Research & Design_.  I moved some relevant folders into it and uploaded some email templates https://usfs.app.box.com/folder/100253110051

Let me know if you have any questions about it.

**Comment by ASprinkle** [comment]
I don't have questions - but I do have a slightly different christmas trees contacts list that I use... that I have saved in the Product Owner folder under Open Forest. It separates out "Current Contacts" from 2018 and older... https://usfs.box.com/s/iu1pyn8mjyaahi1ifxhx1ihih0m72nms

**Comment by ASprinkle** [comment]
> @ASprinkle We've come up with the test script draft and it's ready for you to take a look at when you get a minute - https://usfs.app.box.com/notes/597239653158

I reviewed the notes doc test script. Looks great! I added some edits in the document directly (strike through and bold purple)

**Comment by lisaredux** [comment]
> I don't have questions - but I do have a slightly different christmas trees contacts list that I use... that I have saved in the Product Owner folder under Open Forest. It separates out "Current Contacts" from 2018 and older... https://usfs.box.com/s/iu1pyn8mjyaahi1ifxhx1ihih0m72nms

That makes sense. One thing that I was able to do was copy files from one place to the other. I'll do that same with this one.

**Comment by Rebekah-Hernandez** [comment]
https://usfs.app.box.com/notes/597239653158

Here is the updated test script after Amber's edits and adds. @carlsonem if you would be willing to check it in Amber's absence, that would help immensely. @aQuib is also sending you the pinyon link.

**Comment by carlsonem** [comment]
@Rebekah-Hernandez @aQuib looks good to me, thanks!

**Comment by ASprinkle** [comment]
invites being sent out today for 5 folks, updated wire frame today too.

**Comment by Rebekah-Hernandez** [comment]
Confirmed sent emails to our 5 FS folks so far. Still researching for non FS people to give feedback.

**Comment by ASprinkle** [comment]
@Rebekah-Hernandez  I cc'd you  recently on an email with the following addresses that I bcc'd.
'mattmorris@oceanassoc.com
'h_stone@hotmail.com'
'smcwilliams22@gmail.com' 
'trevor.barclay@gmail.com'

The message was: "Hello, Thank you for raising your hand to be test out the Open Forest pilot (a convenient way for people to get a forest product permit).
We launched the pilot in 2018, and have completed two seasons of offering Christmas tree permits online for a select few forests.
Our team is currently working on a prototype of a new main landing page for the Open Forest website.
I am including Rebekah on this message so that she can get in touch with you about scheduling some time.
Feel free to share my email address with any friends of yours who might also be interested to participate!
Thanks again!"

**Comment by ASprinkle** [comment]
@Rebekah-Hernandez  I added a few names.  Do you have an excel spreadsheet in Pinyon for capturing these contacts?

**Comment by Rebekah-Hernandez** [comment]
Thanks! I do have an excel sheet running. I will update it with those contacts now. @ASprinkle

**Comment by Rebekah-Hernandez** [comment]
@ASprinkle Here is the link for the updated contacts and scheduled tests so far:

https://usfs.app.box.com/file/599204938980

Feel free to update as you see need or if you have info that you think needs including. Thank you

**Comment by ASprinkle** [comment]
@aQuib  @Rebekah-Hernandez we didn't fully discuss this story at stand up today - It appears that to me this one is completed.  It sounds like we'll be using Teams and/or Zoom for testing with public users.

**Comment by Rebekah-Hernandez** [comment]
I will be testing with Aquib this morning the Teams conference line but it is pretty much done. @ASprinkle

**Comment by Rebekah-Hernandez** [comment]
@ASprinkle I converted the box notes in this story to word documents. If you want to see them, the respective links are here:
Research Plan: https://usfs.app.box.com/file/614362045925
Test Script: https://usfs.app.box.com/file/614340322713
