### ISSUE TITLE
As an Open Forest customer, I want to see a main landing page up on staging so that I can continue testing it.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1123]
## Notes
This story is about building the completed main landing page design.
This is connected to story #604
and is dependent on #1054

## Acceptance Criteria
- [ ] An open forest landing page is up in our staging environment, and ready for further refinement (testing)

## Tasks
- [ ] Build the designed main landing page onto the Staging Site
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by carlsonem** [comment]
@briandavidson check if dev environment is ready prior to starting development
