### ISSUE TITLE
As an special uses platform user, I want to know who to contact when I receive an error so that I can get help when I need it.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1125]
## Notes
It looks like error banners still have the old fs-permitting-project@gsa.gov email contact
We need to update all instances of that email address to be our shared email for customer support SM.FS.OpnFrstCsSup@usda.gov

![image](https://user-images.githubusercontent.com/33435621/71122408-5cdc3300-2195-11ea-9e9c-88223a708e62.png)

![image](https://user-images.githubusercontent.com/33435621/71114394-893b8380-2184-11ea-97e0-f70f036d984c.png)

## Acceptance Criteria
- [x] There are no longer any instances of the gsa email address in the Open Forest platform

## Tasks
- [x] replace all instances of gsa email address to the SM.FS.OpnFrstCsSup@usda.gov email address
- [x] PO approved

## Definition of Done
- [x] Pull requests meet technical definition of done
- [x] Compare finished design with mockup
- [x] Usability tested

**Comment by ASprinkle** [comment]
![image](https://user-images.githubusercontent.com/33435621/72101442-8b9f8200-32d9-11ea-8014-9c57c1f1e92b.png)

**Comment by ASprinkle** [comment]
![image](https://user-images.githubusercontent.com/33435621/72101463-96f2ad80-32d9-11ea-9d6c-e687b67e9a54.png)

**Comment by ASprinkle** [comment]
Update from stand up: completed some testing - pull requests going through.

**Comment by ASprinkle** [comment]
Success! thanks Dylan 
![image](https://user-images.githubusercontent.com/33435621/72268988-ad4d8180-35d7-11ea-8296-0d21ef448549.png)
