### ISSUE TITLE
SPIKE High-level sketch of user profile landing page and admin interactions

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1130]
## Notes
* What are things we should consider when making this story *

high level sketch to have some idea about what it would look like for a user to set up an Open Forest profile in order to do business in Open Forest.

We just want to know generally... what would we need to look out for. Let's get some ideas around that for future consideration.

security controls

This converstaion came up during the high-level review of the initial landing page wireframe https://github.com/USDAForestService/fs-open-forest-platform/issues/1052#issuecomment-570643962

## Acceptance Criteria
- [x] We have a sketch of what it would look like for a user to set up an Open Forest profile in order to do business in Open Forest.
- [x] We understand admin workflows

## Tasks
- [x] Create a high-level, low fidelity sketch (workflow) of what the user experience might be if they were required to create a profile (or log in) in order to obtain forest product permits and use a shopping basket feature.
- [x] Create a high-level, low fidelity sketch (workflow) of what the user experience for forest service admins.
- [x] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
@lisaredux is this something that you are currently working on? If so, let's move it to in progress. thanks!

**Comment by lisaredux** [comment]
@ASprinkle @Rebekah-Hernandez here's a rough draft of the workflow. I welcome your feedback and insights.
![Story1130-Workflow4profile-01062020](https://user-images.githubusercontent.com/26801590/71856798-28340b00-30b3-11ea-8666-25248d673bf0.png)

**Comment by ASprinkle** [comment]
Looks like 3 different ways to login.  It's good that you included the opportunity for people to be able to choose to consume information prior to deciding to log in.  I think this is a good start for having an idea of what that a flow w/user log in might look like.

**Comment by lisaredux** [comment]
Thanks @ASprinkle. I've updated it since yesterday. It's also included in the PDF for 1052 to discuss with DEV. Here is the latest...

![Story1130-Workflow-profile-01072020](https://user-images.githubusercontent.com/26801590/71912997-83faa480-3144-11ea-8a82-c96ba629df38.png)

**Comment by ASprinkle** [comment]
Need to present to Jon, Matt, Shadat before done

**Comment by mwreiss** [comment]
@ASprinkle  Thank you Amber, excited to see the next iteration from the design team

**Comment by ASprinkle** [comment]
@mwreiss @lisaredux sent invite for 1/8 1:30PST for the meeting to present this high-level flow for user profile.

**Comment by mwreiss** [comment]
@ASprinkle thank you!  I didn't see the invite come through yet.

**Comment by mwreiss** [comment]
NM!  I got it.

**Comment by lisaredux** [comment]
@ASprinkle here are the updates to validate:

![Workflow overview - future w_ profile](https://user-images.githubusercontent.com/26801590/72176013-8579d600-33ab-11ea-838f-c9f55d530344.png)
![Workflow detailed - future w_ profile](https://user-images.githubusercontent.com/26801590/72176014-8579d600-33ab-11ea-8b6f-66e175ce8603.png)
![Workflow- Admin](https://user-images.githubusercontent.com/26801590/72176096-b0642a00-33ab-11ea-9efc-735f3b3be5b7.png)

**Comment by ASprinkle** [comment]
Is this also saved in Pinyon?

**Comment by lisaredux** [comment]
@ASprinkle - just uploaded it. here it is on Pinyon https://usfs.app.box.com/folder/99991075410
