### ISSUE TITLE
As an admin for Christmas trees, I'd like to edit Robert Barnhart Admin roles so that the appropriate roles are provided.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1133]
## Notes
* What are things we should consider when making this story *

Robert is in a different position at the Region 6 Regional Office.
We initially thought he should be removed from admin access, however he may need it - we'll have to confirm with him.

robert.barnhart@usda.gov

## Acceptance Criteria
- [x] The appropriate roles are granted.
- [x] We've confirmed with Rob what kind of access he may need.

## Tasks
- [x] Confirm with Rob level of access needed.
- [] Grant roles to generate reports for all R6 Forests only, if requested.
- [] Grant roles to view the submitted feedback, if roles are maintained..
- [] Do not allow roles to change season dates or cutting area dates for any forests.
- [] If requested: remove from all admin roles.
- [x] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Usability tested

**Comment by ASprinkle** [comment]
Email from Rob 1/29 "Leave me on to provide backup coverage for Dana."
We will not change his level of access to Open Forest admin for Christmas trees.
