### ISSUE TITLE
cookie-session to express-session

### ISSUE THREAD

**Issue by mtlaney** [USDAForestService/fs-open-forest-platform#1135]
## Notes
Currently we are using cookie-session npm plugin. Need to investigate implementing express-session in order to properly use passport.js user sessions to trigger session timeouts and user full logouts.

## Acceptance Criteria
- [x] express-session implemented
- [x] user is timed out while away
- [x] user can fully logout of the system

## Tasks
- [x] implement express-session
- [x] implement passport-session
- [x] thoroughly test login / logout and timeout features
- [x] PO approved

## Definition of Done
- [x] Pull requests meet technical definition of done
- [x] Compare finished design with mockup
- [x] Usability tested

**Comment by ASprinkle** [comment]
@mtlaney update tasks ^ w/progress
