### ISSUE TITLE
As an SU Administrator, I want to know that an application isn't sent to suds if there's an error during the Accept to SUDS process, so that I am not confused.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1142]
## Notes

When an admin accepts an application to SUDS, and encounters and error - the application shows the error banner, but also shows text in the window that indicates it was sent to SUDS.
- SUDS Identification number is shown
- "Accepted" status bar displays
![image.png](https://images.zenhubusercontent.com/5a00e34b8a75884b90864b6f/cc642514-bed8-4eb2-9624-77391c509fdb)

This leaves the admin confused.  The Admin is forced to verify in TWO places that nothing was sent:
- View Applications Page
- SUDS

In the image example ^ Application ID Number 139 was used.  When checking view applications, it shows the application is still "Pending" -as it should if it was never sent to SUDS
![image.png](https://images.zenhubusercontent.com/5a00e34b8a75884b90864b6f/d4597ed0-1e61-46ed-868f-037da56f95bf)

When accessing to View Details - the details do not show a SUDS ID, nor "Accepted", nor that there was an error previously.
![image.png](https://images.zenhubusercontent.com/5a00e34b8a75884b90864b6f/21094d32-ba2e-4519-9a90-758fa81c5e47)

## Acceptance Criteria
- [ ] An admin does not see "accepted" status update if an error occurs when accepting to SUDS, and the application is not sent to SUDS.
- [ ] An admin does not see SUDS ID number if an error occurs when accepting to SUDS, and the application not sent to SUDS.
- [ ] An admin is informed that an error occurred and that the application was not sent to SUDS.

## Tasks
- [ ] Create a "bad" application that would be rejected by SUDS to use for testing
- [ ] Update the code so it doesn't display the status as accepted, if not accepted by SUDS
- [ ] Update display so the SUDS ID only appears after accepted by the system
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by briandavidson** [comment]
This bug was a bi-product of issue [411](https://github.com/USDAForestService/fs-open-forest-platform/issues/411). The frontend validation was not in coordination with the backend validation so we were seeing an inconsistency in the UI. Now that the validation has been properly implemented this will no longer occur.

**Comment by ASprinkle** [comment]
@briandavidson I was able to generate the occurrence of the confusing "Accepted" status.
The error occured because the First and Last Names are too long. I'll make a story to address the character limits there.

However, I was able to generate the error. We'd like to communicate an error that does not indicate "Accepted" Status, or a "SUDS ID" when an application has an error and is not actually sent to SUDS. 

Do we think that is even possible?
![image](https://user-images.githubusercontent.com/33435621/73108533-6c961800-3eb5-11ea-936b-ec8b5a1fd08a.png)
![image](https://user-images.githubusercontent.com/33435621/73108545-715acc00-3eb5-11ea-9930-1a3a98f6ce88.png)
![image](https://user-images.githubusercontent.com/33435621/73108555-7586e980-3eb5-11ea-88c0-4bd9b6ab4608.png)

**Comment by briandavidson** [comment]
Similar to the issue with the long organization name, I think we want to address the root cause here by implementing validation on the frontend instead of patching up the anomalous effect it has on the status display.

**Comment by ASprinkle** [comment]
@briandavidson  that sounds good to me, I suppose I wasn't sure how to address it in the same way you described!  so will this story be able to be resolved, or would the first/last name character limits story fix that?

**Comment by briandavidson** [comment]
The first/last name character limits should fix that :)

**Comment by ASprinkle** [comment]
Ok. so, let's just move this to done if there is nothing to push to master for this story.
