### ISSUE TITLE
As a user I'd like to know that Snyk is working efficiently so that I feel good about using the system.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1146]
## Notes
From Dev Retro Spike #887
Snyk failures while running a deployment to Circle-CI create inefficiency, adding time to dev work. For example: Make a push, waiting for it to deploy to staging, moving on to next issue - when a failure occurs inside Snyk have to re-do pull requests doubling steps.

## Acceptance Criteria
- [ ] We have an understanding of how to address the snyk failures.

## Tasks
- [ ]  Coordinate with back-end dev to address considerations for possible increase in efficiency.
- [ ] Validation of acceptance criteria completed
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by carlsonem** [comment]
Snyk will no longer be part of the system
