### ISSUE TITLE
As a user I'd like to deploy multiple workflows at the same time in Circle Ci so that I can maximize efficiencies.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1147]
## Notes
Dev Retro #887 
can only do one at a time. Can have workflows running in parallel, but cannot deploy multiple workflows at the same time.

Considerations to try
 Setting up CircleCI to handle parallel workflows which deploy
-Initial research spike, Matt Shadat Abdul - stay with Circle or move on? Followed by another spike to set up parallel workflows.

## Acceptance Criteria
- [ ] needs definition

## Tasks
- [ ] needs refinement
- [ ] Validation of acceptance criteria completed
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by carlsonem** [comment]
OBE
