### ISSUE TITLE
As a user I'd like a seeder file that doesn't slow down the ability to do business, so that I can work more efficiently.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1148]
## Notes
Dev Retro #887
Seeder file and forest updates while in production.
-the seeder file is inhibiting the ability to make changes on the fly.
-To remedy we turned off the seeder file so that it wasn't updating each night - unless we needed to change a core aspect for a forest (season dates, cost, tree measurement).
Seeder files:
-Improve efficiency around season date setting
-Consider impacts for future scale up – other products’ season dates.
-Admins should be able to login at any time and make an update to season dates without having to worry about whether or not the dates will revert if an update is made.
-Should seeder files be connected to season dates, or something else?

## Acceptance Criteria
- [ ] Make updates to the forest information without a dependency on the seeder file

## Tasks
- [ ] Research a way to remove the dependency on the seeder file to make updates to the system
- [ ] Update code to remove dependency on the seeder file
- [ ] Test to ensure the system doesn't require the seeder file to make updates
- [ ] Validation of acceptance criteria completed
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by carlsonem** [comment]
Will be taken care of during the content management issue
