### ISSUE TITLE
As a potential New Admin I'd like an easy way to be added to the system so that I can quickly start using it.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1149]
## Notes
Dev Retro notes 887:
Re-establish how we handle updating or adding a new forest thru an admin panel in the site. This would enable us to make changes on the fly without a production build or running the seeder file.
-Possibly biggest change prior to xmas 2020. Have an admin panel that Mike, Brian, Amber (for example) have different admin priv where we can "Add" or "Delete" a forest in addition to FS field admins who can edit content directly.  
-EEMS would manage roles/priv.
-Functions would be on Open Forest side.
-edits would "post change to database" and not have to run seeder file/trigger a new build.
-Content updated shouldn't occur through code changes - they should occur through application.
-Admins could change content, tree measurements, season dates, etc.

## Acceptance Criteria
- [ ] We've confirmed we have a system that is functioning properly and as expected for FS Admins.

## Tasks
- [ ] 
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
This may be redundant with #1182 let's see how we should refine this once 1182 is done.

**Comment by ASprinkle** [comment]
redundant with 1182
