### ISSUE TITLE
Spike: Write test code to push a single permit through the FPFS API.

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/fs-open-forest-platform#1161]
## Notes
There are assumptions around pushing permitting data through to FPFS and that the data that leaves FPFS and the reporting systems that rely on these data will be unaffected. We need to verify that that is true. We also want to surface any potential firewall issues. Fields that are in product plans in TIM may have to be looked at to see how we might also send that data within the Open Forest structure.

This is foundational work necessary to ensure that the needs of all users who touch the permitting can be met with this FPFS API approach. User needs of particular relevance:

**As a special forest products manager, I can:**

- have funds from online sales distributed to the right place
- get information on species, product, unit of measure, and volume sold online for official upward reporting
- retrieve the number of permits that were issued online

## Acceptance Criteria
- [ ] We have confirmed that the FPFS API can pass all needed permit data from Open Forest to FPFS
- [ ] We understand whether/how downstream reporting systems and workflows may be effected
- [ ] We have documented any next steps or additional experiments needed to mitigate any issues we discover

## Tasks
- [ ] Verify API accessibility between Open Forest and FPFS
- [ ] Exercise the API to send permit data through (could be manual in a terminal) 
- [ ] Survey data that TIM sends to FPFS and make sure it’s all accounted for 
- [ ] Talk to reporting data consumers (Beth, and Product Owners Justin and Roxie) to verify that the API gives FPFS all the data it needs to pass on to downstream reporting systems (FMMI, CDW, and EDW) and they are unaffected
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
~- [ ] Usability tested~

**Comment by MelissaBraxton** [comment]
@aaronburk, @carlsonem, @smahmudFS, and @mwreiss  - This is a first take on documenting the first foundational step we see toward Open Forest being able to support the firewood permitting module. Feel free to add questions, comment, and/or suggest revisions!

**Comment by MelissaBraxton** [comment]
@smahmudFS - wanted to remind you of this issue we created back in Jan. as you create new tasks.

**Comment by carlsonem** [comment]
@mtlaney needs to be refined
