### ISSUE TITLE
As an applicant, I'd like to know what my First and Last name character limitations are so that there are no errors with my application when accepted to suds.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1163]
## Notes
This is similar to #411 (long organizational name)

In this case however, an application should not be allowed to be submitted when the First and Last name characters exceed the acceptable allowable character limit for SUDS.

## Acceptance Criteria
- [ ] Applicants are notified of a character limit for First and Last Name if they reach the threshold.
- [ ] Applicants are not able to submit applications with First and Last Names that exceed the acceptable number of characters.

## Tasks
- [ ] 
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
Character Limits for SUDS per the FSH 
![image](https://user-images.githubusercontent.com/33435621/73110024-cb5d9080-3eb9-11ea-82c9-d6042559e511.png)

**Comment by ASprinkle** [comment]
![image](https://user-images.githubusercontent.com/33435621/73209444-1c10fb80-40fd-11ea-93de-2d590e6b34f6.png)

**Comment by ASprinkle** [comment]
@Dmac26 In reviewing this story, it looks like the updates are working well for the non-commercial group use and for Christmas tree pages.
However it appears, when reviewing the code, that we still need to make the update to the Outfitter Guide application sections 

https://github.com/USDAForestService/fs-open-forest-platform/blob/dev/frontend/src/app/application-forms/temporary-outfitters/temporary-outfitters.component.ts
 
![image](https://user-images.githubusercontent.com/33435621/74064066-afbcb480-49a6-11ea-9fff-96a13d8e5a13.png)

**Comment by ASprinkle** [comment]
TOG name field validations are looking good
![image](https://user-images.githubusercontent.com/33435621/74360048-37c10680-4d79-11ea-8d9a-84bbf7e2d64b.png)

**Comment by mtlaney** [comment]
blocked by #1196
