### ISSUE TITLE
As a forest visitor I want to be able to continue to checkout without having to wonder if I am using a good browser so that I can get my permit easily.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1165]
## Notes
* What are things we should consider when making this story *

## Acceptance Criteria
- [ ] Customers who have incompatible browser know upfront ahead of getting to the checkout page that they won't be able to get their permit w/o using a compatible browser

## Tasks
- [ ] Write test script to show banner only to folks who are using IE and/or other known incompatible browsers.
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished build with mockup
- [ ] Usability tested

**Comment by Rebekah-Hernandez** [comment]
![Story1165](https://user-images.githubusercontent.com/56045852/76254713-f1958080-621a-11ea-8d8a-99ce139769a5.PNG)

Text and appearance of this warning label shown.

**Comment by aQuib** [comment]
@Rebekah-Hernandez the design is good. However, I don't like the language initially recommended in the ticket. It expresses doubt yet we can easily know precisely what browser is being used with HTTP headers. Therefore I suggesting changing it to:

Your web browser ({insert Browser Name version}) is not fully compatible with Open Forest. Your experience on this website will be better if you use a different browser such as Google Chrome, Mozilla Firefox, or Microsoft Edge.

**Comment by Rebekah-Hernandez** [comment]
@aQuib Dylan and I are searching to find a way to do your first suggestion.

I asked Mike yesterday and he told me the only browser we recommend using is Google Chrome. However, if you've heard otherwise, we can change that.

**Comment by aQuib** [comment]
@Rebekah-Hernandez, understood. I wasn't aware, therefore I'm fine reverting it to say only Google Chrome as a recommended browser.

**Comment by Rebekah-Hernandez** [comment]
I was able to see it on both Firefox and IE, but the appearance of it is not filling the width that it should. If possible, please line up the warning label with the text on the rest of the page
![firefox](https://user-images.githubusercontent.com/56045852/77787238-37c94d00-702d-11ea-8e9b-e81c24e9ed66.PNG)

**Comment by mtlaney** [comment]
@Dmac26 is this one already in staging and ready for awaiting acceptance?
