### ISSUE TITLE
As a Christmas tree administrator I want to know where people might be going on my forest so that I can better manage my program.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1168]
## Notes
We heard that forests would like the opportunity to be able to identify where people are going on their forest to get a Christmas tree.  Knowing where people are generally headed helps the forest to:
-make decisions to enable sustainable management of the program
-distribute program support resources in a strategic way (recreation staff, LEO, timber staff)

## Acceptance Criteria
- [ ] We know whether we'll build in the option for Christmas tree hunters to type in or select their anticipated area for Christmas tree hunting
- [ ] We know how we plan to be able to retrieve that information (generated reports page or other)

## Tasks
- [ ] Find out from forests (min 5: 3 from R6, the Flathead, and the ARP) what kind of information would be helpful for them.
- [ ] Develop questions to interview the Forests with.
- [ ] Mock design for public user to enter Christmas tree hunting area description/interaction.
- [ ] Mock design for admin user retrieving Christmas tree hunting area description.
- [ ] PO approved

## Definition of Done
- [ ] Compare finished design with mockup
- [ ] Usability tested
