### ISSUE TITLE
As an admin for a forest I don't want to see a google form or in applicable cutting area text so that I am not confused.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1169]
## Notes

this story is connected to #978

## Acceptance Criteria
- [ ] the google form is not accessible

## Tasks
- [ ] remove any links to the Request Changes google form
- [ ] The hint text is removed below the customer support email address
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
@briandavidson this could be a good one to pull in this week (2/3) if you're operating ahead of schedule :)

**Comment by ASprinkle** [comment]
@briandavidson I reviewed this in staging. I did not see any links to the google form, and the hint text appeared to be removed. All looks good. Please check the task boxes and the definition of done boxes above, and then I will PO approve. thanks!

**Comment by mtlaney** [comment]
blocked by #1196
