### ISSUE TITLE
As a potential New Forest I'd like a way to be easily added to the Open Forest system so that I can start offering online options

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1170]
## Notes
Dev retro indicated a need to find an easier way to add new forests and their content to the system

## Acceptance Criteria
- [ ] We have an easy way to add forests to the system

## Tasks
- [ ] Develop tool to easily add new Christmas tree forests to the system
- [ ] Needs refinement
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested
