### ISSUE TITLE
As a special use applicant I don't want an internal server error when being directed to login.gov so that I can proceed with filling out an application.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1173]
Customers are getting Internal Server errors when being directed to login.gov
 ![Screenshot_20200129-095823_Chrome.jpg](https://images.zenhubusercontent.com/5a00e34b8a75884b90864b6f/ae2ec3c3-cf78-43fe-b840-6fdf981e0f92)
![image.png](https://images.zenhubusercontent.com/5a00e34b8a75884b90864b6f/6249f449-af9f-4b59-8714-c6da90ca0fe8)

## Acceptance Criteria
- [x] We know why the error is occurring.
- [x] Customers can proceed to login.gov without any errors.

## Tasks
- [x] check middle layer
- [x] troubleshoot other possibilities
- [x] Fix issue
- [x] PO Approved

## Definition of Done
- [x] error corrected

**Comment by ASprinkle** [comment]
![image](https://user-images.githubusercontent.com/33435621/73393327-4e069700-4290-11ea-892e-add146e4cda3.png)
I was able to successfully access the login.gov option both on my smartphone and via desktop.
@mtlaney  success!

**Comment by mtlaney** [comment]
@ASprinkle good to hear!

**Comment by ASprinkle** [comment]
@mtlaney  since this is already fixed in prod, should we just move it to Done? is there any more documentation that we should add to this story so that we know what the issue was?

**Comment by mtlaney** [comment]
With your approval I'll move it over to done. We had to update Node.js version on the middlelayer which has been pushed. Jon just approved the SIA so it will be updated in the middlelayer prod as well.
