### ISSUE TITLE
As an Open Forest customer support team member, I need full access to production and staging for special uses so that I can see issues.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1175]
## Notes

We need to make sure Dylan and Rebekah have access to admin site so that they can appropriately address any special uses related customer issues that may arise.

Any and all testing should be done in the staging environment, however access to view things in the admin environment will likely be necessary.

## Acceptance Criteria
- [x] We have confirmed that Dylan and Rebekah have access to https://openforest.fs.usda.gov/admin/applications

## Tasks
- [x] Determine if support team can have production access
- [x] Give Dylan  access
- [x] Give Rebekah access
- [x] Confirm with both that they can indeed access
- [x] PO approved

## Definition of Done
- [x] Usability tested

**Comment by abdul-fs** [comment]
Confirmed their access. They both are on production with admin access.
{
          "admin_username": "REBEKAH_HERNANDEZ",
          "forests": [
            "all"
          ]
        },
        {
          "admin_username": "DYLAN_MCAFEE",
          "forests": [
            "all"
          ]
        },

**Comment by ASprinkle** [comment]
Rebekah and Dylan verified their access:

    Special Uses Admin Production site: https://openforest.fs.usda.gov/admin/applications

    Special Uses Admin Staging site: https://open-forest-staging.app.cloud.gov/admin/applications
