### ISSUE TITLE
SPIKE: As an admin I want to know what SUDS uses for each applicant type instance when TOG applications are sent to SUDS

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1179]
## Notes
Brian Lee requested some more information about what SUDS uses in the Contacts fields for each instance of applicant type. so that he knows what to expect when TOG applications are sent to SUDS.  Depending on the outcome, the SU permit administrator may need to take additional steps in SUDS.

## Acceptance Criteria
- [x] We know what SUDS inputs for each applicant type
- [x] The information has been shared with the MBS

## Tasks
- [x] Create applications for Individual, Corporation, LLC, Partnership or association, State government or Agency, Local government or agency, Nonprofit
- [x]  Send each application to SUDS
- [x] Screen shot SUDS contact screen for what it inputs in the Org/Last Name field for each type of applicant.
- [x] Inform MBS Brian Lee of results
- [x] PO approved

## Definition of Done
- [x] A/C met
- [x] Tasks are completed

**Comment by ASprinkle** [comment]
Email response from Brian Lee on the MBS RE non-profit org names [Nonprofit Org Names in SUDS from Open Forest.pdf](https://github.com/USDAForestService/fs-open-forest-platform/files/4154549/Nonprofit.Org.Names.in.SUDS.from.Open.Forest.pdf)
