### ISSUE TITLE
As an Open Forest admin I want more data options from the reports feature so that I can communicate data easier to management.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1184]
## Notes
In 2019 we heard that admins want more filter/query by options in the report generated feature.
Admins would like to easily compare previous years' sales to current year sales.

## Acceptance Criteria
- [ ] We have different ways of filtering and manipulating the data over multiple seasons for one or all forests depending on roles

## Tasks
- [ ] Design concept
- [ ] Build concept
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested
