### ISSUE TITLE
As an Open Forest manager I want an updated Admins List so that we can integrate EEMS successfully.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1187]
## Notes
Reviewing the list of Admins, we identified some changes that need to be made in prep for EEMS integration
Connected to #1182 

## Acceptance Criteria
- [x]  We have updated the whitelist in prep for EEMS integration.

## Tasks
- [x] Add Jonathan Lerner as read-only (POC2) all forests
- [x] Add Eric Carlson as read-only (POC2) all forests
- [x] Change Robert Barnhart from Rogue River-Siskiyou to All R6 Forests read-only (POC2)
- [x] Change Heather Ibsen from Gifford Pinchot to Mt. Hood (started a new position there recently)
- [x] Remove Jason Page
- [x] Remove Robert Gill
- [x] Remove Fara Humphrey
- [x] Understand that Amber Burleigh and Amber Sprinkle are the same person (Burleigh is maiden name).
- [x] PO approved

## Definition of Done
- [x] Tasks completed.

**Comment by ASprinkle** [comment]
@mwreiss @JonathanLerner54 @abdul-fs here is the updated admins list spreadsheet. I do not have access to the folder: ePermits\SOP\AC Controls Artifacts\Account_Whitelists
You should be able to save this version directly into the box folder and it will automatically override the existing version; thus maintaining version control. 
[FY20 user account list for Jan 2020.xlsx](https://github.com/USDAForestService/fs-open-forest-platform/files/4167616/FY20.user.account.list.for.Jan.2020.xlsx)

**Comment by mwreiss** [comment]
@ASprinkle Thank you Amber!

**Comment by abdul-fs** [comment]
This is completed yesterday.
