### ISSUE TITLE
As an Open Forest customer purchasing a permit on the last day of the season, I want to be warned in advance that I've purchased something on the last day so that I am aware of how much time I have.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1191]
## Notes
Christmas tree customers are notified on the confirmation page that: "This permit was issued on MM/DD/YYYY and expired on MM/DD/YYY".  The customer should be "warned" ahead of committing to the purchase, as well as  "warned" on the confirmation page.
![image](https://user-images.githubusercontent.com/5187168/73775055-29f4fb00-4753-11ea-980c-acff6b069b62.png)

## Acceptance Criteria
- [ ] A customer is warned about last day purchases before committing payment, upon confirmation of purchase.

## Tasks
- [ ] Update text to be present tense. Replace "expired" with "expires".
- [ ] Update banner so that it is not an error designed banner.  Make it yellow with the exclamation mark triangle
- [ ] Add a warning banner to the "Permit Holder Information" page that populates at the top of the page after customer selects "buy permit" on the last day of the season.
- [ ] Permit holder information page warning text should read: "You're about to purchase a permit on the last day of the season. Your permit will expire at midnight MM/DD/YYYY [insert end season date]"
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested
