### ISSUE TITLE
As an Open Forest administrator I'd like to be able to view maps that are uploaded following the format guidelines so that I can review the permit.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1193]
## Notes
The SU application page describes acceptable map upload format
![image.png](https://images.zenhubusercontent.com/5a00e34b8a75884b90864b6f/6785effa-207f-4216-92f2-c9b3d79b7194)

When an applicant uploads a .jpg or .png file, the upload responds as successful.
However, when viewing the map file from the application details page, the file appears corrupted, and does not display properly, showing these types of responses:

![image.png](https://images.zenhubusercontent.com/5a00e34b8a75884b90864b6f/cf855e77-a81d-4798-afe8-0c3a1fe43d73)
![image.png](https://images.zenhubusercontent.com/5a00e34b8a75884b90864b6f/81d3f901-8862-4c84-a847-e7ce01fe404d)

## Acceptance Criteria
- [x]  The correct acceptable map format type is displayed in the hint text of the application page
- [x] The map can be viewed in any of the acceptable format types from the View Application Details page, map document link.

## Tasks
- [x] Find out why .png and .jpg map files are not able to be viewed when successfully submitted with an application
- [x] Determine whether or not .png and/or .jpg files are acceptable formats
- [x] Fix issue
- [x] PO approved

## Definition of Done
- [x] Pull requests meet technical definition of done
- [x] Usability tested

**Comment by ASprinkle** [comment]
@mtlaney can you review the task boxes in the story ^, and check the ones that applied/were completed?
