### ISSUE TITLE
As an applicant making updates to my "on hold" application, I don't want to have errors in unexpected fields (Fax and Email) so that I can submit easily.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1194]
## Notes
When an application is put on hold, the applicant can edit their application to address the questions the FS administrator has.

If the applicant intentionally entered no data in the "Fax Number" field on their original application, the applicant would not expect to have to check that field upon editing. Currently the system inputs a value of "0" into the Fax field when the applicant is in "Edit Application" mode.

Also, the applicant has already validated their email address in their original application. The "Edit Application" mode should not require the applicant to re-enter their email address in the "Email address confirmation" box; it should remain pre-populated with the data they originally entered.
![image.png](https://images.zenhubusercontent.com/5a00e34b8a75884b90864b6f/5ce8f445-2a3e-4482-92e0-f329d963ee87)

![image.png](https://images.zenhubusercontent.com/5a00e34b8a75884b90864b6f/6af04784-0bd3-45b5-aef3-0d0745e2b838)
## Acceptance Criteria
- [x] The "Fax number" field is not pre-populated with any data when in "Edit Application" mode.
- [x] The "Email address confirmation" box is pre-populated with the originally entered data.

## Tasks
- [x] Fix fax number
- [x] Fix email
- [x] PO approved

## Definition of Done
- [x] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [x] Usability tested

**Comment by ASprinkle** [comment]
![image](https://user-images.githubusercontent.com/33435621/74884076-34082380-5327-11ea-9dbb-018f5b3afa7e.png)
