### ISSUE TITLE
As a special uses user receiving an automated email, I want to see my information properly represented so that I feel good about using the system.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1196]
## Notes
We received an automated email "Update" to an application email from the special uses production site.
The email format was good, however, the details and information was missing, and replaced with "Invalid date" and "undefined" text in all fields.

## Acceptance Criteria
- [ ] We have an understanding of why the details of the application were not properly displaying
- [ ] We have remedied the issue and automated emails (including updates and initial submissions) for TOG and NCGU applications are functioning properly.

## Tasks
- [ ] Fix the issue so that details are presenting properly in emails.
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Usability tested

**Comment by carlsonem** [comment]
@mtlaney @briandavidson we would like to add this to the current sprint, but will need to further refine the story.

**Comment by Dmac26** [comment]
I unassigned myself from this card since I don't currently have the correct permissions to to trouble-shoot this issue. Moving on to issue #621 in the meantime.

**Comment by ASprinkle** [comment]
Hey Mike, did you see story #376 it's very similar to this one from 2018!

**Comment by ASprinkle** [comment]
@mtlaney I tested it with both NCGU and TOG.  Upon initially submitting my test applications (182 and 183), the admins received emails, and it all looked good.  

However, when I went to test the functions under Hold status it looks like there is an issue. As an administrator, I placed both applications on Hold.  When that happens, the applicant is supposed to get an auto-generated email informing them &  i did not see any emails come through to me. 
![image](https://user-images.githubusercontent.com/33435621/75387425-31ae4800-5898-11ea-886f-7916ab520eda.png)
![image](https://user-images.githubusercontent.com/33435621/75387436-3672fc00-5898-11ea-8868-a3d1aae72dcf.png)

I should have two emails in my inbox from 12:53 notifying me that my applications are on hold from that administrator 
![image](https://user-images.githubusercontent.com/33435621/75387400-23602c00-5898-11ea-8ca4-e94fae08a313.png)

It looks like the "Hold" status update went through great on both the admin and the applicant side.
![image](https://user-images.githubusercontent.com/33435621/75387456-3c68dd00-5898-11ea-9ba5-742a8f2cd353.png)

I tested updating the applications and it looks like the emails came through, with all the information displaying correctly for the admins to read
![image](https://user-images.githubusercontent.com/33435621/75387706-949fdf00-5898-11ea-81e2-3560737b1d4d.png)
![image](https://user-images.githubusercontent.com/33435621/75387969-00824780-5899-11ea-8c73-d70ca3467757.png)

**Comment by aaronburk** [comment]
Since none of the task boxes s are checked,  I am not sure this ready for validation?we can discuss in standup

**Comment by aaronburk** [comment]
![image](https://user-images.githubusercontent.com/25828899/75888101-d7156e80-5df8-11ea-87fb-dfdccadb77c0.png)
Not sure if I am supposed to be doing this testing in validation or if Rebkah and Dylan are doing it.  We will need to discuss this process further in the meeting today.

**Comment by mwreiss** [comment]
@aaronburk anything in validation should be tested by Dylan and Rebekah (of course they can bring others in to assist as well) , once validated they will move it to awaiting acceptance for you to give final approval and check.
