### ISSUE TITLE
As a user I'd like to know if I am using a good browser to get a Christmas tree permit so that I can have a good experience.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1199]
## Notes
* What are things we should consider when making this story *

## Acceptance Criteria
- [ ] The banner displays for incompatible browsers

## Tasks
- [ ] Build the approved mock up.
- [ ] Develop the code to display the banner
- [ ] Test application using chrome, IE, Edge, so on...
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested
