### ISSUE TITLE
As a customer I want to know that the right people on the Open Forest team have access to automated emails so they can review and resolve issues efficiently.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1202]
## Notes

Dylan and Rebekah should have access to the shared mail inbox sm.fs.openfrstadm@usda.gov, where admins receive automated email notifications when applications are submitted or updated (both from the Staging site and from the Production site) given their customer support roles on the team.

Mike Laney should be added to receive automated admin email messages from applications generated and updated in the staging site.

## Acceptance Criteria
- [ ] All necessary Open Forest team members have access to the email inboxes, and are receiving the automated emails.

## Tasks
- [x] Dylan is added to receive automated emails from applications generated and updated in Staging
- [x] Dylan is added to receive automated emails from applications generated and updated in Prod
- [x] Rebekah is added to receive automated emails from applications generated and updated in Staging
- [x] Rebekah is added to receive automated emails from applications generated and updated in Prod
- [x] Mike is added to receive automated emails from applications generated and updated in Staging
- [x] Amber to test email feature is updated/functioning in staging
- [x] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [x] Usability tested

**Comment by abdul-fs** [comment]
INC is created to add them into shared mail box.
https://usda-servicedesk.fed.onbmc.com/arsys/servlet/ViewFormServlet?form=NTE%3ANotifier&server=onbmc-s&eid=NTS000019597831

**Comment by ASprinkle** [comment]
@abdul-fs I generated a NCGU applicatio in staging, and it looks like Rebekah, Dylan, and Mike were added successfully! 
![image](https://user-images.githubusercontent.com/33435621/75064251-6dfa3680-549b-11ea-999a-1577bd899cad.png)

**Comment by abdul-fs** [comment]
Nope we are good. I will prod will their dylan and rebekah after prod release and we should be good to close it after you test in prod.

**Comment by ASprinkle** [comment]
@abdul-fs  We will not test in prod since we do not want to create too many test applications  in the Prod environment given that the MBS is actively using the system.  We will be good to move this to done AA or Done once all updates are done/releases completed. thanks!

**Comment by abdul-fs** [comment]
@ASprinkle Sounds good. 

Thanks.

**Comment by abdul-fs** [comment]
This is completed.
