### ISSUE TITLE
As an applicant I'd like to clearly view the menu items without breadcrumb trail interruption so that can see it and don't accidentally click on the wrong thing.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1204]
## Notes
The breadcrumb trail on both NCGU and TOG application pages, interrupts step 1 and 2 upon initial scroll down the page.
The breadcrumb trail should stick, without interrupting the left side menu nav upon scrolling down the page.  An example of it sticking/interacting correctly can be seen on both the NCGU and TOG Learn More pages.

Here are screen shots of what the breadcrumb trail is doing:
![image.png](https://images.zenhubusercontent.com/5a00e34b8a75884b90864b6f/89ce7cef-7c28-4dcc-9ce4-3bafdfb1e5d9)
![image.png](https://images.zenhubusercontent.com/5a00e34b8a75884b90864b6f/33a28d64-f6be-4d00-bf10-1c5989c4b3e2)
![image.png](https://images.zenhubusercontent.com/5a00e34b8a75884b90864b6f/3e498252-37cc-4148-b994-c1797f61bbf3)

## Acceptance Criteria
- [ ] The breadcrumb trail does not interrupt the other portions of the page.
- [ ] The breadcrumb trail stays in place upon scroll.

## Tasks
- [ ] Fix breadcrumb trail on non-commercial group use application page
- [ ] Fix breadcrumb trail on temporary outfitting and guiding application page.
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested
