### ISSUE TITLE
As an applicant I want an easier way to review the NCGU application process so that I don't have to read so much text.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1205]
## Notes
We can improve the look and feel of the "Application Process" section of the NCGU application page by including visual icons here to help tell the story of the application process.  These icons would follow the same standards as the "What to Expect" section of the Christmas tree pages

## Acceptance Criteria
- [ ]  The NCGU application process section is easy to read/understand.
- [ ] The NCGU application process section includes relevant visual images that help tell the story

## Tasks
- [ ] Mock up design
- [ ] Build
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested
