### ISSUE TITLE
As a SU applicant entering my phone number, I want a consistent and clear experience so that I don't have to wait for an error to understand what I need to do.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1206]
## Notes
The phone number field for both NCGU and TOG tells the user they need to enter "Telephone number (10 digits)*" for TOG and "Phone number (10 digits)*" for NCGU.

As a user starts entering their phone number, the amount of characters they are allowed to enter stops, without any errors, leaving the applicant to guess how they should enter their phone number. As shown in this screen shot: 
![image.png](https://images.zenhubusercontent.com/5a00e34b8a75884b90864b6f/6e0c8e5b-b191-4b35-b506-4417edb8c357)

When the applicant tries to move to the next box, the error validation does not provide any guidance:
![image.png](https://images.zenhubusercontent.com/5a00e34b8a75884b90864b6f/ea49e7fb-4342-4d80-870d-efff45251ddd)

If they try to skip the field, the error validation is inconsistent with the field title, leaving the user to wonder whether they should enter their "day phone" or their "phone number"
![image.png](https://images.zenhubusercontent.com/5a00e34b8a75884b90864b6f/daf7d383-ac7d-4cee-959f-abe86105a688)

If a user enters some of their phone number and tries to move on, the error validtion is inconsistent with the filed title. The error validation uses the term "characters" while the field title uses "digits". leaving the applicant to wonder if they can/should use hyphens or parenthesis.
![image.png](https://images.zenhubusercontent.com/5a00e34b8a75884b90864b6f/0d6c5c38-5eb0-477c-ad9d-278e98b0585d)

The required task of entering a phone number should be made more clear to applicants by adding hint text such as: "(ex: 1234567890)" or clarifying "10 digits" to say: "10 digits, no special characters "-", "()")

## Acceptance Criteria
- [ ] The applicant understands more about what to expect when entering a telephone number.

## Tasks
- [ ] Mock design for field header with hint text
- [ ] Mock design for field with skipped field error scenario
- [ ] Mock design for field with partially entered field scenario
- [ ] Build per mock ups
- [ ] Make field title the same (per mock ups) for both the NCGU and TOG application pages, naming it "Phone number" everywhere a phone number is requested to be entered.
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by briandavidson** [comment]
Hi @ASprinkle  -- saw the design label on this one but it looked like it might just be for the wording and no actual mockup or wireframe would be needed. Is this good to go for dev or am I neglecting some design work here?

**Comment by ASprinkle** [comment]
Hi @briandavidson  thanks for asking. Initially I thought there would be a design component. But I realized that we're not changing the design of anything... so I updated the tasks above and the lables. I provided the text we should change it all too. This one wasn't part of refinement, so if you have more ?'s let me know, I am around today!

**Comment by Rebekah-Hernandez** [comment]
Changes have been pushed but the language between the two applications is different. (first image is Temporary Outfitters while second is noncommercial)

@Dmac26  can we make both the same language?

![tog](https://user-images.githubusercontent.com/56045852/77651298-9530a180-6f3a-11ea-8b94-e9180fe60c47.PNG)
![ncgu](https://user-images.githubusercontent.com/56045852/77651308-995cbf00-6f3a-11ea-8ce6-a9a344d9f45e.PNG)

**Comment by Dmac26** [comment]
@briandavidson @mtlaney @carlsonem 

I updated a few files per Rebekah's suggestion and created a new pull request: https://github.com/USDAForestService/fs-open-forest-platform/pull/1268

**Comment by Dmac26** [comment]
Here is the PR for easy access:

https://github.com/USDAForestService/fs-open-forest-platform/pull/1273
