### ISSUE TITLE
As an applicant I'd like to read NCGU titles consistently throughout my experience so that I am not confused about what kind of permit application it is.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1207]
## Notes
This story addresses consistent display of the "Non-commercial group use" permit application title.
Currently this is being displayed a few different ways throughout the work flow: noncommercial group use and noncommercial 

## Acceptance Criteria
- [ ] The title for non-commercial group use applications is consistently displayed throughout the workflow

## Tasks
- [ ] Update the help me pick tool pages where it's result is a non-commercial group use application (https://open-forest-staging.app.cloud.gov/mbs/help-me-pick/7)
- [ ] Update the Learn More page main title
- [ ] Remove the "noncommercial contact" text in the Contact us section of the Learn More page
- [ ] Update the apply button text in the Learn More page to read: "Apply for a non-commercial group use permit"
- [ ] Update the title on the application page to read: "Apply for a non-commercial group use permit." (updating title for consistency and removing "Open Forest")
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by Dmac26** [comment]
This PR for this issue has been reviewed, approved, and merged. Waiting for merge to push through so the final stage of validation can be completed.
