### ISSUE TITLE
As an FS admin I want to see correct references to the Forest Service so that I feel good about using the system.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1208]
## Notes
There are many references to the "National Forest Service"

There are "National Forests", and there is the "Forest Service", but there is not the "National Forest Service"

## Acceptance Criteria
- [ ]  The Forest or the Forest Service are correctly referred to in all pages where they are referenced.

## Tasks
- [ ] Update the "Contact us" sections of both TOG and NCGU Learn More pages

- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
@briandavidson can you check the DoD boxes too?
As PO I'll do the acceptance criteria box and PO approved.

I put a note in the Dev channel that  I just tested a NCGU application, and a TOG application, and I did not receive the confirmation email that the applicant is supposed to get. I am unable to complete a check on this story unless I can see the emails the applicants get...
