### ISSUE TITLE
As a TOG applicant I have a lot of information to enter so I'd like to know upfront what my character limits are so that I can describe my needs within those limits.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1209]
## Notes

TOG applicants are not told what their character limits are until they have started entering information and moved on to the next field. Hint text should be provided that informs them ahead of time what the character limits are.
Additionally we received feedback from an applicant about there not being enough room to describe the activities, especially where multiple trips are involved, resulting in additional work for the applicant (outside of open forest) to send the information to the Forest within a reasonable time. This results in duplication of efforts, the character limitations should be increased.

## Acceptance Criteria
- [ ] Applicants know what their character limits are before typing TOG descriptions
- [ ] Applicants have adequate room to provide all the information necessary in the description fields.

## Tasks
- [ ] Find out from MBS if current character limits for TOG description fields are meeting their need for level of detail.
- [ ] If no, find out how much more it should be extended
- [ ] Apply new character limitation to all description fields in the TOG application (i.e., services being offered, client base or audience, clean up or restoration, location of routes starting and end points, client charges)
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested
