### ISSUE TITLE
As an Open Forest customer I want access to all the links in the wiki so that I can get the information I want easily.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1211]
## Notes
There are a number of links in the Open Forest wiki that are broken, or take the user to "Create new page" instead of the page with the information they are seeking.

The wiki is a tool that is available for use by the public and our stakeholders. We need to make sure it's fully functional so that folks are having a good experience with Open Forest.

Here is one example of experience when clicking on a link from the menu that does not work:
![image.png](https://images.zenhubusercontent.com/5a00e34b8a75884b90864b6f/3e5831f7-a9cf-40fd-81aa-b1c9dbc54ab7)

## Acceptance Criteria
- [ ]

## Tasks
- [ ] Test every hyperlink in the Wiki menu to verify it's working as expected.
- [ ] Fix any instance of a broken link if found.
- [ ] Test all hyperlinks within individual pages.
- [ ] Document broken hyperlinks within individual pages for future fixing.
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
The broken links may be a hold over connected to this story from the Program Board https://code.fs.usda.gov/forest-service/Open-Forest-Program/issues/112#issue-18692

**Comment by ASprinkle** [comment]
@Rebekah-Hernandez I updated the title of this story, and the tasks.  So this story is more specific to finding the weaknesses, and documenting where further review and decisions are needed.  Fixing the links where further review is needed would be addressed in a future story, developed as a result of the "Meeting" task I added above.

**Comment by Rebekah-Hernandez** [comment]
@ASprinkle So far, the notes for this story are housed here: https://usfs.app.box.com/notes/623788166970

**Comment by Rebekah-Hernandez** [comment]
Updated notes for this story housed here with a couple screenshots: https://usfs.app.box.com/file/626566972531

@carlsonem @aaronburk the majority of the issues are links to archived 18F repositories or ones that don't exist such as the Ops repository or fs-online-permitting. Would one of you be able to review/let me know what we would like to do with those links?

**Comment by carlsonem** [comment]
@carlsonem @aaronburk need to review

**Comment by carlsonem** [comment]
@Rebekah-Hernandez thanks for the work on going through all the pages. I've added my suggestions in the comments of the document. If you have any questions on my comments, please let me know. Thanks

**Comment by Rebekah-Hernandez** [comment]
@carlsonem within the same document are the instances of 18F that I found in the wiki with all the links included. Some are more content based while others are about the archived repos. Please take a look when you have a chance

https://usfs.app.box.com/file/626566972531 doc link again.

**Comment by Rebekah-Hernandez** [comment]
@carlsonem one more note - everything grayed out has been fixed. You'd have to scroll a bit to find what needs your input. I just didn't want to delete the records of what had been fixed before yet.

**Comment by carlsonem** [comment]
@Rebekah-Hernandez just updated the word document

**Comment by Rebekah-Hernandez** [comment]
To be clear, @carlsonem you want the entire page of Onboarding Checklist deleted or just the information pertaining to 18F?

**Comment by carlsonem** [comment]
Either that, or replace it with the checklist we have for the GithHub onboard issue template

**Comment by Dmac26** [comment]
@carlsonem @Rebekah-Hernandez 
It looks like Rebekah caught pretty much all of the failed links. My main addition though it somewhat unrelated. I added this line to the Pinyon doc:

•	User Research
o	The link under “user research” entitled “Naming the Open Forest platform” leads to a page with the title “Naming the ePermits platform”. Should we change one of the two to make the language consistent?
