### ISSUE TITLE
As an applicant entering numerical data, I'd like to see a field that implies no text should or can be entered so that I don't have to think about it.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1213]
## Notes
In both applications fields that ask for a numerical response (i.e., number of participants, number of trips, etc.) are long rectangular boxes that indicate text may be accepted. Fields do not have consistent validations wihtin the same application (ex: TOG anticipated number of trips and anticipated party size -see screen shot). 

However upon entering information the applicant finds out that only numerical entries are accepted, or that they can enter text information.  The field should match the data expectation, and hint text should be offered.

Fields that ask for numerical data only should be sized appropriately, similar to how the calendar fields are set up. 

The fields that as for numerical data should also accept special characters such as "-" or "/" so that applicants can enter ranges of data.

TOG application different requirements for similar information:
![image.png](https://images.zenhubusercontent.com/5a00e34b8a75884b90864b6f/fbe398ad-2a4f-4f49-9846-e406bccd5dd8)

NCGU application field only accepts numbers, but no hint text is describing that
![image.png](https://images.zenhubusercontent.com/5a00e34b8a75884b90864b6f/e0a21ca7-5058-4b96-9b8c-30e355c5cedc)

## Acceptance Criteria
- [ ] Application fields that ask for the number/quantity of something are sized appropriately
- [ ] The applicant understands what to enter in the field prior to clicking in it, or prior to entering data
- [ ] The applicant is able to enter a range of data in all fields where a range would be appropriate.

## Tasks
- [ ] Identify all fields where numerical entries are expected
- [ ] Mock design for each field that included hint text and error text
- [ ] Build hint text for each field per mock design
- [ ] Build error feature for each field per mock design
- [ ] Resize field entry boxes so that they are sized appropriately for the expected data to be entered.
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by Dmac26** [comment]
@aQuib - Per the mockup here for 1213, I'm supposed to make the labels of this section bold. However, I do not see that format throughout the rest of the application. I'm including a screenshot below to show the contrast between the change I've made and the rest of the application's labels. Do we want these labels to be bold and if so I'm wondering if I need to make a new card to convert all labels to a bold font-weight.

![boldVsNot2](https://user-images.githubusercontent.com/23467847/84064302-01db0a00-a988-11ea-9792-92b766ad3d80.png)

**Comment by briandavidson** [comment]
@aQuib and @Dmac26  -- originally the font across the application for this _was_ bold. At some point we veered off the PR process and unfortunately this change slipped in.

@aQuib if you as the designer prefer it without bold, then no problem we can definitely keep it this way. But if your intention was to keep it uniform with the application, that's exactly why I raised the concern in your PR @Dmac26. 

@Dmac26 if you roll back the code car enough you can see for yourself how it used to look. Unless I'm mistaken and at some point this was change was a deliberate design choice, we should indeed restore them to bold.

**Comment by Dmac26** [comment]
@briandavidson - That would make sense to restore this to bold unless Aquib prefers things as they are now. Would you advise we just restore that feature here on 1213 or open a new card?

**Comment by briandavidson** [comment]
> @briandavidson - That would make sense to restore this to bold unless Aquib prefers things as they are now. Would you advise we just restore that feature here on 1213 or open a new card?

@Dmac26 I'm thinking a new issue altogether to keep the scope of this one in tact.

**Comment by aQuib** [comment]
@Dmac26 @briandavidson - Yes, please keep it consistent with the overall application. Please revert back to December stylng.
