### ISSUE TITLE
As a TOG applicant uploading location map information I'd like to add an active hyperlink to a map site so that the admin reviewing my application review is efficient.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1214]
## Notes
TOG applicant provided feedback regarding map upload process to MBS admin:
"The format for uploading maps did not permit active links to USFS maps.  I ended up making a pdf with the http addresses for the two maps, but they aren't "live", and would require you to copy and paste into the url bar of your browser to bring them up."

Many TOG applicants have websites with interactive map information vs. a .pdf or .docx.  This is a useful and efficient way of sharing information. 

The optional field for "Map of proposed activity" should also offer an opportunity for the applicant to upload a url address for the map feature, similar to what is already built into the Applicant Information section, website field.

## Acceptance Criteria
- [ ] The applicant has an option of uploading a document, or adding a url location for map
- [ ] If the applicant provides a url location for map, that map link is available in the View Application Details page for both the administrator and the applicant.

## Tasks
- [ ] Mock a design of the TOG application page that includes a url address box for map
- [ ] Mock a design of the View Application details page that includes the website address that was entered for the map
- [ ] Build in the url box to the TOG application page
- [ ] Build in the connections so that if a url is entered, it is visible and actionable on the view application details pages for admin and applicant.
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
From refinement, I updated this story to include the security review components, so that we know that Security needs to review it even if Jon is not assigned specifically for the development of the story.

**Comment by aQuib** [comment]
Here are the mockups of the input fields for the map URL:
![issue-1214 (a)](https://user-images.githubusercontent.com/2117062/77562965-0f0f4f00-6e97-11ea-84f7-5a6e15abc81a.png)
![issue-1214 (b)](https://user-images.githubusercontent.com/2117062/77562966-0fa7e580-6e97-11ea-9dfb-5be8a1b90a2a.png)

**Comment by aQuib** [comment]
updated mockups above.

**Comment by aQuib** [comment]
This is ready for development.

**Comment by JonathanLerner54** [comment]
We should use a reputation service to check if a site that is being provided by the user has been compromised, black-listed for spam or malware, spoofing.  There a few free sites and there are some that you must pay for the most current and up-to-date info.  Google host one, BrightCloud host some.  However, any user within the FS/USDA boundary would be vetted by the  Firewall.  Adding our own capability may be overkill.  Also, would be just issue an alert internally or would we inform the user who provided the link, that the site they have provided has been listed as compromised?

**Comment by mwreiss** [comment]
@JonathanLerner54 lets review this when you have a chance.  Thanks!

**Comment by Dmac26** [comment]
@aQuib - (this is the same comments as 1213 but it applies here as well) Per the mockup here for 1214, I'm supposed to make the labels of this section bold. However, I do not see that format throughout the rest of the application. I'm including a screenshot below to show the contrast between the change I've made and the rest of the application's labels. Do we want these labels to be bold and if so I'm wondering if I need to make a new card to convert all labels to a bold font-weight.

![boldVsNot](https://user-images.githubusercontent.com/23467847/84064852-f63c1300-a988-11ea-92bd-bbf016a09c0b.png)

**Comment by briandavidson** [comment]
@mwreiss @JonathanLerner54  -- was there any review that still needed to occur on your folks end for this?

**Comment by Dmac26** [comment]
@mwreiss @JonathanLerner54 @briandavidson - If I remember correctly, I think it was agreed that https validation should be enough security given the other layers of security on the back-end. Is that correct @mwreiss?

**Comment by mwreiss** [comment]
@Dmac26 correct, we did a review on this and are good with the current validations in place.  Thanks.

**Comment by Dmac26** [comment]
@mtlaney @briandavidson - On this one I've gotten as far as creating a migration file that does instantiate a new column in the db. But, whenever I try to user-test things locally, the new field only ever gets populated with a null value.

**Comment by briandavidson** [comment]
> @mtlaney @briandavidson - On this one I've gotten as far as creating a migration file that does instantiate a new column in the db. But, whenever I try to user-test things locally, the new field only ever gets populated with a null value.

@Dmac26 is there a problem with it being populated with `null` here? Perhaps it makes sense that it's `null` if it's something we expect the user to provide.
