### ISSUE TITLE
As an special uses person, I'd like to see Mt. Baker-Snoqualmie referenced the same way so that I have a consistent experience.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1216]
## Notes
There are two different ways the forest name is presented throughout the Open Forest site (special uses and Christmas tree):
Mount Baker-Snoqualmie National Forest
Mt. Baker-Snoqualmie National Forest

## Acceptance Criteria
- [ ]  The forest name is referenced the same everywhere: "Mt. Baker-Snoqualmie National Forest"

## Tasks
- [ ] Final all instances of "Mount Baker-Snoqualmie National Forest" 
- [ ] Replace with "Mt. Baker-Snoqualmie National Forest"
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested
