### ISSUE TITLE
As an applicant in the View Applications window, I want to understand more about each filter by feature so that I know what is expected.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1217]
## Notes
The View Applications page for both admins and applicants has the following filter by features and descriptions
![image.png](https://images.zenhubusercontent.com/5a00e34b8a75884b90864b6f/4740d6e5-13e8-4d21-99b0-466c042b1cc6)
![image.png](https://images.zenhubusercontent.com/5a00e34b8a75884b90864b6f/2f8f1130-202d-4dbe-984b-3445332aebe2)
![image.png](https://images.zenhubusercontent.com/5a00e34b8a75884b90864b6f/9b110b8e-9b49-415d-9aad-875f7551f8c1)
![image.png](https://images.zenhubusercontent.com/5a00e34b8a75884b90864b6f/fe370b32-9e58-4e47-8fd9-cd7c428b6d99)
![image.png](https://images.zenhubusercontent.com/5a00e34b8a75884b90864b6f/7d7b7836-fea4-4dea-928c-601a649290dc)

## Acceptance Criteria
- [ ] Descriptions are updated to give the user a better understanding of each Application Status.

## Tasks
- [ ] Update "Filter by" so that is reads: "Filter by Application Status:"
- [ ] Pending page: Remove "Pending permit applications for Open Forest"
- [ ] Pending page: Replace with "Applications that have been submitted/received and are awaiting a review or action."
- [ ] Accepted page: Remove "Accepted permit applications for Open Forest". 
- [ ] Accepted page: Replace with "Applications that are under further review"
- [ ] Rejected page: Remove "Rejected permit applications for Open Forest". 
- [ ] Rejected page: Replace with "Applications that have been rejected for reasons provided by the permit administrator."
- [ ] Cancelled page: Remove "Cancelled permit applications for Open Forest"
- [ ] Cancelled page: Replace with "Applications that have been submitted and subsequently cancelled by applicants."
- [ ] Make all description text smaller so that it fits pleasantly on one line across the page.
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by Dmac26** [comment]
@Rebekah-Hernandez I finished merging this code today. Unfortunately you won't be able to check it until it's merged into dev and staging.
