### ISSUE TITLE
As an applicant or administrator I want to be able to download the entire application so that I have the flexibility to access it later without internet.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1218]
## Notes

Applicants and administrators should have the flexibility to choose to download the entire submitted application and save it to a file external of open forest, or print it.
This offers flexibility for the administrator and applicant to access their submitted information without the internet. Currently, if they want to download their application, they have to use the print feature in their browser, which is not an optimal solution, and does not also download the files attached to the application.
![image.png](https://images.zenhubusercontent.com/5a00e34b8a75884b90864b6f/0d6f037e-9347-4168-b684-99c73bbd74b9)

## Acceptance Criteria
- [ ] Applications can be downloaded and saved outside of open forest.
- [ ] Applications can be easily printed
- [ ] Application documents such as uploaded operating plans, maps, required certificates are automatically downloaded with the rest of the application.

## Tasks
- [ ] Mock design for a "download application" button in the View Application Details page
- [ ] Build code to allow the entirety of the application to be downloaded to the computer, and saved as .zip file or PDF or determined best file structure.
- [ ]  Build the download application feature as an option in every applications detail page no matter the application status, or role of viewer (i.e., applicant or administrator)
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by carlsonem** [comment]
@Dmac26 is this blocked, or just not started? Seems like this should move over to the icebox.
