### ISSUE TITLE
As an open forest customer I'd like to be routed to the correct pages from the main landing page, and know that tests are working so that I can get the information I need.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1225]
## Notes
This is directly connected to Epic #1123 
Within the overall main landing page #604 Epic

## Acceptance Criteria
- [ ] We have a skeleton page to begin to build from
 -[ ] We know what branch(es) we're connecting to
- [ ] We know our tests are updated and ready for additional work related to the development of the main landing page.

## Tasks
- [ ] create a sample landing page locally and in dev to work from
- [ ] Build branches to work from
- [ ] update routing to special uses url, 
- [ ] update routing for user view applications, 
- [ ] update routing for admin view applications, 
- [ ] update routing to remove the main Christmas tree landing page route: https://openforest.fs.usda.gov/christmas-trees/forests, 
- [ ] Update admin routing from: https://openforest.fs.usda.gov/admin/christmas-trees/reports  to openforest.fs.usda.gov/christmas-trees/admin/reports 
- [ ] Update admin routing from: https://openforest.fs.usda.gov/admin/applications to openforest.fs.usda.gov/special-uses/admin/applications
- [ ] All login call backs rewrite
- [ ] Fine tooth comb all unit tests and e2e tests (exciting!) and fixing as needed.
- [ ] PO Approved

## Definition of Done
- [ ] e2e tests are updated for application routing changes.
- [ ] e2e tests are functioning. 
- [ ] Child routes for existing pages are working.
- [ ] Pull requests meet technical definition of done.
- [ ] Usability tested.

**Comment by Dmac26** [comment]
@mtlaney The links look good. Everything seems to be routing properly!

**Comment by aaronburk** [comment]
@Dmac26 do you need me to go in and test anything or is it all looking good?
