### ISSUE TITLE
SPIKE Research main landing page deploy to production options

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1226]
## Notes

The purpose of this spike is to  explore ways to keep the main landing page so that it doesn't get deployed to production while still in test while other items need to be moved to production (possible options keep it on dev server, or new instance on cloud.gov and have it build off of 1123 branch vs. dev branch).

We completed a preliminary estimate for this story - but would like Abdul's input.

## Acceptance Criteria
- [ ] We know how we're going to make updates without deploying to production too early.

## Tasks
- [ ] Find out what our best option is
- [ ] Mike and Abdul and Shadat and Matt to pair on this
- [ ] Validation of acceptance criteria completed
- [ ] PO approved

## Definition of Done
- [ ] Decisions are documented, and the team is aware.

**Comment by abdul-fs** [comment]
Sure, we can create a branch and push that changes in Dev env to test the landing page.

**Comment by carlsonem** [comment]
OBE
