### ISSUE TITLE
As a customer I'd like to have a main page to work from so that I know basic content is being constructed.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1227]
## Notes
Need to insert link to the wire frame for construction

## Acceptance Criteria
- [ ] We have a main landing page that we can see/use and is working as expected.

## Tasks
- [ ] Build the main landing page header
- [ ] Build the main page breadcrumbs
- [ ] Build the main landing page "forest products" bar (include Christmas trees only)
- [ ] Build the screen shot or image (place holder) of the interactive map
- [ ] Build the main landing page "special uses permit applications" section
- [ ] Build the main landing page "about" section
- [ ] Build the main landing page footer
- [ ] Incorporate all of the new graphics and .png images
- [ ] PO Approved

## Definition of Done
- [ ] e2e tests are updated 
- [ ] e2e tests are functioning 
- [ ] Child routes are working
- [ ] Pull requests meet technical definition of done
- [ ] The finished page matches the mockup (Christmas trees only, not other products yet).
- [ ] Usability tested

**Comment by carlsonem** [comment]
@mtlaney @briandavidson. Ishan is going to do the map portion of the landing page. Please leave a placeholder on the landing page for him to add his code.

**Comment by carlsonem** [comment]
@ishanashams This is the issue to create the map

**Comment by carlsonem** [comment]
@aaronburk Happen to know where we could get the coordinates for the various Forests? We will need to have the lat/long for the map
