### ISSUE TITLE
As a customer I'd like to know that the interactive map is being constructed so that I can start with finding a forest near me if I want to.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1228]
## Notes
There are some things we're not sure about yet regarding building out the interactive map. This story is attempting to capture some of the research needed, as well as the construction.
We may need to separate those two pieces out when we get to this point; depending on what we've learned so far.

## Acceptance Criteria
- [ ]  We know how we are going to build the interactive map
- [ ] We have an interactive map on the main landing page
- [ ] The interactive map allows users to find a forest near them, and is ready for further refinements.

## Tasks
- [ ] Spike: Ishan (EAD) and Brian call RE integrating ESRI maps - data/information gathering
- [ ] Figure out who will implement the ESRI mapping system/time and coordination w/team
- [ ] Refine further based on information gathered
- [ ] Build the interactive map on the main landing page
- [ ] Build and test map hyperlinks to relevant sections of Open Forest
- [ ] PO Approved

## Definition of Done
- [ ] e2e tests are updated 
- [ ] e2e tests are functioning 
- [ ] Child routes are working
- [ ] Pull requests meet technical definition of done
- [ ] The finished page matches the mockup (Christmas trees only, not other products yet).
- [ ] Usability tested

**Comment by ishanashams** [comment]
thanks
