### ISSUE TITLE
As someone who just completed my Temporary outfitting and guiding application, I'd like my email subject line to correctly reflect they type of permit I've applied for so that I am not confused.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1229]
## Notes
In completing the tasks for story #1203 we discovered that updating the email subject line should be a separate story given the level of work associated with it. 

Currently email notifications regarding temporary outfitting and guiding applications refer to them as "Temp outfitter" applications in the subject line. This should be updated so that the title of the application is accurately reflected.

## Acceptance Criteria
- [ ] The email subject line denotes the full title of the application: "Temporary outfitting and guiding"

## Tasks
- [ ] Update fields associated with temp outfitters so that they recognize "Temporary outfitting and guiding."
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Usability tested
