### ISSUE TITLE
As a customer I'd like to see a list of Forests that offer the product I've selected from the main landing page so that I know what my choices are.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1236]
## Acceptance Criteria
- [ ] From the Home Page Customers can navigate to the forest products page where they can select their national forest of interest, or choose to filter again
- [ ] Every Kid Outdoors banner only displays when filtered by Christmas tree
- [ ] Banner image header is aligned with product filtered by (i.e., noble fir bough show when Christmas tree is filtered, mushrooms show when mushrooms are filtered etc..) 
- [ ] Upon selecting forest (After applying filter) customer is taken to page that allows them to obtain the permit they are interested in (they do not have select their product of interest a second time).

## Tasks
- [ ] Build application routing to take users to the Forest product page pre-filtered based on product type they selected
- [ ] Build page based on Hi-fi sketch https://sketch.cloud/s/L1EZ5/a/pMRDOr
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by aQuib** [comment]
Here is banner image for products page:
![products_hero_banner](https://user-images.githubusercontent.com/2117062/77567435-8647e180-6e9d-11ea-916c-7ea33b63a4b8.png)

**Comment by mtlaney** [comment]
thanks @aQuib !
