### ISSUE TITLE
As a customer I'd like to see a forest's page with all the online permit options available for that forest so that I know what I can do in Open Forest.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1237]
## Notes
Forest Information Page - the page people are brought to after selecting their forest, but without having identified their product of interest.
![image.png](https://images.zenhubusercontent.com/5a00e34b8a75884b90864b6f/3349c145-bcc1-42b1-8617-7c2c8548f1bb)
![image.png](https://images.zenhubusercontent.com/5a00e34b8a75884b90864b6f/c2495221-70b3-487d-951d-10cd05247049)

## Acceptance Criteria
- [ ] From the Home Page Customers can navigate to the Forest's info page where they can select the product or application they are interested in
- [ ] Customers can choose to "Learn More" about all available products
- [ ] Customers can choose to go direct to "Apply" or "Get Permit" if the season is open.
- [ ] Customers can see the season dates for the available product(s)
- [ ] Customer knows what forest page they are on
- [ ] Customer has the ability to go back easily

## Tasks
- [ ] Build application routing to take users to the Forest's information page from the home page when they've selected a forest w/o identifying the product yet.
- [ ] Build page based on Hi-fi sketch https://sketch.cloud/s/L1EZ5/a/pMRDOr (only build in products that are currently available through Open Forest)
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by mtlaney** [comment]
@aQuib do you have a mockup for the 12 forests that don't have special-use permits?

**Comment by aQuib** [comment]
@mtlaney Here is the updated mockup of a forest page without special use:
https://sketch.cloud/s/L1EZ5/a/OpPQWq

**Comment by Rebekah-Hernandez** [comment]
@mtlaney For forest specific images when you're ready, this is what I was able to find from the flickr account:
https://usfs.app.box.com/folder/105403496623

And a couple forests sent images as well:
https://usfs.app.box.com/folder/105403433535

**Comment by mtlaney** [comment]
@Rebekah-Hernandez @aQuib Do you guys have any images we should use for the below forests?

ARP
FREMONT-WINEMA
WILLAMETTE
OKANOGAN-WENATCHEE
UMATILLA
OCHOCO

**Comment by Rebekah-Hernandez** [comment]
@mtlaney Umatilla and ARP forest admins sent a few pictures in and here is where those pics are:

https://usfs.app.box.com/folder/105403433535

Other than that, I was unable to find anything forest specific on the flickr nor have I received anything from the forests themselves. If @aQuib thinks it might be a good idea to search elsewhere, I can try to find more images on the internet. Just not sure which sources are good to use.

**Comment by mtlaney** [comment]
@Rebekah-Hernandez Thanks Rebekah, I did see the umatilla and arp photos, but I don't believe they are the quality we're looking for.
