### ISSUE TITLE
BUG NCGU and TOG application emails not going to applicants

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1242]
## Notes

(in staging) Applicants are not receiving emails when initially submitting applications or when updating applications from being on hold.

## Acceptance Criteria
- [x] Admins are receiving email notifications when TOG applications are submitted
- [x] Admins are receiving email notifications when NCGU applications are submitted
- [x] Admins are receiving email notifications when TOG applications are updated by the applicant in response to "hold" status.
- [x] Admins are receiving email notifications when NCGU applications are updated by the applicant in response to "hold" status.
- [x] Applicants are receiving email confirmations when TOG applications are submitted.
- [x] Applicants are receiving email confirmations when NCGU applications are submitted.
- [x] Applicants are receiving email notifications when a TOG application is put on hold.
- [x] Applicants are receiving email notifications when a NCGU application is put on hold.
- [x] Applicants are receiving email notifications when a TOG application is rejected.
- [x] Applicants are receiving email notifications when a NCGU application is rejected.
- [x] Applicants are receiving email notifications when a TOG application is sent to suds.
- [x] Applicants are receiving email notifications when a NCGU application is sent to suds.

## Tasks
- [x] Mike to refine
- [x] Validation of acceptance criteria completed
- [x] PO approved

## Definition of Done
- [x] Pull requests meet technical definition of done
- [] Compare finished design with mockup
- [x] Usability tested

**Comment by abdul-fs** [comment]
issue is fixed by smtp email. Its been tested in staging and we are able to generate emails outside USDA.

![image](https://user-images.githubusercontent.com/31516419/75810659-fe1c6380-5d58-11ea-95c4-045935fcbd61.png)

**Comment by mwreiss** [comment]
Additional note: This could have been caused by a higher level policy push that we were not notified about.  May need to dig a little further.

**Comment by aaronburk** [comment]
re the "Definition of done" items complete? 
![image](https://user-images.githubusercontent.com/25828899/75887715-345cf000-5df8-11ea-80c1-de72b111e188.png)

**Comment by abdul-fs** [comment]
yes, we should be good to close this card.
