### ISSUE TITLE
Christmas Tree Forest Content Maintiance

### ISSUE THREAD

**Issue by carlsonem** [USDAForestService/fs-open-forest-platform#1267]
## Notes
Find a more efficient way for new and existing forests to add/edit content on their individual forest Christmas tree forests pages so that developers don't need to be involved to make as many content changes.

## Acceptance Criteria
- [ ] Forest are able to make content updates to their own forest pages to reduce the workload on developers.

## Tasks
- [ ] Identify which fields a forest should be able to make their own content changes to
- [ ] If 
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested
