### ISSUE TITLE
As an xmas admin I want the team to conduct research to inform what parts of the xmas tree platform I should have access to update so that I can do admin things easily.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1282]
## Notes
This story is within Epic 1027.

This story is specific to accomplishing the user experience research necessary to inform an MVP design deliverable

## Acceptance Criteria
- [ ] We understand which parts of the Christmas tree platform admins will have the autonomy to update 
- [ ] We are ready to develop a low fidelity wireframe for the admin content updates interface.

## Tasks
- [ ] Identify what fields the forest would prefer to maintain themselves
- [ ] Verify fields don't violate a security policy
- [ ] Verify fields identified with Forests- what is specific to certain forests that need contextual inputs
- [ ] Determine if new roles are required, if so updated role based access
- [ ] Validation testing
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
@aQuib This is the first story from the 1027 epic development. Considering our meeting earlier today, I set this one up as "In Progress" and tagged you in it.  Not sure if Rebekah should also be assigned to this card.  @carlsonem FYI :)

**Comment by aQuib** [comment]
@aaronburk  - The user interview insight are [located here in Pinyon](https://usfs.box.com/s/4iufyqd69z0yonb4bgocbh3xk47c2lij) if you wish to review.
