### ISSUE TITLE
As an xmas admin I'd like to test a low-fi wireframe that would allow me to update information so that I can do xmas tree admin things easily.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1283]
## Notes
This story is within Epic #1027

This story is specifically related to the design and testing of a low-fi wire frame.
The low-fi wire frame should incorporate the results of story #1282

## Acceptance Criteria
- [ ] We have received feedback on the low-fi wire frame
- [ ] We have an understanding of what is needed to improve the admin content updates interface.

## Tasks
- [ ] Build low fi wireframe
- [ ] Test with users
- [ ] Review with dev
- [ ] Test with FS admins

- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by aQuib** [comment]
Here is the finalized [Usability Research Plan](https://usfs.app.box.com/notes/659342539817)

**Comment by aQuib** [comment]
Here are the [Insights for Usability Testing](https://usfs.box.com/s/juxtke5cgye81r69q2jq2oy72v8hbr60)
