### ISSUE TITLE
As an xmas admin want the Development team to build admin content update portal from a high-fidelity wire frame so that I'll be able to easily update my forest's Christmas tree content.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1284]
## Notes
This story is within Epic #1027

This story is specific to building a high-fidelity wire frame based off of what we learned from the low-fidelity wire frame tests.  This story builds the high-fidelity wire frame, and hands it off to the development team for build to staging.

## Acceptance Criteria
- [ ] A high fidelity wire frame is designed
- [ ] The development team understands how to use it, and is ready to build it in staging.

## Tasks
- [ ] Design a high fidelity wireframe
- [ ] Meet with the development and security team for design hand off
- [ ] 
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested
