### ISSUE TITLE
As an xmas admin I want to access a content updates section of the admin site so that I can update my forests Christmas tree information without having to go through the Open Forest team first.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1285]
## Notes
This story is within epic #1027

This story is specific to building the high fidelity wire frame so that it can be tested by Admins on the staging site.

## Acceptance Criteria
- [ ] In the staging site, admins can update content for their forest.
- [ ] We have an understanding of what further tests or builds are needed before we push the updates to production. 

## Tasks
- [ ] Build the high fidelity wireframe from story 1285
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by carlsonem** [comment]
@carlsonem update
