### ISSUE TITLE
As an xmas admin I want to test content updates in staging so that I know I'll be able to do Christmas tree admin things easily this coming season.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#1286]
## Notes
This is the last story of Epic #1027.

This story is specific to testing with FS admins what has been built in the staging site for admins to be able to make content updates.

## Acceptance Criteria
- [ ] We know how well the new functions will work for admins
- [ ] We have an understanding of what is needed next (push to prod, or additional updates before push to prod)

## Tasks
- [ ] Test with FS Admins
- [ ] Validation testing
- [ ] PO approved

## Definition of Done
- [ ] Tasks are completed
- [ ] A/C is met
- [ ] Documentation from tests are saved in an easily accessible location.
