### ISSUE TITLE
As an Admin I want the radio button for the forest's season dates I am viewing to remain selected so that I always know which forest's dates I am viewing..

### ISSUE THREAD

**Issue by Dmac26** [USDAForestService/fs-open-forest-platform#1297]
## Notes

When attempting to change the season dates on a forest in the staging site, it was noticed that the radio button indicating which forest's season date you are viewing goes to an un-selected state after the "Update season dates" button is clicked. An example of the issue, with screenshots, can be seen below. 

The Ochoco forest is selected and the default season dates are displayed.
![RadioButton_1.PNG](https://images.zenhubusercontent.com/5d93a896a615ef000109902d/a5a35cf9-81a2-470f-82f4-baf3d2fdd309)

The season dates are updated in the text fields.
![RadioButton_2.PNG](https://images.zenhubusercontent.com/5d93a896a615ef000109902d/e8653dd1-5ad5-4104-ad9f-d52e09dbefa5)

A display of the Ochoco forest after the "Update season dates" button was selected. As you can see, radio button appears un-selected.
![RadionButton_3.PNG](https://images.zenhubusercontent.com/5d93a896a615ef000109902d/3959b54a-899d-4e31-a7be-61d615130532)

## Acceptance Criteria
- [ ] The radio button indicating which forest's dates you are viewing remains selected.

## Tasks
- [ ] Refactor logic to allow the radio button to remain selected even after clicking "Update season dates".
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested
