### ISSUE TITLE
As a Super User Admin, I would like to be able to choose my forest in the season dates and cutting area dates, so that I can change the dates for my forest if I need to.

### ISSUE THREAD

**Issue by Rebekah-Hernandez** [USDAForestService/fs-open-forest-platform#1298]
## Notes
The superuser admin role is not allowing the admin to choose their forest when changing season dates or area cutting dates.

![68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3564393361373732633865346438303030313232376139352f35643864613563352d656161642d346164662d383734392d383962366533363365636363 copy](https://user-images.githubusercontent.com/56045852/79903798-54ad3200-83d9-11ea-8e91-52e875f1df2f.png)

![68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3564393361373732633865346438303030313232376139352f35383738366330622d393230332d343538312d393635622d303466306563616333303134 copy](https://user-images.githubusercontent.com/56045852/79903805-57a82280-83d9-11ea-8787-677222ba709a.png)

## Acceptance Criteria
- [ ] The superuser admin role has all the needed permissions and availability for all forests

## Tasks
- [ ] The superuser admin role is able to see all of the forests under Season Dates
- [ ] The superuser admin role is able to change the season dates for any forest
- [ ] The superuser admin role is able to see all of the forests under Cutting Area Dates
- [ ] The superuser admin role is able to change the cutting area dates for any forest
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Usability tested

**Comment by mwreiss** [comment]
Christmas Tree:
![image](https://user-images.githubusercontent.com/50459930/80377665-345df700-8861-11ea-96f2-9ff43a5067e9.png)

![image](https://user-images.githubusercontent.com/50459930/80377785-53f51f80-8861-11ea-86fa-783f20559163.png)

![image](https://user-images.githubusercontent.com/50459930/80377835-666f5900-8861-11ea-82b0-4cac4358124d.png)



Special Uses:

![image](https://user-images.githubusercontent.com/50459930/80377479-f5c83c80-8860-11ea-8de4-19d927dbbd1c.png)

**Comment by briandavidson** [comment]
Hey @carlsonem and @Rebekah-Hernandez as discussed in standup earlier this seems to be redundant with #1182 and can be closed.

The PR for that is [here](https://github.com/USDAForestService/fs-open-forest-platform/pull/1315). After it gets approved and merged in this issue will be resolved.
