### ISSUE TITLE
As a MBS admin, I would like to be able to submit an application and view the details so that I can test and process applications.

### ISSUE THREAD

**Issue by Rebekah-Hernandez** [USDAForestService/fs-open-forest-platform#1299]
## Notes
We are seeing 2 errors in the dev environment for MBS.

1. When submitting an application, an error is being shown instead of submitting:

![test-dev-ncgu-partial-screen.PNG](https://images.zenhubusercontent.com/5d93a772c8e4d80001227a95/e67e42a0-ab92-45db-9704-d6c5a1caa797)

![test-dev-tog-partial-screen.PNG](https://images.zenhubusercontent.com/5d93a772c8e4d80001227a95/e11db866-9a30-4199-8d36-e0298dfc10e1)

2. When an admin is attempting to view any application details, they are given an error.

![sudev_appdeets.PNG](https://images.zenhubusercontent.com/5d93a772c8e4d80001227a95/7332926f-2443-47c1-9a95-aa211510b114)

## Acceptance Criteria
- [ ] MBS Admin role is functioning properly

## Tasks
- [ ] MBS Admin role is able to submit an TOG application
- [ ] MBS Admin role is able to submit a NCGU application
- [ ] MBS Admin role is able to view details for applications
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Usability tested

**Comment by briandavidson** [comment]
Hey @carlsonem and @Rebekah-Hernandez as discussed in standup earlier this seems to be redundant with #1182 and can be closed.

The PR for that is [here](https://github.com/USDAForestService/fs-open-forest-platform/pull/1315). After it gets approved and merged in this issue will be resolved.
