### ISSUE TITLE
As a Regional admin, I would like to have the correct permissions so that I can perform my job well.

### ISSUE THREAD

**Issue by Rebekah-Hernandez** [USDAForestService/fs-open-forest-platform#1300]
## Notes
We would like to add 2 new Regional POC eAuth roles for Arapaho Roosevelt and Flathead

![neweauthroles.PNG](https://images.zenhubusercontent.com/5d93a772c8e4d80001227a95/8cafe55c-5721-4902-9772-b881becc312c)

## Acceptance Criteria
- [ ] POC 1 for Arapaho Roosevelt has been updated
- [ ] POC 2 for Arapaho Roosevelt has been updated
- [ ] POC 1 for Flathead has been updated
- [ ] POC 2 for Flathead has been updated

## Tasks
- [ ] Update FS_Open-Forest_arp_POC1  AND  FS_Open-Forest_arp_POC2 to point to FS_Open-Forest_R02 Instead of FS_Open-Forest_R06
- [ ] Update FS_Open-Forest_flathead_POC1 AND FS_Open-Forest_flathead_POC2 to point to FS_Open-Forest_R01 instead of FS_Open-Forest_R06
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Usability tested

**Comment by mwreiss** [comment]
**I assigned R02 Role and got a successful result, I see the two region 2 forest show up as expected.**

![image](https://user-images.githubusercontent.com/50459930/83261873-acca1780-a181-11ea-9f5f-1ffba79edf16.png)

**R02 Season Dates look great:**

![image](https://user-images.githubusercontent.com/50459930/83262026-e8fd7800-a181-11ea-8ed8-deccf4b1a1b2.png)

**R02 Cutting area dates look great:**

![image](https://user-images.githubusercontent.com/50459930/83262241-42fe3d80-a182-11ea-83e3-f87e27f83359.png)

**Comment by mwreiss** [comment]
![image](https://user-images.githubusercontent.com/50459930/83262657-fbc47c80-a182-11ea-87f0-194054c139f0.png)

**Comment by Rebekah-Hernandez** [comment]
I'm seeing Region 6 as this:

Generate Reports
![Generate_r6](https://user-images.githubusercontent.com/56045852/83267491-eacb3980-a189-11ea-8021-80378abb3dd2.PNG)

Changing Season Dates
![seasondates_r6](https://user-images.githubusercontent.com/56045852/83267508-f159b100-a189-11ea-8920-90467a744402.PNG)

Cutting Area Dates
![cuttingarea_r6](https://user-images.githubusercontent.com/56045852/83267521-f61e6500-a189-11ea-8d4b-fac81f48e576.PNG)

**Comment by mwreiss** [comment]
Roles work when moved to Staging environment: R02 role

![image](https://user-images.githubusercontent.com/50459930/83289605-ec592980-a1aa-11ea-94d9-8b2bff9c5341.png)

**Comment by Rebekah-Hernandez** [comment]
Region 6 in staging:

Generate Reports
![generate_staging_r6](https://user-images.githubusercontent.com/56045852/83290270-021b1e80-a1ac-11ea-825d-eea55fa3b18a.PNG)

Changing Season Dates
![staging_seasondates_r6](https://user-images.githubusercontent.com/56045852/83290298-0cd5b380-a1ac-11ea-89cd-f01a52e20b0d.PNG)

Cutting Area Dates
![cuttingarea_staging_r6](https://user-images.githubusercontent.com/56045852/83290318-1828df00-a1ac-11ea-896e-2fc3659152f0.PNG)

**Comment by aaronburk** [comment]
i notice non of  the boxes have been checked related to task @Rebekah-Hernandez @briandavidson .  Have all the tasks been completed?? They look good per Matt's input.
 Thanks!!

**Comment by Rebekah-Hernandez** [comment]
@aaronburk Everything's checked off now, thank you!
