### ISSUE TITLE
As a MBS admin, I would like all of the redirected to the correct pages so that there are no errors and I can easily get to where I need to go

### ISSUE THREAD

**Issue by Rebekah-Hernandez** [USDAForestService/fs-open-forest-platform#1313]
## Notes
When Amber was testing, it was found that some of the pages redirected after the log out or canceling an application to error pages:

![MicrosoftTeams-image (1).png](https://images.zenhubusercontent.com/5d93a772c8e4d80001227a95/e0e2f608-bf01-4a83-8a75-1d94e5ab0ffc)

![MicrosoftTeams-image.png](https://images.zenhubusercontent.com/5d93a772c8e4d80001227a95/25163d92-56ce-49f4-8026-705cf09968b9)

The cancellation of the application still went through, but the redirection after the cancellation was to an error page.

## Acceptance Criteria
- [ ] No pages lead to a 404 error

## Tasks
- [ ] Logging out as an admin will lead to the landing page
- [ ] Cancelling an application will lead to a confirmation page
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Usability tested

**Comment by briandavidson** [comment]
@mtlaney I'm taking myself off as one of the assignees for this one just to help stay organized - assuming this was part of the routes rework but obv LMK if ya need me to hop on it :)

**Comment by mtlaney** [comment]
@Dmac26 thanks Dylan, it hasn't been pushed to staging yet.
