### ISSUE TITLE
Integrating Open Forest Help Desk Tickets w/ ServiceNow

### ISSUE THREAD

**Issue by carlsonem** [USDAForestService/fs-open-forest-platform#1333]
## Notes
Help desk tickets that are submitted from the Open Forest system are captured in ServiceNow.

## Acceptance Criteria
- [ ] Ticket is submitted from Open Forest System and Open Forest support team receives notification of ticket via email

## Tasks
- [ ] Discover capabilities of ServiceNow ticketing system
- [ ] Add Open Forest to ServiceNow system
- [ ] User accounts created for Open Forest team
- [ ] Add any additional fields to ServiceNow ticket system that are required and not included on standard form
- [ ] Update Open Forest code to have email routed to ServiceNow system
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Usability tested
