### ISSUE TITLE
Minimal Landing Page for Prod Release

### ISSUE THREAD

**Issue by mtlaney** [USDAForestService/fs-open-forest-platform#1342]
## Notes
Create a minimal landing page for PROD release that not include links to Products Pages or Christmas tree pages

## Acceptance Criteria
- [ ] Landing Page only includes map and MBS links
- [ ] Christmas Trees still works
- [ ] Products still works

## Tasks
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested
