### ISSUE TITLE
As a Open Forest employee, I would like to see the development workflow, deployment pipeline and checks on the wiki page so I have easy access to the information I need to perform my job well.

### ISSUE THREAD

**Issue by Rebekah-Hernandez** [USDAForestService/fs-open-forest-platform#1350]
## Notes
We want to put the development workflow and the deployment pipeline and checks onto the wiki page from a presentation that was previously made.

## Acceptance Criteria
- [ ] All the necessary information is included on the wiki page
- [ ] Wiki page has been included into the sidebar for easy access

## Tasks
- [ ] Development workflow information is on the wiki
- [ ] Deployment pipeline overview is on the wiki
- [ ] Deployment pipeline checks are on the wiki
- [ ] New wiki page is a part of the sidebar 
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done

**Comment by Rebekah-Hernandez** [comment]
The information and images that I have are up on the wiki here:

https://github.com/USDAForestService/fs-open-forest/wiki/Development-Workflow-and-Pipeline-Checks

For @mwreiss @smahmudFS @aaronburk to take a look at when convenient. Please let me know if there is any more information that needs to be included.

**Comment by mwreiss** [comment]
@Rebekah-Hernandez looking awesome!  I sent you a few updates in DM.  All in all looks great.

**Comment by Dmac26** [comment]
@Rebekah-Hernandez 

Hey, it looks good! Moving it over to "Awaiting Acceptance"

**Comment by aaronburk** [comment]
Looks great
