### ISSUE TITLE
Ensure Forest with active Open Forest permits have live link from the landing page map to Open Forest

### ISSUE THREAD

**Issue by aaronburk** [USDAForestService/fs-open-forest-platform#1354]
## Notes
* What are things we should consider when making this story *
The current link is directing user to the general Forest page and there will be a need for an additional link to Open Forest to get a permit 
## Acceptance Criteria
- [ ] When the user clicks on the polygon the a link pops up to the Open Forest permit

## Tasks
- [ ] Create a layer that allows for another filed to be added for the link to Open Forest
- [ ] Add a field to the existing layer to allow for Open Forest links to be added
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by carlsonem** [comment]
@mtlaney has any work been done on this one yet?

**Comment by mtlaney** [comment]
@carlsonem Not as of yet

**Comment by mtlaney** [comment]
@Dmac26 can you verify this one is good for validation? 

Steps to re-prod
Open Dev, and on the mainpage click on one of our firewood forests. You should see a link to firewood permits.

<img width="794" alt="Screen Shot 2020-10-19 at 8 55 56 PM" src="https://user-images.githubusercontent.com/18233188/96527277-b433af80-124d-11eb-81ee-901bf7221ea0.png">
