### ISSUE TITLE
Close the Open Forest Christmas Tree product site

### ISSUE THREAD

**Issue by aaronburk** [USDAForestService/fs-open-forest-platform#1355]
## Notes
Ensure is someone clicks on Open Forest during Christmas Season the receive guidance to contact their local Forest for information on Christmas Tree Sales (this may be re-visted when the Recreation.gov staff stand up their Christmas Tree sales system we can add a link to that service but for now we need something that at least sends a user to a local forest)

## Acceptance Criteria
- [ ] Messaging needs to be clear an concise so user know what to do if they would like to purchase a Christmas Tree

## Tasks
- [ ] Write a message and ensure it somehow conveyed on the landing page before October 15th 2020
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by MelissaBraxton** [comment]
When we're ready to pick this up, consider reframing around the needs who arrive to the site looking for Christmas tree permits. Something like: 

_As a member of the public who visits Open Forest looking for a Christmas tree permit, I need to know that the site no longer offers Christmas tree permits and where I can go to get one..."

**Comment by carlsonem** [comment]
@aQuib

**Comment by Rebekah-Hernandez** [comment]
First design mocks for this story here:

On the landing page
![landing-page](https://user-images.githubusercontent.com/56045852/91861501-81e4d900-ec32-11ea-86b4-a88a328fa6d3.png)

If someone searches openforest.usda.gov/christmas-trees/forests
![christmas-trees](https://user-images.githubusercontent.com/56045852/91861546-94f7a900-ec32-11ea-9667-a0e7a1304a82.png)

**Comment by aQuib** [comment]
@Rebekah-Hernandez - I have minor changes I will send to you regarding the language of these mockups.

**Comment by Rebekah-Hernandez** [comment]
Based on @aQuib notes, the text has been reworded and is shown here. Please check when you are able to move forward.

landing page
![landing-page2](https://user-images.githubusercontent.com/56045852/91992403-b5d70180-ecf9-11ea-91b9-2c2e95c2eb03.png)

/christmas-trees
![christmas-trees2](https://user-images.githubusercontent.com/56045852/91992439-c2f3f080-ecf9-11ea-807d-0f2fbf095f87.png)

**Comment by mtlaney** [comment]
@carlsonem @aQuib @Rebekah-Hernandez Let's review this one today in standup, it looks like it's probably ready for the engineering tab, nice work guys!

**Comment by Rebekah-Hernandez** [comment]
Should be the final update. Changed the link so this should be good to go!

![landing-page3](https://user-images.githubusercontent.com/56045852/92150819-a6cd7d80-ede5-11ea-93c6-c68f983865aa.png)
![christmas-trees3](https://user-images.githubusercontent.com/56045852/92150825-a9c86e00-ede5-11ea-838a-5486fad6e7dd.png)

**Comment by carlsonem** [comment]
@mtlaney Is this one complete? If I'm not mistaken, you finished it

**Comment by mtlaney** [comment]
@carlsonem no not yet, I'm starting it this morning. I'll change the tag over to Engineering

**Comment by mtlaney** [comment]
@aQuib and Julie, this one is ready for design review on dev

**Comment by mtlaney** [comment]
@Dmac26 can you review this one on dev. Looks good to me, if g2g please move to awaiting acceptance.
