### ISSUE TITLE
As a Special-Use Administrator I'd like to know that any and all links in the permit email I receive are routed correctly so that I can easily get to the Special-Use Admin section

### ISSUE THREAD

**Issue by Dmac26** [USDAForestService/fs-open-forest-platform#1362]
## Notes
Administrators should have the ability to navigate to the admin section of special-uses from the permit application email that is sent to administrators. Currently the link is throwing a 404 error as it is using the old route the the admin page.

![AdminEmailCapture.PNG](https://images.zenhubusercontent.com/5d93a896a615ef000109902d/bcbbcf8a-5aec-4f20-8744-ac368d1a2995)
![AdminLink404Capture.PNG](https://images.zenhubusercontent.com/5d93a896a615ef000109902d/30138da4-bdbe-4625-a07c-4e61cda58f41)

## Acceptance Criteria
- [ ] Admins are able to navigate from the Permit Application email to the admin sections via the link included in the email

## Tasks
- [ ] Update the route of the link included in the auto-generated application email that admins receive so that it goes to the current admin section for special-uses
- [ ] Validation of acceptance criteria
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested
