### ISSUE TITLE
As a Special Use admin, I would like to have access to applications from Open Forest in the role that I am assigned, so that I can review special use applications.

### ISSUE THREAD

**Issue by Rebekah-Hernandez** [USDAForestService/fs-open-forest-platform#1364]
## Notes
On all environments, roles POC1 and POC2 for MBS are not redirecting or allowing access to the applications on the admin side. When attempting to log in at the correct url: (prod: https://openforest.fs.usda.gov/special-use/admin/applications; staging: https://open-forest-staging.app.cloud.gov/special-use/admin/applications), the admin is redirected to a logged in blank page:

![garcia.jpg](https://images.zenhubusercontent.com/5d93a772c8e4d80001227a95/e7e410c9-7d32-4d80-8dc4-a9b2f85a988d)

## Acceptance Criteria
- [ ] POC1 is able to access the MBS applications in dev/staging environment
- [ ] POC1 is able to access the MBS applications in the prod environment
- [ ] POC2 is able to access the MBS applications in the dev/staging environment
- [ ] POC2 is able to access the MBS applications in the prod environment

## Tasks
- [ ] The source of the issue has been found
- [ ] 
- [ ] All POC1 roles are working as expected
- [ ] All POC2 roles are working as expected
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Usability tested

**Comment by briandavidson** [comment]
@Rebekah-Hernandez I'll need to be temporarily assigned one of the problematic roles to work on this please.

**Comment by Rebekah-Hernandez** [comment]
@briandavidson you've been assigned both POC1 and POC2

**Comment by Rebekah-Hernandez** [comment]
@briandavidson you've been assigned POC1 and @mtlaney is assigned POC2

**Comment by mwreiss** [comment]
It appears this resolved the issue!  Woo!hoo!

Great work team!

![image](https://user-images.githubusercontent.com/50459930/94697196-84078980-02fd-11eb-82a9-69432c3d9f8c.png)


![image](https://user-images.githubusercontent.com/50459930/94697448-d5b01400-02fd-11eb-88ed-af7d0d1cf0d2.png)
