### ISSUE TITLE
As Special-Use Admin I'd like to know that I can accept applications to SUDS without getting a warning message, so that I can respond to our applicants in a timely manner.

### ISSUE THREAD

**Issue by Dmac26** [USDAForestService/fs-open-forest-platform#1371]
## Notes
Currently, admins on Special-Uses (whether POC1, POC2, or SuperUser) are unable to accept applications to SUDS. Instead they get a warning message informing them that their request was not able to processes. 

![can't accept app snap.jpg](https://images.zenhubusercontent.com/5d93a896a615ef000109902d/d9b2f47c-7b69-4b69-a758-a57d1bb10006)

## Acceptance Criteria
- [ ] Super Users are able to accept applications to SUDS
- [ ] POC1 users are able to accept applications to SUDS
- [ ] POC2 users get the proper warning message when the attempt to accept applications

## Tasks
- [ ] Reproduce the issue in production for testing purposes
- [ ] Test to see if issues reproduces in dev and staging
- [ ] Identify recent change preventing admins from accepting applications
- [ ] Correct or revert any changes that are preventing admins from accepting applications

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Usability tested

**Comment by Dmac26** [comment]
It's come to our attention that this same issue can be reproduced locally, with a more descriptive error message.

![submitToSUDSError.png](https://images.zenhubusercontent.com/5d93a896a615ef000109902d/43fb6f38-7c22-4aea-a978-301f3b1bbd9f)

**Comment by abdul-fs** [comment]
@Dmac26 @mwreiss @ericsorenson This is completed. The issue was in suds accepting permits in dev and staging. It is resolved.  the issue was site was down from suds database team.

**Comment by abdul-fs** [comment]
![image](https://user-images.githubusercontent.com/31516419/84820672-fde26400-afe7-11ea-810f-dd67ae2dc8cd.png)
