### ISSUE TITLE
Implement Sonarqube Fixes for PROD

### ISSUE THREAD

**Issue by mtlaney** [USDAForestService/fs-open-forest-platform#1379]
## Notes
We need to implement Sonarqube fixes for production release. This includes fixing 8 bugs and 8 code fixes. 

## Acceptance Criteria
- [ ] Sonarqube is not passing all tests

## Tasks
- [ ] Implement fixes for 8 bugs
- [ ] Implement fixes for 8 code smells

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested
