### ISSUE TITLE
As an Open Forest Admin I'd like both the "Business name" field in the TOG application and the "Organization name" field in NCGU application to have their character limits restricted to 30 characters so that I can know end user's applications will be accepted to SUDS.

### ISSUE THREAD

**Issue by Dmac26** [USDAForestService/fs-open-forest-platform#1386]
## Notes

While troubleshooting the reason for a certain applicant's application not being accepted into SUDS it was determined that two fields in the Open Forest platform that require user input point to the ORG_CODE column in the SUDS database. Unfortunately, this column only accepts a string of 30 characters or less.

For the time being, the fields in our Open Forest application that point to this column (as pictured below) need to have their character limits restricted to 30 characters with accompanying hint text and error message so that the user is made aware of this restriction before making the input and in the event that they exceed the limit.

![BusinessNameField.PNG](https://images.zenhubusercontent.com/5d93a896a615ef000109902d/b40ff053-00eb-47cb-88e9-84f54e6b3612)

![OrganizationNameField.PNG](https://images.zenhubusercontent.com/5d93a896a615ef000109902d/26c946b9-f065-4861-a81e-3a9213c9d380)

## Tasks
- [ ] Restrict the character limit of the "Business name" field to 30 characters
- [ ] Add hint text to the "Business name" field to make the user aware of the 30 character limit
- [ ] Change the error message that fires for the "Business name" field to trigger at 30 characters so that the user is aware if they have passed their limit
- [ ] Restrict the character limit of the "Organization name" field to 30 characters
- [ ] Add hint text to the "Organization name" field to make the user aware of the 30 character limit
- [ ] Change the error message that fires for the "Organization name" field to trigger at 30 characters so that the user is aware if they have passed their limit
- [ ] While make these corrections determine which column/s in our DB the "Business name" and "Organization name" fields are pointing to for future improvements
- [ ] Make a card for the Icebox linked to this card explaining the changes that were made and laying out the steps needed to get the ORG_CODE column in the SUDS DB changed to allow at least 60 characters
- [ ] PO approved

## Definition of Done
- [ ] Both the "Business name" and "Organization name" fields have had their character limits restricted to 30 characters
- [ ] Both the "Business name" and "Organization name" fields have hint text warning the user that they are only allowed 30 characters for their business' or organization's name
- [ ] Both the "Business name" and "Organization name" fields have error messages that are thrown when a user inputs more than 30 characters
- [ ] A card has been created in the Icebox pipeline to ensure follow up to this issue

**Comment by Dmac26** [comment]
@aQuib - Hey Aquib, would you mind taking a look at a change I made for this card? As you can see in the screenshots below I added some hint text to two fields, that informs the user of a character limit. Is hint text okay in the situation? And, if so, do you like the current format or is there any change you'd like me to make?

Thank you sir!

![BusinessNameNoHint.png](https://images.zenhubusercontent.com/5d93a896a615ef000109902d/4139ae58-338e-4f9f-8bbb-db951dcacf6d)
![Business name HInt.png](https://images.zenhubusercontent.com/5d93a896a615ef000109902d/f53d98de-afbb-46ed-a7da-8e142ce7bf19)

![OrganizationNameNoHint.png](https://images.zenhubusercontent.com/5d93a896a615ef000109902d/54aca151-1316-4c9c-b364-4f782c4b8ec4)
![Organization name Hint.png](https://images.zenhubusercontent.com/5d93a896a615ef000109902d/c4f9b9f7-f6aa-49da-a10a-46bb9617fcd6)

**Comment by aQuib** [comment]
@Dmac26  - I would move the location to right below the input field and reduce the text to say "Only 30 character allowed" etc (which adhere more the USWDS approach for character counter limits)

**Comment by mtlaney** [comment]
tested to be working correctly on dev
