### ISSUE TITLE
As an Open Forest Admin I'd like title descriptions of each section of the TOG and NCGU applications to be bold as per the original design so that users have a consistent experience.

### ISSUE THREAD

**Issue by Dmac26** [USDAForestService/fs-open-forest-platform#1387]
## Notes
At some point the title descriptions for the TOG and NCGU applications was un-bolded. During testing for the [1215](https://app.zenhub.com/workspaces/open-forest-58f8bbe105a35fad2d275a0c/issues/usdaforestservice/fs-open-forest-platform/1215)this inadvertent change was noticed. This card is to revert those title descriptions to their original design. The screenshots below show the original and current designs of these sections.

## Tasks
- [ ] Every title description of the TOG application has been reverted to it's original bold design
- [ ] Every title description of the NCGU application has been reverted to it's original bold design
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by Rebekah-Hernandez** [comment]
No critiques. Validated today. Looks good!
