### ISSUE TITLE
As a Special Use Admin I'd like for end users to have the ability to enter their entire Business or Organization name while still allowing their application to be accepted to SUDS

### ISSUE THREAD

**Issue by Dmac26** [USDAForestService/fs-open-forest-platform#1393]
## Notes

While troubleshooting the reason for a certain applicant's application not being accepted into SUDS it was determined that two fields in the Open Forest platform that require user input point to the `ORG_CODE` column in the SUDS database. Unfortunately, this column only accepts a string of 30 characters or less.

The [1386](https://app.zenhub.com/workspaces/open-forest-58f8bbe105a35fad2d275a0c/issues/usdaforestservice/fs-open-forest-platform/1386) card addressed this issue temporarily by restricting the character limit for the "Business name" and "Organization name" fields. Going forward we would like the users to be able to input more than 30 characters to ensure that they can enter their entire business or organization name.

NOTE: The two columns in our database that point to the SUDS database's `ORG_CODE` are the `applicant_info_org_name` columns in both the `noncommercialApplications` table and the `tempOutfitterApplications` table in our database.

Below are some screenshots showing the fields affected:

![BusinessNameField.PNG](https://images.zenhubusercontent.com/5d93a896a615ef000109902d/b40ff053-00eb-47cb-88e9-84f54e6b3612)

![OrganizationNameField.PNG](https://images.zenhubusercontent.com/5d93a896a615ef000109902d/26c946b9-f065-4861-a81e-3a9213c9d380)

## Tasks
- [ ] Reach back out to Aaron Burk to check on the possibility of having SUDS expand their character limit of the ORG_CODE column or perhaps they have another column we can point to
- [ ] Reach out to SUDS to see about expanding ORG_CODE or if they have another column we can point to
- [ ] experiment with other solutions to the problem: perhaps the Organization name only needs to be restricted/sliced down as an Admin submits the application to SUDS (Are we OK with SUDS having an incomplete Business or Org name?)
- [ ] PO approved

## Definition of Done
- [ ] A permanent solution for the character limit issue has been settled upon
- [ ] A new card for that permanent solution is created
