### ISSUE TITLE
Remove extra forest.abbr and dead map link from IPNF

### ISSUE THREAD

**Issue by mtlaney** [USDAForestService/fs-open-forest-platform#1407]
## Notes
* There is an extra {{forest.abbr}} inside of IPNF when to cut that needs removed. There is also a dead map link for IPNF couers d'alene that will need removed until we get an updated map *

## Acceptance Criteria
- [ ] {{forest.abbr}} is removed
- [ ] couers d'alene map link is temp removed

## Tasks
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested
