### ISSUE TITLE
Create NRM test API endpoint

### ISSUE THREAD

**Issue by mtlaney** [USDAForestService/fs-open-forest-platform#1414]
## Notes
* NRM needs an endpoint setup to test the data flow connecting to the application *

## Acceptance Criteria
- [ ] New endpoint has been created
- [ ] API endpoint can access a simple get request to return data
- [ ] Has been tested on Swagger

## Tasks
- [ ] Create endpoint
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested
