### ISSUE TITLE
NRM-EDW - TIM data feed interface and related business logics

### ISSUE THREAD

**Issue by smahmudFS** [USDAForestService/fs-open-forest-platform#1438]
## Notes
* Establish business rules and logics associated with NRM TIM to receive data from Open Forest, for upward reporting to CDW and EDW.

## Acceptance Criteria
- [ ]Design is agreed and signed off by PO, and NRM
- [ ]Design is tested and validated via API pilot implementation  

## Tasks
- [ ] NRM to provide initial design
- [ ] OF to validate NRM design against planned User Stories and Design, including data fields 
- [ ] OF to provide input to NRM design with specific data field and validation process
- [ ] OF to share and review design with NRM and demo on overall process
- [ ] OF to implement pilot API in alignment with specific business rules, logics
- [ ] NRM and OF validate process via testing
- [ ] OF to align future operational tasks (i.e. customer service for processing failures on data if these are not covered via business rules)
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished product with design 
- [ ] Implementation tested

**Comment by smahmudFS** [comment]
NRM provided information on:
1.	NRM Open Forest 
[NRM Open Forest WS Process_v1.pptx](https://github.com/USDAForestService/fs-open-forest-platform/files/5170060/NRM.Open.Forest.WS.Process_v1.pptx)
[ICDCopy of OF_permits_reporting_staging_tables_v2.xlsx](https://github.com/USDAForestService/fs-open-forest-platform/files/5170063/ICDCopy.of.OF_permits_reporting_staging_tables_v2.xlsx)

WS Process_v1 - is the power point presentation that includes our planned tasks, the flow of activities from the NRM side and the expected exceptional handling.
2.	ICDCopy of OF_permits_reporting_staging_tables_v2 – is the ICD that includes the proposed validation to be done by NRM

**Comment by MelissaBraxton** [comment]
@smahmudFS and @mwreiss: This looks good to me w/ one Q - I know that Grant mentioned in his email that y'all would build on their visualization, but I think it would be useful for the team (and more instructive for NRM as well) for you to  augment the flow that Aquib and Rebekah have created that bridges the front end user experience and the back end info flow, adding in the details re: exception handling. What do you think? 

@aQuib can you please link to the current info flow model here?

**Comment by aQuib** [comment]
[Here is the info flow model](https://whimsical.com/Em3ENhBhJS8Eui8EaxvooA)

**Comment by smahmudFS** [comment]
@MelissaBraxton : Sounds great.  Matt or I can present the design.  Would you be able to present or should we pull in Aquib to share the front end user experience - I believe they wanted a high level view (additionally) to understand how Firewood was going to be designed.  Thoughts?

**Comment by MelissaBraxton** [comment]
As much as I love walking through information flow diagrams (seriously! 🤓 )... It would probably be best if the high level walkthrough comes from someone other than me (to the end of 18F rolling off over the next few months). I like the idea of @aQuib walking folks through the first part of it and handing it off to you and Matt once it gets down to the exception handling details. Totally open to other thoughts though. For example, the NRM folks might be interested in seeing what's in staging?

**Comment by MelissaBraxton** [comment]
In looking at the info flow, it looks like there are a number of Qs that you may want to resolve before going over it with NRM. This draft also still shows Login.gov as the ID verification piece, which may also need to be updated, depending on how that decision lands--wanted to give y'all a heads up!

**Comment by smahmudFS** [comment]
[NRM Open Forest WS Process_v2.pptx](https://github.com/USDAForestService/fs-open-forest-platform/files/5190229/NRM.Open.Forest.WS.Process_v2.pptx)
Please validate slides 7 to 10.  @aQuib has agreed to do the overview on slide 7 (thank you!).  These are our slides.  I am assuming that we have done finished a mapping of NRM required fields vs. OF datasets (planned).  Essentially, this is an activity that need to be completed together with NRM.

**Comment by carlsonem** [comment]
After scope is better known, please update the LOE

**Comment by mgwalker** [comment]
Looks like I duplicated some of this in [timber-permitting/#185](https://github.com/USDAForestService/USFS-timber-permitting/issues/185). Do y'all think this should be a sub-issue of the new 185, or would it make more sense to convert that issue into strictly an FPFS data mapping issue?

**Comment by smahmudFS** [comment]
Attached is the draft mapping that is under review for NRM-TIM and OF:
[ICDCopy of OF_permits_reporting_staging_tables_v2.xlsx](https://github.com/USDAForestService/fs-open-forest-platform/files/5211402/ICDCopy.of.OF_permits_reporting_staging_tables_v2.xlsx)

**Comment by carlsonem** [comment]
@mwreiss please update and closed out

**Comment by mwreiss** [comment]
A test API was created to validate connectivity.  The data feed web services will be followed in a new issue created by Mike.
