### ISSUE TITLE
Coding Load Tag

### ISSUE THREAD

**Issue by carlsonem** [USDAForestService/fs-open-forest-platform#1447]
## Notes
* What are things we should consider when making this story *

## Acceptance Criteria
- [ ]

## Tasks
- [ ] Code Load Tag
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested
