### ISSUE TITLE
As an Open Forest Customer Support employee, I would like to see all the information pertaining to Customer Support procedures is in a public accessible place, so that I can perform my job properly.

### ISSUE THREAD

**Issue by Rebekah-Hernandez** [USDAForestService/fs-open-forest-platform#1461]
## Notes
Now that a majority of the information pertaining to Customer Support has been created and currently stored in Pinyon, we need to move the documentation onto the wiki.
- https://usfs.app.box.com/folder/122061423039
- https://usfs.app.box.com/folder/122674592862

## Acceptance Criteria
- [ ] Information has been reviewed and approved by Project Manager
- [ ] All ready information has been added to the wiki
- [ ] The Christmas trees information on the wiki has been archived
- [ ] All links have been updated from Christmas trees to firewood in the Support folder

## Tasks
- [ ] All current created materials have been reviewed and approved by Project Manager
- [ ] All information under the Support folder has been moved to the wiki and updated
- [ ] All information under the Support for Front Line Staff has been moved to the wiki and updated
- [ ] All information pertaining to Christmas trees has been removed from the sidebar
- [ ] All links on pages have been updated to firewood
- [ ] No more links reference the Christmas trees portion of the wiki
- [ ] PO approved

## Definition of Done
- [ ] Final draft on the wiki has been reviewed by Project Manager and approved

**Comment by Rebekah-Hernandez** [comment]
@Dmac26 Ready for peer validation review. Please check and then assign Beth and move to awaiting acceptance if all looks good. Please check all the Support wiki pages to make sure I didn't miss anything!

**Comment by Dmac26** [comment]
@Dmac26 - This looks great! I like the changes you made to the navigation page. g2g!

**Comment by Dmac26** [comment]
@MelissaBraxton - I reviewed the pages Rebekah posted to the wiki. They look good to me! Would you mind giving them the once over and final approval?
