### ISSUE TITLE
As a Special Use Privacy Officer, I need to see the OMB number on the web forms, so that I can track the permit and perform audits.

### ISSUE THREAD

**Issue by Rebekah-Hernandez** [USDAForestService/fs-open-forest-platform#1469]
## Notes
As noted in these hard copies of both non-commercial group use and temporary outfitters and guides, both have an OMB number in the top right corner. Open Forest web forms need to include OMB numbers for privacy and auditing purposes.

## Acceptance Criteria
- [ ] TOG web forms include an OMB number
- [ ] NCGU web forms include an OMB number

## Tasks
- [ ] 
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested
