### ISSUE TITLE
As a Special Uses Admin, I need to be able to accept Applications to SUDS when the applications meets our standards

### ISSUE THREAD

**Issue by Dmac26** [USDAForestService/fs-open-forest-platform#1509]
## Notes
An email was sent to us, making us aware of the fact that admins are currently unable to accept applications to SUDS. Instead they are given the following warning banner with an additional error showing in the console:

![Capture.PNG](https://images.zenhubusercontent.com/5d93a896a615ef000109902d/4205c3c9-3330-44a3-aa71-5ec940e55617)

## Tasks
- [ ] Identify what is inhibiting the pushing of applications to SUDS
- [ ] Apply appropriate fix
- [ ] Deploy to dev and test
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested
