### ISSUE TITLE
As a SU admin submitting an app to SUDS, I should be able to select among multiple similar contacts that SUDS gives me back, so that I reduce the number of duplicative contacts

### ISSUE THREAD

**Issue by hannahkane** [USDAForestService/fs-open-forest-platform#152]
## Acceptance Criteria
- [ ]

## Tasks
- [ ] Update server
- [ ] Create admin interface
- [ ] PO approved.

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by msadakFS** [comment]
Do you need a definition of what fields need to be validated against within SUDS so similar contacts are found? @lauraGgit

**Comment by lauraGgit** [comment]
@msadakFS so we already have the [middlelayer retrieving the contacts](https://github.com/18F/fs-middlelayer-api/blob/master/src/controllers/nrmconnection/post.js#L199) -its a question of what happens when there is more than one of the same:
- 1. if no contact is found, it should create a new contact
- 2. if only one contact is found it will use that contactId to create the application
- 3. If multiple contacts with the same contId are found the middlelayer will return an error with an array of the contacts

this ticket is about the platform having a user interface to select which contact is the desired contact, or forcing the creation of a new contact in SUDS.
- this would require the design of this interface
- server changes to supply the multiple contact info
- changes to the middlelayer to handle the SUA's selection.

What is unclear from lack of real use or direct access to SUDS so far is how frequently we are likely to see this error. It may very well be rare and then not worth while. We can also set a filter in our logs to see if this is a thing that happens often as the errorType is only called from this function.

**Comment by msadakFS** [comment]
@lauraGgit I was chatting with the local Special Uses folks here on the frequency of multiple contacts with same contact ID and she stated that there was an effort a couple years back to clean up the database to remove the array of contacts. That said, not everything was cleaned up, but the frequency should be pretty low.

**Comment by lauraGgit** [comment]
@msadakFS that's great to hear. Because the interface to display the contacts could be a fairly big lift.

**Comment by lauraGgit** [comment]
There may be a smaller story that we'd want to address, is that we return the contact control number, so that all future permits from that applicant are created with the same ID.

**Comment by msadakFS** [comment]
There is a manual workaround at this time

**Comment by lauraGgit** [comment]
We likely want to keep this in the inbox until we know for sure this is an issue.

**Comment by ASprinkle** [comment]
#679
