### ISSUE TITLE
As an applicant, I'd like to have uploaded files consistently validated so that I know they have uploaded correctly.

### ISSUE THREAD

**Issue by hursey013** [USDAForestService/fs-open-forest-platform#261]
## Notes
When files are uploaded they are checked by the frontend for file size, extension, and mimetype. If for some reason a file makes it past those validations but isn't actually valid the server will accept it no matter what since we do not have validation on the server currently. This creates a potential situation where a file will make it to the server and be passed to the middlelayer where it is rejected (since it has the same file validation criteria as the frontend). Ideally, the frontend, server, and middlelayer should have identical file validation.

## Acceptance Criteria
- [x] File won't get rejected due to inconsistent file validation.
- [x] File upload status is communicated back to the user.
- [x] If the file is **rejected** they know what their next steps are.
- [x] Add hint text to communicate next steps.

## Tasks
- [x] Verify back-end is working properly.
- [x] PO approved.

## Definition of Done
- [x] Code unit / e2e tested and comply with QWASP
- [x] Server actions captured by logs
- [x] No new security vulnerabilities
- [x] Internal team code review
- [x] Documentation / readme.md / CircleCI updated
- [x] Docker updated
- [x] Compare finished design with mockup
- [x] Usability tested

**Comment by lauraGgit** [comment]
This seems worthwhile prior to usability testing

**Comment by lauraGgit** [comment]
@adborden 
## Middlelayer locations:
The middlelayer is a bit odd and is in both this translation schema:
- https://github.com/18F/fs-open-forest-middlelayer-api/blob/master/src/controllers/translate.json
- https://github.com/18F/fs-open-forest-middlelayer-api/blob/master/src/controllers/fileValidation.js

## Server locations: 
https://github.com/18F/fs-open-forest-platform/blob/dev/server/src/controllers/temp-outfitter.es6#L461

## frontend locations
https://github.com/18F/fs-open-forest-platform/blob/dev/frontend/src/app/application-forms/fields/file-upload.component.ts

In particular, we know that the middlelayer does not let you upload an empty file, whereas the frontend does.

**Comment by adborden** [comment]
Thanks @lauraGgit, I see two paths forward, a quick fix or a more comprehensive fix. Here's my assessment, and then maybe you have ideas on which way we should go.

These are the validations happening in the middlelayer:

- file extension
- file mimetype
- file size minimum (zero)
- file size maximum (dynamic based on the type of document, 10MB is the smallest maximum)
- if required document is missing

From the front end:
- file size maximum (10MB)
- mime type

No validations from what I can tell on the server.

Since the validations on the front end are done with `ng2-file-upload`, we don't have much control over that. The quick fix would be to add some missing validations on the front end and duplicate them in the server. I'm not sure if the front end is currently sharing code with the server, but it would be nice if we didn't have to copy/paste.

The comprehensive fix would be to extract the middlelayer validation into an npm module that we can share in all three layers. It would be similar to how the middlelayer works today, defining a jsonschema-like object that defines the different validations to perform for each document type.

What do you think?

**Comment by adborden** [comment]
I took a closer look at [ng2-file-upload](https://github.com/valor-software/ng2-file-upload) and although it's not well documented, you can pass in custom `Filters` which would allow you to pass in validations.

**Comment by adborden** [comment]
Just an update on this one, I implemented the filters on [261-file-filters](https://github.com/18F/fs-open-forest-platform/tree/261-file-filters) but need some angular muscle to write tests for it.

**Comment by ASprinkle** [comment]
Is this for special use applicants only? or does this also apply in some way to FS administrators? Would this result in an information box for the user stating that their files have "successfully uploaded" or something similar?

**Comment by jdamis4XD** [comment]
@lisaredux 
From a design POV:
- Need to confirm if the UI indicates file size limit
-  If there is a file size validation being done and a subsequent error message provided to user

**Comment by lisamcmichael** [comment]
File size validation is occurring. There maybe some back-end server validation that needs to occur.

**Comment by ASprinkle** [comment]
"done-ish" doing some final checks on email story...

**Comment by ASprinkle** [comment]
@mtlaney I don't know how to check this since it seems like it's mostly middle layer stuff.  Can you update the tasks boxes above?

**Comment by ASprinkle** [comment]
From Mike: "unfortunately no real way for you to test that one, just make sure we can still upload valid files to temp outfitters (which I tested)"
