### ISSUE TITLE
As a Guide, I need to obtain a non-commercial, temporary outfitter guide permit within the production env.

### ISSUE THREAD

**Issue by msadakFS** [USDAForestService/fs-open-forest-platform#280]
## Acceptance Criteria
- [ ] See checklist https://docs.google.com/spreadsheets/d/1GzmTMYHSqUKvknpEe1Pe7lN6MsjL7ZBSTKOM6qCXUqE/edit#gid=0 

## Tasks
- [ ] needs refinement
- [ ] PO approved.

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] Server actions captured by logs
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by msadakFS** [comment]
@hannahkane I am assuming that we cannot complete the checklist until we get the ATO. Should I move this issue over to blocked for now?

**Comment by hannahkane** [comment]
@msadakFS - I think I've forgotten what this issue is about. Does it refer to completing each of the items in the "Launch Tasks" sheet of the spreadsheet? If so, I would agree it's blocked. Either way, I think we could clarify in the first comment what this issue means.

**Comment by msadakFS** [comment]
Dependent on ATO, need to validate items in the checklist

**Comment by lauraGgit** [comment]
Tested this in comparison to staging - and staging has the API down, so blocked to check that NRM SUDS DEV is back up & that API has not been removed.

**Comment by lauraGgit** [comment]
Ok, further testing with staging and an accepted application. Staging/Prod are returning the same errors for a random control number submitted. This suggests that it is enabled in production but cannot fully verify until an actual application is submitted in SUDS. Moving to PO acceptance.

**Comment by lauraGgit** [comment]
Oops, last few comments should have been on #149

**Comment by lauraGgit** [comment]
No longer blocked! 🎉

**Comment by lisamcmichael** [comment]
@ASprinkle When you have time, look at this story. I wonder if it needs updating, or should be "mothballed"? Thx.

**Comment by ASprinkle** [comment]
The link in the story is to this spreadheet.
Based on the information in this spreadsheet and our current program increment plan, I agree this story can be closed.

[ePermit Production Checklist.xlsx](https://github.com/USDAForestService/fs-open-forest-platform/files/3820908/ePermit.Production.Checklist.xlsx)
