### ISSUE TITLE
As a user, I should be directed to my intended form/application process after I'm done creating an account on login.gov

### ISSUE THREAD

**Issue by annepetersen** [USDAForestService/fs-open-forest-platform#371]
## Notes
Usability test participant entered the login.gov account creation process after clicking the “Noncommercial permit / Apply now” button from the Noncommercial Permit Information page. 

Participant assumed they would exit the account creation process (“Continue” from login.gov) and go straight into the application process rather than back to the Information page and was surprised when the Information page resulted.

**NEW (10.24.19) 
Expectation that if a person clicks Apply button, then enters User Name and Password, that person **would be directed to the Application** (not the Info page).**

## Acceptance Criteria
- [ ] A button stating "Noncommercial permit / Apply now" should end on that form's page once the login.gov process is complete.
- [ ] A button stating "Temp outfitter's permit / Apply now" should end on that form's page once the login.gov process is complete. 

## Tasks
- [ ] Update the server to handle application type redirects when after successful login.gov log in.
- [x] Add video/screenshots to show the correct user flow.
- [ ] PO approved.

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] Server actions captured by logs
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by lauraGgit** [comment]
add `localStorage.setItem('requestingUrl');` handler on logged-in component

**Comment by lauraGgit** [comment]
the initial take did not seem to work.

**Comment by ASprinkle** [comment]
See also #608

**Comment by lisamcmichael** [comment]
Expectation that if a person clicks Apply button, then enters User Name and Password, that person **would be directed to the Application** (not the Info page).

**Comment by lisaredux** [comment]
Ideal state flow chart, updated to demonstrate changes already made in summer of 2019: https://docs.google.com/presentation/d/1MzvE8QKD6JxStiYmFm8gCA1--8zR_vtuO5XrbF0fLRg/edit#slide=id.g50bf42e953_0_197

**Comment by lisamcmichael** [comment]
> Ideal state flow chart, updated to demonstrate changes already made in summer of 2019: https://docs.google.com/presentation/d/1MzvE8QKD6JxStiYmFm8gCA1--8zR_vtuO5XrbF0fLRg/edit#slide=id.g50bf42e953_0_197

Hey Lisa - thx for putting these flows together. I understand flows 1 and 4, but I'll need your help with 2 and 3. If it's not too much trouble, add notations? Thx again!

**Comment by lisaredux** [comment]
@lisamcmichael Not a problem. I realized that slides 2 and 3 were outdated, so slide 4 is the only one that we need to reference currently as to the future state: https://docs.google.com/presentation/d/1MzvE8QKD6JxStiYmFm8gCA1--8zR_vtuO5XrbF0fLRg/edit#slide=id.g50bf42e953_0_197

@ASprinkle + @briandavidson @mtlaney -  here is the video of how special use currently functions with login.gov:
[OpenForest-Story371-login-video.zip](https://github.com/USDAForestService/fs-open-forest-platform/files/3772823/OpenForest-Story371-login-video.zip)

**Comment by lisamcmichael** [comment]
Hey @lisaredux, as I'm cleaning up stories we discussed today, I went ahead and put your name on this one, given your work on it.

**Comment by ASprinkle** [comment]
@briandavidson When attempting to test this out I had some odd interactions that were difficult to capture on screen shot... I think I will check it in again tomorrow, and coordinate with you if needed.

**Comment by ASprinkle** [comment]
Great work on this Brian! the workflow operated really well!! 
(by the way, the "Apply Now" button design looks like it changes based on whether or not the individual has already logged in through login.gov).

![image](https://user-images.githubusercontent.com/33435621/68515109-b5ceb800-0234-11ea-9d90-22e6bd2a9cea.png)
