### ISSUE TITLE
As an special use applicant, I want to be automatically notified when my permit application is approved, so that I don’t need to contact the Special Use Administrator to know the status of my application.

### ISSUE THREAD

**Issue by lauraGgit** [USDAForestService/fs-open-forest-platform#399]
## Notes
[Pulled from the scale up RFP](https://github.com/18F/its70-fs-epermit-scale-up/blob/master/solicitation-documents/Draft-RFP.md#epic-make-application-activity-transparent-to-applicants-and-special-use-administrators)

## Acceptance Criteria
- [ ] As a special use applicant when my application is approved in SUDS, I should receive an email notifying me of its approval.

## Tasks
- [ ] PO approved.

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] Server actions captured by logs
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by lisaredux** [comment]
@ASprinkle Attaching the email as the initial application email PDF so we can see what the template looks like [Your Noncommercial Open Forest permit application has been submitted for review.pdf](https://github.com/18F/fs-open-forest-platform/files/3070472/Your.Noncommercial.Open.Forest.permit.application.has.been.submitted.for.review.pdf)

**Comment by lisamcmichael** [comment]
@ASprinkle will add notes on this story and then close it.

**Comment by ASprinkle** [comment]
Approval of the application from SUDS is still a human process. The applicant receives automatic notification when their application is "accepted to SUDS", "rejected" or "on hold" through Open Forest. Based on this, closing this story.
