### ISSUE TITLE
As a special use applicant, I would like to submit my application with a long organizational name, so that I don't have to make something up.

### ISSUE THREAD

**Issue by lauraGgit** [USDAForestService/fs-open-forest-platform#411]
## Notes
Acceptance to SUDS for applications with a long name are recieving a middlelayer error that ORG code is too long. Likely need to slice orgCode here: https://github.com/18F/fs-open-forest-middlelayer-api/blob/ad826ea7c418fb4265196f30038cc7ce719247e2/src/controllers/sudsconnection/post.js#L105

to 30 characters.

## Acceptance Criteria
- [x] UPDATE 1/27:  Organizational Name field is 60 Character Limit (including spaces)
- [x] applicant knows how many characters they are restricted to when entering organizational name.
- [x] applicant cannot submit an application with an org name greater than 30 characters.

## Tasks
- [x] UPDATE 1/27 Edit code to 60 characters for organizational name field
- [x] UPDATE 1/27 Edit validation message to 60 characters for organizational name field.
- [x] Build code to restrict the Character Limit for Organizational Name to 30 characters or Less.
- [x] Add validation for applicant if more than 30 characters are entered into the box. Validation message should read: "The Organizational Name must be less than 30 characters." 
- [x] Validation shows red border indicating error.
- [x] Validation shows red exclamation mark in the left nav. menu if the error still exists.
- [x] PO approved.

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [x] No new security vulnerabilities
- [ ] Internal team code review
- [x] Usability tested by Dev.

**Comment by briandavidson** [comment]
@ASprinkle do we know if this is for sure still an issue? And if so do, we have steps to reproduce it? After running some tests I was unable to make it occur.

**Comment by ASprinkle** [comment]
this is functioning really well. Great work @briandavidson 
![image](https://user-images.githubusercontent.com/33435621/72463601-766a9d80-3788-11ea-9bd3-a1271e519ecd.png)
![image](https://user-images.githubusercontent.com/33435621/72463603-79fe2480-3788-11ea-85ad-20f3ea5c33c4.png)
![image](https://user-images.githubusercontent.com/33435621/72463621-84b8b980-3788-11ea-8bad-54239e7d643e.png)
![image](https://user-images.githubusercontent.com/33435621/72463636-8a160400-3788-11ea-8c4e-acfd03f8d798.png)
![image](https://user-images.githubusercontent.com/33435621/72463662-97cb8980-3788-11ea-9d82-a739aa1a9f70.png)

**Comment by ASprinkle** [comment]
@briandavidson  I moved this to in progress based on our backlog refinement discussion today regarding acceptable character limits in SUDS. I also updated the A/C and the Tasks.

**Comment by ASprinkle** [comment]
Great work on this Brian! 
![image](https://user-images.githubusercontent.com/33435621/73578645-01a88c00-4435-11ea-895e-3f8407644b5f.png)
![image](https://user-images.githubusercontent.com/33435621/73578650-04a37c80-4435-11ea-83dc-c34f6c5276fa.png)
