### ISSUE TITLE
As a special use applicant, I would like to make sure I consent to the use of my PII

### ISSUE THREAD

**Issue by lauraGgit** [USDAForestService/fs-open-forest-platform#467]
## Notes
We added in per the Plan of Action Milestone (POAM), consent for xmas tree purchasing, but not on the special use side.

## Acceptance Criteria
- [x] The applicant knows they are entering PII, understands why, and agrees to entering it.
- [ ] The applicant is required to check the box before submitting their application.

## Tasks
- [x] Get the text for consent: Research for PII language on the temporary outfitter guide forms
- [x] Design check box to temp outfitter page
- [x] Design check box to non-commercial group use page
- [x] Move PII consent info and checkbox to above application form
     - [x] New design to show a revision to the PII content/text
          - to be clear about "why" this info is being collected and stored (aka, the purpose) see the privacy impact statement for guidance on the rewrite
         - to not specify name and email, rather "information entered"
- [x] Add the check box to temp outfitter page
- [x] Add check box to non-commercial group use page
- [x] PO approved.

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] Server actions captured by logs
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
@ASprinkle find out where this came from on the Christmas tree side for background.

**Comment by lauraGgit** [comment]
@ASprinkle this was a story as a result of our security and compliance process. our ATO

**Comment by ASprinkle** [comment]
The goal of this story is similar to that of closed story #339 for Christmas trees.

**Comment by lisaredux** [comment]
Here with updated placement based on Story 489 updates: <img width="384" alt="screen shot 2019-02-22 at 11 30 00 am" src="https://user-images.githubusercontent.com/26801590/53256449-e87c5480-3695-11e9-9639-8da644e7b4b4.png">

**Comment by lisaredux** [comment]
@davemcorwin @ASprinkle trying to figure out where this is. It's handed off from design. PO might need to approve before dev picks up.

**Comment by ASprinkle** [comment]
The design looks good. The story is ok for the backlog. I will need to work on prioritizing the backlog

**Comment by ASprinkle** [comment]
Update 10/11/2019. A small change to the text in the design will be needed before it is ready for Dev.

**Comment by lisaredux** [comment]
@ASprinkle here is the proposed update for Temporary outfitters and Non-commercial special use forms PII content and placement.... please confirm:

<img width="844" alt="Screenshot 2019-10-22 17 16 18" src="https://user-images.githubusercontent.com/26801590/67334224-ce7a6680-f4ef-11e9-9e0a-043f2e015743.png">

<img width="686" alt="Screenshot 2019-10-22 17 23 20" src="https://user-images.githubusercontent.com/26801590/67334738-a7706480-f4f0-11e9-98ec-290c7dee0ab0.png">

**Comment by ASprinkle** [comment]
@lisaredux can you include the action mock up for not checking the box? There is a red text requirement offered in the Christmas tree PII if the box is not checked before moving on.

**Comment by lisaredux** [comment]
@ASprinkle here it is with the error message. 
![Screenshot 2019-10-23 18 41 35](https://user-images.githubusercontent.com/26801590/67439643-cd673900-f5c4-11e9-8692-f7b9b710e8ec.png)

To note: I wasn't sure if the checkbox was supposed to have a red border because I couldn't recreate it with CSS classes. 

Moving this to ready for DEV to pick up @briandavidson @mtlaney — let me know if you have any questions.

**Comment by ASprinkle** [comment]
Hi @lisaredux I don't think I know what CSS clases are. As long as we have that red reminder text that pops up if they try to submit their application w/o checking the box, I think we are good to go! Thank you.

**Comment by ASprinkle** [comment]
Looks great!
