### ISSUE TITLE
As a special uses applicant, I want to know upfront what documents or information I need to provide so that I can complete my application efficiently.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#531]
## Notes
- Applicants want to know what they need before they begin the application process so that they know they have it and/or readily have access to it during the application process.
- Applicants want to know if they need to upload something, and/or enter data from it.

## Acceptance Criteria
- [x] Applicants know what they need before they begin the application process.
- [x] Applicants know if they need to upload something, and/or enter data from it, to include format.
- [x] Usability tested

## Tasks
- [x] Compile a list of the documents that a non-commercial and temp outfitter applicant will need.
- [x] Explain document requirements.
- [x] Document format request is consistent with existing formatting (for example asking for an excel doc if it's normally a PDF written description).
- [x] Design mock ups (possible modal?)
- [x] Wire frame drafted, reviewed and PO approved
- [x] build on staging
- [x] Review on staging
- [x] PO Approval

## Definition of Done
- [ ] Pull requests meet technical defintion of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by lisaredux** [comment]
Everything is required unless marked optional

**Non-commercial**

* Applicant information 
* Event details

**Temporary Outfitters**

* Applicant information 
* Event details

* certificate of good standing or state equivalent / or /
partnership or association agreement / or / Not for Profit: IRS Form 990 
* operating plan - template (docx)
.jpg, .png, or .pdf format, and less than 10MB. 
* Liability insurance
* Guide identification
* Map of proposed activity  (optional)
* Acknowledgement of risk (optional)

**Comment by lisaredux** [comment]
This information would be on a breakout page for Temporary Outfitters, etc <img width="331" alt="Screenshot 2019-03-13 10 17 47" src="https://user-images.githubusercontent.com/26801590/54288769-65586b00-457e-11e9-9b10-9cfd2dbdb29f.png">

**Comment by ASprinkle** [comment]
@lisaredux this is a great start.  For the descriptions under each permit type, I think we could use some more refining.
Temporary Outfitter Guide: "Permits are non-renewable and would be valid for short-term use; no more than 200 service days within a 180-day period."
Non-Commercial Permits: "Permits are required for groups of 75 people or more. Must not charge fees; the purpose of the group activity is not related to selling goods or services."

**Comment by lisaredux** [comment]
> @lisaredux this is a great start. For the descriptions under each permit type, I think we could use some more refining, here are some suggestions:
> Temporary Outfitter Guide: "Permits are non-renewable and would be valid for short-term use; no more than 200 service days within a 180-day period."
> Non-Commercial Permits: "Permits are required for groups of 75 people or more. Must not charge fees; the purpose of the group activity is not related to selling goods or services."

Thank you @ASprinkle. I'll make those changes. Also, the updated page structure is shown here: https://docs.google.com/presentation/d/1MzvE8QKD6JxStiYmFm8gCA1--8zR_vtuO5XrbF0fLRg/edit?usp=sharing

**Comment by lisaredux** [comment]
<img width="384" alt="Screenshot 2019-03-27 10 42 57" src="https://user-images.githubusercontent.com/26801590/55085814-ad4ab800-507d-11e9-8f16-9f36320d4fcf.png">
Copy updates from @ASprinkle included in this iteration: <img width="386" alt="Screenshot 2019-03-27 10 42 36" src="https://user-images.githubusercontent.com/26801590/55085815-ad4ab800-507d-11e9-9f95-40dafbf64c86.png">

**Comment by ASprinkle** [comment]
Lisa, that looks great for me.  For "event details" do we need more description there, maybe it could say "Details about the event".  also for the bullets under the temp outfitter guide section, some items could be capitalized.  This is great!

**Comment by davemcorwin** [comment]
@lisaredux where does this new screen belong in the flow through the application? We already do have a "learn-more" page that could be added to...

**Comment by lisaredux** [comment]
> @lisaredux where does this new screen belong in the flow through the application? We already do have a "learn-more" page that could be added to...

Good question. It's an alternate page that is demonstrated here as an ideal flow. https://docs.google.com/presentation/d/1s_29ejmsICLOCPkfY0BSZktTY8nwYxnjxzrkql0eH4w/edit?usp=sharing

Currently, this breakout page doesn't exist so I am not aware of the LOE to create new ones. 

To pick up text, go here: https://docs.google.com/document/d/1q1aaHSSdyj6jUV9ZPh8jY-Q2JPWpn-9sr74jEnwsQ2A/edit

**Comment by davemcorwin** [comment]
@lisaredux:
1. Are you referring to the "MBS Non-comm details page" on the third slide of the presentation? 
2. Is the idea that from the MBS home page, the user clicks on the primary CTA and before they see the form/sent to Login.gov they see the new page?
3. My impression is that some of the information is related or even duplicative of what is currently on the "Learn more" page currently accessible on the MBS home page via the secondary link "Click here to learn more about this permit." Is the idea here to ensure that we communicate the super important pieces of info, and if so, should we include the new information on the "Learn more" page as well?

**Comment by lisaredux** [comment]
@davemcorwin @ASprinkle This is in the same situation as #533 - too many unknowns and underlying variables to tackle this as team at the moment

**Comment by lisaredux** [comment]
@davemcorwin 
> 
> 1. Are you referring to the "MBS Non-comm details page" on the third slide of the presentation?
> 2. Is the idea that from the MBS home page, the user clicks on the primary CTA and before they see the form/sent to Login.gov they see the new page?
> 3. My impression is that some of the information is related or even duplicative of what is currently on the "Learn more" page currently accessible on the MBS home page via the secondary link "Click here to learn more about this permit." Is the idea here to ensure that we communicate the super important pieces of info, and if so, should we include the new information on the "Learn more" page as well?

To answer your questions:
1) Yes, I'm referring to that, for each of reference, this one... pre-authentication (in yellow because it doesn't exist yet)
<img width="385" alt="Screenshot 2019-04-11 16 51 04" src="https://user-images.githubusercontent.com/26801590/55992202-015abc80-5c7a-11e9-9a11-a9f3c63fecda.png">
2) Yes, exactly
3) Agreed. There was a lack of discussion of how we are going to deal with the overall update of the page flow, so we recommend putting this on hold until we sort out the global details — namely a issue we might have to create to tackle the foundation before the paint

**Comment by lisaredux** [comment]
Also, to demonstrate the pains with this process...
<img width="1015" alt="Screenshot 2019-04-12 16 56 51" src="https://user-images.githubusercontent.com/26801590/56065905-2f0c3800-5d44-11e9-89cf-846a2093d693.png">

**Comment by davemcorwin** [comment]
@lisaredux @ASprinkle This is currently in "Ready" should this be moved to "Refining"?

**Comment by lisaredux** [comment]
> @lisaredux @ASprinkle This is currently in "Ready" should this be moved to "Refining"?

@davemcorwin Good point. That seems logical... @ASprinkle @MelissaBraxton ?

**Comment by ASprinkle** [comment]
@lisaredux @davemcorwin I added a dependency to #608

**Comment by lisaredux** [comment]
@ASprinkle We discussed #608 with Dave and confirmed that we can use multiple URLs with login.gov. Should we move this to refining?

**Comment by ASprinkle** [comment]
@lisaredux  yes!

**Comment by lisaredux** [comment]
@ASprinkle @carlsonem @DawnDesigner - this is now in refining, and design will discuss design possibilities next week in person

**Comment by jdamis4XD** [comment]
@ASprinkle @carlsonem @davemcorwin @DawnDesigner @lisaredux We didn't get to discuss this issue last week, so Design plans to address this week.

**Comment by carlsonem** [comment]
Need to make sure that mobile is considered in the design. Might already be done, but need to confirm.

**Comment by lisaredux** [comment]
@ASprinkle we (@jdamis4XD @DawnDesigner and I) are collectively working on this, but we will need to schedule a meeting with you to vet the new content organization. I am currently working on wireframing the content for this and #530 and #627.

**Comment by lisaredux** [comment]
Wireframe of the updated content flow under review by @ASprinkle https://sketch.cloud/s/MGMV9

**Comment by ASprinkle** [comment]
Thanks @lisa - wire frame approved. 
Ok to move to design mock up.  
We will keep in mind that we will continue to have changes to some extent, but this wire frame provides a good baseline to work from.

I cannot leave comments in the attachment - 
the left menu nav should populate the sub headings as the user scrolls through.  For this story, it was not clear to me that "Applicant Requirements" was a subheading of "Apply for a temporary use permit".  Also, "Applicant Requirements" sounds more like requirements for an individual person vs. required documents needed to have a valid application.  I think we can continue to work on that through design.
-Good placement of the Apply Now buttons!

**Comment by lisaredux** [comment]
Thanks @ASprinkle. That makes sense — especially regarding the future text updates. I'm removing myself and adding @DawnDesigner now

**Comment by DawnDesigner** [comment]
A/B testing with two prototypes in progress for these issues and will be removed from blocked when testing is completed and these issues are refined and put into ready.
#530 , #531, #565 and #627

**Comment by DawnDesigner** [comment]
This testing study is now complete. Findings and recommendations can be found on this repositories Wiki (Design and Research) here:

https://github.com/18F/fs-open-forest-platform/wiki/Usability-Testing:-Special-Uses-(Content-Flow-Study)-June-2019

**Comment by ASprinkle** [comment]
@lisaredux @DawnDesigner can we mock the pages for this story so that we can prepare it for dev?

**Comment by DawnDesigner** [comment]
@ASprinkle @lisaredux Here is the mock up for #565 that shows the text and where it sits on the page. the text is not yet finalized, but is acting as a placeholder.

![SU - Landing Page 3](https://user-images.githubusercontent.com/47989077/60106695-a3475c80-9733-11e9-97c1-ea07d78247dd.png)

**Comment by DawnDesigner** [comment]
Here is the final location of this information on the Non-Commercial and Outfitters details page.

![Req-Docs-TextLocation Noncommercial](https://user-images.githubusercontent.com/47989077/60185773-7f018380-97f8-11e9-81bc-6ca63e968834.PNG)
![Req-Docs-TextLocationOutfitter](https://user-images.githubusercontent.com/47989077/60185775-7f018380-97f8-11e9-94ce-1c1332ea277a.PNG)

**Comment by ASprinkle** [comment]
@DawnDesigner @lisaredux Is there anything you need from me on this story at this point?

**Comment by lisaredux** [comment]
@ASprinkle Nothing needed at this point. thanks!

**Comment by ASprinkle** [comment]
I see this is in Awaiting Acceptance. I checked the special uses staging site, and it does not appear that the learn more pages have been updated.  

Should I minimize the "Review Staging" Acceptance Criteria and will note that the design/research work is completed, but the development work on staging still needs to be done?

**Comment by lisaredux** [comment]
Thanks @ASprinkle — that makes sense to me. Wasn't sure where to put it next in the cycle for development to pick up.

**Comment by ASprinkle** [comment]
@lisaredux Let's talk about this at stand up tomorrow.  Thanks! :)

**Comment by carlsonem** [comment]
@mtlaney ready for development

**Comment by lisaredux** [comment]
@ASprinkle here's the update, also in #627 

![SpecialUse-LandingPage07032019](https://user-images.githubusercontent.com/26801590/60621776-9a4a3100-9dac-11e9-8013-41fe74ccd658.png)

This is ready for dev @mtlaney. Including a PDF to grab text content from. Let us know if you have any questions. 
[SpecialUse-LandingPage07032019.pdf](https://github.com/18F/fs-open-forest-platform/files/3356677/SpecialUse-LandingPage07032019.pdf)

**Comment by ASprinkle** [comment]
(note: let's pay attention to usability testing regarding the Smokey/Woodsy photo in the non-com group use block - this may create confusion for some folks, but let's wait and see.)

**Comment by lisamcmichael** [comment]
Met w/ Amber: Take a screen of what’s in staging, add comments and set this story to “done”.

**Comment by ASprinkle** [comment]
The special uses landing page has been updated to meet A/C 
![image](https://user-images.githubusercontent.com/33435621/66662838-6af25e00-ebfe-11e9-9a2a-257eca002a0a.png)
