### ISSUE TITLE
As a special use applicant, I want to know if the information I enter can be saved so that I can complete my application later or make a future application process easier.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#532]
## Notes

 - Knowing whether or not an application can be saved would help inform the time estimate for completing an application, and would help the user manage their time.
- Knowing whether or not their application information can be saved (to return to later, or for future applications) could improve the value of the data they input.
- Knowing whether or not a users application information can be saved could improve the user experience, and help them manage their time.

## Acceptance Criteria
- [x] We know whether or not Open Forest can save data/user information.
- [] If Open Forest can save applicant data then develop user stories to support the issue.
- [x] The applicant is informed that they cannot save their application mid-way through completing it.

## Tasks
- [x] Confirm whether or not Open Forest can save applicant data for return use. (Privacy Impact Analysis, System of Record Notice?)
- [x] We have confirmed that we cannot easily save data at this time in prep for MVP launch. See comments below. We could research and build the ability to save data, but not for MVP at this time.
- [x] Meet with Development team to discuss feasibility
- [x] Mock the design that includes the expectation language:
- [x] in the temporary outfitter and guide application page, at the top of the page before the step 1 Applicant Information header, add hint text "**"It may take a while to complete the application. To save time, have all of your documents ready.  You won’t be able to save the application to complete it later. The application will be saved once it’s submitted."**
- [x] in the non-commercial group use application page, at the top of the page before the Applicant Information header, add hint text "**"It may take a while to complete the application. To save time, have all of your documents ready.  You won’t be able to save the application to complete it later. The application will be saved once it’s submitted."**
- [x] Mock the design to move the required fields text to a more appropriate location 
- [x] Mock the design to move the PII text and box to a more appropriate location (before the submit button and after the initials box)
- [x] Hand off with Dev
- [ ] Build it using mock ups here: https://github.com/USDAForestService/fs-open-forest-platform/issues/532#issuecomment-554041628
- [x] Dev to add applicant cannot save application text to the NCGU application page
- [x] Dev to add application cannot save application text to the TOG application page
- [x] Dev to move the PII check box to the bottom of the application page on NCGU
- [x] Dev to move the PII checkbox to the bottom of the application page on TOG
- [x] Dev to move the "required fields*" text to the location shown on the mock up for NCGU application page.
- [x] Dev to move the "required fields*" text to the location shown on the mock up for TOG application page.
- [x] PO approved.

## Definition of Done
- [ ] Pull requests meet technical defintion of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by lisaredux** [comment]
@ASprinkle @davemcorwin Did we ever figure out if we could potentially save information for 1) a session and for 2) future profile use with a privacy disclose?

**Comment by ASprinkle** [comment]
@lisaredux To my knowledge, we have not worked out the Privacy question for design to pick this up.

**Comment by lisamcmichael** [comment]
For 532 – not MVP; need to look into storing PII. @ASprinkle to check with Aaron. 
-	Can we store info?
-	Possible workflow implications?

**Comment by aaronburk** [comment]
I recall this question.  My understanding is the current design does not allow the user to save the session part way through. I am also recalling the most of the information gets send to the system of record which is SUDS and Open FOrest is not meant to store much of the information.  Thus as mentioned above there will be need discussion related to what it would take to build in such functionality on both back and front end but also if that impacts the current security posture.  We will need to engage @JonathanLerner54 Jon lerner to look at what PII information is being proposed for storage vs what was approved in the security impact analysis to determine what is needed (if anything from that perspective for this story.

**Comment by JonathanLerner54** [comment]
Do we have a data dictionary established for this?  For ePermits we avoided the PII by pushing the Credit Card information off on the pay.gov.  So let's start with the data elements and figure out where it will be held while processing and at rest and go from there.  If someone can point me to any documentation we have on this, I can get started with initial review.   THANKS!

**Comment by aaronburk** [comment]
I am not sure if we have a data dictionary per se ( the developers may know) one could easily be created i suspect.  THe current system for MBS was reviewed closely and all types of info being collected were approved in the ATO package which included PII, SIA etc.  The main difference is it appears the user story would create a "holding area" of sorts or a profile for a user that stores their information for retrieval before final submission and ease of access for future submission. While SUDS would still be the system of record it will be good to have a data dictionary of some sort by workflow for ease of reference for security staff and others.  thanks for being so responsive everyone.  This is what DevSecOps looks like! :) @carlsonem @ASprinkle @JonathanLerner54  @smahmudFS @mwreiss

**Comment by ASprinkle** [comment]
For MVP launch 2019/early 2020, we can mock a design to implement informing the applicant early on, that their application cannot be saved to complete later and to ensure they have all documents necessary to complete the application etc... @lisamcmichael @lisaredux  Looks like we've got some research to do in the meantime around what it would look like to accomplish the "save and return later" feature.

**Comment by JonathanLerner54** [comment]
Two approaches:  

1. holding area would store only non-PII data and any PII field can be prompted to re-enter.  The system can use a dialog box stating this prior saving, so the user is reminded that their PII will not be saved as part of this process
2.  Data will be encrypted using FIPS compliant modules to protect the PII in transit and at rest(storage).  This will mean that we will need a key storage capability and will require a means to recover the keys over time.

**Comment by davemcorwin** [comment]
If the user is logged in at the time you may be able to leverage a solution that involves encrypting the PII with the user's password and keeping it in the session so it's possible for them to "save and continue later" with certain constraints. If you're interested in learning more about this approach, I believe Login.gov does something similar during the Identify Proofing process and I can connect y'all with Jonathan Hooper who is a mastermind at this sort of thing.

**Comment by lisamcmichael** [comment]
@ASprinkle and @lisaredux  a meeting with this group, and Jonathan, would help us better define any MVP option and/or option for later release. Thoughts?

**Comment by lisamcmichael** [comment]
> @lisamcmichael @ASprinkle Agreed. With a meeting, at least we could scope out the option for a future release if saving options don't make it into the MVP.
> 
> In the meantime, for this story, we can design an approach where we put text on the Learn More page and near the PII checkbox (#467). I'll take suggestions for verbiage and will implement into a design as soon as this story is ready to take on

Based on the 10/24 "icebox" meeting, we'll wait until Amber is ready to schedule our team's meeting to go over the ideas Joe and Dave have for this story.

**Comment by lisaredux** [comment]
@ASprinkle Verbiage here in bold in the design: ![Screenshot 2019-10-31 13 18 13](https://user-images.githubusercontent.com/26801590/67973414-d9678200-fbe6-11e9-8c67-2936f94377ed.png)

**Comment by ASprinkle** [comment]
@lisaredux  can we use the following text: "Please allow up to an hour to complete this form. This session cannot be saved." so that it coincides with the "Application time: Appx. 1 hour" information on the landing page? see tasks list above..

**Comment by JonathanLerner54** [comment]
Are we saying that the user should expect the completion of the form takes an hour to fill out?  or are we saying, that the system will time out if the form is not completed within a one hour time period and they user will have to start over?

**Comment by ASprinkle** [comment]
@JonathanLerner54 we are expecting the time to complete the application to take up to an hour.  We do not expect that the form will time-out at any point in the process.  We want people to be able to plan their day and understand that if they start the application, and then stop/walk away, that the information they enter won't  be saved.

**Comment by ASprinkle** [comment]
waiting on results of #1003  before we decide on the language.

**Comment by ASprinkle** [comment]
The Results Are In: 

**"It may take a while to complete the application. To save time, have all of your documents ready.  You won’t be able to save the application to complete it later. The application will be saved once it’s submitted."**

**Comment by lisamcmichael** [comment]
Hi @lisaredux, 4 days ago Amber and I reviewed survey results of the best way to explain that applications cannot be saved. This is the updated content. We have a task to mock it up before going to development. Any questions, just let me know.

**It may take a while to complete the application. To save time, have all of your documents ready. You won’t be able to save the application to complete it later. The application will be saved once it’s submitted.**

**Comment by lisaredux** [comment]
@lisamcmichael thanks for the update. That is definitely a nice, clear and concise version. Well-done!

**Comment by lisaredux** [comment]
Working on the mockup this afternoon

**Comment by lisaredux** [comment]
@ASprinkle @lisamcmichael here's the latest... feel free to give feedback or, if none, to move it to ready for DEV
![Screenshot 2019-11-13 14 20 06](https://user-images.githubusercontent.com/26801590/68796573-1d17ae00-0621-11ea-9966-09124cfa2e6a.png)

**Comment by ASprinkle** [comment]
@lisaredux that looks like our plan.  I would suggest making it a gray hint text. I realize it's bold in the tasks list above, but I don't think we want it bold here.  Also, is there anything we can do to the design/flow of the series of information here to make it feel friendlier?  Looking at the header, followed by required fields, followed by PII, followed by our new text feels a bit wonky. Any thoughts on how we could present this series of information so that it's friendlier?

**Comment by lisaredux** [comment]
<img width="1176" alt="Screenshot 2019-11-13 15 56 14" src="https://user-images.githubusercontent.com/26801590/68803644-25c2b100-062e-11ea-8373-161b9fb2ec35.png">

**Comment by lisaredux** [comment]
@ASprinkle @lisamcmichael @Rebekah-Hernandez Updated design for your review here:
<img width="1190" alt="Screenshot 2019-11-13 16 29 16" src="https://user-images.githubusercontent.com/26801590/68806011-f9f5fa00-0632-11ea-8a37-42e854813188.png">

<img width="1186" alt="Screenshot 2019-11-13 16 27 40" src="https://user-images.githubusercontent.com/26801590/68806064-198d2280-0633-11ea-956e-c61e0024827d.png">


@briandavidson I grabbed the the hint text class from Xmas trees, and it is "usa-form-hint"

**Comment by lisamcmichael** [comment]
For non-commercial, it's a streamlined application. What do @lisaredux @ASprinkle @Rebekah-Hernandez  think about having this (_instead of the full "disclaimer_)?  You won’t be able to save the application to complete it later. The application will be saved once it’s submitted.

**Comment by ASprinkle** [comment]
Ahh, good suggestion since it only takes 20 minutes or so. However if someone decided to type in a bunch of detail it could take a while....

**Comment by Rebekah-Hernandez** [comment]
I think it would be fine to take the bit off about time. Even if they input a lot of details, I don't think we would need to include that it would take "a while". Going into the application, it mentions that it should take 20-30 minutes.

**Comment by ASprinkle** [comment]
Lets mock it up for the non-commercial group use side. Sounds good? @lisaredux

**Comment by ASprinkle** [comment]
BTW the Temp OG mocks look really good.

**Comment by lisaredux** [comment]
@ASprinkle @lisamcmichael @Rebekah-Hernandez Updated non-commercial:
<img width="836" alt="Screenshot 2019-11-14 11 06 19" src="https://user-images.githubusercontent.com/26801590/68874203-cb2d6180-06ce-11ea-8c47-0e83dc440e48.png">

![](https://user-images.githubusercontent.com/26801590/68807901-b3a29a00-0636-11ea-82ab-10c75a81ee3e.png)

**Comment by ASprinkle** [comment]
I wonder if "You won't be able to..." as the first intro leaves the user feeling good, or not.  Perhaps we should lighten it and switch the order of things... "Your application will be saved once it is submitted. You won't be able to save the application to complete it later."  Sound ok?

**Comment by Rebekah-Hernandez** [comment]
I think that sounds a lot better personally.

**Comment by lisaredux** [comment]
@ASprinkle OK, here are both mockups...

@briandavidson @mtlaney  I grabbed the the hint text class from Xmas trees, and it is "usa-form-hint"

Non-commercial: "Your application will be saved once it is submitted. You won't be able to save the application to complete it later."

![Screenshot 2019-11-14 14 18 23](https://user-images.githubusercontent.com/26801590/68888878-c4f8ae80-06e9-11ea-87cc-7c8171ed11b3.png)

![](https://user-images.githubusercontent.com/26801590/68807901-b3a29a00-0636-11ea-82ab-10c75a81ee3e.png)

Temporary outfitters: "It may take a while to complete the application. To save time, have all of your documents ready. You won’t be able to save the application to complete it later. The application will be saved once it’s submitted."


![](https://user-images.githubusercontent.com/26801590/68808045-f8c6cc00-0636-11ea-8cf2-0032ebdae67c.png)

![](https://user-images.githubusercontent.com/26801590/68806064-198d2280-0633-11ea-956e-c61e0024827d.png)

**Comment by ASprinkle** [comment]
@lisaredux awesome!

**Comment by ASprinkle** [comment]
Thanks @briandavidson this looks great on staging!
