### ISSUE TITLE
As a user I want to be able to access the special uses admin pages so that I can test the function of the site.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#551]
## Notes
When I try to access https://open-forest-staging.app.cloud.gov/admin/applications I receive an Open Forest access denied error.

I am able to successfully access the same site in an incognito window. To access it,  I am prompted to enter the staging site username and password, and go through eAuth.

## Acceptance Criteria
- [ ] Team members can access the Special Uses admin staging site, and all of it's functions without error.

## Tasks
- [ ]  Find out what the steps are to access the staging site.
- [ ]  Update list of folks who should have access to the special uses admin staging site.

## Definition of Done
- [ ] Pull requests meet technical defintion of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by davemcorwin** [comment]
@mtlaney is this being addressed as part of [#548](https://github.com/18F/fs-open-forest-platform/issues/548)?

**Comment by mtlaney** [comment]
@davemcorwin @ASprinkle I am unable to replicate this on my end either in prod, staging, or local. May have been a caching issue?

**Comment by carlsonem** [comment]
Ready for master

**Comment by ASprinkle** [comment]
Unable to replicate. Closing
