### ISSUE TITLE
As a developer I want the mock pay gov implementation to be thoroughly tested so that I know our test cases are working.

### ISSUE THREAD

**Issue by davemcorwin** [USDAForestService/fs-open-forest-platform#560]
## Notes
Flesh out mock pay gov tests.
Testing to make sure fake implementation is working to make sure our test cases are working.

## Acceptance Criteria
- [x] PO confirms with a developer it's working correctly. No UI changes to look at.

## Tasks
- [x] Add mock pay gov tests
- [x] PO approved

## Definition of Done
- [ ] Pull requests meet technical defintion of done
- [ ] Compare finished design with mockup
- [ ] Usability tested
