### ISSUE TITLE
As a forest visitor I would like a better way to select my forest so that I am sure of the forest I am choosing.

### ISSUE THREAD

**Issue by DawnDesigner** [USDAForestService/fs-open-forest-platform#564]
## Notes
As a user I would like to see an attractive image of the forest I am about to apply for a permit and text that clearly states which forest I am applying to so that I can clearly know I’m applying with the correct forest. 

## Acceptance Criteria
- [ ] We have a user friendly forest selection option
- [ ] Selection options follow a consistent design approach
- [ ] Visitors can select their forest in very few clicks, to get started quickly.

## Tasks
- [ ]  Design the Open Forest Christmas tree landing page with high volume of forests in mind
- [ ] Usability test plan completed
- [ ] Usability testing is completed
- [ ] Usability testing notes are housed in a shareable location.
- [ ] PO approved
 
## Definition of Done
- [ ] All links work and point to correct url
- [ ] Usability tested

**Comment by DawnDesigner** [comment]
Amber's comment from #533
"For MVP to get special uses up and running, I don't think we need to spend time on putting a picture from the forest at the top of every page. Perhaps that could be a future/long-term goal, but I wouldn't recommend spending time on that while we ramp up Special Uses side for pilot launch."

Thanks Amber, sorry - this user story was intended only for the landing page, not all pages - probably my bad grammar.  Lisa and I both thought as a UCD discipline it would be great to have because imagery is preferred and creates a better user experience. If your thoughts are just for this site to save development time I understand, but would love for us to consider it for all future permitting sites. 

Would you also consider asking how much time this would take on this project just for the landing page. It's a standard in the 18f css and it would be very quick and easy to drop into the landing page for the development team.

**Comment by ASprinkle** [comment]
From Meeting
Photo on landing page only
FS photo - permissions. (flickr)

**Comment by ASprinkle** [comment]
Original story was specific to MBS special uses.  here is a note from the original story.
"_**Note: 75% of a users response to a web page on first entry is imagery - photos are found to be an excellent way to communicate a culture or branded identify - found to be very effective for Forest Service products - in permitting it helps to connect the user with the environment of the permitting forest._"

**Comment by lisamcmichael** [comment]
@lisaredux when we are both back in the office next week (10/23), let's find some time (no rush) to review this. It's low priority and not MVP, so when we can fit it in.

**Comment by lisamcmichael** [comment]
@ASprinkle Do you think we can close this because Story #604 can encompass it?

**Comment by ASprinkle** [comment]
@lisamcmichael Yes, and I made a note in 604 referencing this story in the event we need a refresher, or a better idea of tasks or A/C.
