### ISSUE TITLE
As an Open Forest applicant, I would like to quickly and clearly see instructions that tell me what fields are required and what fields are not required in the form I am about to fill out

### ISSUE THREAD

**Issue by DawnDesigner** [USDAForestService/fs-open-forest-platform#566]
## Notes
* As a user I would like to quickly and clearly see instructions that tell me what fields are required and what fields are not required in the form I am about to fill out *

## Acceptance Criteria
- [x] Users can clearly see which fields are required before receiving an error
- [x] The required fields indicator is populated on both applications (non-comm group use, and and temp outfitter guide)

## Tasks
- [x] build this design: https://github.com/USDAForestService/fs-open-forest-platform/issues/566#issuecomment-548497527
- [x] Remove "All form fields are required unless otherwise noted."
- [x] Add "required fields *" as shown in the design under the header.
- [x] Remove the "optional" text where it currently exists
- [x] Populate a red asterisk on the outside edge of each required field title indicating that it is required.
- [x] Show a red asterisk between the check box and the PII acknowledgement text at the top of the page. 
- [x] On the Christmas Tree "Buy a Christmas tree permit" page, add: "required fields" with an asterisk underneath the "Permit information" header
- [x] add an asterisk next to "Number of Christmas trees" to indicate it's a required field
- [x] add an asterisk next to the PII checkbox to indicate it is a required field.
- [x] asterisk size on cert of good standing is consistent with others.
- [x] asterisk size on liability insurance is consistent with others.
- [x] Liability insurance exclamation mark is present when the requirement isn't met.
- [x] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [x] Compare finished design with mock up

**Comment by ASprinkle** [comment]
From meeting:
change required field text from red to another color (to confuse w/errors).
placement so that it can be seen throughout the application process (under nav menu?)

**Comment by DawnDesigner** [comment]
Required field text now moved to under left sidebar so it's visible during entire process, and changed to bright blue - not to be confused with alerts.

![Required fields2](https://user-images.githubusercontent.com/47989077/55829389-89a35b00-5adc-11e9-8996-8b5935985763.png)

**Comment by ASprinkle** [comment]
That looks clear to me.  As I understand from our previous meeting, the expectation would be that it would always be present on the screen as the applicant scrolls through the page, or navigates to the different steps.
With the font in something other than Red, there would be no confusion regarding errors or missing fields.
Is blue part of the design protocol for Open Forest?  I think this is the first I have seen blue. Usually texts are green, brown, black, or red in the case of errors or missing information.

**Comment by DawnDesigner** [comment]
@ASprinkle -  I've changed the text to brown - was worried it wouldn't show up enough for the users to see easily as something as important, but maybe with the caps and bold it will work.  We'll do some user testing on it to make sure.

![Required fields3](https://user-images.githubusercontent.com/47989077/56316885-766e3c00-6129-11e9-8c2b-becbf166f55f.png)

**Comment by DawnDesigner** [comment]
@ASprinkle  @davemcorwin  @mtlaney - Sorry all, here we go for a final round. My apologies, but this time we've got it right

Based on usability tests recently studied by the NNG (Neilson, Norman Group) to debunk a trend to not use a red asterisk next to the title of required fields because the red offends users, it showed the overall hands down preference after hundreds of users tested - is that users don't find it offensive, and in fact prefer to have a small red asterisk next to the tile of the field - even if a large number of fields are required.

Forgive this change in standards, but I was feeling from the first that not using the red asterisk wasn't the right choice but needed user testing to confirmation.   

It has been agreed by the design team that this product will now adopt that standard:

1. All required fields on any forms that are required will have a small red asterisk after the title of the field, with the  title above the input box.

2. Directly before the form input fields begin there will be a sentence that reads "* Required fields " With the asterisk a standard red

3. NNG did not find the need to the confirmation (Optional field) - so no need for that statement.  If it doesn't not have an asterisk it's not considered required by the users.

Keeping best practices for usability, and making it user friendly is the key.  The tactic of removing the red asterisk was found to be confusing for the users in a controlled tested group. Thanks

![RequiredFields Red Asterisk](https://user-images.githubusercontent.com/47989077/57534110-4cb1ca80-730d-11e9-81b4-64e471b3f903.png)

**Comment by DawnDesigner** [comment]
@ASprinkle @carlsonem Can we move this to ready?

**Comment by ASprinkle** [comment]
@DawnDesigner I appreciate the question - but we are not ready to move it up in priority yet.  while this story has platform related applicability - it will have to wait for now as we learn more about our Christmas tree scale up.

**Comment by lisamcmichael** [comment]
See the notes/design on April 17 (design should “anchor” the NOTE: All fields required unless noted otherwise”

**Comment by lisamcmichael** [comment]
Here's what I took down yesterday: @lisaredux will create an updated mock-up.

**Comment by lisaredux** [comment]
We decided to remove the required note in the left-nav and to keep it only above the form. Update here shown: 
![Screenshot 2019-10-31 13 18 13](https://user-images.githubusercontent.com/26801590/67973244-8ab9e800-fbe6-11e9-9d9c-9a18061c7ed8.png)

**Comment by lisamcmichael** [comment]
@ASprinkle We decided to launch this design w/out more research, and monitor feedback for any potential issues.

**Comment by ASprinkle** [comment]
@lisaredux Can you create a full page mock showing the changes for each Step in both permit scenarios. I have updated the Tasks and the A/C, but wonder if there isn't more detail we could provide for Dev?

**Comment by lisamcmichael** [comment]
@briandavidson **Take a look at the Screenshot Lisa posted 6 days ago.** Any further questions, let me know.

**Comment by ASprinkle** [comment]
@briandavidson I was reviewing some Christmas tree stuff, and I noticed that it looks like some of the work for this story is showing up on the Christmas tree pages. I think this is a happy unplanned thing, since we'll likely want to denote required fields across the platform in the future.
![image](https://user-images.githubusercontent.com/33435621/68443779-d42ba980-0189-11ea-9254-c246c734db24.png)
![image](https://user-images.githubusercontent.com/33435621/68443784-d7bf3080-0189-11ea-9d9d-b00cb23233c3.png)
Just checking to see if this was the intention.  

Also, I was unable to review the rest of it on the Special Uses side, because of a curious login.gov interaction.  I would like to follow up with you on this tomorrow.

**Comment by briandavidson** [comment]
@ASprinkle that was actually not my intention! Apparently some of the UI components used in non-commercial and temporary-outfitter application forms are reused in other areas of site, despite not being in the `/shared` folder with the other reusable components.

**Comment by ASprinkle** [comment]
@briandavidson I updated the tasks for the Christmas tree page interaction.

**Comment by ASprinkle** [comment]
@briandavidson it looks like this is already up on Prod, however the story is still in progress, and has work left on it. here are some screen shots from Christmas tree in prod:
![image](https://user-images.githubusercontent.com/33435621/68806958-c78cd280-061b-11ea-9ed4-93c9247c86a5.png)
![image](https://user-images.githubusercontent.com/33435621/68806974-d1aed100-061b-11ea-9dd6-1761f3feb8ee.png)

**Comment by lisamcmichael** [comment]
@briandavidson **Thx!**

**Comment by lisaredux** [comment]
@ASprinkle - @briandavidson and I just talked about this. We found two fixes that need to change from the 3 forms, and Brian is handling that now.

Otherwise, I'm including screenshots for DEV reference on where to put the "_required fields *_" introduction now on Christmas trees and special uses forms:

![Screenshot 2019-11-19 16 22 55](https://user-images.githubusercontent.com/26801590/69189750-f1973680-0aec-11ea-9f97-e53ffa540863.png)

![68888878-c4f8ae80-06e9-11ea-87cc-7c8171ed11b3](https://user-images.githubusercontent.com/26801590/69189710-d9271c00-0aec-11ea-9e28-04d019b09ccd.png)

<img width="1061" alt="68808045-f8c6cc00-0636-11ea-8cf2-0032ebdae67c-1" src="https://user-images.githubusercontent.com/26801590/69189733-e7753800-0aec-11ea-9ca7-a2c10039b643.png">

**Comment by ASprinkle** [comment]
@lisaredux @briandavidson Awesome! :) great update!

**Comment by ASprinkle** [comment]
@briandavidson @lisaredux I see what looks like some required fields in Special Uses that don't have asterisk, but appear to be required for "Individuals" Liability Insurance, Certificate of Good Standing.
![image](https://user-images.githubusercontent.com/33435621/69450533-37811400-0d12-11ea-9ac1-8a0efef0eb45.png)
![image](https://user-images.githubusercontent.com/33435621/69450539-3b149b00-0d12-11ea-9609-e0fdf003fe25.png)

**Comment by briandavidson** [comment]
@ASprinkle / @lisaredux where do we want to put the `*` for these?

**Comment by lisaredux** [comment]
> @ASprinkle / @lisaredux where do we want to put the `*` for these?

thanks @briandavidson — I'll tackle a mockup now

**Comment by lisaredux** [comment]
@ASprinkle @lisamcmichael I tackled this two different ways... feel free to weigh in which makes the most sense

First option, next to the button...
<img width="760" alt="Screenshot 2019-11-25 11 10 20" src="https://user-images.githubusercontent.com/26801590/69558077-9eeace00-0f75-11ea-9853-06f046d3e956.png">
<img width="477" alt="Screenshot 2019-11-25 11 08 03" src="https://user-images.githubusercontent.com/26801590/69558078-9eeace00-0f75-11ea-8783-0adcc762737f.png">



Second option, next to the relevant heading:

<img width="817" alt="Screenshot 2019-11-25 10 48 44" src="https://user-images.githubusercontent.com/26801590/69558084-9f836480-0f75-11ea-9d1c-c096629c9803.png">
<img width="472" alt="Screenshot 2019-11-25 10 52 52" src="https://user-images.githubusercontent.com/26801590/69558081-9f836480-0f75-11ea-99d3-9ab99bb97c11.png">

**Comment by briandavidson** [comment]
@ASprinkle , @lisamcmichael , @lisaredux , any decisions on how we want to treat this?

**Comment by lisamcmichael** [comment]
**The UI pattern seems to be adding it next to the label** (especially when there is not a header/form field.) I would go w/ the pattern. @lisaredux would you agree?

**Comment by lisaredux** [comment]
Yes. I agree @lisamcmichael. Thanks for your input.

@briandavidson thanks for your patience. We will go with this placement for the astericks as shown in these screenshots:
![](https://user-images.githubusercontent.com/26801590/69558084-9f836480-0f75-11ea-9d1c-c096629c9803.png)

![](https://user-images.githubusercontent.com/26801590/69558081-9f836480-0f75-11ea-99d3-9ab99bb97c11.png)

**Comment by ASprinkle** [comment]
@briandavidson 

This is looking really good. Looks like some great communication between Dev and Design.  I have two comments when I review on staging.
It appears that the Liability Insurance and certificate of good standing asterisks are noticeably larger when compared to all the other ones... is there a way to make them the same size as the rest?
Also, i noticed the menu option didn't show the red exclamation markl error for liability insurance when I attempt to submit with out completing the field. 
![image](https://user-images.githubusercontent.com/33435621/69739908-56562080-10ed-11ea-91ca-eff5aef381d2.png)

**Comment by briandavidson** [comment]
@ASprinkle yep, we can adjust the asterisk size to match the others. And I'll look into what's up with the Liability Insurance check as well.

**Comment by ASprinkle** [comment]
@briandavidson maybe we can meet up on this today. It looks like I am still seeing the inconsistency on error message 
![image](https://user-images.githubusercontent.com/33435621/69987056-80e01900-14f3-11ea-98f2-c827550f66d1.png)

**Comment by ASprinkle** [comment]
@briandavidson can we adjust the asterisk for the certificate of good standing? it is still bigger than the rest.
The Liability insurance one looks good and the error notation in the menu is great!
 
 
![image](https://user-images.githubusercontent.com/33435621/70067255-db847e00-15a2-11ea-9bef-ccd69535e47e.png)

![image](https://user-images.githubusercontent.com/33435621/70067265-df180500-15a2-11ea-9b8a-578756f9739e.png)

**Comment by ASprinkle** [comment]
awesome!
![image](https://user-images.githubusercontent.com/33435621/70080632-c536ec00-15bb-11ea-915a-b8dd4d25f297.png)

**Comment by ASprinkle** [comment]
This is looking really great in Prod, thanks for your work on this @briandavidson
