### ISSUE TITLE
As an administrator and security operator I want administrator privileges to be restricted to a specific EAuth user.

### ISSUE THREAD

**Issue by davemcorwin** [USDAForestService/fs-open-forest-platform#579]
## Notes
Currently, adminstrator privileges for EAuth users are determined by the user's full name. However, full name is not unique or protected in any way, making it possible for any EAuth user with the same name as an administrator to assume administrator privileges.

## Acceptance Criteria
- [ ] An EAuth user with the same name as an administrator is not granted administrative access.

## Tasks
- [ ] Use the EAuth email address to determine administrator privileges instead of full name
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical defintion of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by davemcorwin** [comment]
blocked by #609

**Comment by DawnDesigner** [comment]
Completed #609

**Comment by carlsonem** [comment]
@briandavidson reach-out to Shadat to get guidance

**Comment by ASprinkle** [comment]
@mwreiss is this story necessary given the work being done currently around admin user management ICAM/EEMS integrations?

**Comment by mwreiss** [comment]
@ASprinkle  I think this one can be closed out.  Thanks Amber!
