### ISSUE TITLE
As an Open Forest user, I would like one main landing page for Open Forest so that I can easily manage permitting for multiple forests and permits from one place.

### ISSUE THREAD

**Issue by DawnDesigner** [USDAForestService/fs-open-forest-platform#604]
## Notes

Create a landing page for Open Forest so that users have one place to access all permits/features available.
- consider scale up to include multiple permit types for one forest
- An image of each forest could enhance the UX, and make it more understandable / relevant.

**Benefits to users:**
- Users would have one place to access all permits from one page instead of multiple prod links to work from.
- Users who want multiple permits across several forests would have one place to find permit options for multiple permits in one session (for example, mushroom hunters might travel between the Mt. Hood, and Willamette NFs)
- Better SEO
- Better management for analytic tracking and permit management

"Information Foraging: A theory of how people navigate on the Web
https://www.nngroup.com/articles/information-foraging/

****
## Acceptance Criteria
- [ ]  Users (Forest Service and the Public) can go to openforest.fs.usda.gov and choose their direction.

## Tasks
- [x]  Refine user story with SME's/POCs
- [x] Research existing information from previous team research
- [x] Meet with Aaron and Amber RE landing page "research/define" approach
- [x]  Find out about connecting design to development program (efficiencies in mock ups) 
- [x]  Define info architecture (IA) options/approaches
- [x]  Research UI patterns for complex IA  (aka, think about A11Y)
- [x] Standardize UI/UX platform to Sketch (or some other agreed upon system)

## The following tasks would be completed through individual stories associated with this epic (#1051 #1052 #1122 #1053 #1054 #1123 #1055)
- [x] initial landing page research completed #1051
- [x]  Create clickable wireframe to determine layout and new workflows, reviewed w/Dev #1052 
- [x]  Develop test plan #1122
- [x]  Test wireframe #1053 
- [x]  Refine landing page design based on test results #1054 
- [x]  Build the main landing page into staging #1123
- [x] Test the main landing page in the staging environment #1055
- [x] Validation of acceptance criteria completed
- [x] PO Approved 

## Definition of Done
- [x]  All acceptance criteria are met
- [x] Stories inside this Epic are completed
- [ ] Usability tested

**Comment by jdamis4XD** [comment]
@DawnDesigner @lisaredux  depending how many forests become options we might want to explore other ways to make the forest selection due to accessibility and ease of use.  Ran across this study that has some things that we should consider when implementing the feature: https://baymard.com/blog/drop-down-usability

**Comment by ASprinkle** [comment]
Chris Bentley suggested a map tool during a Christmas tree sprint review. christopher.w.bentley@usda.gov

**Comment by lisamcmichael** [comment]
Aaron's _Program Increment_ has this story slated in December (_Finalize Updated forest
selection experience for Xmas Tree, something besides drop down_). @ASprinkle and @lisaredux I'll research UI patterns for "multi-selectors".

**Comment by ASprinkle** [comment]
@lisamcmichael good to be thinking about this, however I think we've got some other design stories prioritized over this one in the backlog.

**Comment by lisamcmichael** [comment]
@ASprinkle I've combed through icebox and backlog, and most stories are suitable for design or dev), or identified as not for MBS pilot. Here are some stories that I could work on. Just let me know. Also, point me to ones that you have in mind. Possibly #348 (researching ideas?); although this story is not identified for pilot. There's #948, (creating language) for the feedback has been submitted function. And there is #259, creating an error message.

**Comment by lisamcmichael** [comment]
We can meet, @ASprinkle, on this as soon as you and @lisaredux are ready.

**Comment by ASprinkle** [comment]
Thanks @lisamcmichael I'll see if I can find a time for us!

**Comment by lisamcmichael** [comment]
I WILL ADD MY CURRENT NOTES HERE, and after we meet today I'll move them.

![image](https://user-images.githubusercontent.com/52501060/68888515-16546e00-06e9-11ea-946d-c910181429b0.png)

**Comment by lisamcmichael** [comment]
Consider how we can break this story out into more manageable/edible chunks.

Here are some ideas:
One story
Refine story with SMEs
Brainstorm ideas around a landing page (portal) expectation

One Story
Wireframe design option based on previous story research
Review option with dev for feasibility considerations
Schedule tests

One Story
Refine Wireframe based on dev considerations
Finalize mock wireframe
Test wireframe with users
Synthesize user feedback

One Story
Finalize mock design
Build mock up

One story
Test
Refine
Launch

**Comment by ASprinkle** [comment]
Folder for documentation around this Epic is created in Pinyon in the Content 2019 folder. https://usfs.box.com/s/v866vdkg4oxz8sscytu1ar0y6skve3wj

**Comment by ASprinkle** [comment]
@lisamcmichael @lisaredux @Rebekah-Hernandez I completed an initial refinement/updates for all of the stories associated with this epic.

**Comment by lisamcmichael** [comment]
Folder for documentation around this Epic is created in Pinyon in the Content 2019 folder. https://usfs.box.com/s/v866vdkg4oxz8sscytu1ar0y6skve3wj

**Comment by lisamcmichael** [comment]
**An initial concept from Dawn** in collaboration with Melissa, @lisaredux and Jennifer. 

![Open Forest Landing _d blancard](https://user-images.githubusercontent.com/52501060/69356596-b3ffee00-0c51-11ea-926c-dedb744a31fb.png)

**Comment by lisamcmichael** [comment]
@ASprinkle and @lisaredux I will pull out relevant "key" research findings to support the design direction we should take and have that ready by Monday. For instance, prior research supports including a Search feature; this is because the common user behavior is to go directly to Search (typically Google) to find the "right thing". That's a bit of a sidebar, although this is the type of thing we should keep on the table for discussion.

**Comment by lisaredux** [comment]
Thanks for pulling that up, @lisamcmichael . Just an FYI, Dawn was the only one working on that design concept. 

Today, I'll work on testing a collaborative format for our design side - Sketch or Figma or whatever works. And I'll look at whether I can connect with DEV's side to create an interactive branch in Github for design tinkering.

Looking forward to our discussions about it tomorrow.

**Comment by lisamcmichael** [comment]
_Meeting with Aaron/Amber/Lisa S to discuss research approach to take:_

- Bargain UX most feasible due to budget constraints
- Lisa S: she needs to know the scope of information to design prototype
- Aaron/Amber: design a landing page that is going to work for the next 2 yrs.? Then it will be revisited.  
- Amber:  Also considering an in-person Retro w/pilot forests, to help align w/ Gifford-Pinchot (program increment)
- Look at Aaron's questions for user interview ideas
- MVP could be mid to high-fi (depends on where we are in the process).

**Comment by lisamcmichael** [comment]
**@lisaredux All research for the landing page Epic is here on Pinyon:**
https://usfs.box.com/s/v866vdkg4oxz8sscytu1ar0y6skve3wj

**Comment by lisaredux** [comment]
- Going to pull up with Brian to get help getting my local environment started.  Hoping to see we can design and mock up in a dev environment using the templates and code
- Sent email to Shadat and Eric to get confirmation on collaborative tool licensing for the design team - Figma or Sketch as a fallback

**Comment by lisamcmichael** [comment]
@ASprinkle and @lisaredux, these **research questions** were shared w/ 18F on Thursday. I'm _meeting w/ Melissa and Mark on Wed_. Just "lmk" if you have addt'l questions to include.

https://usfs.app.box.com/file/566822961291

**Comment by lisamcmichael** [comment]
@lisaredux and @ASprinkle here's an initial set of **info architecture schemes that might be useful for us to consider:**  The article is dated (2010), the insights/recommendations are still applicable and relevant ways to organize information.
https://www.uxbooth.com/articles/classification-schemes-and-when-to-use-them/

**Alphabetic:**
There are only a _couple of situations where you’d use alphabetic as the main way of organizing your content—dictionaries and glossaries_ come to mind. But they’re _great secondary schemes_ to a main scheme. Even as a secondary scheme they can be valuable; I’ve worked on intranets where people said: “Do whatever you like, just don’t take away the A-Z.” [example: "dense footer" with links to top-level categories and/or deep linking to hard to find but important pages) LM: the SU footer could be enhanced to take advantage of this scheme.)

**Geographical (map) scheme:**
"Geographical schemes can be used for any content with some sort of geography as a key attribute. I can’t tell you how many web and intranet project meetings I’ve been in where someone has said: _“We should just include a map on the home page and let people use that.” In some cases it’s a perfectly good suggestion, but in others, it’s not so good._ 

So when is it good? There are _two real criteria for a successful geographical scheme_. The first is that your audience must want to access information in that way. The second is more important—_they must understand the geography you’re using, often in quite a lot of detail._ Geography may be **good as a secondary way to access information**, supporting one of the other schemes. [LM: the map scheme seems like a good secondary way for the public to access info, but not the sole or primary way.]

**Format scheme**
Format is a great way to _show people the different types of information_ available (e.g., read instructions, watch a video, hear a description, etc.) once they’ve found the topic. _There is one caveat:_ people tend to think first about what they want to do, _and then_ about the format they want to see it in.

**Subject/topic**
A subject scheme groups similar things together based on what they’re about...it’s worth knowing _this type of classification scheme works well for most content_. And as long as you can do it in a way that makes sense for your audience, it will be suitable for them as well.

**Comment by lisamcmichael** [comment]
@ASprinkle If we do run a _card sorting research activity,_ here's a **2.5 minute video** with details on open vs. closed card sorts. https://www.nngroup.com/videos/open-vs-closed-card-sorting/

_A master list of articles:_
https://www.nngroup.com/search/?q=card+sorting

**Comment by ASprinkle** [comment]
@lisamcmichael those videos are really helpful.  Let's schedule some time to follow up and make a decision or get better understand about about first step/path towards IA.  Once we do that I think we can satisfy the task for IA in this story.

**Comment by ASprinkle** [comment]
Follow up on IA scheduled for 12/9

**Comment by lisaredux** [comment]
Working on wireframes and ideas on shared Balsamiq workspace: 
https://balsamiq.cloud/sjnh4c9/pdjueup/r2278

**Comment by ASprinkle** [comment]
12/11/2019 Design meeting to brainstorm user journeys to inform IA considerations.

**Comment by ASprinkle** [comment]
IA options/approaches:  Starting point to be validated with testing: 
Search feature option
Location features (city/radius) presenting user with forests and associated services for those forests.
Categories for services with sub categories with features opportunity within each service.
then route customer to appropriate Open Forest information page to being purchase

**Comment by lisaredux** [comment]
Possible user scenarios are getting captured here: https://usfs.app.box.com/notes/573288780620

Balsamiq wireframes in progress here: 
https://balsamiq.cloud/sjnh4c9/pdjueup/r2278

**Comment by ASprinkle** [comment]
This card is currently in Blocked until all stories under this Epic are completed.

**Comment by carlsonem** [comment]
@aQuib can this be closed out?

**Comment by aQuib** [comment]
@ericsorenson - yes it can
