### ISSUE TITLE
As an Open Forest team, I'd like to have the design created for a feedback instrument, so that we can capture input from the public and admins..

### ISSUE THREAD

**Issue by carlsonem** [USDAForestService/fs-open-forest-platform#617]
## Notes
* What are things we should consider when making this story *

What is the business problem that we are trying solve with the feedback system (define the scope)?
- Gathering feedback is a requirement as part of USDA customer experience office, guidance in Presidents management agenda to gather customer feedback.
- GSA office of customer experience has detailed information about what we should collect.

## Acceptance Criteria
- [x] We understand what is needed to develop a feedback system
- [x] We have a system design for capturing feedback, public/admin.
- [x] We have a system design for accessing the feedback
- [x] The tool is designed to capture feedback in a way that is meaningful and could be measured (qualitative/quantitative)

## Tasks
- [x] Ensure stories are created for development based on the design mock ups
- [x] PO approved

## Definition of Done
- [ ] Tasks and A/C

**Comment by ASprinkle** [comment]
From our design meeting 5/1 - We may want to move this back into the backlog because:
GSA office of customer experience is going to have an ATO component that we could use - ready in Summer? (Demo next week?)

**Comment by ASprinkle** [comment]
Demo being scheduled for 5/10

**Comment by ASprinkle** [comment]
Need a decision on which feedback tool to use before we can incorporate one.

**Comment by DawnDesigner** [comment]
@ASprinkle - Do we need to better understand where in the users journey a feedback tool would work best? I can do some background research and make recommendations to the team. That might help in the decision process.

1. Where will access to the tool be available for the user
2. What are we trying to discover through the survey tool? (specific)
3.  Who will manage the responses and report to the team?
4.  What format is more user friendly (multiple choice, commenting etc.)

**Comment by ASprinkle** [comment]
@DawnDesigner  see story #676 (part of this epic issue) in the backlog . I will take your comments here and add them to that story to aid in refinement.

**Comment by ASprinkle** [comment]
I had asked Melissa for some recollection on this and this is what she shared with me: " I believe the team decided to work toward a code snippet that used an open ended Q to gather qualitative feedback. IIRC, Eric was going to talk it over with Mike and consider using some of the touchpoints code to simply add in a pop-up, as the MVP."

**Comment by carlsonem** [comment]
That sounds right!

**Comment by lisamcmichael** [comment]
As I mentioned in 676, let me know when and how to jump in and help.

**Comment by lisamcmichael** [comment]
@carlsonem 
_I've assigned myself to #676. That story is identical to this one. **I think we should close #617**._

**Comment by lisamcmichael** [comment]
See #676 (public feedback) and #776 (admin/poc feedback)

**Comment by lisamcmichael** [comment]
@ericsorenson @ASprinkle After discussing this with @lisaredux , we recommend not running usability testing on this simple feedback form. After it's implemented, if responses are low, or none, to using the form, then we can run some tests.

**Comment by ASprinkle** [comment]
@lisamcmichael @lisaredux @carlsonem I agree 100%

**Comment by lisaredux** [comment]
I agree @ASprinkle — closing this sounds good to me while the other stories are in motion

**Comment by ASprinkle** [comment]
Ok... I updated the A/C here. and made a story to update the Wiki for the feedback process once the tools have been developed.

**Comment by ASprinkle** [comment]
#855
#856 
#840 
#676
#776
