### ISSUE TITLE
As a FS administrator I would like a way to easily manage multiple internal FS users (e.g. admins) so that FS admins can be easily added or removed as positions change.

### ISSUE THREAD

**Issue by carlsonem** [USDAForestService/fs-open-forest-platform#618]
## Notes
Currently, individual forest admins are white-listed by the system. The objective is to create a way to better add/delete/manage forest admins.

## Acceptance Criteria
- [ ] We understand how a super admin can add/delete individual forest service admins platform wide (for special uses and Christmas trees).
- [ ] We have an understanding of what the Super Admin's roles are, and how those roles are managed.
- [ ] We can easily add or remove FS credentialed individuals.

## Tasks
- [ ] Mock design based on the workflow (meeting design standards, 508).
- [ ] Build in new functions/pages.
- [ ] Develop admin management functions.
- [ ] Usability tested by "super admins"
- [ ] PO approved.

## Definition of Done
- [ ] Pull requests meet technical defintion of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
Update from planning: This story will likely become an Epic resulting in multiple stories that might consider: 
-workflow research regarding potential process to add/remove FS admins. 
-designing a new page for admins.
-determining level of access for FS admins and applicable platform accesses points (i.e., Christmas tree or special uses).
-determining whether or not there would be authentication needs associated with this process.
-determine who the "super admins" should be, and how those might be managed.

**Comment by ASprinkle** [comment]
Closing based on ICAM research and expectations to integrate with the existing user management system #922 and #926
