### ISSUE TITLE
As an applicant, I want to be able to quickly identify which fields are entered incorrectly so I can successfully submit an application

### ISSUE THREAD

**Issue by carlsonem** [USDAForestService/fs-open-forest-platform#620]
## Notes
If a user incorrectly inputs data in an application form and/or leaves a required field blank, the user should quickly be able to identify which field is causing them not to be able to submit the issue.

-Need to be more specific identifying where validation needs to occur, where it isn't occurring right now.

## Acceptance Criteria
- [ ] When incorrect or wrong data is entered in an application, the user can quickly identify which field is causing the issue.

## Tasks
- [ ] Develop design and/or action needed when a field is not completed correctly
- [ ] Develop code to make incomplete/wrong data fields noticeable to user

## Definition of Done
- [ ] Pull requests meet technical defintion of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by carlsonem** [comment]
Need to specificy where validation is needed.

**Comment by ASprinkle** [comment]
See also story #605
