### ISSUE TITLE
As a Christmas tree permit recipient, I want to download my permit with rules and guidelines attached from the confirmation page so that I don't have to click a checkbox before I know what I might be missing

### ISSUE THREAD

**Issue by lisaredux** [USDAForestService/fs-open-forest-platform#630]
## Notes
* On the confirmation page, the customer has to click a checkbox to get the rules and guidelines along with their permit. The customer might miss the opportunity to get the rules and guidelijnes at all, especially if they didn't enter their email address correctly. It's better to get too much and make printing decisions than to miss out on some important information when going to cut a tree.
![57232886-99cf2d00-6feb-11e9-928d-406aec92fac3](https://user-images.githubusercontent.com/26801590/57381013-23ac0100-7178-11e9-9b85-192844febebc.png)

## Acceptance Criteria
- [ ]  Change default to including the rules and guidelines in a final permit pdf so user is sure to receive those before cutting a tree

## Tasks
- [ ]  - Add rules and guidelines to the api
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical defintion of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
Here is a brief summary of why Open Forest has these as two separate documents:
Permit is required to be printed.
Rules are not required to be printed.
With the permit as one document, the user does not have to specify a page range to print.
With the permit as one document, the user is not burdened to print many pages of information.
Open Forest wants to minimize the amount of resources required by the user, for the user to be in compliance with the Forest.

There is probably more of a story here around document format. Currently, the permit is a .png,  and the rules come as a .html link and a .txt  
This was set up this way so that emails wouldn't be auto rejected by some systems.
Is there more we can do here with the document type for the attachments?

**Comment by ASprinkle** [comment]
closing based on comments above, and because the rules and guidelines are emailed to them.

**Comment by lisaredux** [comment]
@ASprinkle @jdamis4XD I am just seeing that this has been closed. Let me know if you would like to discuss alongside story #629, #631, and #489

**Comment by ASprinkle** [comment]
I reopened this and moved it to the icebox for now. This story might be more of an enhancement to Christmas trees - it would probably be better to icebox it rather than close it so that the idea isn't lost for future opportunity.

**Comment by ASprinkle** [comment]
This is redundant with #899 so I am closing this story.
