### ISSUE TITLE
As a Christmas tree permit recipient, I'd like my permit to have an easy to identify name by default so that I can easily search it on my computer after downloading it from the confirmation page.

### ISSUE THREAD

**Issue by lisaredux** [USDAForestService/fs-open-forest-platform#631]
## Notes
* Currently, the PDFs downloaded from the confirmation page have a name "Untitled Document.pdf " which is difficult to search on a computer. Including as many relevant names as possible into the PDF would help customers find their permits that they download more easily 
<img width="346" alt="Screenshot 2019-05-08 10 21 55" src="https://user-images.githubusercontent.com/26801590/57382909-d467cf80-717b-11e9-99e8-4c49b169fa79.png">

## Acceptance Criteria
- [x] A "permit name" is added to the file when a PDF is created when downloading a permit purchased through the system

## Tasks
- [x] Change file name to "ChristmasTreePermit" instead of "UntitledDocument"
- [x] Auto populate PDF permit file name when downloading
- [x] PO approved

## Definition of Done
- [ ] Pull requests meet technical defintion of done
- [ ] Compare finished design with mockup
- [ ] QA Design Tested (508 compliant)

**Comment by ASprinkle** [comment]
I reopened this and moved it to the icebox for now. This story might be more of an enhancement to Christmas trees - it would probably be better to icebox it rather than close it so that the idea isn't lost for future opportunity.

**Comment by ASprinkle** [comment]
Looks good!
![image](https://user-images.githubusercontent.com/33435621/67960833-1700e680-fbb8-11e9-8ea6-3aa43b6baac8.png)
