### ISSUE TITLE
Search Engine Optimization - SEO - Christmas Tree

### ISSUE THREAD

**Issue by DawnDesigner** [USDAForestService/fs-open-forest-platform#638]
## Notes
* As a permit seeker in the Open Forest system, when I want to purchase a permit to cut a Christmas tree I would like to easily find the Christmas tree permitting site for my forest easily in the search engines on the internet.

## Acceptance Criteria
- [ ] Meta tags updated
- [ ] Page content optimized
- [ ] Plan for search engine submission is drafted and agreed upon
- [ ] Testing confirms efforts have moved a site identified as a means has improved in ranking

## Tasks
- [ ] Identify SEO best practices
- [ ] Identify what has - if any - already be accomplished
- [ ] Draft meta tags - PR 
- [ ] Draft a plan to develop optimized content for landing pages
- [ ]Plan reviewed - PR
- [ ] PO approved

## Definition of Done
- [ ]  All tasks are completed and approved by PO
- [ ] Pull requests meet technical definition of done
- [ ] Ranking of test site has improved
- [ ] Usability tested

**Comment by lisamcmichael** [comment]
Closed story. Added tasks, A/C and Def. Done to #636
