### ISSUE TITLE
As an Administrator, I'd like to be able to request changes to the Christmas tree content for my Forest so that I can ensure that visitors to my forest have the most up-to-date information.  

### ISSUE THREAD

**Issue by MelissaBraxton** [USDAForestService/fs-open-forest-platform#659]
## Notes
* Currently, FS admins submit content change requests via a Google form. This form and the email to which responses are delivered are overseen by GSA. At a minimum, FS needs to create a new Google form and direct responses to an FS email account. It's also possible that the FS team comes up with a different solution to meet this need. 

## Acceptance Criteria
- [ ] Administrator is able to submit content change requests from within the Open Forest System (not GoogleDocs)
- [ ] Content change requests are able to be submitted by FS admin and Open Forest team is able to receive the change request in a timely manner 

## Tasks
- [ ] Determine user requirements for content change request mechanism
- [ ] Design mechanism
- [ ] Implement mechanism
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
When an FS admin submits a content change request using the Google Form version, an email (shown below) is sent to myself and Laura Gerhardt with links to view the change request... 

From: Google Docs [mailto:notify@google.com] 
Sent: Monday, July 1, 2019 11:52 AM
To: Gerhardt, Laura (GSA) <laura.gerhardt@gsa.gov>
Subject: "Request changes to National Forest Christmas Tree permit website (Responses)" was edited recently

See the changes in the Google Document "Request changes to National Forest Christmas Tree permit website (Responses)": Click here
•	A user made changes from 7/1/19 11:51 AM to 11:51 AM (Pacific Daylight Time)
Open the current version of the Google Document "Request changes to National Forest Christmas Tree permit website (Responses)": Click here

Powered by Google Sheets
---
Want to stop receiving this email? Click here

**Comment by ASprinkle** [comment]
Moving this to Ice Box for now - we may see how content change requests are managed through the Admin feedback tool, and or the customer service email.

**Comment by lisamcmichael** [comment]
> Moving this to Ice Box for now - we may see how content change requests are managed through the Admin feedback tool, and or the customer service email.

@ASprinkle and @lisaredux "got it" and agree this is a tbd story now.
