### ISSUE TITLE
As a security operator I want application administrators to be required to be EAuth Level 2

### ISSUE THREAD

**Issue by davemcorwin** [USDAForestService/fs-open-forest-platform#667]
## Notes
Our PIA requires that application administrators are authenticated with EAuth Level 2, but currently EAuth level 1 uses are allowed to be administrators.

Because EAuth Level 2 requires identity verification, we may want to consider relaxing this constraint in non-production environments.

## Acceptance Criteria
- [ ] Application administration in production is limited to EAuth Level 2 users
- [ ] Application administration in non-production environments is limited to EAuth Level 1 users (tbd)

## Tasks
- [ ] Update EAuth integration configuration and logic to restrict administrative access to EAuth Level 2 uses
- [ ] Add a "feature flag" to configure restriction to EAuth Level 2 users by environment (optional)
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
#689 may address this story. When #689 is complete, we can review whether or not the need for this story still exists.

**Comment by abdul1234e** [comment]
this is in progress on program board. This is already implemented in dev environment.

Reference number 118

**Comment by ASprinkle** [comment]
Closing based on comment ^
