### ISSUE TITLE
Streamline and update deployment process

### ISSUE THREAD

**Issue by davemcorwin** [USDAForestService/fs-open-forest-platform#673]
## Notes
When deploying to Cloud.gov, we leverage the [autopilot](https://github.com/contraband/autopilot) plugin to perform a "zero downtime" deployment that prevents our users from experiencing any downtime when we deploy. However, this plugin:
- is no longer maintained
- temporarily requires a higher memory allocation since multiple applications are running simultaneously
- is used for deployments to the `staging` environment where downtime is not an issue.

To mitigate these issues we can migrate to [v3-zdt-push](https://docs.cloudfoundry.org/devguide/deploy-apps/rolling-deploy.html) which uses a rolling restart strategy to achieve zero downtime without increasing memory requirements. This has the added advantage of using a Cloud Foundry built-in feature as opposed to a community-provided plugin. Note - This feature is currently in beta.

## Acceptance Criteria
- [ ] Production deployments have zero downtime
- [ ] All Deployments do not increase the required memory

## Tasks
- [ ] update **production** deployment process by replacing `autopilot` with `v3-zdt-push` 
- [ ] updated **staging** and **dev** deployment processes to use `cf push` instead of any "zero downtime" deployment strategy
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [] Compare finished design with mockup
- [] Usability tested

**Comment by mwreiss** [comment]
Thanks Dave for getting this queued up after our discussion yesterday.  Is this something that we can get in place before Friday, and or do you want to run through it with @abdul1234e @briandavidson and myself?

**Comment by davemcorwin** [comment]
We can bring it up during the stand to prioritize, I don't think its super urgent, but given the nature of our agreement with Cloud.gov, at a minimum, we should probably remove the zero downtime deployment from non-prod environments sooner rather than later.

**Comment by ASprinkle** [comment]
@carlsonem @mwreiss check for redundancy on the program board.

**Comment by mwreiss** [comment]
@ASprinkle  we can move this issue to close.  I have this captured on the program board. 152
