### ISSUE TITLE
As an Open Forest public user, I want to provide thoughtful feedback on my user experience at a point in the permit process that makes sense.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#676]
## Notes
* What are things we should consider when making this story *

The Open Forest program needs to implement a feedback feature so that we can continue to improve the user experience over time.  The team should refer to #626  and program board story 26 for additional background.

Farmers.gov has a Feedback tool example we can refer to (or choose to adopt) https://www.farmers.gov/

## Acceptance Criteria
- [x] We have an understanding of what it is we are collecting feedback on.
- [x] Feedback questions adhere to the Paperwork Reduction Act requirements.
- [x] A feedback option exists for the public to use on Open Forest
- [x] The team understands where the feedback goes and can easily retrieve the feedback information.

## Tasks
- [x] Identify where in the workflow, a feedback option should be available/present (for Christmas trees, and Special Uses).
- [x] Develop the feedback question(s)
- [x] Mock the feedback tool
- [x] Update the footer of Open Forest to include read "For help or technical questions: SM.FS.OpnFrstCsSup@usda.gov" per the design.
- [x] In the footer remove "General Information 1-800 number" and "For Help or Feedback fs-permitting email".
- [x] Build the feedback tool / Ready for DEV @mtlaney @briandavidson
https://xd.adobe.com/view/a4f7b920-6330-4f2a-6cdc-3a0fcd11a431-d2c6/?fullscreen

- [] Ensure that instructions for users submitting feedback and how it is handled are updated in the wiki here - https://github.com/USDAForestService/fs-open-forest/wiki/2018-Christmas-Tree-Email-Response-Protocol  (Amber will create a new issue for this task move this to a separate story if needed)

- [x] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup

**Comment by ASprinkle** [comment]
See #626 for more background

**Comment by ASprinkle** [comment]
From @DawnDesigner #617:
 
@ASprinkle - Do we need to better understand where in the users journey a feedback tool would work best? I can do some background research and make recommendations to the team. That might help in the decision process.

Where will access to the tool be available for the user
What are we trying to discover through the survey tool? (specific)
Who will manage the responses and report to the team?
What format is more user friendly (multiple choice, commenting etc.

**Comment by lisamcmichael** [comment]
@amber Now that I see what this is, I might be able to take it on.

**Comment by ASprinkle** [comment]
@carlsonem From Melissa "I did not take notes during the meeting. I believe the team decided to work toward a code snippet that used an open ended Q to gather qualitative feedback. IIRC, Eric was going to talk it over with Mike and consider using some of the touchpoints code to simply add in a pop-up, as the MVP."

**Comment by carlsonem** [comment]
Shadat and Eric will explore what code exists today and then send to the design team to produce mock-ups and such.

**Comment by lisamcmichael** [comment]
@carlsonem @lisaredux 
Let me know when to jump into this and help.

**Comment by lisamcmichael** [comment]
@lisaredux I would like to work with you on this. Let me know if that's a concern.

**Comment by lisamcmichael** [comment]
**Version 1 Survey Design - options**
Before we settle on what type of survey approach, we'll decide _what we want to learn._ 

My initial ideas to prime the pump...

**Net Promoter Score**: gauge satisfaction (typically the hallmark measure of success). 
**Upside:** Quick/easy and most likely to be answered
**Downside:** Doesn't indicate what is working well or not 
**Modification:** Include a write-in box for comments (to get more details), must be optional or it will cause frustration

_How likely are you to recommend Open Forest to a friend?_
Response Scale: 1 (Not Likely) ... 5 ... 10 (Very Likely)

Placement: will get back to you on this (based on what we decide to do)

**Survey design options** pinpoint if a "high priority page" is working well or not, or to gauge sentiment, or to recruit for other studies. Response scales would be designed based on the survey/poll. These are in no order of importance.

Option: Did you find what you were looking for?
Option: What brought you to Open Forest?
Option: How did you hear about us?
Option: If you could change one thing about buying a Christmas tree permit, what would it be?
Option: What do you like least/most about Open Forest?
Option: Would you like to participate in a 15-minute user interview about Open Forest? 
Option: How did you hear about Open Forest?
Option: What was your first impression of Open Forest?

**Comment by lisamcmichael** [comment]
@ASprinkle Amber closed #626, on June 11 ( "The team should refer to #626 and program board story 26 for additional background.) What, if anything, do we want to discuss now.

**Comment by lisamcmichael** [comment]
TWO OPTIONS (drafts of course) for collecting feedback from the Public. Again, the idea is to leverage the existing Google Form if possible. 

Where this could go in 2 places depending on the user's behavior, (again, my initial thoughts): 1 - When a site visitor has browsed through all sections, the survey pops up. 2- When a site visitor has completed a purchase, pops up.

![Google Form - OF public input option 1](https://user-images.githubusercontent.com/52501060/63186221-e3d3a000-c029-11e9-9674-24f1ed587fa9.jpg)

![Google Form - OF public input option 2](https://user-images.githubusercontent.com/52501060/63186243-f352e900-c029-11e9-89d1-e1001341af9b.jpg)

**Comment by lisaredux** [comment]
Working on the implementation of the link to initiate feedback — the link would go to either the public feedback form (this story) or the admin feedback form ([776](https://github.com/USDAForestService/fs-open-forest-platform/issues/776)) depending on whether the user is authenticated as an admin or not. 

Possible design solutions to follow.

**Comment by lisamcmichael** [comment]
Met with Matt, Brian and Mike about the form's design. No issues repurposing the Google Form as shown above. _Brian raised questions about the data collection repository - where will the data be stored._  Also, we still need to decide on the tool to create the survey. Will it be a Google form or a internally-made form. Matt thought either could work.

**Comment by carlsonem** [comment]
Google forms will not be an option, keep it stored internally on the servers or Pinyon.

**Comment by lisaredux** [comment]
Public user would click on Give Feedback , presumably in the header, and would be directed to the public specific survey form.
<img width="612" alt="Screenshot 2019-08-19 14 49 46" src="https://user-images.githubusercontent.com/26801590/63290974-97d66480-c290-11e9-9a0c-45ff9a590839.png">

See it linked up here:
https://xd.adobe.com/view/cc48261c-9ad0-4e64-5360-7c815af2ce6a-ba79/screen/a9772821-9ed1-4c33-afb3-a63265521723/Scenario-3-Write-Access-ARP-only-P5-2

**Comment by lisaredux** [comment]
Updating with corrected image for Xmas trees: <img width="612" alt="STORY676" src="https://user-images.githubusercontent.com/26801590/63469604-a3fd2600-c438-11e9-9fc3-da2c9feac5b7.png">

Updating with image/placement for Special uses: 
<img width="639" alt="Screenshot 2019-08-21 17 30 26" src="https://user-images.githubusercontent.com/26801590/63470010-841a3200-c439-11e9-844a-262e5efa9553.png">

[prototype link](https://xd.adobe.com/view/cc48261c-9ad0-4e64-5360-7c815af2ce6a-ba79/screen/a9772821-9ed1-4c33-afb3-a63265521723/STORY-676-PUBLIC)

**Comment by lisaredux** [comment]
Yesterday, @ASprinkle @lisamcmichael and I had a meeting to discuss this and [776 ](https://github.com/USDAForestService/fs-open-forest-platform/issues/776) 

Here is the updated prototype from our discussion https://xd.adobe.com/view/a4f7b920-6330-4f2a-6cdc-3a0fcd11a431-d2c6/?fullscreen

We will be reviewing with DEV today or tomorrow and iterating from that.

**Comment by ASprinkle** [comment]
@lisaredux I noticed the "give feedback" link in the bottom footer.. This will need to be updated to: "For help or technical questions: SM.FS.OpnFrstCsSup@usda.gov"
And we will need to remove the 1-800 phone number, it was not very helpful last year.

**Comment by lisaredux** [comment]
Updated prototype with super-admin feedback screen (in progress) https://xd.adobe.com/view/a4f7b920-6330-4f2a-6cdc-3a0fcd11a431-d2c6/?fullscreen

**Comment by lisamcmichael** [comment]
@lisaredux the only suggestion is to add this under the submit button (Clicking Submit will return you to Open Forest home page) ... or something similar

**Comment by lisaredux** [comment]
> @lisaredux I noticed the "give feedback" link in the bottom footer.. This will need to be updated to: "For help or technical questions: [SM.FS.OpnFrstCsSup@usda.gov](mailto:SM.FS.OpnFrstCsSup@usda.gov)"
> And we will need to remove the 1-800 phone number, it was not very helpful last year.
> 
> Also, in the prototype link above, the Thank you, return to Open Forest Christmas trees link shows it taking the public user to:
> ![image](https://user-images.githubusercontent.com/33435621/64038416-ded41d80-cb0c-11e9-8273-da9cb9b4fb75.png)
> 
> Instead of the Christmas tree home page.

Thanks @ASprinkle - making those updates to the prototype now

**Comment by lisaredux** [comment]
@ASprinkle @lisamcmichael @mtlaney @briandavidson Added this page as the logic to collect and display feedback for super-admin view. Feedback welcome. <img width="451" alt="Screenshot 2019-09-04 13 54 33" src="https://user-images.githubusercontent.com/26801590/64278798-96a56880-cf1b-11e9-9c8b-0f8e15e12391.png">
https://xd.adobe.com/view/a4f7b920-6330-4f2a-6cdc-3a0fcd11a431-d2c6/?fullscreen

**Comment by ASprinkle** [comment]
@lisaredux can you check the link - when I click on it, it appears to only give me the public submit feedback workflow.

**Comment by lisaredux** [comment]
> @lisaredux can you check the link - when I click on it, it appears to only give me the public submit feedback workflow.

Yes, I've updated the connections so it flows from [676 (public)](https://xd.adobe.com/view/a4f7b920-6330-4f2a-6cdc-3a0fcd11a431-d2c6/?fullscreen) to [776 (admin auth)](https://xd.adobe.com/view/a4f7b920-6330-4f2a-6cdc-3a0fcd11a431-d2c6/screen/39a87a68-4b8a-4a72-a183-a1b01066ba6e/STORY-776-INTRO?fullscreen) to where the [feedback goes ](https://xd.adobe.com/view/a4f7b920-6330-4f2a-6cdc-3a0fcd11a431-d2c6/screen/d0efead3-c42b-4411-ab88-621ca3528237/STORY-776-INTRO-1?fullscreen)

**Comment by lisaredux** [comment]
Talked with @ASprinkle and updated the interaction when a user hits submit to go to this screen:

<img width="452" alt="Screenshot 2019-09-04 16 23 36" src="https://user-images.githubusercontent.com/26801590/64288530-5d2b2800-cf30-11e9-86b1-c4d70f60d487.png">

https://xd.adobe.com/view/a4f7b920-6330-4f2a-6cdc-3a0fcd11a431-d2c6/?fullscreen

**Comment by lisaredux** [comment]
Ready for DEV @mtlaney @briandavidson 
https://xd.adobe.com/view/a4f7b920-6330-4f2a-6cdc-3a0fcd11a431-d2c6/?fullscreen

**Comment by lisaredux** [comment]
> @lisaredux I noticed the "give feedback" link in the bottom footer.. This will need to be updated to: "For help or technical questions: [SM.FS.OpnFrstCsSup@usda.gov](mailto:SM.FS.OpnFrstCsSup@usda.gov)"
> And we will need to remove the 1-800 phone number, it was not very helpful last year.
> 
Also, @ASprinkle @mtlaney @briandavidson the update in the footer is addressed on this page: https://xd.adobe.com/view/a4f7b920-6330-4f2a-6cdc-3a0fcd11a431-d2c6/screen/9a6f0e73-1cf3-4086-91e5-e2cd3911e239/Scenario-3-Write-Access-ARP-only-P5-2/?fullscreen

<img width="597" alt="Screenshot 2019-09-05 10 16 33" src="https://user-images.githubusercontent.com/26801590/64350237-57802180-cfc6-11e9-8739-143ea3d8a458.png">

**Comment by ASprinkle** [comment]
Moving to Ready - removing the Lisas from the assignee list.

**Comment by lisamcmichael** [comment]
@ASprinkle and @lisaredux - I removed "Usability tested" based on the decision that we will launch the survey, and monitor the frequency and number of comments left by the public. If it's low, then we'll reassess our decision to run some form of user testing.

**Comment by ASprinkle** [comment]
Hi @briandavidson for this story and the FS admin one... is the "Give Feedback" link being developed so that it is only available on the landing page? or will it be available in the upper right corner of very page throughout the process? Preference would be every page, unless that is too big to bite off at this time, in prep for Nov. 1 MVP.

**Comment by ASprinkle** [comment]
@briandavidson I see this story in Awaiting Acceptance, but I when I check staging, I do not see anything. I will check again tomorrow morning. Thanks

**Comment by mtlaney** [comment]
@briandavidson 
- [ ] Public user should only see share your feedback, no need for forest selection
- [ ] Change text to read 'We'd like to know how we can improve this permit experience for you'
- [ ] Add Return Home button
- [ ] Thank you for sharing your feedback on success
- [ ] Add max char limit
- [ ] Look into adding line break on admin view feedback.

**Comment by ASprinkle** [comment]
Text changes, return home button, thank you banner apply to both public and admin workflows.

**Comment by briandavidson** [comment]
Thanks @ASprinkle and @mtlaney, I'll get to work on this right away - apologies for missing the meeting regarding these changes earlier, I was feeling 🤢

@ericsorenson - I concur with your estimate from earlier. Mike and I will be able to have these changes fixed by EOW.

**Comment by ASprinkle** [comment]
@carlsonem ^^

**Comment by ASprinkle** [comment]
@briandavidson for the public user feedback tool, can we please remove the "let us know which forests" header and text window? leaving only the "Please share your feedback here:" header and text window.

The thank you for sharing your feedback banner works really well! 
![image](https://user-images.githubusercontent.com/33435621/67815647-bf9e3180-fa64-11e9-9c07-f1255e3a323a.png)

**Comment by ASprinkle** [comment]
![image](https://user-images.githubusercontent.com/33435621/67882629-c75ee400-faff-11e9-8d98-6e7bedfc7bf2.png)

Awesome!!
