### ISSUE TITLE
As an Open Forest platform administrator I want to research what is needed for adding and removing other administrators so that I can begin to develop an easy to use admin management system.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#677]
## Notes
What are things we should consider when making this story 

*This story would help us gain an understanding of what may be needed when working to develop the ability for a Super Admin/"Platform Admin" to add or remove other administrators, with the first step being to complete research that would inform a workflow.

## Acceptance Criteria
- [x] We have a workflow that has been researched, and is ready to be developed.
- [x] We know who the super admins would be.
- [x] We know what kinds of admin management systems exist.

## Tasks
- [ ] Identify method to research the workflow.
- [ ] Identify what questions would be necessary to guide the research.
- [x] Identify what admin management systems already exist that could be integrated.
- [x] Identify who the super admins would be.
- [x] Research workflow
- [ ] PO Approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
Story #689 addresses the goals of this story.

**Comment by ASprinkle** [comment]
Super Admins: Amber and Aaron and Open Forest team

**Comment by lisamcmichael** [comment]
@ASprinkle @lisaredux  Just wondering if this story seems is resolved by #689, and possibly the research-related one #855.

**Comment by ASprinkle** [comment]
This one is "Platform" related, and so would apply to the Special Uses side as well. We'll keep it in the backlog for now - low priority at the moment

**Comment by lisamcmichael** [comment]
@ASprinkle Given the new changes to user administration, will this story be relevant for the platform? Or, just need revising as some point?

**Comment by ASprinkle** [comment]
I think we can close this story all together given the ICAM Spike #922 . thanks for catching this! @lisamcmichael
