### ISSUE TITLE
As an Open Forest platform administrator I want to build a workflow for adding and removing other administrators so that I can begin to develop an easy to use admin management system

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#678]
## Notes
What are things we should consider when making this story :

This story would help us gain an understanding of what may be needed when working to develop the ability for a Super Admin to add or remove other administrators. with the second step being to build a workflow based on research completed (#677).

## Acceptance Criteria
- [ ] We have an understanding of what the next steps are to build the platform administrator function into Open Forest.
- [ ] We have an understanding of what the role of the platform administrator might be.
- [ ] We have an understanding of what levels (i.e., District, Forest, Region, and/or Open Forest) of administrators the platform administrator would control.
- [ ] We know whether or not more administrator functions would be necessary.
- [ ] We have an understanding of where authentication points may be needed.
- [ ] We have an understanding of whether or not we want an existing admin management system to be integrated with Open Forest.

## Tasks
- [ ] Build workflow based on research
- [ ] Review/present workflow with team
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
Super Admins: Amber and Aaron and Open Forest team
This story is connected to the work on the Christmas tree side of Open Forest story #689

**Comment by lisamcmichael** [comment]
#922
