### ISSUE TITLE
As an SU applicant I want my application successfully transferred to SUDS without replacing or duplicating existing SUDS customer data so that I have a successful experience.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#679]
## Notes

If this is not a duplicate of program board story 13 ( https://code.fs.usda.gov/NFS/Open-Forest-Program/issues/13#issue-16706 ) then we can refine this more to ensure we capture the work we need to do.
Reference platform board SPIKE 601 ( https://github.com/18F/fs-open-forest-platform/issues/601#issue-432684661 )

## Acceptance Criteria
- [x] We have a better understanding of our next steps regarding similar customer contact information transfer from Open Forest to SUDS.
- [] Customers information successfully transfers from Open Forest into SUDS without deleting data.

## Tasks
- [x] Coordinate with NRM to reuse existing connectivity for integration, including API 
- [x] Coordinate with NRM to understand overwriting existing data in NRM
- [x] Coordinate with NRM regarding data integration/update
- [x] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by carlsonem** [comment]
@smahmudFS @mwreiss please refine

**Comment by carlsonem** [comment]
@smahmudFS please add tasks

**Comment by smahmudFS** [comment]
Added tasks

**Comment by mwreiss** [comment]
Thanks @smahmudFS , I will assign it to us and move it to in progress.

**Comment by smahmudFS** [comment]
We are meeting with Mark Awad and Xin on 11/20 to discuss

**Comment by smahmudFS** [comment]
## Notes
It looks like we **OF** flows for when the contact is a "person" or an "organization". The difference is the contact id for an organization is the organization name, whereas for a person it is `lastname,firstname`.

## Findings
- The current flow is the following:
  - **OF** queries **SUDS** contacts by last name
  - **OF** filters the **SUDS** contacts by contact id
  - If there are no matches, **OF** sends to **SUDS**
    - contact 
    - contact address
    - contact phone
  - If there are multiple matches **OF** throws an error
  - If there is a single match, **OF** sends to **SUDS** the application
- I think that we are generating the contact id and sending it to **SUDS** when creating a contact

## Questions

- Is it possible that the contact control number is the unique identifier that **SUDS** uses to identify a contact?
- Are there legacy requirements that drove these decisions? Ex. are we trying to leverage contacts (people and organizations) that are already exist in SUDS instead of creating new ones for **OF**?
- Are there any character restrictions in play that would prevent us from using email address as the contact id for a person? (organization name is probably fine for organizations)

**Comment by ASprinkle** [comment]
We know that the contacts module in SUDS is an issue.  We can follow up with SUDS moderination team for the SUDS redesign considerations. We know going into the pilot that there are risks associated with contact information overriding other matching  contacts.  We will communicate this to the MBS, so that expectations are clear.

**Comment by ASprinkle** [comment]
Potential issue RE over write existing SUDS information. 
Potential issue RE FMMI customer code if customer information is over written for future permit types.
