### ISSUE TITLE
As an FS admin on a forest I want a code added to POSS so that Open Forest transactions for my Forest can be sent to the right location.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#686]
## Notes
* What are things we should consider when making this story *

Current pilot forests have POSS item numbers associated with them in POSS. Any new forests added to Open Forest will need to be verified appropriately in POSS so that Open Forest financial transactions from Pay.gov can be processed through POSS and then sent to FMMI for forest reconciliation and reporting.

## Acceptance Criteria
- [x] We have open forest codes for new forests
- [x] We can have a way of testing it to know that it works (funds are automatically allocated to the appropriate areas 5% to Region, 95% to Forests).

## Tasks
- [x] Reach to CFO to get an understand of the process.
- [x] Obtain new codes.
- [x] Develop a user test case scenario so that we have an understanding of what we're testing.
- [x] Implement new codes into Open Forest system.
- [x] We have confirmed (With Jamin Bhatt, Robin Key, and Daniel Cha) that validation tests show transactions in staging are working.
- [x] PO approved.

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
POSS codes for current pilot forests:
Christmas Tree Permit - Arapaho and Roosevelt National Forests - $20 - 999900004
Christmas Tree Permit - Flathead National Forest - $5 - 999900005
Christmas Tree Permit - Shoshone National Forest - $8 - 999900006
Christmas Tree Permit - Mt. Hood National Forest - $5 – 999900007

**Comment by ASprinkle** [comment]
Email from July 3 from Jaimin Bhatt:

Here are the item numbers. We just assigned them sequentially from where we stopped with the 4 forests in the initial pilot.

•	Deschutes National Forest - 999900008
•	Rogue River-Siskiyou National Forest - 999900009
•	Mt. Baker/Snoqualmie National Forest - 999900010
•	Okanogan-Wenatchee National Forest - 999900011
•	Willamette National Forest - 999900012
•	Umatilla National Forest - 999900013
•	Gifford Pinchot National Forest - 999900014
•	Fremont-Winema National Forest – 999900015

Todd, please provide us the proper accounting to setup these items in POSS. 


Thanks,

**Comment by ASprinkle** [comment]
@carlsonem what are the next steps to completing the other tasks for the A/C?

**Comment by ASprinkle** [comment]
Update from stand up. Shadat coordinated within CIO team to set up web service POSS architecture so that we can consume reporting information. Daniel and Jamin are working on the accounting piece of the process. Eric and Shadat are working on this.

**Comment by carlsonem** [comment]
Moving this to the backlog, as it won't be able to be completed until the pages are developed.

The setup of item accounting needs to be done in POSS and does not take that long. Are you guys ready with the code changes in Open Forest to add the new forests and send the necessary response to pay.gov to complete a transaction? If your development for Open Forest is complete in your DEV environment, you can do some test transactions in Pay.gov QA and we will download the file. At that point, we can add the accounting information in POSS and import/process the collection activity file.

[‎7/‎19/‎2019 10:00 AM] Carlson, Eric - FS: 
Got it

We are still developing the pages for the new forests, so sounds like we need to get that part done first  

[‎7/‎19/‎2019 10:01 AM] Bhatt, Jaimin - FS: 
yep!

[‎7/‎19/‎2019 10:02 AM] Carlson, Eric - FS: 
There are going to be 8 new forests, so is it best to wait until they are all done and contact you again?
Or connect them as they are completed. Seems like the former is prob better

[‎7/‎19/‎2019 10:03 AM] Bhatt, Jaimin - FS: 
the integration between open forest and POSS is dependent on pay.gov. Your application integrates with pay.gov to call up the payment form and performs the transaction. POSS integrations with pay.gov to download the completed transaction data and processes it through POSS to send it over to FMMI.
Depending on how you guys plan to go live, we are flexible to do either one at a time or all together. I would also recommend all at once if that fits your needs.

[‎7/‎19/‎2019 10:04 AM] Carlson, Eric - FS: 
ok, thanks!

**Comment by ASprinkle** [comment]
@lisamcmichael the result of the meeting wasn't as helpful as I anticipated.  I have reached out to Dawn Heutte to see what her expectation is to be able to verify that the funds are being appropriately deposited during this season's pilot.

**Comment by carlsonem** [comment]
@carlsonem needs to reach-out to CFO

**Comment by ASprinkle** [comment]
Regarding adding the Ochoco item, once the item is created, it will get the following accounting:
Transaction type: MP
Revenue Source: 105

•	Ochoco National Forest – **Item Number TBD**
o	5% FDDS36 0627, 95% FDDS36 0607

**Comment by lisamcmichael** [comment]
I am back online @carlsonem, and wasn't sure if I needed to be updated on this. Thx.

**Comment by ASprinkle** [comment]
From Todd Harbin: Regarding adding the Ochoco item, once the item is created, it will get the following accounting:
Transaction type: MP
Revenue Source: 105

• Ochoco National Forest – Item Number TBD
o 5% FDDS36 0627, 95% FDDS36 0607

**Comment by ASprinkle** [comment]
Some background from the Region 6 Budget Officer perspective: 
"No I don’t need any remedial system interface testing as long as the software function has not changed.

Thanks for let me know about the change.  It easier for the collection officers to be Recreation Fee only, and simplifies the audits.  This contentment is based, as well,  on two assumptions:
Krystal Fleeger’s Christmas tree program memo has been updated to include the Ochoco NF and 
Dana Croll, TIM coordinator is working with the staff to destroy the inventory of TIM manual permits for Christmas trees at the Ochoco, as well as the other Open Forest participants."

**Comment by carlsonem** [comment]
@mtlaney @briandavidson 
Happen to know how this is done? Do we need to do a switch to the code to be able to make the payments to this test site?

From the CFO staff...

"Please go ahead and do some test transactions for the new permits against qa.pay.gov and let us know the date on which they we done and details about the transactions.

We’ll download the collection activity from pay.gov QA and process it. Will let you know how things go."

**Comment by ASprinkle** [comment]
@carlsonem @mtlaney @briandavidson I went in to grab some reports on permits that have been issued through the staging site, in hopes that you might be able to back track some of the info. It looks like there are only 5 forests that have the Generate Reports feature working in staging: MTH, FLT, ARP, SHO, MBS.  All other forests show: 
![image](https://user-images.githubusercontent.com/33435621/64733833-5190b180-d49a-11e9-8e28-38af7cf6eda7.png)

I created a new story at the top of the backlog to address this issue...

**Comment by carlsonem** [comment]
@ASprinkle is there test credit card information I can use for generating a permit for the various forests? Or can I just makeup a random credit card number, address and so on?

**Comment by ASprinkle** [comment]
@carlsonem YES! the test credit card number that I have been using is 4111111111111111 (that's a 4 followed by 15 "1").  i use any expiration date in the future and any 3 digit set of number for the CVB code

**Comment by ASprinkle** [comment]
I just did one for the Gifford Pinchot NF yesterday during the sprint review demo... :)

**Comment by ASprinkle** [comment]
@carlsonem 
I also have received emails from test permits for the following.. going back to mid-july:

Gifford Pinchot (9/12) $15.00
Arapaho Roosevelt (9/12) $40.00
Umatilla (9/10) $5.00
Mt. Hood (9/5) $10.00
Deschutes (8/21) $5.00
Deschutes (8/21) $10.00
Okanogan-Wenatchee (8/21) $10.00
Okanogan-Wenatchee (8/21) $20.00
Gifford Pinchot (8/7) $15.00
Okanogan-Wenatchee (8/2) $10.00
Willamette (8/2) $10.00
Fremont Winema (7/26) $15.00
Gifford Pinchot (7/24) $25.00
Mt. Hood (7/16) 20.00
Shoshone (7/16) $24.00
Arapaho-Roosevelt (7/12) $40.00

**Comment by carlsonem** [comment]
Test transactions from staging
[Open Forest Transaction Testing.xlsx](https://github.com/USDAForestService/fs-open-forest-platform/files/3616809/Open.Forest.Transaction.Testing.xlsx)

**Comment by ASprinkle** [comment]
9/16 Eric emailed Jamin Bhatt, Robin Key, and Daniel Cha requesting to validate test permits from the staging site. This story is blocked until we hear back from them.

**Comment by carlsonem** [comment]
Here is how the transactions you did for open forest will roll up to FMMI. If we need to send this to FMMI in DEV, let me know. We’ll have to coordinate it with them before we post the file. The amounts on these lines should match up to your total amounts and based on the items sold, they are distributed to the appropriate job codes and rruu’s.

LX0110      P0120A906478D   NPOSSUSERLXP0120A9064780110               E      203020                      14.25               191002                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         POS1
LX0110      P0120A906478L001NPOSSUSER001          01100110              0105           FDDS3620        FS COLLECT           14.25I MP                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       POS1
LX0156      P0120A906479D   NPOSSUSERLXP0120A9064790156               E      203020                        .75               191002                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         POS1
LX0156      P0120A906479L001NPOSSUSER001          01560156              0105           FDAS3620        FS COLLECT             .75I MP                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       POS1
LX0210      P0220A906480D   NPOSSUSERLXP0220A9064800210               E      203020                      19.00               191002                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         POS1
LX0210      P0220A906480L001NPOSSUSER001          02100210              0105           FDDS3620        FS COLLECT           19.00I MP                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       POS1
LX0214      P0220A906481D   NPOSSUSERLXP0220A9064810214               E      203020                      22.80               191002                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         POS1
LX0214      P0220A906481L001NPOSSUSER001          02140214              0105           FDDS3620        FS COLLECT           22.80I MP                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       POS1
LX0216      P0220A906482D   NPOSSUSERLXP0220A9064820216               E      203020                       2.20               191002                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         POS1
LX0216      P0220A906482L001NPOSSUSER001          02160216              0105           FDAS3620        FS COLLECT            2.20I MP                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       POS1
LX0601      P0620A906483D   NPOSSUSERLXP0620A9064830601               E      203020                       9.50               191002                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         POS1
LX0601      P0620A906483L001NPOSSUSER001          06010601              0105           FDDS3620        FS COLLECT            9.50I MP                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       POS1
LX0602      P0620A906484D   NPOSSUSERLXP0620A9064840602               E      203020                      19.00               191002                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         POS1
LX0602      P0620A906484L001NPOSSUSER001          06020602              0105           FDDS3620        FS COLLECT           19.00I MP                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       POS1
LX0603      P0620A906485D   NPOSSUSERLXP0620A9064850603               E      203020                       9.50               191002                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         POS1
LX0603      P0620A906485L001NPOSSUSER001          06030603              0105           FDDS3620        FS COLLECT            9.50I MP                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       POS1
LX0605      P0620A906486D   NPOSSUSERLXP0620A9064860605               E      203020                      19.00               191002                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         POS1
LX0605      P0620A906486L001NPOSSUSER001          06050605              0105           FDDS3620        FS COLLECT           19.00I MP                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       POS1
LX0606      P0620A906487D   NPOSSUSERLXP0620A9064870606               E      203020                       4.75               191002                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         POS1
LX0606      P0620A906487L001NPOSSUSER001          06060606              0105           FDDS3620        FS COLLECT            4.75I MP                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       POS1
LX0610      P0620A906488D   NPOSSUSERLXP0620A9064880610               E      203020                      19.00               191002                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         POS1
LX0610      P0620A906488L001NPOSSUSER001          06100610              0105           FDDS3620        FS COLLECT           19.00I MP                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       POS1
LX0614      P0620A906489D   NPOSSUSERLXP0620A9064890614               E      203020                       4.75               191002                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         POS1
LX0614      P0620A906489L001NPOSSUSER001          06140614              0105           FDDS3620        FS COLLECT            4.75I MP                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       POS1
LX0617      P0620A906490D   NPOSSUSERLXP0620A9064900617               E      203020                       9.50               191002                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         POS1
LX0617      P0620A906490L001NPOSSUSER001          06170617              0105           FDDS3620        FS COLLECT            9.50I MP                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       POS1
LX0618      P0620A906491D   NPOSSUSERLXP0620A9064910618               E      203020                       4.75               191002                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         POS1
LX0618      P0620A906491L001NPOSSUSER001          06180618              0105           FDDS3620        FS COLLECT            4.75I MP                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       POS1
LX0627      P0620A906492D   NPOSSUSERLXP0620A9064920627               E      203020                       5.25               191002                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         POS1
LX0627      P0620A906492L001NPOSSUSER001          06270627              0105           FDAS3620        FS COLLECT             .25I MP                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       POS1
LX0627      P0620A906492L002NPOSSUSER002          06270627              0105           FDDS3620        FS COLLECT            5.00I MP

**Comment by ASprinkle** [comment]
We were not able to confirm the 95/5 split in staging. Need to test that with real money
