### ISSUE TITLE
As an FS admin I want to see my forest as an option for selection on the Open Forest Christmas tree landing page so that our customers can buy Christmas tree permits online.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#688]
## Notes
* What are things we should consider when making this story *

Add the forest name to the selection drop down following the existing schema.

## Acceptance Criteria
- [x] The forest name is added to the drop down in an organized way (alphabetically by forest name, or by state, or by some other organization)
- [x] The forest name can be selected, and the user directed to the informational page for that forest. (initial page has a site being built message)

## Forest Names added
- [x] Deschutes National Forest
- [x] Gifford Pinchot National Forest
- [x] Fremont-Winema National Forest
- [x] Mt. Baker-Snoqualmie National Forest
- [x] Okanogan-Wenatchee National Forest
- [x] Rogue River-Siskiyou National Forest
- [x] Umatilla National Forest
- [x] Willamette National Forest

## Tasks
- [x] Mock drop down
- [x] Add the forest name 
- [x] Make sure the user is routed correctly
- [x] PO approved

## Definition of Done
- [x] Pull requests meet technical definition of done
- [x] Compare finished design with mockup
- [x] Usability tested

**Comment by ASprinkle** [comment]
From refinement: We can anticipate a user story regarding a "long list" of items in the drop down, resulting in a need for design work to improve that experience in the future. For the time being, focusing on MVP, we will maintain the existing list structure.

**Comment by lisaredux** [comment]
Basic structure so far...

currently 4 forests in dropdown: 

Flathead | Montana
Arapaho & Roosevelt | Colorado
Mt. Hood | Oregon
Shoshone | Wyoming

https://open-forest-staging.app.cloud.gov/christmas-trees/forests
<img width="374" alt="Screenshot 2019-06-24 14 15 06" src="https://user-images.githubusercontent.com/26801590/60041935-8145cf80-968a-11e9-84a4-c907c95a875d.png">

Add 8 forests: 
Deschutes National Forest
Rogue River-Siskiyou National Forest
Mt. Baker/Snoqualmie National Forest
Okanogan-Wenatchee National Forest
Willamette National Forest
Umatilla National Forest
Gifford Pinchot National Forest
Fremont-Winema National Forest

@aaronburk - can you validate this this list above correct? I pulled it from Teams lists

**Comment by lisaredux** [comment]
@ASprinkle Here's what 12 forests lists would look like in one dropdown. I think both could work, although I prefer and recommend the list by state, so that if a customer doesn't see a forest under the state, they know it's not included in the list. Curious to hear your feedback for passing this onto development. 

**ALPHABETICAL LIST:** 

Arapaho & Roosevelt | Colorado
Deschutes I Oregon
Flathead | Montana
Fremont-Winema  I Oregon
Gifford Pinchot I Washington
Mt. Baker-Snoqualmie | Washington
Mt. Hood | Oregon
Okanogan-Wenatchee I Washington
Rogue River-Siskiyou I Oregon
Shoshone | Wyoming
Umatilla  I Washington
Willamette  I Oregon

-----OR-----

**LIST BY STATE:**

**COLORADO**
  Arapaho & Roosevelt 
**MONTANA**
  Flathead 
**OREGON**
  Deschutes 
  Fremont-Winema 
  Mt. Hood 
  Rogue River-Siskiyou
  Willamette  
**WASHINGTON** 
  Gifford Pinchot 
  Mt. Baker-Snoqualmie 
  Okanogan-Wenatchee
  Umatilla 
**WYOMING**
  Shoshone

**Comment by carlsonem** [comment]
Ready for development

**Comment by ASprinkle** [comment]
@lisaredux @carlsonem for MVP the Alphabetical list will do. We can find out more with future testing.  Confirmed, ready for Dev to take on to ensure Forests are listed alphabetically

**Comment by carlsonem** [comment]
As a note, this issue is well underway. As pages are being created, Mike/Brian and adding to the list.

**Comment by ASprinkle** [comment]
Excellent work on this!! @mtlaney @briandavidson @lisaredux
