### ISSUE TITLE
As an Open Forest team member, I want to be able to manage admin roles so that admin functions can be performed.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#689]
## Notes
* What are things we should consider when making this story *

Currently admins are white listed in the applications.  This is not a long term solution.
We should have an understanding of what the admin roles are, what their functions are, and how admins can be best managed. Researching how our admin management can tie into existing systems is important to determining longer term solutions.

When we scale up and add a new forest, we need to add an admin for that forest so that they can generate reports, change season dates, and update cutting area dates (if an applicable function/need for that forest).

https://fsapps.fs.usda.gov/fsapps/index.jsp
Production Admin Site: https://openforest.fs.usda.gov/admin/christmas-trees/reports
Staging Admin Site https://open-forest-staging.app.cloud.gov/admin/christmas-trees/

## Acceptance Criteria
- [x] We understand how admins will be manged
- [ ] We have the information documented in a location that team can access
- [ ] The Open Forest team (Super Admins) have an easy way to add/remove admins without having to change code/white list.
- [x] We know who the admins will be for which pilot forest(s).
- [] admins having access to their pilot forests will be addressed in a separate story

## Tasks
- [x] Obtain a list of admins by pilot Forests
- [x] Define the roles (i.e., super admin - someone who gives roles, admin - someone who uses roles)
- [x] Define entry points (i.e., log-in process (eAuth), how they find the page to get to admin functions).
- [x] Research existing solutions/systems for managing admins
- [x] Define solution to manage roles with role based access
- [x] Mock the admin user management workflow
- [ ] Implement search functionality as type-ahead
- [ ] Build the admin page
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Define solution to manage roles with role based access
- [ ] Usability tested with (up to) 10 forest team members

**Comment by ASprinkle** [comment]
Should cover #667 regarding Eauth Level 2 Access.

**Comment by carlsonem** [comment]
@ASprinkle are you good with moving forward with integrating the admin side of the application with FS Apps? Much of that work is actually done by the FS Apps team, which I'll start engaging if you are good with this approach. This will help align the application with FS Standards and help with security issues. I'll create a new card if we are good with that.

**Comment by carlsonem** [comment]
![User Management](https://user-images.githubusercontent.com/13070243/61957091-74b7de00-af8c-11e9-870a-0f28c793f931.png)

Here's an example screen from the AAR application we use for managing users. We can certainly use this code as a starting point for this application if we want.

**Comment by carlsonem** [comment]
![registratin form](https://user-images.githubusercontent.com/13070243/61957702-d75da980-af8d-11e9-8b4f-d88b4a1e8b7b.png)

Don't love the look of this actual form...but it provides an example of how we might want this application to work. This is the screen that appears to a user on the IBS system if they login to the application but haven't been assigned a role. The user completes this form, it's sent to the CFO security folks and they are added to the application based on their role approved for. Going forward, the system automatically reads their eAuth credentials and displays the  pages/content they should have access to based on their role.

**Comment by carlsonem** [comment]
[Open Forest Admin Login Path.pptx](https://github.com/18F/fs-open-forest-platform/files/3436219/Open.Forest.Admin.Login.Path.pptx)

My quick and dirty workflow of how I see this working

**Comment by lisamcmichael** [comment]
@carlsonem 

The "list of admins by pilot Forests" is checked off. Could I have that list? I'll start outlining/organizing content requirements (a rough draft). 

Question - will this be a "responsive" design? I ask because Open Forest is responsive.

**Comment by ASprinkle** [comment]
Hi @lisamcmichael I do not know that "responsive design" means... I'll leave that to Eric... Here is the list of Admins for the new Pilot Forests:
There are two pages in the attached doc. 
[Open Forest 2019 Admins Story 689.docx](https://github.com/18F/fs-open-forest-platform/files/3436536/Open.Forest.2019.Admins.Story.689.docx)

**Comment by ASprinkle** [comment]
@carlsonem I am good with what is easy RE FSapps. If this becomes an issue, we don't need it for MVP. for this season. Admins can access it direct with a link provided to them. It's worth creating a card for!

**Comment by carlsonem** [comment]
@lisamcmichael as a note, the specific issues of adding the actual admins to the application is issue #749.

@ASprinkle All "responsive design" means is a fancy way of saying the application is functional on a desktop, tablet or mobile device. Yes, we will want to make this module a responsive design as well.

**Comment by carlsonem** [comment]
@ASprinkle Sounds good and fully agree on the MVP part. In the short term, we should simply white-list the users similar to the pilot forests. That can be done anytime. Most of the FSApps work will actually be on that team, not ours, so I'll engage them to give them a heads-up to add us to their backlog. I've created a card to start tracking that work.

**Comment by lisamcmichael** [comment]
@carlsonem @lisaredux @ASprinkle  Here is a start at organizing information needed to fulfill this story. Lisa - I am around today to meet and discuss. ![Story 689.jpg](https://images.zenhubusercontent.com/5d24da694b6f4e0ca39d8303/cd3f12c6-bba4-4db2-8e0b-25543c99b23c)

**Comment by lisaredux** [comment]
Posting screenshots along with screencapture of accessing admin view of Xmas trees [](https://open-forest-staging.app.cloud.gov/admin/christmas-trees/ )

<img width="902" alt="Screenshot 2019-07-29 12 35 46" src="https://user-images.githubusercontent.com/26801590/62068310-d2099480-b203-11e9-82ed-4b42086fc69e.png">
<img width="837" alt="Screenshot 2019-07-29 12 46 23" src="https://user-images.githubusercontent.com/26801590/62068369-ddf55680-b203-11e9-93b9-b9355e44d6c7.png">

[Screen Recording 2019-07-29 at 12.38.57 PM.zip](https://github.com/18F/fs-open-forest-platform/files/3443533/Screen.Recording.2019-07-29.at.12.38.57.PM.zip)

**Comment by lisamcmichael** [comment]
Thanks Lisa. @carlsonem I'd like to share the roles and access definitions I've created so far. Could you find 30 minutes to meet and  include Amber and Lisa S.? Thx.

**Comment by lisamcmichael** [comment]
Sent Lisa S. multiple screenshots of user role management components

**Comment by lisaredux** [comment]
@ASprinkle @carlsonem @lisamcmichael Here's [the prototype](https://adobeid-na1.services.adobe.com/ims/jump/eyJraWQiOiJLMjAxNiIsImFsZyI6IlJTMjU2In0.eyJqdGkiOiIxNTY0Njg2MzI4NTIxXzAyODE3ZjU5LTQ3NWEtNDBiYy1iYzVlLWUwNTU2Nzg2YzJjNl91ZTEiLCJjaWQiOiJDb21ldFdlYjEiLCJ1aWQiOiIyMzI0MzVFNDVBODIzQTI0MEE0OTVFOERAQWRvYmVJRCIsInJ1IjoiaHR0cHM6Ly94ZC5hZG9iZS5jb20vdmlldy81ZmUyOWQwZi0zNzhiLTRiZjktNjQ3YS0xNTE4NGRkODk5YzUtMjlkMy8iLCJydCI6InRva2VuIiwiY2UiOiJBVXZjRDEtYW83aXlqZURUUUFTVTNOclBkaFE0d0JHMkJqOGRPTEk4WFZ2M0hiMXBnS3lrVnJYeEJfWDRodVM0d0RQVlREeVZGTXJRVGtxT0VETHlhRnZvb09rM1l2ekZFRU4weEdZel9Hd2I4QSIsImV4cCI6MTU2NDY4NzIyODUyMSwicmYiOiJUVVVWRUpKN1hMUDc3WFdXSzRSMk8yQUFTRT09PT09PSIsImlzcyI6Imh0dHBzOi8vaW1zLW5hMS5hZG9iZWxvZ2luLmNvbSJ9.oe7DTyJiENTm97YeGlkB6CdJO7XQkqr6RKiGTsTHBTa69wSCaou2gtJkTHuSK2ORUz-4eMYtXj0DhRPgwDpRJAkalXZxNpekea4H7HiOEFnpBcKjAH_HzwQwjHLpHPd-6qkllv7unLDqpRgMhrZQCVFG5d-mmn1L7RnJHLk9sAB0SFI-vECudcPuJfuCYTA7rrWxg3xZ0y4_WFtnmoEzabjrJCnkn2UeA-dPlIwASMgP9aYU76HgriTvfChLg-X-2MGW-tnKCYjN_0O3kPRc1fUIe3ZiwN3W__F2OShTMl6_1J7ZXXlrwTedOkXubkZBQDrCh8pLP4I9mQZ3thnn6A) in progress to show 3 different possible views of accounts:

1) write-access, all forests
2) read-access only
2) write access, ARP only

From here, I'll create the super-admin side UI variations, schedule a meeting to discuss, and show to larger team for feedback. Feel free to make comments directly in the prototype. And let me know if you have questions about it in the meantime.

**Comment by lisamcmichael** [comment]
Hi Lisa – thx for sending this. I cannot access them w/out a password.



[cid:image001.png@01D5491D.8D1BB460]

**Comment by lisaredux** [comment]
> Hi Lisa – thx for sending this. I cannot access them w/out a password. [cid:image001.png@01D5491D.8D1BB460] 

Thanks for letting me know. I must've fat-fingered the link... updated in the comment, and here is the correct one for easy reference  https://xd.adobe.com/view/5fe29d0f-378b-4bf9-647a-15184dd899c5-29d3/

**Comment by carlsonem** [comment]
@lisamcmichael @lisaredux Do you have the mock-up of the actual user management screen? That is what we need so we can have the developers build the page.

**Comment by lisamcmichael** [comment]
I know that @lisaredux was working on it (that's my understanding).

**Comment by lisaredux** [comment]
> @lisamcmichael @lisaredux Do you have the mock-up of the actual user management screen? That is what we need so we can have the developers build the page.

@carlsonem Yes, I'm working on it now. We can discuss options and variations in the 4p meeting, ideally

**Comment by lisaredux** [comment]
Updated with Manage users tab and screens: 
https://xd.adobe.com/view/75009daa-4faa-461c-6030-958c50432030-0331/ 
(tweaking in progress, though feel free to comment)

**Comment by lisaredux** [comment]
@ASprinkle @carlsonem @lisamcmichael The developers and I used standup to discuss the viability of the current workflow of Manage Users for this story:
https://xd.adobe.com/view/75009daa-4faa-461c-6030-958c50432030-0331/screen/2a05e423-842a-4ba6-91a5-09982fb146ce/Manage-Users?fullscreen

<img width="254" alt="Screenshot 2019-08-08 14 53 41" src="https://user-images.githubusercontent.com/26801590/62729627-57532d00-b9ec-11e9-8b69-acd8b402734f.png">

<img width="588" alt="Screenshot 2019-08-08 14 36 50" src="https://user-images.githubusercontent.com/26801590/62728718-7650bf80-b9ea-11e9-93de-5865c4255590.png">

1) DEV confirmed that all three inputs: 1-firstname, 2-lastname, 3-email address are required in this first version, so I will update the prototype accordingly

2) DEV also confirmed that adding modals to Open Forest framework will not be an easy task, so I will design the "add" and "edit" functions under Manage Users in a regular page structure instead of modals.

3) DEV also confirmed that disabling or hiding options to users are the same level of difficulty, so either way is TBD but I will design for the disabled version in the tabs as well.

4) There are currently no styles for pagination in Open Forest. We may need to add an issue to design for that, or else just leave it will an unpaginated table until post-MVP

5) Adding the search bar functionality is not difficulty, but also might be unnecessary in this first version

Now I will make updates to the current prototype with all the above notes and to demonstrate the variable user access.

**Comment by ASprinkle** [comment]
@lisaredux Wow, that is great progress on this story! The design looks like a great start from what we coordinated on last week.

@carlsonem @aaronburk A question came to my mind as I was reviewing this.  As we build in admin/user management into Open Forest... do we have the Privacy Impact Assessment set up to address this? Are admin related Name and Email address being entered into Open Forest for User Management in a way that is retrievable? Just checking to make sure we are not being inconsistent with our security protocols related to PII as we build this system.
If we don't have appropriate measures set up to store admin PII in Open Forest this way, then at least we can have a solid design to start from.

**Comment by lisamcmichael** [comment]
@lisaredux Agree, looking good!  My 2-cents: for #4 (pagination), it makes sense to track it somehow if it's post MVP. About #5 (search), I'm advocating it be added in the MVP.

**Comment by lisaredux** [comment]
Updates and forthcoming updates in this prototype link: https://xd.adobe.com/view/4ae695d5-b6c4-493a-4ea9-c372dc077062-3cd7/?fullscreen

Main updates so far:
1) updated Add user criteria to have firstname, lastname, AND email

2) Adding _manage-access_ as a value

**Comment by carlsonem** [comment]
@ASprinkle I'll confirm with Jon, but I'm almost certain there is no PII concern entering an email/name. As a side note, the name and email will be stored in the system, but it's only for internal forest service staff, not the general public.

**Comment by lisaredux** [comment]
Updated prototype:
https://xd.adobe.com/view/4ae695d5-b6c4-493a-4ea9-c372dc077062-3cd7/?fullscreen

Main updates:

1. Added user criteria to have firstname, lastname, AND email
2. Manage-access is a new value 

updates to be made:
- remove modals, show in page template (will demo with one page)

considerations: 
- with the page template, do we want to have _Remove User_ in the table ([page 8](https://xd.adobe.com/view/4ae695d5-b6c4-493a-4ea9-c372dc077062-3cd7/screen/2a05e423-842a-4ba6-91a5-09982fb146ce/Manage-Users)) or under options to _Edit User_ ([page 9](https://xd.adobe.com/view/4ae695d5-b6c4-493a-4ea9-c372dc077062-3cd7/screen/2a6fe400-247e-4a82-9649-fbddb04cb7e3/Manage-Users-2))?

**Comment by lisamcmichael** [comment]
@lisaredux @ASprinkle @carlsonem 
Looks good; nothing to add on the design. 

About the terminology used for access levels, because this area of the site will be used infrequently, it's helpful to include more of a 'hint' about each access level. This is just to make it super easy, so folks don't have to recall them, rather just recognize them and make the selection(s). 

Manage access (Administrator, POC)
Write access (Site Editor)
Read access (User)

**Comment by carlsonem** [comment]
A few notes...

- Jon (our security SME) suggested not using the term "admin" for individual forest pages.  Not change in design, just a terminology item
-Might want to change the name of the Forest/s column so we can capture roles in other parts of the application, beyond only the FS pages. e.g. Want a way to grant someone access to the "manage users" page. I could also see they need for reports pages and such down the road.
- Ditto comment above, where you click edit user, instead of "select forest" made call it "select module, page, something like that. This way we can add other parts of the application to the list.

-

**Comment by lisaredux** [comment]
Thanks for the feedback @carlsonem and @lisamcmichael — I will update the design accordingly and renew the link for review

**Comment by carlsonem** [comment]
@lisaredux Can we setup a time to review this today or tomorrow? Want to try and get this ready for the developers to start building.

**Comment by lisamcmichael** [comment]
@carlsonem @ASprinkle @lisaredux 
I'd like to get the design in front of 5 or 6 Open Forest Admin/POC users to:
 _(1) test terminology:_ Do users understand how to assign roles with these options: "Manage Access, Write Access and Read Access"? Or, do they better understand how to assign roles with these options: "Manage access (Administrator, POC) Write access (Site Editor) Read access (User)"? 
_(2) test workflow_

**Comment by lisaredux** [comment]
> @lisaredux Can we setup a time to review this today or tomorrow? Want to try and get this ready for the developers to start building.

Yes, thanks @carlsonem, I was thinking the same thing. I'm making design tweaks now so anytime after 3p EST is good with me. I have some questions about your notes above, when I read it again after my last comment.

**Comment by lisaredux** [comment]
@lisamcmichael @carlsonem @ASprinkle Here is an updated link for the meeting, for review: https://xd.adobe.com/view/fb0181bf-b7f9-4d46-5a62-1e3196af9d73-8d30/

**Comment by lisaredux** [comment]
@carlsonem @lisamcmichael @ASprinkle and I had a meeting to discuss the prototype in progress. Here are the updates that need to be made to this [current prototype](https://xd.adobe.com/view/fb0181bf-b7f9-4d46-5a62-1e3196af9d73-8d30/): 

- [ ] Update tabs to make them less characters
- [ ] Show tabs that are unavailable to users as visible but disabled-greyedout
- [ ] Move “Request a content change” to different place
- [ ] Add another scenario—user Deschutes only manage-access
- [ ] Add remove user back to edit function
- [ ] Clarify admin names in the table, add diverse forests and roles logic
- [ ] Make sorting in first column, on name only

 Eric to followup with DEV team to see about the LOE for modal implementation in Open Forest.

I will post static images of the Manage Users page and the prototype link here when they are ready.

**Comment by lisaredux** [comment]
Core design here:
<img width="254" alt="Screenshot 2019-08-22 13 55 22" src="https://user-images.githubusercontent.com/26801590/63537807-a321ce00-c4e4-11e9-97a0-bbb58f134d32.png">

Prototype here to show variables (in progress):
 https://xd.adobe.com/view/fbefa3d7-9e9d-4491-7cb3-c912e4def4d3-8dde/screen/2a05e423-842a-4ba6-91a5-09982fb146ce/Manage-Users?fullscreen

**Comment by lisaredux** [comment]
@ASprinkle @carlsonem from my perspective, this is ready for DEV to start. 
 
Let me know if you have questions @mtlaney and team

**Comment by ASprinkle** [comment]
@lisaredux Agreed. I'll move this into Ready. I suggest we have a hand off meeting of sorts with Dev.

**Comment by carlsonem** [comment]
@mtlaney @briandavidson This is ready for dev

**Comment by ASprinkle** [comment]
Paired with @briandavidson 
- Regarding the Search feature: dev will build the type-ahead feature in search (by name).
- Super Admins in PROD for now should be Amber Sprinkle, Aaron Burk, (super admins have ability to add remove user for all forests).
- When a new user is added to the system (i.e., if a super admin has made an entry for them, or someone with Manage Access has added them), they should be able to enter the system through eAuth and automatically see their levels of admin under Manage Users.
- If nothing is set up for a FS user as an admin for open forest they should not be able to access the Admin features of the site.
**Manage Access - someone who can add/edit/remove users for their assigned forest(s). This person can also change season dates, change cutting area dates, and generate reports.
**Write Access - someone who can change Season Dates and Cutting Area Dates, and generate reports for their assigned forest(s). (cannot add/remove/edit users)
**Read Access - Someone who cannot make any changes, but can see information for their assigned forest(s). This person can generate reports.
**Super Admin - untouchable by other forest admins. Can add/remove/edit users and access for any forest. Can change season dates, cutting area dates for any forest. Can generate reports for all forests.

**Comment by ASprinkle** [comment]
@carlsonem blocking this Dev story for User Management based on the discussion about ICAM and user management process expectations at stand up today. Also pending a follow up meeting with @mwreiss and @smahmudFS  (invite sent for 10/2)

**Comment by ASprinkle** [comment]
@briandavidson @mtlaney I will be closing this story based on the results of SPIKE story #922 - Open Forest will not house a unique admin user management system.  I want to check with you both first to see if there are any dev related tasks that should be completed related to this story before closing it - meaning, do we need to remove any code, or tidy up any work that Brian had started on this so that it's not confusing to a developer in the future?

**Comment by ASprinkle** [comment]
The branch for work that has been completed on this story is isolated from all other work.
We may be able to salvage some of the work accomplished in this story so that we can more easily integrate with ICAM/EEMS in the future.

**Comment by ASprinkle** [comment]
@lisaredux @briandavidson please save any admin management documentation to the User Management pinyon folder: https://usfs.box.com/s/axc60zuazso8ec1xadrm7sbd5he092s9

**Comment by lisaredux** [comment]
@ASprinkle here's the latest clickable prototype (as a web page) https://xd.adobe.com/view/7fb194e3-f45f-4517-77e2-f8ded72ef8cf-0980/?fullscreen

I tried inserting into Pinyon but it doesn't take links well. I'll try another method on Monday.

**Comment by ASprinkle** [comment]
@lisaredux I was able to save your github email message with the link ^ as a PDF in pinyon, and we can access it that way :)
