### ISSUE TITLE
As an FS admin for the Gifford Pinchot, I would like to know that my Forest's Christmas tree information on the Staging site in prep for this season.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#721]
## Notes

This is about taking the design researched Forest information and developing it onto the Open Forest staging site in preparation for content reviews, and launch to prod this season.

## Acceptance Criteria
- [x] The Gifford Pinchot Forest Christmas tree information is populated on the Open Forest site.
- [x] All menu items are populated with existing information
- [x] We have an understanding of what other information is needed, or what improvements may need to be made in order to complete the addition of the GP (i.e., the need for additional user stories is identified and they are created)

## Tasks
- [x] Utilize the design research document to build the content for the GP
- [x] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by mtlaney** [comment]
[Gifford.Pinchot.Forest.Info.2019.v3 (1).docx](https://github.com/18F/fs-open-forest-platform/files/3412172/Gifford.Pinchot.Forest.Info.2019.v3.1.docx)

**Comment by mtlaney** [comment]
Need a way to find, obtain, or create the POSS ID for GP.  (poss_financial_id)

**Comment by mwreiss** [comment]
@mtlaney you probably found it already but #686 references the ID's

**Comment by ASprinkle** [comment]
Update from stand up: nearly ready for staging. Borrowed tree information from another forest, will need to verify with GP. and Cutting, season dates.

**Comment by ASprinkle** [comment]
@mtlaney This is really great!!  Here are my comments for adjustments:

Under the Where to cut your tree section.  There should be a sub-header "No cutting or removing trees within:" so that the statement is not repeated in each bullet under it.
No cutting or removing trees within:
•	Congressionally designated Wilderness Areas.
•	Mount St. Helens National Volcanic Monument.
•	Experimental forests.
•	Developed campgrounds.
•	Administrative sites.
•	Within 300 feet of streams.
•	On private or state-owned lands within national forest boundaries.
•	In any other posted area.

Cutting area maps:
we will need to include a link first to the "[2017 Special Forest Products Map](https://www.avenzamaps.com/maps/670768/gifford-pinchot-national-forest-special-forest-products-map)" linked in the word document, and then offer the maps and publications page second.

In the How to cut your tree section. The three items with images should be:
Stump Height: 12 inches or less should be shown instead of "Stump Diameter: 0 inches maximum"

In the How to plan your trip section, the "map" link takes me to a page on the Flathead. this should revert me back to the GP maps and pubs page.

In identifying tree species. Please remove the Pacific Yew photo and info.

Contact us:
Please adjust the text so that it wraps similar to other forest's contact us pages 
Ranger District
Street
City State Zip
Phone Number

Do not include office hours - sorry I should have caught that in the word doc! 
In the text we say that each district office has different hours, so we don't need to specify hours here.

**Comment by ASprinkle** [comment]
I'll create separate story for things on the Rules page and for the Permit.

**Comment by mtlaney** [comment]
- [ ] Change cutting rules to match
- [ ] Change Stump Height
- [ ] Fix Map Link
- [ ] Add Map Linked in Doc
- [ ] Change Contact us to match, remove hours

**Comment by mtlaney** [comment]
@ASprinkle Once Brian is able to approve the new pull request, I'll move this back over and shoot you a note to check it out.

**Comment by ASprinkle** [comment]
![image](https://user-images.githubusercontent.com/33435621/61898754-e2053980-aece-11e9-9b89-1af025fef3dd.png)
@mtlaney @briandavidson  can you check the contact us section - i see the Spotted Bear Ranger District in the Gifford Pinchot's contact us section, and it does not belong there.. I believe that is for the Flathead NF.

In the Christmas tree cutting rules section, can we remove "The tree stump must be less than 0 inches in diameter" rule - it does not apply to the GP
![image](https://user-images.githubusercontent.com/33435621/61898988-5b9d2780-aecf-11e9-88dd-c67109874342.png)

The Permit looks great!

**Comment by ASprinkle** [comment]
Looks great, thank you!
