### ISSUE TITLE
As a R6 forest, I want to know that my Forest's Christmas tree info is available on the Staging site in prep for this season so that people can buy a Christmas tree permit online for my forest.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#722]
## Notes

This is the epic for adding the forest's initially researched information to the staging site.  In this epic, each forest has it's own story so that the work can be tracked and completed in edible, forest-by-forest chunks.

## Acceptance Criteria
- [x] Gifford Pinchot National Forest information is added to the staging site
- [x] Umatilla National Forest information is added to the staging site
- [x] Willamatte National Forest information is added to the staging site
- [x] Rogue River-Siskiyou National Forest information is added to the staging site
- [x] Okanogan-Wenatchee National Forest information is added to the staging site
- [x] Deschutes-Ochoco National Forest information is added to the staging site
- [x] Mt. Baker Snoqualme National Forest information is added to the staging site
- [x] Fremon-Winema National Forest information is added to the staging site

## Tasks
- [ ] 
- [x] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested
