### ISSUE TITLE
As an FS admin for the Umatilla, I would like to know that my Forest's Christmas tree information on the Staging site in prep for this season

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#724]
## Notes
This is about taking the design researched Forest information and developing it onto the Open Forest staging site in preparation for content reviews, and launch to prod this season.

## Acceptance Criteria
- [x] The forest's Christmas tree information is populated on the Open Forest site.
- [x] All menu items are populated with existing information
- [x] We have an understanding of what other information is needed, or what improvements may need to be made in order to complete the addition of the forest (i.e., the need for additional user stories is identified and they are created)

## Tasks
- [x] Utilize the design research document to build the content for the forest
- [x] PO approved

## Definition of Done
- [x] Pull requests meet technical definition of done
- [x] Compare finished design with mockup
- [x] Internally usability tested

**Comment by mtlaney** [comment]
[Umatilla.Forest.Info.2019.v2.1.docx](https://github.com/18F/fs-open-forest-platform/files/3462217/Umatilla.Forest.Info.2019.v2.1.docx)

**Comment by ASprinkle** [comment]
@mtlaney One change:  Please show the state of Oregon associated with the Umatilla. The site currently shows Washington, and that is incorrect.

![image](https://user-images.githubusercontent.com/33435621/62551101-3c33c200-b820-11e9-87f6-0a39394bc3e3.png)


We can address other updates in future stories to from content reviews

**Comment by ASprinkle** [comment]
@mtlaney Given that this is the first thing pilot forests will see, it will be important to update the state associated with the forest prior to tomorrow's kick off meeting.. :)

**Comment by mtlaney** [comment]
@ASprinkle updated states on Umatilla and Dechutes now!
