### ISSUE TITLE
As an FS admin for the Deschutes-Ochoco, I would like to know that my Forest's Christmas tree information on the Staging site in prep for this season

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#725]
## Notes
This is about taking the design researched Forest information and developing it onto the Open Forest staging site in preparation for content reviews, and launch to prod this season.

## Acceptance Criteria
- [x] The forest’s Christmas tree information is populated on the Open Forest site.
- [x] All menu items are populated with existing information
- [x] We have an understanding of what other information is needed, or what improvements may need to be made in order to complete the addition of the forest (i.e., the need for additional user stories is identified and they are created)

## Tasks
- [x] Utilize the design research document to build the content for the forest
- [x] PO approved

## Definition of Done
- [x] Pull requests meet technical definition of done
- [x] Compare finished design with mockup
- [x] Internally usability tested

**Comment by ASprinkle** [comment]
Deschutes-Ochoco research information is completed, and housed within #687

**Comment by ASprinkle** [comment]
@mtlaney 
The Deschutes is in "Oregon"
![image](https://user-images.githubusercontent.com/33435621/62400208-43fb1a00-b533-11e9-8031-8d00f754b6fb.png)

There are some artifacts in the contact us section.
![image](https://user-images.githubusercontent.com/33435621/62400242-6a20ba00-b533-11e9-9ec0-ef5d460fbd4d.png)

Once these are clean up I'll mark it PO approved

**Comment by mtlaney** [comment]
@briandavidson can you take a look at Ambers comments above?

**Comment by ASprinkle** [comment]
@mtlaney @briandavidson  Given that this is the first thing pilot forests will see, it will be important to update the state associated with the forest prior to tomorrow's kick off meeting.. for this story, the Deschutes should be associated with Oregon, not Washington. :)

**Comment by mtlaney** [comment]
@ASprinkle should be good to go now

**Comment by briandavidson** [comment]
Thanks for stepping in and helping knock this one out @mtlaney

**Comment by ASprinkle** [comment]
![image](https://user-images.githubusercontent.com/33435621/62574799-250bc900-b84e-11e9-8fe6-b4c6d0b84e88.png)

The drop down looks great and same with the contact us! PO Approved
