### ISSUE TITLE
As an FS admin for the Willamette, I would like to know that my Forest's Christmas tree information on the Staging site in prep for this season

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#726]
## Notes
This is about taking the design researched Forest information and developing it onto the Open Forest staging site in preparation for content reviews, and launch to prod this season.

## Acceptance Criteria
- [x] The forest’s Christmas tree information is populated on the Open Forest site.
- [x] All menu items are populated with existing information
- [x] We have an understanding of what other information is needed, or what improvements may need to be made in order to complete the addition of the forest (i.e., the need for additional user stories is identified and they are created)

## Tasks
- [x] Utilize the design research document to build the content for the forest
- [x] PO approved

## Definition of Done
- [x] Pull requests meet technical definition of done
- [x] Compare finished design with mockup
- [x] Internally usability tested

**Comment by mtlaney** [comment]
[Willamette Forest Info 2019 v2.docx](https://github.com/18F/fs-open-forest-platform/files/3418746/Willamette.Forest.Info.2019.v2.docx)

**Comment by ASprinkle** [comment]
Updates:  The forest name should be shown as "Willamette National Forest" vs. "Willamette Forest".  
![image](https://user-images.githubusercontent.com/33435621/62380609-645cb180-b4fe-11e9-85bb-5e3909f27246.png)
![image](https://user-images.githubusercontent.com/33435621/62380617-66bf0b80-b4fe-11e9-8b53-a50a3c21bed8.png)
![image](https://user-images.githubusercontent.com/33435621/62380658-7b9b9f00-b4fe-11e9-9c32-18161eb2d601.png)

Please remove :"To cut a tree over 20 feet tall, a permit must be purchased in person at a forest ranger district office." because we do not have the cutting specs for the forest yet.

Please update contact us format to wrap each line so that it looks like:
Ranger District
Street
City state zip
Phone number

At the end of the contact us section, please add the link for the Willamette National Forest's website:  https://www.fs.usda.gov/main/willamette
![image](https://user-images.githubusercontent.com/33435621/62380695-9241f600-b4fe-11e9-910c-0db23e483563.png)

so that it looks like this example from the Mt. Hood
![image](https://user-images.githubusercontent.com/33435621/62380733-af76c480-b4fe-11e9-99a6-97f6a109d519.png)

**Comment by mtlaney** [comment]
- [ ] update to willamette national forest
- [ ] remove 20ft tall tree text
- [ ] format contact us section
- [ ] add site link to contact us
