### ISSUE TITLE
As an FS admin for the Rogue River-Siskiyou, I would like to know that my Forest's Christmas tree information on the Staging site in prep for this season

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#727]
## Notes
his is about taking the design researched Forest information and developing it onto the Open Forest staging site in preparation for content reviews, and launch to prod this season.

## Acceptance Criteria
- [x] The forest’s Christmas tree information is populated on the Open Forest site.
- [x] All menu items are populated with existing information
- [x] We have an understanding of what other information is needed, or what improvements may need to be made in order to complete the addition of the forest (i.e., the need for additional user stories is identified and they are created)

## Tasks
- [x] Utilize the design research document to build the content for the forest
- [x] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Internally usability tested

**Comment by mtlaney** [comment]
[Rogue River-Siskiyou Forest Info 2019 v3.docx](https://github.com/18F/fs-open-forest-platform/files/3418740/Rogue.River-Siskiyou.Forest.Info.2019.v3.docx)

**Comment by ASprinkle** [comment]
@mtlaney @briandavidson for this story, I would suggest inserting a LINK to the Forest's Christmas tree cutting area maps on the forest website instead of embedding the maps onto Open Forest.  They are quite complex, and would take a lot of time developing adequate Alt Text.

**Comment by mtlaney** [comment]
@ASprinkle I agree, will get it done

- [ ] remove maps only use the links and qr code
