### ISSUE TITLE
As an FS admin for the Fremont-Winema, I would like to know that my Forest's Christmas tree information on the Staging site in prep for this season

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#728]
## Notes
This is about taking the design researched Forest information and developing it onto the Open Forest staging site in preparation for content reviews, and launch to prod this season.

## Acceptance Criteria
- [x] The forest’s Christmas tree information is populated on the Open Forest site.
- [x] All menu items are populated with existing information
- [x] We have an understanding of what other information is needed, or what improvements may need to be made in order to complete the addition of the forest (i.e., the need for additional user stories is identified and they are created)

## Tasks
- [x] Utilize the design research document to build the content for the forest
- [x] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Internally usability tested

**Comment by mtlaney** [comment]
[Fremont-Winema.Forest.Info.2019.v2.1.docx](https://github.com/18F/fs-open-forest-platform/files/3427217/Fremont-Winema.Forest.Info.2019.v2.1.docx)

**Comment by mtlaney** [comment]
@ASprinkle items missing for Fremont-Winema

Tree Height:
Stump Diamater: 
Stump Height: 
Org Structure Code:

**Comment by ASprinkle** [comment]
Correct, we do not have any of that information for the Fre-Win yet... Can we populate "0" for now?

What is "Org Structure Code"? is it the POSS Code? Fremont-Winema National Forest – 999900015

**Comment by mtlaney** [comment]
I'm not entirely sure what Org Structure Code is used for, but it's seperate from POSS code.

For instance, Mt. Hood is org_structure_code: '11-06-06',

**Comment by ASprinkle** [comment]
The Fre-Win Forest code is 06-02  (06=Region, 02=Forest number)

They have many additional codes, one fore each of their "Districts", but I do not think we are using this information (i.e., District specific) in the Open Forest program.
060201, 060202, 060203, 060204, 060205, 060207, 060208, 060211, 060212, 060213

**Comment by ASprinkle** [comment]
This looks great. I understand we do not have information  yet for more cutting rules (i.e., stump height, tree height) we'll get that soon! I'll make a follow up story for it.

Can you please update the Rules section so that it does not reference Gifford Pinchot info?
![image](https://user-images.githubusercontent.com/33435621/61965902-39b2ac00-af86-11e9-967b-e47a53614c70.png)

**Comment by ASprinkle** [comment]
Created story #758 to address the specifications for "how to cut your tree" section.
