### ISSUE TITLE
As an FS admin for the Mt. Baker-Snoqualmie, I would like to know that my Forest's Christmas tree information on the Staging site in prep for this season

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#729]
## Notes
This is about taking the design researched Forest information and developing it onto the Open Forest staging site in preparation for content reviews, and launch to prod this season.

## Acceptance Criteria
- [x] The forest’s Christmas tree information is populated on the Open Forest site.
- [x] All menu items are populated with existing information
- [x] We have an understanding of what other information is needed, or what improvements may need to be made in order to complete the addition of the forest (i.e., the need for additional user stories is identified and they are created)

## Tasks
- [x] Utilize the design research document to build the content for the forest
- [x] PO approved

## Definition of Done
- [x] Pull requests meet technical definition of done
- [x] Compare finished design with mockup
- [ ] Internally usability tested
- [ ] Have Page 508 Tested

**Comment by mtlaney** [comment]
[Mt.Baker.Snoqualmie.Forest.Info.2019.v3.1.docx](https://github.com/18F/fs-open-forest-platform/files/3432323/Mt.Baker.Snoqualmie.Forest.Info.2019.v3.1.docx)

**Comment by mtlaney** [comment]
@ASprinkle Do we happen to know max number of trees / permits for mbs?

**Comment by ASprinkle** [comment]
In the "How to cut your tree" section, can we add language similar to what we have for the Shoshone NF regarding the information about cutting a tree greater than the height limit... "To cut a tree over 12 feet tall, a permit must be purchased in person at a forest ranger district office."

Do the maps have alt text on them?  We may need to add this. If so, I suggest a separate story and have Lisa M or Lisa S help with that.

Can we have the address wrap so that it's:
Ranger Station
# and Street
City, ST
Phone number 

Instead of address on one line, and phone number on the next line. So that the format mirrors the original 4 forest's contact us sections.

**Comment by ASprinkle** [comment]
from stand up: @briandavidson will review alt text on maps for forests being added.  @carlsonem suggests running this through 508 testing (Ursa)

**Comment by ASprinkle** [comment]
Have the above ^ been addressed or should this be back "in progress"?

**Comment by mtlaney** [comment]
@ASprinkle Hey Amber! couple of quick questions

The formatting of contact info is no problem. The Alt text, can you perchance share a sceenshot of it, I can't seem to find it anywhere on the maps. Are we looking for standard alt text like "ZigZag Cutting Map" or something much more intricate?

Also, the _To cut a tree over {{treeHeight}} feet tall, a permit must be purchased in person at a forest ranger district office._ portion was removed in some if they were missing a max tree height, but I will add it back to any that does have a max tree height. Do you still want it removed if the max-tree height is currently 0?

**Comment by ASprinkle** [comment]
@mtlaney @briandavidson I inserted this word doc in Teams as well
[New Forests Alt Text maps.docx](https://github.com/18F/fs-open-forest-platform/files/3461816/New.Forests.Alt.Text.maps.docx)

LMK if you have any questions about this. Certainly if you see a typo take liberty to fix it :)  

Regarding:"Do you still want it removed if the max-tree height is currently 0?" - Yes.  We'll adjust and refine as Forest do content reviews. Thanks!
