### ISSUE TITLE
As an FS admin for the Okanogan-Wenatchee, I would like to know that my Forest's Christmas tree information on the Staging site in prep for this season

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#730]
## Notes
This is about taking the design researched Forest information and developing it onto the Open Forest staging site in preparation for content reviews, and launch to prod this season.

## Acceptance Criteria
- [x] The forest's Christmas tree information is populated on the Open Forest site.
- [x] All menu items are populated with existing information
- [x] We have an understanding of what other information is needed, or what improvements may need to be made in order to complete the addition of the forest (i.e., the need for additional user stories is identified and they are created)

## Tasks
- [x] Utilize the design research document to build the content for the forest
- [x] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Internally usability tested

**Comment by ASprinkle** [comment]
@mtlaney 
under the "Measuring your tree":
Please add the tree height maximum: 15 feet (same for rules section)
Please remove stump diameter  (same for rule section)

I'll make other stories for further refinements.

**Comment by mtlaney** [comment]
@briandavidson one more for you :)

**Comment by ASprinkle** [comment]
@briandavidson 
How to cut your tree section looks great!
![image](https://user-images.githubusercontent.com/33435621/62579845-aae14180-b859-11e9-9fc3-33af0a5c39dd.png)

The Christmas tree cutting Rules & Guidelines section still has some other information in it shown here. I'll create another story to update the Rules and Guidelines section so that we can call this story done.

The permit correctly displays the info 
![image](https://user-images.githubusercontent.com/33435621/62579979-057a9d80-b85a-11e9-8f6b-b67c4661af00.png)

![image](https://user-images.githubusercontent.com/33435621/62579896-ca786a00-b859-11e9-9995-b4d38c43292d.png)
