### ISSUE TITLE
As a permit holder I want my Permit to be valid for the season in which I have purchased it, so that I can be in compliance.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#731]
## Notes
* What are things we should consider when making this story *

We need to make sure that the permit printed for this season (or any season) is automatically relevant to the current year, and does not have previous YYYY on it.

## Acceptance Criteria
- [x] The permit prints with the current season/year YYYY on it.

## Tasks
- [x] Identify the cause of the issue
- [] Update the code so the correct date is on the permit
- [x] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
If Open Forest can automatically update the YYYY for the current year's Xmas tree season, that would be preferred.  However, if a heavy lift, then for purposed of MVP, manually update the permit for 2019.

**Comment by briandavidson** [comment]
@ASprinkle can you clarify a bit on where you want the YYYY to be updated? The title and description in the ticket indicate that it should be addressed specifically for permits but I'm guessing we want to use the current year for the Xmas tree season everywhere it's used.

**Comment by ASprinkle** [comment]
from stand up: @briandavidson let's meet today 8/21 to follow up on this. Thanks

**Comment by ASprinkle** [comment]
@briandavidson @abdul1234e and @ASprinkle tested iterations of season dates and issuing permits. The permit YYYY automatically updates.

**Comment by ASprinkle** [comment]
Here are screen shots that illustrate the automatic update
If the Season Date starts in year 2018, then the YYYY that prints on the permit will match the season start date year, 2018 no matter what year the permit is issued in.
Here is a 2018 Season Start Date example:
![image](https://user-images.githubusercontent.com/33435621/63464634-8027e900-c414-11e9-83b4-a2da8df4979f.png)
![image](https://user-images.githubusercontent.com/33435621/63464636-828a4300-c414-11e9-91ae-781166b7d654.png)
![image](https://user-images.githubusercontent.com/33435621/63464646-874ef700-c414-11e9-923b-5beef633fec3.png)

Here is a 2019 Season Start Date example:
![image](https://user-images.githubusercontent.com/33435621/63464863-f4628c80-c414-11e9-9f93-5c67e7b52cb1.png)
![image](https://user-images.githubusercontent.com/33435621/63464876-f75d7d00-c414-11e9-9a94-44a1c35519c5.png)
![image](https://user-images.githubusercontent.com/33435621/63464887-fa586d80-c414-11e9-95af-7e5d24853d5e.png)
