### ISSUE TITLE
As an FS Administrator for a NEW forest, I want to have roles for my pilot forest so that I can perform admin functions.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#749]
## Notes
* What are things we should consider when making this story *

This story is about adding FS administrators to the Open Forest system so that they can Generate Reports of christmas tree permits issued on their forest, change season dates, change cutting area dates, and (request content changes)

## Acceptance Criteria
- [x] FS POCs for pilot forests have administrator roles in dev and staging for the specified forest
- [x] We are prepared to confirm that FS POCs can access the administrator functions in dev and staging.

## Tasks
- [x] Give FS POC for new pilot forests admin roles in Dev
- [x] Create documentation on how this is done today
- [x] Give FS POC for new pilot forests admin roles in Staging
- [x] PO approved

## Definition of Done
- [x] Pull requests meet technical definition of done
- [x] Compare finished design with mockup
- [x] Usability tested

**Comment by ASprinkle** [comment]
Pilot Forest | Last Name | First Name | Position Title | Email
Region 6 | Croll | Dana | Regional TIM Coordinator | dcroll@fs.fed.us
Region 6 | Fleeger | Krystal | Recreation Fee Specialist | krystal.fleeger@usda.gov
Umatilla | Weseman | Darcy | Public Affairs Officer | darcy.weseman@usda.gov
Umatilla | Gutierrez | Deb | Administrative Officer | debra.gutierrez@usda.gov
Gifford Pinchot | Gates | Joe | Silviculturist | joseph.gates2@usda.gov
Gifford Pinchot | Rose | Robin | Recreation Program Manager | robin.rose@usda.gov
Mt. Baker-Snoqualmie | Schlafmann | Mike | Public Services Staff Officer | mike.schlafmann@usda.gov
Mt. Baker-Snoqualmie | Busscher | Rebecca | Resource Specialsit | rebecca.busscher@usda.gov
Okanogan-Wenatchee | Jump | Terri | Timber Resource Specialist | terri.jump@usda.gov
Rogue River -Siskiyou | Barnhart | Rob | Veg. Module Leader | robert.barnhart@usda.gov
Rogue River -Siskiyou | McGovern | Anna | Timber Resource Specialist | anna.mcgovern@usda.gov
Deschutes-Ochoco | Tandy | Brian | Forest Products and Silv Program Lead | brian.tandy@usda.gov
Willamette | Mercado | Christian | Small Sales/SFP Forester - Middle Fork RD | christian.mercado@usda.gov
Fremont-Winema | Lammers | Serena | Administrative Officer | seana.lammers@usda.gov
Fremont-Winema | Burley | Chuck | NR Staff Officer | charles.burley@usda.gov

**Comment by ASprinkle** [comment]
Mt. Hood NF Changes:
Remove Jason Page, jason.page@usda.gov
Add Mark Terhune, mark.terhune@usda.gov
Add Robert Gill, robert.gill@usda.gov

Flathead NF Changes
Add Michael Reichenberg, michael.reichenberg@usda.gov

**Comment by mwreiss** [comment]
Reference for whitelisting users:

https://github.com/18F/fs-open-forest-ops

**Comment by carlsonem** [comment]
@abdul1234e do you know how to white-list users? If so, can you please take on this task

**Comment by abdul1234e** [comment]
@ericsorenson @mwreiss The above list is added into white-list user for dev environment. Please validate.

**Comment by mwreiss** [comment]
@abdul1234e @carlsonem I have reviewed that the users are set for white-list in dev.

**Comment by ASprinkle** [comment]
@abdul1234e @mwreiss When will I be able test pilot forest POC admin access to the production site with the pilot forest folks?

**Comment by carlsonem** [comment]
@ASprinkle wouldn't it make more sense to have them test in dev first? After they confirm their page it good to go, we push it to production and provide them access. Thoughts?

**Comment by ASprinkle** [comment]
Of course, but I wasn't sure if they would be able to test their admin roles access in dev or not.

**Comment by ASprinkle** [comment]
From stand up:  @carlsonem will be assigned admin roles for a new forest and test the system prior to Amber reaching out to Pilot forest POC for their testing/confirming access. Team will update audit logs when making admin role changes for Eric in this testing method.

**Comment by abdul1234e** [comment]
@carlsonem Added Eric to the list. You should be good to go for testing it.

**Comment by mwreiss** [comment]
@carlsonem @abdul1234e  I would like to do a screen share with you Eric to get eyes on results.  Let Abdul and I know when you have time

**Comment by carlsonem** [comment]
Mt. Hood is the Forest Eric is assigned to for testing

**Comment by ASprinkle** [comment]
From stand up: Two different tests to be completed: one in staging environment and one in production environment. @carlsonem is point for testing.

**Comment by mwreiss** [comment]
@ASprinkle  @carlsonem I updated this issue to address just dev and staging.  A new issue is being created to address prod.  Thanks!

**Comment by abdul1234e** [comment]
@carlsonem Flathead is the Forest role assigned to Eric for testing in staging environment.

**Comment by ASprinkle** [comment]
@mwreiss  @abdul1234e   I moved the story for testing in Prod to the top of the backlog so you all can grab it when you're ready.

**Comment by abdul1234e** [comment]
@mwreiss @ASprinkle. The above users are added into prod whitelist with respective of their roles.

Ref 784

**Comment by mwreiss** [comment]
This one is completed as well @ASprinkle.  Moving to waiting/acceptance with PO approval box ready when you are.

**Comment by ASprinkle** [comment]
PO Approved!

**Comment by aaronburk** [comment]
Approed
