### ISSUE TITLE
As a customer I want to read about Every Kid Outdoors, instead of EKiP so that I know I am receiving updated information.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#761]
## Notes
Current language: ![image.png](https://images.zenhubusercontent.com/5a00e34b8a75884b90864b6f/795ceebe-7a85-407b-9870-f6611dc033a2)

We will need to update our logo and text to match the upcoming Sept. 1, 2019 name change from "Every Kid in a Park" to "Every Kid Outdoors"

## Acceptance Criteria
- [x] Site updated to reflect name change/logo of EKiP

## Tasks
- [x] Gather new logo and text
- [x] Update page with new logo and text
- [x] PO approved

## Definition of Done
- [x] Pull requests meet technical definition of done
- [x] Compare finished design with mockup
- [ ] Usability tested

**Comment by lisaredux** [comment]
@ASprinkle I gathered the new Every Kid Outdoors information from their new website....

New link (the old one already redirects to this one):
https://everykidoutdoors.gov/index.htm

About language from site: "Every Kid Outdoors was created so fourth graders and their families could discover our wildlife, resources, and history for free."
....not sure if you'd want to tinker with that, so I'm including the PDF brochure for language: https://everykidoutdoors.gov/media/EKO_Brochure_Condensed.pdf

New logo:
![logo-eko](https://user-images.githubusercontent.com/26801590/64726933-aede3000-d4a5-11e9-902e-2b5d103d8f57.png)

**Comment by ASprinkle** [comment]
Hi @lisaredux Yes, we need to update the language. I had never noticed before, but what we have on our site now calls out "national parks" w/o including national forests... so let's just change the entire text on the Open Forest landing page to read:

Fourth graders may be eligible to receive a free Christmas tree permit. Please visit the [Every Kid Outdoors](https://everykidoutdoors.gov/index.htm) website or contact your [local forest service office](https://www.fs.fed.us/) for details.

**Comment by lisaredux** [comment]
@ASprinkle Absolutely... new text and logo integrated into full- and partial- mockups below 

Full: https://xd.adobe.com/view/06053140-b3f8-442f-5aca-499d7b28141f-7034/?fullscreen
Partial: 
<img width="611" alt="Screenshot 2019-09-11 16 26 32" src="https://user-images.githubusercontent.com/26801590/64732974-d76c2700-d4b1-11e9-87d5-4284355a94c3.png">

**Comment by ASprinkle** [comment]
That looks great @lisaredux I'd say this is ready for dev. I'll move it to the backlog for now given the other dev work in the Ready column at the moment.

**Comment by ASprinkle** [comment]
Yes!  :)
![image](https://user-images.githubusercontent.com/33435621/67621826-61edb900-f7c8-11e9-9389-722090fc32fa.png)
