### ISSUE TITLE
As and Admin I want to be able to select the log out option and not stay logged in so that my information is not compromised.

### ISSUE THREAD

**Issue by carlsonem** [USDAForestService/fs-open-forest-platform#762]
## Notes
eAuth is keeping users logged into Admin Portal of Open Forest when they close the page, or leave the site.

## Acceptance Criteria
- [x] When a user closes the admin page, or has no activity for an amount of time, they are automatically "logged out".
- [x] An admin must log in to access the admin page after they have logged out.

## Tasks
- [x] Provide screenshots of issue
- [x] Determine the changes that are required for the eAuth team
- [x] Dev changes are needed from application level
- [x] Refine additional tasks, after eAuth team responds
- [x] PO approved

## Definition of Done
- [ ] A user who presses the logoff button actually logs off admin portal

**Comment by lisaredux** [comment]
Providing a screen video of the issue, included as a ZIP file below. The video originates at Staging Admin site https://open-forest-staging.app.cloud.gov/admin/christmas-trees 
To note: I don't have whitelisted admin access to the production site.

Video of issue: [ScreenRecording-LogOutIssue-Xmastrees-eAuth.zip](https://github.com/18F/fs-open-forest-platform/files/3447077/ScreenRecording-LogOutIssue-Xmastrees-eAuth.zip)

Let me know if you have any questions or want to do screenshare @carlsonem @ASprinkle and others

**Comment by abdul1234e** [comment]
@lisaredux I suggest to clear the cache settings from your chrome. I was able to logout from staging successfully and also did a refresh.
 lets do screen share to review it.

**Comment by mwreiss** [comment]
@carlsonem  eAuth doesn't enforce a timeout on the app, we need to put some of that logic on the OF app side to redirect back to the eAuth login page after 15min or the default standard.

**Comment by ASprinkle** [comment]
@lisaredux  do you have another link to that video ^ I receive a 404 error when I click on it.

**Comment by lisaredux** [comment]
@ASprinkle that's strange, I get the same 404 error now. Let me try and see what I can do. Thanks for letting me know

**Comment by lisaredux** [comment]
@ASprinkle & team — hope this one works now. The other one above might've expired
[ScreenRecording-LogOutIssue-Xmastrees-eAuth.zip](https://github.com/USDAForestService/fs-open-forest-platform/files/3805565/ScreenRecording-LogOutIssue-Xmastrees-eAuth.zip)

**Comment by abdul-fs** [comment]
Sent out again an email to eauth team to address the setting level asap.

**Comment by abdul-fs** [comment]
Meeting has been setup on wednesday. we will apply these changes in dev then staging and prod.

**Comment by abdul-fs** [comment]
After discussion, there is dev work to be done from application side. The max we have for eauth time out is 9 hrs.

**Comment by mwreiss** [comment]
Additional info.....

After the meeting Dec 19th it was determined:

1) eAuth hands off sessions to an application once authenticated, future state of eAuth might include ways to kill user sessions but at this point its to large of a project to tackle.
  
2) A session timeout value will need to be set in the open forest website to kill idle sessions max 9 hrs.  Mike mentioned creating a session expiration job. (some further dev work needed).

3) A redirect will be put into place to revert a user back to the Open Forest home page. Users can attempt a new login as normal.

4) A user that logs out should be redirected back to the Open Forest home page and session set to expire immediately. - eAuth doesn't do this for us as mentioned above.

**Comment by ASprinkle** [comment]
So in terms of next steps. do we need to:

Create a new story that addresses: 
2. A  session timeout value will need to be set in the open forest website to kill idle sessions max 9 hrs. Mike mentioned creating a session expiration job. (some further dev work needed).

Add a task to this story that addresses:
3. A redirect will be put into place to revert a user back to the Open Forest home page. Users can attempt a new login session as normal.

Add or edit the Acceptance Criteria so that it includes:
4. A user that logs out should be redirected back to the Open Forest home page and session set to expire immediately. - eAuth doesn't do this for us as mentioned above.
**Question: - what is being defined as the "Open Forest home page" in this number 4 scenario? I assume it is the special uses MBS landing page if the user a public user that is "logging out".  If the user is an admin, they should be routed to the landing page respective to the admin function they logged in for (either Christmas tree or special uses).

**Comment by mwreiss** [comment]
On the ^^
2. yes
3. yes
4. I would agree with what you said, redirect/routed back to the page they originally logged in from.

**Comment by mtlaney** [comment]
Current timeout is set for 20 minutes of inactivity for our eAuth session. Clicking logout will now destroy the user session and they will need to log back in. Pushed to staging to test.

**Comment by ASprinkle** [comment]
@mtlaney I tested this in staging on my computer and I didn't see any changes after 20 minutes. I think you said this would be difficult to test in staging environment. I am ok to move this to Ready given the difficulty in testing in Staging, so long as you agree, and I haven't missed anything.
