### ISSUE TITLE
Update pa11y routes 

### ISSUE THREAD

**Issue by mtlaney** [USDAForestService/fs-open-forest-platform#764]
## Notes
Need to update pa11y routes within .pa11yci to ensure we are accessability testing all newly added routes

## Acceptance Criteria
- [x] added correct url's to all new forests and associated pages

## Tasks
- [x] Add urls for our new forests within christmas-trees
- [x] PO approved

## Definition of Done
- [x] Pull requests meet technical definition of done
- [x] Compare finished design with mockup
- [x] Usability tested

**Comment by ASprinkle** [comment]
@mtlaney can you check the boxes above indicating the completed tasks and A/C is met?  Once you do that, please move it to Ready for Master. 
Thanks!!

**Comment by mtlaney** [comment]
@ASprinkle done!

**Comment by aaronburk** [comment]
Approved
