### ISSUE TITLE
*TEMP* Remove Chromium Update

### ISSUE THREAD

**Issue by mtlaney** [USDAForestService/fs-open-forest-platform#767]
## Notes
On 7-30-2019 Google released latest stable version of chrome 76. Selenium and Protractor testing are both listening for a chrome version between 71 and 75. We need to temporarly disable installing latest chrome version until Protractor and Selenium are updated by their respective teams. 

Tests run within CircleCI are failing due to version mismatching.

## Acceptance Criteria
- [x] Temporary bypass installing latest Chrome Stable

## Tasks
- [x] Temporary bypass installing latest Chrome on the CircleCI testing suite. 
- [x] PO approved

## Definition of Done
- [x] Pull requests meet technical definition of done
- [x] Compare finished design with mockup
- [x] Usability tested
