### ISSUE TITLE
As a FS administrator for Open Forest, I would like to contact the Open Forest team to provide feedback on the system.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#776]
## Notes
* What are things we should consider when making this story *

Forest service admins should be able to provide feedback/or contact the Open Forest team regarding their Open Forest experience with the admin site.

This feedback opportunity would only be available to people logged in as admin in Open Forest - for admin related things.

This would be different from "Request a content change"

## Acceptance Criteria
- [x] FS user is able to submit feedback for open forest team to consider

## Tasks
- [x] Review Google Doc and document existing features
- [x] Determine if any new features are required
- [x] Determine appropriate location(s) for the input form
- [x] Develop workflow of new feature
- [x] Develop Mock-up of new feedback loop
- [x] Research admin user management needs associated with building out admin user feedback tool.
- [x] Build it using this mock-up:
https://xd.adobe.com/view/a4f7b920-6330-4f2a-6cdc-3a0fcd11a431-d2c6/screen/39a87a68-4b8a-4a72-a183-a1b01066ba6e/STORY-776-INTRO?fullscreen
- [x] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [x] Compare finished design with mockup
- [ ] Usability tested with 5 Forest Service "frontliners"

**Comment by lisamcmichael** [comment]
![Google Form - FS admin input.jpg]

**Comment by lisamcmichael** [comment]
![Google Form - FS admin input.jpg](https://images.zenhubusercontent.com/5d24da694b6f4e0ca39d8303/e1f1293d-ead1-437f-83ed-667d1e7d6b78)

**Comment by lisamcmichael** [comment]
![Google Form - FS admin input.jpg](https://images.zenhubusercontent.com/5d24da694b6f4e0ca39d8303/615993aa-6f1b-4e58-ad43-cb712763e2a2)

**Comment by lisamcmichael** [comment]
_This poll is a stripped-down version of the Google doc "existing form"._ It would be added to each forest's site. As for location on the site...I'll work on that next.

_Justification:_ It's simple design should encourage feedback. If it's complicated (e.g., several steps, heavy decision-making, and appears to take too long), it will discourage participation. Our Forests may take an "easier route" and complain to their leadership who will email/call Amber (defeating the purpose). 

Also, it's okay to take anonymous feedback; some forest frontliners may not want to identify him/herself. If we don't allow that, we may miss out on some important ideas for improvement. And, we (or I) can follow-up with the forest to identify what, if any, actions are needed to improve the forest's site. 

_Considerations:_ What is the level of effort to modify the Google form? Is a blank (write in) form field feasible? !

[Google Form - FS admin input v1.jpg](https://images.zenhubusercontent.com/5d24da694b6f4e0ca39d8303/a41e9b9a-40ea-4d26-9cd9-375b4c253dcc)

**Comment by lisamcmichael** [comment]
@lisaredux This story is almost identical to #676 (for the public to offer feedback). Could you work with me on this?

**Comment by lisamcmichael** [comment]
@lisaredux I am considering _where to place the online poll_ on the administrative area of the site. Here are some possibilities; let me know what you think (don't be shy to point out what doesn't work, and suggest what would). Thx!

- footer
- near the log in and log out feature
- near my account

Btw, I'm not thinking that this survey would pop up while someone is using the site. I'd like it to be a fixture of the site, and our FS people can know where it is at all times. 

https://images.zenhubusercontent.com/5d24da694b6f4e0ca39d8303/a41e9b9a-40ea-4d26-9cd9-375b4c253dcc

**Comment by lisaredux** [comment]
@lisamcmichael Thanks for getting this started. I like where this is going. 

As far as where to place the online poll on the administrative area of the site, I recommend near the log in/log out function or somewhere in the header or tabs vs. in the footer. Essentially, the footer seems to have more FS general information and someone might not look for Christmas tree specific functions there.  

Narrowing it down from there, I can wireframe 2-3 different scenarios so we can see the different options. Here it is today in admin view: 
<img width="777" alt="Screenshot 2019-08-15 16 38 39" src="https://user-images.githubusercontent.com/26801590/63125246-2ee2aa00-bf7b-11e9-9e4e-827a2da5fd95.png">

Do we want to keep "Request a content change" where it is or move it near the button for giving feedback as well? If we move it, this will make it easier to fit the new function "Manage users" in the tab structure as well. Just a thought.

**Comment by lisamcmichael** [comment]
You know, it does make sense to group "request a content change" with giving feedback. I am okay w/ the footer for both. This leaves room at the top for more important or "high frequency" tasks w/in the tab structure.

**Comment by lisamcmichael** [comment]
@carlsonem @lisaredux @ASprinkle Just a quick FYI, the I'm meeting with Lisa before our standup to discuss the design of the form, and come up with a recommendation for the form's design, and where the feedback form should go.

**Comment by lisaredux** [comment]
<img width="838" alt="Screenshot 2019-08-19 12 53 38" src="https://user-images.githubusercontent.com/26801590/63283871-5fc72580-c280-11e9-9655-6c30ca548034.png">

Admin user would click on _Give Feedback_ , presumably in the header, and would be directed to the Admin specific form. 

See it linked up here: 
https://xd.adobe.com/view/cc48261c-9ad0-4e64-5360-7c815af2ce6a-ba79/?fullscreen

**Comment by lisamcmichael** [comment]
@lisaredux @carlsonem @ASprinkle Just made _updates to #676_ to capture notes/actions because these 2 stories are related (survey forms).  Lisa is working on some design aspects, and we'll regroup later in the week.

**Comment by lisaredux** [comment]
Yesterday, @ASprinkle @lisamcmichael and I had a meeting to discuss this and [676](https://github.com/USDAForestService/fs-open-forest-platform/issues/676).

Working on updates from our discussion. Here is the [prototype link](https://xd.adobe.com/view/a4f7b920-6330-4f2a-6cdc-3a0fcd11a431-d2c6/screen/94eb1b0a-4fcd-4039-9cf4-9dccdb0ed8c4/Scenario-3-Write-Access-ARP-only-P5-1).

We will be reviewing with DEV today or tomorrow and iterating from that.

**Comment by lisaredux** [comment]
Reviewed design concept with Mike and Brian today. Some updates to be implemented from our conversation... same goes for story 776:

1) **Where does the data go?**
DEV mentioned putting the feedback into the admin panel will be easier than setting up a mail client, so I will design a page for the admin panel that displays feedback to mirror the _Reports_ [page](https://open-forest-staging.app.cloud.gov/admin/christmas-trees/reports) 

2) **What page does the user end up on after giving feedback?** 
we can address it in one of 2-3 ways that I will mock-up:
- One way is to bring in this module and take the user back where they started with this _success_ feedback type implementation
![Screenshot 2019-08-29 15 44 15](https://user-images.githubusercontent.com/26801590/63975284-a7b62b80-ca7c-11e9-9597-2433d1dcd245.png)
- Another way is to show a page with _Thank you_ and have a link that takes them back to the homepage or wherever page they left to give feedback

3) **Does the form page have the same header and tab as the application page they were on before clicking _Give feedback_?** 
for MVP, yes, this will be the easiest way to build it, and the forms will be reusable for implementation into Special uses too

**Comment by ASprinkle** [comment]
@lisaredux 
when you "design a page for the admin panel" I do not think we want the feedback received to be available for viewing for all our Open Forest admins. Can we restrict this only for Open Forest dev/design team members?

Let's have the user end on a page with Thank you and have a link that takes them back to the Christmas tree homepage or wherever they left

**Comment by lisaredux** [comment]
@ASprinkle sounds good. As far as the page for the admin panel, I agree and we can certainly restrict that. I was thinking to design it in the "super-admin" view that you will have.

**Comment by ASprinkle** [comment]
@lisamcmichael sounds like a great plan!

**Comment by lisaredux** [comment]
Updated prototype with super-admin feedback screen (in progress) https://xd.adobe.com/view/a4f7b920-6330-4f2a-6cdc-3a0fcd11a431-d2c6/?fullscreen

**Comment by lisaredux** [comment]
Ready for DEV @mtlaney @briandavidson. Let me know if you have questions:
https://xd.adobe.com/view/a4f7b920-6330-4f2a-6cdc-3a0fcd11a431-d2c6/screen/39a87a68-4b8a-4a72-a183-a1b01066ba6e/STORY-776-INTRO?fullscreen

**Comment by ASprinkle** [comment]
Moving to ready. Removing the Lisas from the assignee list.

**Comment by briandavidson** [comment]
@lisaredux i noticed that the only real difference between the form that a public user uses and the one an FS admin uses in order to submit feedback is that the one for admins also has a field for specifying forests.

I just want to make sure that is what we want. And if it is, what do want to put in the table of feedback entries for the forest cell when the entry is submitted by a public user?

**Comment by ASprinkle** [comment]
@briandavidson @lisaredux Hi Brian, Lisa is OOO this week.  You're correct: the FS admin function offers the option (not required) to specify which forest they are referring to if applicable. So yes, there should be a forest cell available for the review of entries, or we would need to somehow capture that data.  That is shown in the workflow that Lisa S provided above.. here's a screen shot 
![image](https://user-images.githubusercontent.com/33435621/66943896-eb4eff80-f000-11e9-8f05-cde507a99e4b.png)

**Comment by briandavidson** [comment]
@ASprinkle okay that makes sense, thanks Amber!

**Comment by ASprinkle** [comment]
@briandavidson I see this story in Awaiting Acceptance, but I when I check staging, I do not see anything. I will check again tomorrow morning. Thanks!

**Comment by ASprinkle** [comment]
@briandavidson as an admin submitting feedback, I noticed that if someone accidentally provides all their feedback in one box, and hits submit, there is no error validation telling them to provide their feedback. Perhaps this will not be an issue. We can launch it an see if we need to build in further restrictions.
![image](https://user-images.githubusercontent.com/33435621/67815964-ab0e6900-fa65-11e9-9e84-670e989837aa.png)

**Comment by ASprinkle** [comment]
I also do not think we will have time to test the feedback tool with frontline staff at this time. I think we can go ahead and build it and gather information on it this season to continue to refine it. I am less concerned about the usability around the admin feedback tool vs. the public user feedback tool.
