### ISSUE TITLE
As a forest visitor I would like to easily read the Contact Us sections for all forests so that I can quickly make decisions.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#777]
## Notes
* What are things we should consider when making this story *

As we built content for new forests, the Contact Us section was formatted like this:
Ranger station/office name
Street, City, State, Zip
Phone number.

And should be changed to match the format of the original four forests.

Formatting for the original four forests is set up this, way.
Ranger station/office name
Street
City State Zip
Phone number

## Acceptance Criteria
- [x] Contact Us format is consistent between forests, matching the format of the original 4 forests.

## Tasks
- [x] update format
- [x] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
@mtlaney @briandavidson There is a small code artifact on the Deschutes Contact Us section
PO Approved - but please remove the artifact
![image](https://user-images.githubusercontent.com/33435621/62575202-17a30e80-b84f-11e9-93f6-6dd12c76b7c7.png)
