### ISSUE TITLE
As a forest visitor I want to see the updated season dates for the forests so that I can plan ahead for Christmas tree season.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#778]
## Notes
* What are things we should consider when making this story *

As we built content for new pilot forests, we did not have the season dates for all forests.

## Acceptance Criteria
- [x] The team as contacted forests for updated season dates.

## Tasks
- [x] Ensure season dates are accurate on Open Forest per 
[2019 Forest Season Dates .docx](https://github.com/USDAForestService/fs-open-forest-platform/files/3654841/2019.Forest.Season.Dates.docx)

- [x] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
@briandavidson  There might be some time-related issues - can you check these and see what's up?

* ARP is showing on staging as Nov 1, 2019 - Jan 5, 2020; it should be Jan 6, 2020. All the cutting area dates look correct.
* Flathead shows Nov 15, 2019 - Dec 30, 2019; it should be Dec 31, 2019.
* Mt. Hood shows Nov 13, 2019 - Dec 24, 2019; it should be Nov 14, 2019 - Dec 24, 2019
* Shoshone shows as Nov 18, 2019 - Dec 29, 2019; it should be Dec 30, 2019

Deschutes is good.
Fremont-Winema is good.
Gifford Pinchot is good.
Mt. Baker-Snoqualmie is good.
Okanogan-Wenatchee is good.
Rogue River-Siskiyou is good.
Umatilla is good.
Willamette is good.
