### ISSUE TITLE
As an Okanogan-Wenatchee Forest Admin I would like my forest name to be correctly displayed and maps linked to.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#779]
## Notes
* What are things we should consider when making this story *

On the Open Forest page, the Forest's name is not consistently shown as "Okanogan-Wenatchee"
![image.png](https://images.zenhubusercontent.com/5a00e34b8a75884b90864b6f/4190c9fd-1b50-4235-adb1-844d86b8fc5a)

![image.png](https://images.zenhubusercontent.com/5a00e34b8a75884b90864b6f/208e0f60-4f7f-426d-8197-29ece3ccc3ce)

![image.png](https://images.zenhubusercontent.com/5a00e34b8a75884b90864b6f/5c3c0fab-3403-4b7b-bc19-adce8e49610a)

## Acceptance Criteria
- [x] The forest's name is consistently shown as "Okanogan-Wenatchee" National forest
- [x] The maps are linked

## Tasks
Update the forest's name on the 
- [x] Landing drop down
- [x] Information page & banner
- [x] Rules and Guidelines page
- [x] Admin pages
- [x] Confirmation Page
- [x] Permit
- [x] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by briandavidson** [comment]
@ASprinkle and @mtlaney we are currently linking [here for the Okanogan-Wenatchee maps](https://www.fs.usda.gov/main/okawen/maps-pubs).

Is that what we want, or do we want to be linking to specific map files? This looks like more of an overview page for all the Okanogan-Wenatchee maps.

**Comment by ASprinkle** [comment]
@briandavidson @mtlaney in addition to the maps and publications page, we should link to https://www.fs.usda.gov/detail/okawen/passes-permits/?cid=fsbdev3_053596
where someone will find the Christmas tree cutting area maps. If it is possible to link directly to the maps that would be preferred.

**Comment by briandavidson** [comment]
@ASprinkle alrighty, so it sounds like we're leaving it as is for now. If at some point we get updated maps we can circle back to this.

**Comment by ASprinkle** [comment]
Above the text in this section:
![image](https://user-images.githubusercontent.com/33435621/62511221-7d4bb800-b7c7-11e9-80fe-c6a577f0cbe3.png)

we should add a hyperlink for Christmas tree cutting area maps 

https://www.fs.usda.gov/detail/okawen/passes-permits/?cid=fsbdev3_053596

where someone will find the Christmas tree cutting area maps for the Oka-Wen.

**Comment by briandavidson** [comment]
@ASprinkle how does this look?
![image](https://user-images.githubusercontent.com/5187168/62560354-dad51880-b84a-11e9-8c0d-b9e5e651a841.png)


.. if that doesn't work or if you had something else in mind for the messaging let me know :)

**Comment by ASprinkle** [comment]
Excellent!!! 

![image](https://user-images.githubusercontent.com/33435621/62579556-edeee500-b858-11e9-9e46-877b64230b35.png)
