### ISSUE TITLE
As a user who relies an accessible technology, I want to be able to read alt text for maps on the forest website so that I can be informed.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#780]
## Notes
* What are things we should consider when making this story *

Alt text for forests with maps
[New Forests Alt Text maps.docx](https://github.com/18F/fs-open-forest-platform/files/3461816/New.Forests.Alt.Text.maps.docx)

## Acceptance Criteria
- [x] Alt text is added to maps that are on the open forest website.

## Tasks
- [x] Add alt text to maps
- [x] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by mtlaney** [comment]
[New.Forests.Alt.Text.maps.docx](https://github.com/USDAForestService/fs-open-forest-platform/files/3502357/New.Forests.Alt.Text.maps.docx)

re-uploading due to github transfer

**Comment by ASprinkle** [comment]
@mtlaney can you please walk me through how to read this/test this on staging?

**Comment by ASprinkle** [comment]
Catpuring from Teams chat: "[Yesterday 2:32 PM] Laney, Michael - FS
    That's a good question that I need to do some more research on. Typically alt text is visible in the browser using some dev tools, however the alt - text on maps is only going to play over a screen-reader, so I need to find a suitable screen reader and play it that way
(1 liked)​[8:05 AM] Sprinkle, Amber D -FS
    Ok. I'll PO appv.  Thanks!"
