### ISSUE TITLE
As a Flathead NF Administrator I want to make sure roles are set so that we have access to the Christmas tree admin site.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#781]
## Notes
* What are things we should consider when making this story *
In a prep call with the Flathead NF I was informed of some changing roles. We need to make sure we have admin roles set up correctly.

## Acceptance Criteria
- [x] We have reviewed our white listed names and completed the tasks below.
- [x] We are ready to reach out to the Flathead NF Admins to ask them to confirm their roles.

## Tasks
- [x] Verify that Tami Kerr still has admin access tamara.kerr@usda.gov 
- [x] Verify that Sarah Freund still has admin access sarah.freund@usda.gov
- [x] Verify that MIchelle Owens still has admin access michelle.owens@usda.gov
- [x] Remove Janette Turk janette.turk@usda.gov she has changed positions.
- [x] Add Meghan Mulholland meghan.mulholland@usda.gov (temporary detail through Oct) Public Affairs Officer 
- [x] Add Add Michael Reichenberg michael.reichenberg@usda.gov (on temporary detail)
- [x] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by mwreiss** [comment]
@ASprinkle moving this to in progress as we have addressed #784 and #749 already.

**Comment by abdul1234e** [comment]
@ASprinkle 

Tamara kerr has admin access to flathead.
Sarah Freund is not added in the list. 
MIchelle Owens has admin access to flathead
Removed Janette Turk
Meghan Mulholland is not added in the list
Michael Reichenberg has admin access to flathead

**Comment by abdul1234e** [comment]
@mwreiss 

The whitelist is updated and and added missing users into flathead roles.  This is completed.

**Comment by ASprinkle** [comment]
@mwreiss have they been added to Prod? or was this only for staging?

**Comment by abdul1234e** [comment]
@ASprinkle Yes. Those are added in production.

**Comment by mwreiss** [comment]
@ASprinkle We should be good to go.  We did an internal test to verify they were restricted to their respective forests.  If anyone needs help working through issues, @abdul1234e and I can assist as needed.  Will you be sending out a notice to the users to have them test? Thanks!

**Comment by ASprinkle** [comment]
@abdul1234e thank you!
@mwreiss  yes I plan to send a message to them today to have them test it. I will include in my message that this is for the production site, and the test is to ensure they can access it. They will need to know that if they update season dates that the update would go live and the public will see it. thanks!

**Comment by abdul1234e** [comment]
@ASprinkle @mwreiss: FYI  https://openforest.fs.usda.gov/admin/christmas-trees/ That's the admin prod url for users to access it and authenticate with eauth creds.

**Comment by ASprinkle** [comment]
@abdul1234e I sent email to Flathead NF admins to request verification. If any problems or questions arise, will address in a new story. Thanks!
