### ISSUE TITLE
Update production with NEW forest FS administrator based on their roles. 

### ISSUE THREAD

**Issue by abdul1234e** [USDAForestService/fs-open-forest-platform#784]
## Notes
* What are things we should consider when making this story *
This is to update production by adding FS administrators to the Open Forest System so that they perform admin changes based on their roles.

## Acceptance Criteria
- [x] FS POCs for pilot forests have administrator roles

## Tasks
 - [x] Give FS POC for new pilot forests admin roles in Prod
 - [x] Activity to be performed after business hours
- [x] Restart production after updating whitelist checklist
 - [x] PO approved

## Definition of Done
- [x] Pull requests meet technical definition of done
- [x] Compare finished design with mockup
- [x] Usability tested

**Comment by abdul1234e** [comment]
@mwreiss - Reference to 749. This is updated in production with requested whitelist.

**Comment by mwreiss** [comment]
@ASprinkle this is now completed and tested.  Moving to waiting/acceptance and can be moved to done if you are good.  Great work @abdul1234e !

**Comment by ASprinkle** [comment]
Excellent!! Thank you @abdul1234e and @mwreiss!!!

**Comment by aaronburk** [comment]
I approve
