### ISSUE TITLE
As a Christmas tree cutter on a new pilot forest I want to make sure the Rules and Guidelines I agree to match the information on the permit so that I am not confused.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#788]
## Notes
* What are things we should consider when making this story *

The Christmas tree cutting Rules & Guidelines section still has some other information in it shown here. 
![image](https://user-images.githubusercontent.com/33435621/62579896-ca786a00-b859-11e9-9995-b4d38c43292d.png)

The permit & the info pages correctly displays the info  the rules section should match
![image](https://user-images.githubusercontent.com/33435621/62579979-057a9d80-b85a-11e9-8f6b-b67c4661af00.png)
![image.png](https://images.zenhubusercontent.com/5a00e34b8a75884b90864b6f/3d3a540a-64d2-43b7-9259-bbbc0aa7eb7a)

## Acceptance Criteria
- [ ] Rules and Guidelines information is updated to match the tree cutting specificatons for the Oka-Wen as correctly shown on the permit and in the Information Page for the forest.

## Tasks
- [ ] 
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
redundant with high priority #861
