### ISSUE TITLE
***CI/CD Demo*** Change text field

### ISSUE THREAD

**Issue by mtlaney** [USDAForestService/fs-open-forest-platform#795]
## Notes
* As a user, I would like to be told that I do not need a special permit *

## Acceptance Criteria
- [ ] change text from permit to special permit, tests pass

## Tasks
- [ ] change the text
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested
