### ISSUE TITLE
As an Open Forest Researcher, I want to review each forest's Christmas tree permit content for accuracy and completeness before it goes live to the public.

### ISSUE THREAD

**Issue by lisamcmichael** [USDAForestService/fs-open-forest-platform#798]
## Notes
* What are things we should consider when making this story *

## Acceptance Criteria 

_For all 8 forests (Deschutes, Gifford-Pinchot, Fremont-Winema, Rogue River-Siskiyou, MBS, Oka-Wen, Umatilla, Willamette)_
- [ ] reviewed their Open Forest website
- [ ] provided feedback on their Open Forest website
- [ ] approved the approach to implement or backlog requested changes or enhancements
- [ ] signed-off on their Open Forest website before go live

## Tasks
- [ ] Create EPIC; create a card/story for each forest; link to EPIC
- [ ] Schedule and complete a demo with each forest
- [ ] Review the demo outcomes/findings with PO; get PO approval
- [ ] Make design and/or development changes  
- [ ] Update cards/stories for each forest

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested with forests meets MVP
