### ISSUE TITLE
As an Open Forest Researcher, I need to get approval of Christmas tree permit content from each forest in Region 6 before the season starts.

### ISSUE THREAD

**Issue by lisamcmichael** [USDAForestService/fs-open-forest-platform#799]
## Notes
* During a workshop on August 7, eight forests in Region 6 were introduced to Open Forest. They're expecting to review and approve their forest's website content before it's introduced to the public.*

Deschutes, Gifford-Pinchot, Fremont-Winema, Rogue River-Siskiyou, Mt Baker-S, Oka-Wen, Umatilla, and Willamette  AND OCHOCO NF (as of 9/5/2019)

## Acceptance Criteria
- [x] Each forest has given approval of its Open Forest website  

## Tasks
- [x] Create EPIC
- [x] Create stories for each forest
- [x] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested with most or all forests

**Comment by lisamcmichael** [comment]
**R6 Open Forest Content Review participant list**

https://usfs.box.com/s/gkey8e7i1cw3zipvcsguovgvzztuye58
