### ISSUE TITLE
As the POC for Willamette Open Forest, I want to review and have Christmas tree permit content updated so that I know the information is correct before the season starts.

### ISSUE THREAD

**Issue by lisamcmichael** [USDAForestService/fs-open-forest-platform#800]
## Notes
* See EPIC 799 *
On Pinyon: https://usfs.box.com/s/qrwhht4ls421uajx3yivgy7kkqu6p01d

## Acceptance Criteria
- [x] reviewed and approved "MVP" website content
- [x] approved backlog content (for next season)
- [x] The Forest's content has been updated based on Forest POC review.
 
## Tasks
- [x] Complete a demo with the forest, capture feedback
- [x] Review findings with PO

- [x] Implement changes:
- [x] *FYI: Season dates will be updated by the Forest.*
- [x] Just before "No cutting or removing trees within" statement, add "Five-needle pines (sugar and white pines) cannot be cut."
- [x] Under "No cutting or removing trees within" add the following to the top of the bullet list: "50 feet of trails and paved roads", "300 feet of campgrounds", "100 feet of streams", "Areas posted "Christmas Tree Cutting Prohibited". ALSO, revise "Botanical areas" to "Botanical areas and fenced plantations." 

- [x] Update maps using what has been recently provided by Forest POC.
- [x] Under cutting area maps section. *remove the office hours information* (see below). 
- [x] Under cutting area maps section, add "Cut trees only in cutting areas shown in green on these maps."
- [x] Under the cutting area maps section, add the following text before each map.
 - Christmas tree map of Detroit Ranger District. (Click to view larger map)
 - Christmas tree map of Sweet Home Ranger District. (Click to view larger map)
 - Christmas tree map of McKenzie Ranger District. (Click to view larger map)
 - Christmas tree map of Middle Fork Ranger District East. (Click to view larger map)
 - Christmas tree map of Middle Fork Ranger District West. (Click to view larger map)
- [x] Scale the maps similar to Mt. Hood "Clackamas" - or if there is a standard, go with that.

- [x] Update the How to Cut your Tree section with the cutting specifications and the associated images: Stump Height: 6 inches maximum, Tree Height: 12 feet maximum.
- [x] Update helpful cutting tips to add: "Help keep road ditches functioning and keep debris off of, and away from, roadways (at least 50 feet)."
-  [x] Under "Identifying Tree Species" add Grand Fir (copy from Flathead National Forest), add Pacific Yew  (copy from Mt. Hood National Forest).

- [x] Update the "Contact Us" introductory paragraph to read: "“You can buy Christmas tree permits in person at the following Willamette National Forest ranger district offices [Remove Hyperlink to the office] or at local vendors [keep hyperlink to local vendors]. District offices have different hours during the Christmas tree cutting season. Call first to make sure someone is available to sell permits. All offices are closed on federal holidays.
- [x ] Alt tags provided/updated by POC
Alt text is saved in BOX https://usfs.box.com/s/zfgbp73m82r08ks2uqznfi1iyi27r239
I also updated it in the Alt text document in Teams Files.

- [x] Forest POC has been informed of updates.
- [x] PO approved.

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested with forest

**Comment by lisamcmichael** [comment]
Scheduled Willamette for 8/22 with Christian

**Comment by lisamcmichael** [comment]
No backlog content discussed during the content review on 8/22 with Christian.

**Comment by ASprinkle** [comment]
@lisamcmichael I moved this back into "in progress" because there are a few tasks listed above that we still need to complete for this story. Great work on doing the content review with Christian!

**Comment by ASprinkle** [comment]
@lisamcmichael I renamed the story title (Which we should consider doing for the other similar stories) because the draft content is already on the Production site.

**Comment by lisamcmichael** [comment]
@ASprinkle I'll make those story updates.

**Comment by ASprinkle** [comment]
@mtlaney @briandavidson can we please address the content updates for the Willamette NF first? They are on a timeline for sharing a presentation of their site, and would like the updates to be made before they give their presentation.

**Comment by mtlaney** [comment]
@ASprinkle Hey Amber, just seeing this, I will begin work on Willamette first thing tomorrow (Possibly tonight)

**Comment by mtlaney** [comment]
@ASprinkle @carlsonem working thru an issue on my end to access the maps, hopefully I get it cleared soon.

<img width="1096" alt="Screen Shot 2019-09-09 at 7 14 07 PM" src="https://user-images.githubusercontent.com/18233188/64572606-0cec0580-d336-11e9-9f27-2f854936e730.png">

**Comment by lisamcmichael** [comment]
@mtlaney Hey Mike - I am having my own issues today (twice on calls with the FS Service Desk), and I'm unable to login to with my FS laptop to access those maps, etc. So...the point in all that is I can be available early tomorrow morning to help if needed. 

On a related note, I was wondering if you and Brian would like to have a standing meeting with me each day or something like that, say for 15 to 30 minutes, for forest stuff? If it's not needed we will skip it, but if it is we have it on our calendars. I'm not a big fan of creating meetings for the heck of it, only if it smooths out workflow. 

If you're reading this tonight ... have a good one!!

**Comment by ASprinkle** [comment]
@mtlaney @lisamcmichael Here are all of the files that are in the Content Review folder for the Willamette NF for this story:  You can use these until you are able to gain access back to pinyon again (@carlsonem perhaps you need to re invite Mike?)

[MiddleForkEast_XMasTreeHarvestMap_20151014_FINAL_Back.pdf](https://github.com/USDAForestService/fs-open-forest-platform/files/3596241/MiddleForkEast_XMasTreeHarvestMap_20151014_FINAL_Back.pdf)
[MiddleForkWest_XMasTreeHarvestMap_20151014_FINAL_Front.pdf](https://github.com/USDAForestService/fs-open-forest-platform/files/3596242/MiddleForkWest_XMasTreeHarvestMap_20151014_FINAL_Front.pdf)
[SweetHomeRD_XMasTreeHarvestMap_20151014_FINAL.pdf](https://github.com/USDAForestService/fs-open-forest-platform/files/3596243/SweetHomeRD_XMasTreeHarvestMap_20151014_FINAL.pdf)
[Willamette Content Review 2019 -v2.docx](https://github.com/USDAForestService/fs-open-forest-platform/files/3596244/Willamette.Content.Review.2019.-v2.docx)
[Willamette National Forest Alt Text for Maps.docx](https://github.com/USDAForestService/fs-open-forest-platform/files/3596245/Willamette.National.Forest.Alt.Text.for.Maps.docx)
[DetroitRD_XMasTreeHarvestMap_20151014_FINAL.pdf](https://github.com/USDAForestService/fs-open-forest-platform/files/3596246/DetroitRD_XMasTreeHarvestMap_20151014_FINAL.pdf)
[McKenzieRD_XMasTreeHarvestMap_20151014_FINAL.pdf](https://github.com/USDAForestService/fs-open-forest-platform/files/3596247/McKenzieRD_XMasTreeHarvestMap_20151014_FINAL.pdf)

When I tried to add Mike in Pinyon, this was the error I received:
![Adding Mike to Box Error](https://user-images.githubusercontent.com/33435621/64623999-d26a8300-d39e-11e9-853d-6287e73ce544.jpg)

**Comment by lisamcmichael** [comment]
Hmm, that's interesting. Mike confirmed w/ me on Slack he is able to access Box get to the files.  @ASprinkle , he is running some demos now.

**Comment by ASprinkle** [comment]
@mtlaney 
I went into front end content to update the following screen shot that is on staging... 
![image](https://user-images.githubusercontent.com/33435621/64874483-f973bf80-d5ff-11e9-8079-6c2f328c50f6.png)
I am not sure if I did that correctly. I might need a refresher!

**Comment by ASprinkle** [comment]
@mtlaney regarding the maps:
When I click to view the Detroit district larger map, the quality is granular - hard to read.
All other maps looks great except for the middle-fork-west map... this is what I see when I click to view larger:
![image](https://user-images.githubusercontent.com/33435621/64876745-b1a36700-d604-11e9-9dae-ab4b9f1f938c.png)


Does our conversation earlier about Stump Height/Tree Height have to do with not seeing this update on Staging? Stump Height: 6 inches maximum, Tree Height: 12 feet maximum.
![image](https://user-images.githubusercontent.com/33435621/64876964-3aba9e00-d605-11e9-9124-2358f971a546.png)

**Comment by mtlaney** [comment]
@ASprinkle I'll look into the maps, should all be the same resolution. And yes the stump height and tree height will be addressed with the seeder update.

**Comment by lisamcmichael** [comment]
@ASprinkle Let me know if I can help on the maps, for instance I can drop Christian a note to see if the PDF version of those 2 maps are available as JPGs, PNGs, or something that Mike might be able to manipulate. @mtlaney - does that make sense?

**Comment by ASprinkle** [comment]
moving back to in progress until the maps ? is resolved.

**Comment by ASprinkle** [comment]
@briandavidson can you work on this and other content stories please while Mike is out? Admin user management can wait for now - content updates are #1 priority.

**Comment by briandavidson** [comment]
@ASprinkle yup, will do!

**Comment by ASprinkle** [comment]
@mtlaney looks great! thank you!!

**Comment by lisamcmichael** [comment]
@mtlaney @briandavidson @ASprinkle The forest has updated its **Season End Date to January 6, 2020.**

**Comment by briandavidson** [comment]
> @mtlaney @briandavidson @ASprinkle The forest has updated its **Season End Date to January 6, 2020.**

I created the following PR to make this update: https://github.com/USDAForestService/fs-open-forest-platform/pull/884

**Comment by ASprinkle** [comment]
@briandavidson Looks good!!!  Christian had some issues with the Willamette staging site during the presentation yesterday: 404 error when clicking to view maps, progress bar not loading with dotted line and arrow, error when trying to access pay.gov. I was not able to recreate those issues today.  So, on ward!
