### ISSUE TITLE
cloud.gov intermittent redis failures - login to manage OF apps fail

### ISSUE THREAD

**Issue by mwreiss** [USDAForestService/fs-open-forest-platform#801]
## Notes
cloud.gov has a intermittent service failures (https://cloudgov.statuspage.io/ ) creating an issue with the OF team to login and authenticate to the OF environments. The OF applications are still up and running, access and management to the OF environment is failing.

## Acceptance Criteria
- [ ] cloud.gov issues are resolved

## Tasks
- [ ] Email the cloud.gov team
- [ ] Test access once cloud.gov GSA team has resolved the infrastructure issues

## Definition of Done
- [ ] Access to the cloud.gov environment is working

**Comment by abdul1234e** [comment]
![image](https://user-images.githubusercontent.com/31516419/63177316-a82edb00-c015-11e9-9fab-bc7da3f7888e.png)

![image](https://user-images.githubusercontent.com/31516419/63177925-f1cbf580-c016-11e9-8efe-ad06e30601a0.png)

@mwreiss Thanks for tracking this. we can access now in cloud.gov

**Comment by ASprinkle** [comment]
PO approved.
