### ISSUE TITLE
As the POC for Umatilla Open Forest, I want to review and have Christmas tree permit content updated so that I know the information is correct before the season starts.

### ISSUE THREAD

**Issue by lisamcmichael** [USDAForestService/fs-open-forest-platform#802]
## Notes
See EPIC 799
Word document on Box: https://usfs.box.com/s/7kszxuet7a0kssh56b2e1e9ekk59xdc0

## Acceptance Criteria
- [x] POC reviewed and approved content
- [x] POC approved any backlog content ( if there is any for next season)
- [x] The Forest's content has been updated based on Forest POC review.

## Tasks
- [x] Start scheduling content review with POC
- [x] Complete a demo with the forest, collect feedback
- [x] Review findings with PO

 _Implement changes_
- [x] Season dates: Nov 18, 2019 – Dec 31, 2019 
- [x] Cost: [use this updated info] Christmas trees cost $5.00 each, and a household is allowed to cut one tree, which includes taking a minor amount of bough material (tree branches up to 25 lbs. can be removed from the forest). All permits are non-refundable. 
- [x] Prohibited areas and restrictions: 
Include this under the headline: Cut trees only within the national forest boundary and respect surrounding private property.
- [x] No cutting or removing trees within, indent these 2 bullet points:
Park and Cook Ridges.
Lick Creek area, including Sheep Creek, Cabin, Capehorn and Mud Springs ridges.
- [x] No cutting or removing trees within, remove the "s" from sales. Bullet point should read: Active timber sale areas.
- [x] Measuring your tree, change Stump height to read: 10 inches maximum

- [x] Identifying tree species

**Subalpine Fir**
Image on Arapaho site and here: https://plants.usda.gov/java/largeImage?imageID=abla_001_ahp.tif]
Has ¾-inch needles.
Needles are single on the twig, blunt or notched at the tip, and flattened.
Tree bark is smooth and grayish-white with pitch blisters.

**Grand Fir** 
Image on Flathead site and here: https://plants.usda.gov/java/largeImage?imageID=abgrg_001_ahp.tif
Has up to 2-inch needles.
Needles are dark green on the upper side and silver-white on the lower side.
Needles are flat with a notch in the tip. The needles grow off the twig in a way that makes the branch look flat.	

**Englemann Spruce**
Image on Arapaho site and here:  https://plants.usda.gov/core/profile?symbol=PIEN&photoID=pien_002_ahp.tif#
Has 1-inch needles.
Needles are prickly to the touch and pointed, the same color on all sides, and they radiate in all directions on the twig.
Tree bark is thin and scaly, and grayish-red to purplish-brown.

**Douglas-fir**
Image on Arapaho site: 
Has 1- to 1 ½-inch needles.
Needles hold a blue to dark green color.
Needles radiate in all directions on the twig and are generally soft to the touch. The shape and positioning of needles on the twig make it resemble a pipe cleaner or bottle brush.
Can turn brown faster than other Firs even if put immediately into water after harvesting.

- [x]  How to plan your trip: 
Add this sentence as the first bullet point in the list: 
•	Do not park at a Sno-Park unless you have a valid Sno-Park permit displayed in your vehicle.
- [x] Contact us:
Remove link to "Umatilla National Forest ranger district offices)
Add link to "[local vendors](https://www.fs.usda.gov/detail/umatilla/news-events/?cid=FSEPRD603154)" 
- [x] Contact us: include addresses after intro paragraph:
Umatilla National Forest Headquarters
72510 Coyote Road
Pendleton, OR 97801
541-278-3716

Pomeroy Ranger District
71 West Main
Pomeroy, WA 99347
509-843-1891

Walla Walla Ranger District
1415 West Rose St.
Walla Walla, WA 99362
509-522-6290

- [x] Under the Contact Us: Wrap the address so that the City, State, Zip displays under the Street info.

- [x] ALT Text and Tags added to images (provided by POC)

- [x] Forest POC has been informed of updates.
- [x] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested with forest

**Comment by lisamcmichael** [comment]
@carlsonem @ASprinkle **Started scheduling the forest.**

**Comment by lisamcmichael** [comment]
Completed content review with Umatilla National Forest

**Comment by ASprinkle** [comment]
I made some of the updates to content and checked boxes for ones I completed.

**Comment by ASprinkle** [comment]
@briandavidson I just checked my work on the Contact Us part of this story. It looks like on staging my updates are there, but the format isn't right. I don't know how to make the address appear so that it is wrapped in this fashion:
Street
City, State Zip
![image](https://user-images.githubusercontent.com/33435621/65270172-76ef7200-dacf-11e9-9ac2-adefbea7ecd2.png)

**Comment by briandavidson** [comment]
Hey @ASprinkle, I can touch it up for you if you want -- an extra line is needed in between the street and city/state/zip.

**Comment by ASprinkle** [comment]
@briandavidson that would be great since you're in there! :) thanks Brian

**Comment by briandavidson** [comment]
@ASprinkle actually what I said earlier was incorrect, I apologize!

Apparently to get the line to wrap once two spaces are required i.e.:
```
First line<blank space><blank space>
Second line
<blank line>
Third line
```
Kind of a wonky syntax in my opinion. I'll make sure it's correct.

**Comment by briandavidson** [comment]
@lisamcmichael and @ASprinkle, do we have map alt text for Umatilla? I'm not seeing any in the docs I have.

**Comment by ASprinkle** [comment]
@briandavidson I do not believe we have any Christmas tree cutting maps for the Umatilla. Some forests do not have special maps. so we've linked to their Maps and Publications Page

**Comment by lisamcmichael** [comment]
@briandavidson Morning! Are you set for ALT text for the Tree Species images?

FYI: ALT Text for Maps created by Amber (should a forest have them): https://usfs.box.com/s/45xmzk04xm09so39dah104m2l3jvagf0

**Comment by briandavidson** [comment]
Hi @lisamcmichael, to my knowledge I'm all set however I haven't made any changes to the existing ALT text for any tree species images.

**Comment by briandavidson** [comment]
@lisamcmichael I'm also a little confused about the remaining task regarding cost. The cost for trees at Umatilla is already 5 and the limit per household is already 1. I'm not sure what to we are trying to do with the rest of the info provided for that update.

**Comment by lisamcmichael** [comment]
We are good to go on ALT text for images.

About the "cost" content, it is confusing as written. I've updated it to:
Cost: [use this updated info] Christmas trees cost $5.00 each, and a household is allowed to cut one tree, which includes taking a minor amount of bough material (tree branches up to 25 lbs. can be removed from the forest). All permits are non-refundable. 

Any questions, just lmk.

**Comment by briandavidson** [comment]
Ok sounds good @lisamcmichael !
