### ISSUE TITLE
As the POC for Okanogan-Wenatchee Open Forest, I want to review and have Christmas tree permit content updated so that I know the information is correct before the season starts.

### ISSUE THREAD

**Issue by lisamcmichael** [USDAForestService/fs-open-forest-platform#804]
## Notes
See EPIC #799
On Pinyon/Box: https://usfs.box.com/s/i9gdbrkyk6i62ffv07viv6upoayk5tq8

## Acceptance Criteria
- [x] POC reviewed and approved content
- [x] POC approved any backlog content ( if there is any for next season)
- [x] The Forest's content has been updated based on Forest POC review.

## Tasks
- [x] Start scheduling content review with POC
- [x] Complete a demo with the forest, captured input
- [x] Review findings with PO
- [x] **Implement changes:**
- [x] Season dates
- [x] Nov 1, 2019 – Dec 31, 2019
- [x] WHEN TO CUT TREES: note that "... a household is allowed to cut up to **2 trees.**  [not 5]
- [x] WHERE TO CUT YOUR TREE: **Fix a typo.** It should read "No cutting or removing trees within:", the "or" shows as "ore on the website". AND, the statement "No cutting or removing trees within:" should be bold.
                    (---Amber updated this the typo and the bolding, but the commit failed.)
- [x] CUTTING AREA MAPS: add this before the first map: Cut trees only in cutting areas shown in green on these maps.
- [x] CUTTING AREA MAPS: **add 3 maps** in this order: Wentachee, Leavenworth, Chelan. Above each map add this text (respectively as): 
Christmas tree map of Wenatchee Area. (Click to view larger map)
Christmas tree map of Leavenworth Area. (Click to view larger map) 
Christmas tree map of Chelan Area. (Click to view larger map)
- [x] HELPFUL CUTTING TIPS: ADD this as the last bullet, "Cut your tree a bit longer than you'll need (6-12"), so you'll have room to make a fresh cut on the bottom before putting it in water."

- [x] IDENTIFYING TREE SPECIES: 

ADD these species:
Noble Fir
[Get Image from Mt. Hood site]
•	Has 1-inch needles.
•	Needles are bluish-green with a silvery appearance and point upward from the twig.
•	Has short, stiff branches great for heavier ornaments.
•	Holds needles and maintains color well.
Subalpine Fir
[Get Image from Arapaho site]
•	Has ¾-inch needles.
•	Needles are single on the twig, blunt or notched at the tip, and flattened.
•	Tree bark is smooth and grayish-white with pitch blisters.
Pacific Silver Fir
[Get Image from Mt. Hood site]
•	Has flat 3/4 - to 1 ½-inch needles.
•	Needles are dark green on top with white lines underneath.
•	Needles point forward and upward rather than lying flat.
•	Stay green and holds needles well.
Douglas-fir
[Get image from Arapaho site]
•	Has 1-1 ½-inch needles.
•	Needles hold a blue to dark green color.
•	Needles radiate in all directions on the twig and are generally soft to the touch. The shape and positioning of needles on the twig make it resemble a pipe cleaner or bottle brush.
•	Can turn brown faster than other Firs even if put immediately into water after harvesting.
Grand fir
[Get image from Flathead site]
•	Has up to 2-inch needles.
•	Needles are dark green on the upper side and silver-white on the lower side.
•	Needles are flat with a notch in the tip. The needles grow off the twig in a way that makes the branch look flat.

- [x] Under the last tree add: "Photos courtesy of USDA Natural Resources Conservation Service."

HOW TO PLAN YOUR TRIP: 
- [x] Add this as a FIRST bullet point: "Do not park at a Sno-Park unless you have a valid Washington State Sno-Park permit displayed in your vehicle." 
- [x] Add this as a SECOND bullet point:  A valid [Recreation Pass](https://www.fs.usda.gov/main/okawen/passes-permits/recreation) is required at designated recreation fee sites.
- [x] CONTACT US: "... ["local vendors"] should be a hyperlink (https://www.fs.usda.gov/detail/okawen/passes-permits/forestproducts/?cid=fsbdev3_053596) 
- [x] CONTACT US: **include this info** before the addresses: "A PDF version of our Christmas Tree cutting information is available to view or print in either English or Spanish."

[English version](https://www.fs.usda.gov/Internet/FSE_DOCUMENTS/stelprdb5397463.pdf)[Spanish version](https://www.fs.usda.gov/Internet/FSE_DOCUMENTS/stelprdb5397464.pdf
)
- [x] CONTACT US: Wenatchee River Ranger District is **missing phone number** "509-548-2550".
- [x] ALT Text and Tags added to images (provided by POC)

- [x] Forest okayed tree species
- [x] *Forest provided maps*
- [x] Forest POC has been informed of updates.
- [x] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested with forest

**Comment by ASprinkle** [comment]
@lisamcmichael I received this information after our Kick Off workshop:

[Christmas tree info 2018.pdf](https://github.com/USDAForestService/fs-open-forest-platform/files/3536620/Christmas.tree.info.2018.pdf)

[Christmas tree info spanish 2018.pdf](https://github.com/USDAForestService/fs-open-forest-platform/files/3536621/Christmas.tree.info.spanish.2018.pdf)

**Comment by lisamcmichael** [comment]
@carlsonem @ASprinkle **Started scheduling the forest for next week.**

**Comment by lisamcmichael** [comment]
@ASprinkle 
Although the forest's content review is next week, Leo sent changes to us and I'll start those now.

**Comment by lisamcmichael** [comment]
**From Amber**
-	We won’t be changing the language except for the Oka-Wen tree limit. So it should read “Christmas trees cost $5 each, and a household is allowed to cut up to 2 trees.  All permits are non-refundable.”
o	If this continues to be a pain point/question for Leo/Oka-Wen team, then I can give them a call. It’s fairly clear in the text that the “tree” costs $5, and a household is allowed up to 2 “trees”. These limits will be built into the Open Forest system, so a person will physically not be able to purchase more than 2 trees/permit in one transaction.

-	Again, more sno-parks language. I think we should add a logo in the how to plan your trip section at least for R6 Forests.

Other items of interest RE tree care and transportation. I would not like to add more text to the info page. We will have a link back to the Forest’s website.  We could also add a PDF download of their brochure. I think other forests that have brochures may want to do this as well.

**Comment by lisamcmichael** [comment]
I've updated Oka-Wen based on the latest input from the forest, and your edits/input @ASprinkle. One question I have is about Sno-Park, using the Sno-Park Logo. We should be able to fit it into our meeting today.

**Comment by lisamcmichael** [comment]
**Box File (Word Document) with the above Notes included.**
https://usfs.box.com/s/925ecz07dtc95voi9m52f8ohwbnficwl

**Comment by lisamcmichael** [comment]
@ASprinkle now that we've reviewed this, is it okay to check off the  "reviewed and approved"? Thx.

**Comment by ASprinkle** [comment]
Yes for PO reviewed, I'll do PO approved after their review is done next week

**Comment by ASprinkle** [comment]
@lisamcmichael here is the language with the hyperlink specific to the OkaWen: A valid Recreation Pass is required at designated recreation fee sites

https://www.fs.usda.gov/main/okawen/passes-permits/recreation

**Comment by lisamcmichael** [comment]
@ASprinkle the only _follow-up_ I have is obtaining bullet points for the additional species. I'll follow-up w/ the Forest.

**Comment by ASprinkle** [comment]
@lisamcmichael let me draft something for them to just approve/review

**Comment by ASprinkle** [comment]
I made this update: WHERE TO CUT YOUR TREE: Fix a typo. It should read "No cutting or removing trees within:", the "or" shows as "ore on the website". AND, the statement "No cutting or removing trees within:" should be bold.

**Comment by ASprinkle** [comment]
Changed the sno-park language to be consistent with how it reads for the GP as well. We'll use "A Washington Sno-Park permit is required for parking at designated Sno-Parks." for washington sno-park info.

**Comment by lisamcmichael** [comment]
@briandavidson @ASprinkle **Updated season END date based on input from the forest.**

**Comment by briandavidson** [comment]
@ASprinkle / @lisamcmichael do we have the cutting area map files for this?

**Comment by lisamcmichael** [comment]
> @ASprinkle / @lisamcmichael do we have the cutting area map files for this?

Brian - I don't think we do. I will contact the forest POC and "cc" Amber.

**Comment by ASprinkle** [comment]
@lisamcmichael @briandavidson The Oka-Wen maps as they are now do not have legends, or a north arrow or a scale bar or anything.
I think the forest would have to recreate something potentially – which we don’t want them to have to do.

If we aren’t getting good maps/files from a forest, we can just keep the setup we have on the website and link to their Christmas tree page where they have maps posted already.
![image](https://user-images.githubusercontent.com/33435621/65522976-6c9ef080-dea0-11e9-96af-0a46b7bba3c5.png)

If we don't get something back from them today/tomorrow. I am OK with maintaining what we have on Open Forest currently (a link back to their forest site), so that we can can continue forward with our progress.

**Comment by lisamcmichael** [comment]
The Forest  (Leo) asked their Web Editor for maps... "coming soon". So @ASprinkle and @briandavidson, we might receive something 'decent' enough to use. If not, we have a backup plan (a link back to their forest's site).

**Comment by briandavidson** [comment]
@lisamcmichael and @ASprinkle I went ahead and dug for the maps on fs.usda.gov site and I believe I've found what we need.

As you said Amber: "The Oka-Wen maps as they are now do not have legends, or a north arrow or a scale bar or anything."

I just merged this into dev a few minutes ago so we should be able to check out what they look like on staging in a few minutes. If we don't want to use them we can easily revert to the system that we had per your suggestion Amber.

**Comment by briandavidson** [comment]
Wenatchee Area:
![image](https://user-images.githubusercontent.com/5187168/65535647-d71b5500-decf-11e9-8a61-ad380ca0518c.png)

**Comment by briandavidson** [comment]
Leavenworth Area:
![image](https://user-images.githubusercontent.com/5187168/65535714-f1553300-decf-11e9-9c78-20f47d3c6fa0.png)

**Comment by briandavidson** [comment]
Chelan area:
![image](https://user-images.githubusercontent.com/5187168/65535748-ffa34f00-decf-11e9-97cb-b9e63d50e268.png)

**Comment by lisamcmichael** [comment]
@ASprinkle Is it worth asking Leo to see if his Web Editor can provide that info, so long as the maps look good?

**Comment by lisamcmichael** [comment]
@briandavidson and @ASprinkle 

Hi Lisa,
I took those little maps off the firewood page on our website a long time ago since they weren’t really needed and only confused people, and they shouldn’t be used anywhere else. If you need JPGs of the large maps that are part of the permit handout ( in PDF format on website), I can get those to you. Let me know. They are located here:

https://www.fs.usda.gov/Internet/FSE_DOCUMENTS/stelprd3828476.pdf
https://www.fs.usda.gov/Internet/FSE_DOCUMENTS/stelprd3828475.pdf
https://www.fs.usda.gov/Internet/FSE_DOCUMENTS/stelprd3831617.pdf
https://www.fs.usda.gov/Internet/FSE_DOCUMENTS/stelprd3831618.pdf
https://www.fs.usda.gov/Internet/FSE_DOCUMENTS/stelprd3831621.pdf

**Comment by lisamcmichael** [comment]
@ASprinkle I am sending the email to you (from Daniel O'Connor) about the new maps.

**Comment by ASprinkle** [comment]
@briandavidson Please do not use the PDF maps ^ Those are "woodcutting" maps. 
For cutting areas for the Oka-Wen: let's leave it the way you've got it in staging now. If we need to make a change later per the forest POC we can do that. Thanks Brian and Lisa!
@lisamcmichael 

![image](https://user-images.githubusercontent.com/33435621/65623048-cf18ef00-df7b-11e9-8124-1cebaa1be98c.png)

![image](https://user-images.githubusercontent.com/33435621/65623025-c0323c80-df7b-11e9-996d-3e7a32d87be4.png)
