### ISSUE TITLE
As the Mt. Baker-Snoqualmie Open Forest POC, I want to review and have Christmas tree permit content updated so that I know the information is correct before the season starts.

### ISSUE THREAD

**Issue by lisamcmichael** [USDAForestService/fs-open-forest-platform#805]
## Notes
See EPIC #799
Word doc on Pinyon: https://usfs.box.com/s/dcsdh3pdjgh3yibwt192dzthxxpcxuz0

## Acceptance Criteria
- [x] POC reviewed and approved content
- [x] POC approved any backlog content ( if there is any for next season)
- [x] The Forest's content has been updated based on Forest POC review.

## Tasks
- [x] Start scheduling content review with POC
- [x] Complete a demo with the forest, captured input
- [x] Review findings with PO

- [ ]* _Implement changes_*
- [x] Include "National" in every reference to the forest as: Mt. Baker-Snoqualmie National Forest (including breadcrumb trail) 
- [x] Season dates are: Nov 12, 2019 - Dec 30, 2019
- [x] PROHIBITED AREAS AND RESTRICTIONS: Remove "Download our Christmas Tree Cutting Sheet"
- [x] HOW TO CUT YOUR TREE (read as): Stump height: 12 inches maximum. 
- [x] HOW TO CUT YOUR TREE:  Tree height: 15 feet maximum
- [x] HOW TO CUT YOUR TREE (read as): "Remove snow _from_ around tree base so you can..." 
("from" missing on staging site)
- [x] HOW TO CUT YOUR TREE (add): To cut a tree over 12 feet tall, a permit must be purchased in person at a forest ranger district office.  
         - [ ] MBS updated 9/18 Tree Height to 15 Feet
- [x] HOW TO PLAN YOUR TRIP: Add the following at the beginning of the bullet-ed list: 	
- Parking at a Sno-Park requires a valid Sno-Park permit displayed in your vehicle.
- Parking at a trailhead may require a NW Forest Pass or Federal Interagency Pass.
- [x] CONTACT US: change the hyperlink for [local vendors](https://www.fs.usda.gov/detail/mbs/news-events/?cid=STELPRDB5440163)
- [x] CONTACT US: Add this under the last address: Visit [Mt. Baker-Snoqualmie National Forest](https://www.fs.usda.gov/main/mbs/home) for more information.
- [x] ALT Text and Tags added to images (provided by POC)
- [x] Tree species are okay-ed by the forest

**_NEW UPDATE_** within IDENTIFYING TREE SPECIES
- [x] Add Western Hemlock 
- [x] Add Photo: https://plants.usda.gov/java/largeImage?imageID=tshe_012_ahp.tif
- [x] Add bullet points describing western hemlock:

- Avoid using this as a Christmas tree, sheds needles quickly and often.
- Can turn brown faster than other trees even if put immediately into water after harvesting
- Needles are irregular, and generally less than a three-quarters inch in length.
- Cones are small, scaly, and hanging at the end of the twig.

- [x] Forest POC has been informed of updates.
- [x] *NEW UPDATE 9.26* - Add 2 maps (PDF), see comments below
- [x] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested with forest

**Comment by lisamcmichael** [comment]
@ASprinkle and @carlsonem This forest is scheduled for a content review on Wed. 9/4 with Rebecca.

**Comment by lisamcmichael** [comment]
Completed review with POC

**Comment by ASprinkle** [comment]
I made some of the updates to content and checked boxes for ones I completed.

**Comment by ASprinkle** [comment]
MBS Updated Tree Height to 15 feet maximum 9/18

**Comment by ASprinkle** [comment]
@briandavidson here is the Alt Text for the MBS' Maps....

**Comment by briandavidson** [comment]
Okay cool, I think Lisa might have included those in the files she gave me too but I wasn't totally clear if they were the ones provided by POC -- thanks Amber!

**Comment by ASprinkle** [comment]
@briandavidson we didn't get any Alt Text from POCs... I created the Alt Text in a vacuum based on what the maps displayed.

**Comment by lisamcmichael** [comment]
Good morning @ASprinkle and @briandavidson. I rec'd a request from Rebecca and wanted to see if we could do this for her. 

_"I had a request to include Western Hemlock as a species to avoid.  Could we add Western Hemlock as a species at the bottom of the Mount Baker-Snoqualmie (MBS) “Identifying Tree Species” with “avoid” next to it?"_

**Comment by ASprinkle** [comment]
@lisamcmichael 
Yes. I'd follow same photo protocol as other photos. Do not add the word "avoid" as a call out in the photo like we do for prohibited species. 

Photo: https://plants.usda.gov/java/largeImage?imageID=tshe_012_ahp.tif

In the bullet list describing western hemlock:
- Avoid using this as a Christmas tree, sheds needles quickly and often.
- Can turn brown faster than other trees even if put immediately into water after harvesting 
- Needles are irregular, and generally less than a three-quarters inch in length.
- Cones are small, scaly, and hanging at the end of the twig.

**Comment by ASprinkle** [comment]
@briandavidson I removed the "add prohibited label" task... it's not a prohibited species... just one to avoid that the MBS would like to call out. No special labels.

**Comment by ASprinkle** [comment]
@briandavidson the MBS tree height should be 15 feet. Looking on staging it still says 12 feet. Perhaps I checked staging too soon?
![image](https://user-images.githubusercontent.com/33435621/65539643-af6fc100-debe-11e9-972b-b4ff5c781325.png)

We'll need to remove this scentence. The Forest recently sent and update saying that they are only offering the one kind of permit option this year:
"To cut a tree over 12 feet tall a permit must be purchased in person at a forest ranger district office."
![image](https://user-images.githubusercontent.com/33435621/65539761-f067d580-debe-11e9-89d6-7eddccd66e26.png)

**Comment by briandavidson** [comment]
@ASprinkle CircleCI says it got deployed to staging so it looks like the seeder is probably not running. I'll make sure it builds correctly before moving them to awaiting acceptance going forward.

**Comment by lisamcmichael** [comment]
@briandavidson and @ASprinkle **I just rec'd this from the forest. Let me know if it can go on the site (is reworkable), or if you need a different file format, or something else. Thx.**

[Mt. Baker Chirstmas tree maps.pdf](https://github.com/USDAForestService/fs-open-forest-platform/files/3659931/Mt.Baker.Chirstmas.tree.maps.pdf)

**Comment by briandavidson** [comment]
Hey @lisamcmichael - yah we can put that on the site, but it will just be as a text link directly to the PDF file. If we had an image file we could actually display it. As for format we seem to be using JPG for the other map image files.

**Comment by lisamcmichael** [comment]
Hi again @briandavidson and @ASprinkle  - before I respond to Rebecca at MtB-S Forest, I want to clarify something. _Their site has maps displayed, and those will be removed and in place of them we'll have a text link to the new PDF maps._  Also, if she wants to have the "new" maps displayed, we'll need JPG files. 

Sound good?

**Comment by ASprinkle** [comment]
@lisamcmichael it sounds like @mtlaney can convert PDFs to jpg files... Mike?

**Comment by mtlaney** [comment]
> @lisamcmichael it sounds like @mtlaney can convert PDFs to jpg files... Mike?

yes, if we have a high enough quality pdf I can convert to png or jped

**Comment by ASprinkle** [comment]
@mtlaney quick ? - why can't we have downloadable PDFs on the page vs. .png files?

**Comment by briandavidson** [comment]
> @mtlaney quick ? - why can't we have downloadable PDFs on the page vs. .png files?

@ASprinkle not to speak for @mtlaney here of course, but i'm thinking maybe my prior comment was misleading.

we can definitely have downloadable PDFs on the page, they just won't appear as images on the site unless we convert them to actual image files.

after quick chat with Mike, i'm gonna go ahead and take a crack at the conversion and try to wrap this issue up.

**Comment by briandavidson** [comment]
@mtlaney I don't have access to adobe and tried doing the conversions using GIMP and they came out poor quality. Already mentioned this to you on slack but just wanted to note it here on the issue as well for reference.

**Comment by mtlaney** [comment]
@lisamcmichael @ASprinkle 

Help me out quick with these maps and the comment below:
Hi again @briandavidson and @ASprinkle - before I respond to Rebecca at MtB-S Forest, I want to clarify something. Their site has maps displayed, and those will be removed and in place of them we'll have a text link to the new PDF maps. Also, if she wants to have the "new" maps displayed, we'll need JPG files.

MBS currently has 5 maps on the site:
North Bend, Enumclaw 1, Enumclaw 2, Enumclaw 3, and Skykomish. Do we want to add the two new maps so we have a total of 7? Or remove the first 5 and replace with links and only have the new 2 maps?

Also, for the 2 new maps, should they be called North Fork Nooksack Area and Skagit area as labeled, or something else entirely?

**Comment by ASprinkle** [comment]
@mtlaney  I left a voicemail for Rebecca to confirm - waiting for a call back... unless @lisamcmichael  has more insight on the expectations. Thanks!

**Comment by lisamcmichael** [comment]
@mtlaney @ASprinkle  
Thx for reaching out to Rebecca to confirm her expectations.  I am looking through notes now to see if there's something I can confirm w/ Mike to help unblock progress.

**Comment by lisamcmichael** [comment]
@mtlaney - Sorry I don't have more definitive info. There will be **7 total maps** (see below her note). I assume the names are _North Fork Nooksack Area and Skagit_. 

From Rebecca: "I just had some Christmas tree maps sent to me.  Is it possible to add them to Open Forest (Mount Baker-Snoqualmie page)?"

**Comment by ASprinkle** [comment]
@lisamcmichael Those are good assumptions on the titles.
@mtlaney  I'll make any notes for additional updates here when I hear back from Rebecca, but I don't think I will have anything to share that would be different from what lisa updated.

**Comment by ASprinkle** [comment]
@mtlaney we now need to remove this information from the MBS site: "To cut a tree over 12 feet tall a permit must be purchased in person at a forest ranger district office."

**Comment by briandavidson** [comment]
@mtlaney and @ASprinkle i created a PR to remove that line of text.

**Comment by ASprinkle** [comment]
Approved! @briandavidson
