### ISSUE TITLE
As the Gifford-Pinchot Open Forest POC, I want to review and have Christmas tree permit content updated so that I know the information is correct before the season starts.

### ISSUE THREAD

**Issue by lisamcmichael** [USDAForestService/fs-open-forest-platform#806]
## Notes
See EPIC #799
Word doc on Pinyon: https://usfs.box.com/s/isrlg9j03ud34biylneml4svo0wjmlea

## Acceptance Criteria
- [x] POC reviewed and provided content updates
- [x] POC approved any backlog content ( if there is any for next season) 
- [x] The Forest's content has been updated based on Forest POC review.

## Tasks
- [x] Start scheduling content review with POC
- [x] Complete a demo with the forest, captured input
- [x] Review findings with PO

- [x] *Implement changes:* 
- [x] Updated Season Dates: Nov 1, 2019 - Dec 31, 2019

- [x] *Add the following under “Prohibited areas and restrictions”*:
- [x] Cut trees only within the national forest boundary and respect surrounding private property.
- [x] A Washington Sno-Park Permit is required for parking at designated Sno-Parks.
- [x] A valid Recreation Pass is required at designated recreation fee sites.
- [x] Make “Recreation Pass” a link to the recreation passes info on GPNF website. https://www.fs.usda.gov/main/giffordpinchot/passes-permits/recreation

- [x] REPLACE CONTACT US information with: You can buy Christmas tree permits in person at the following Gifford Pinchot National Forest ranger district offices or at local vendors. Each district office has different hours during the Christmas tree cutting season. Call first to make sure someone is available to sell permits. All offices are closed on federal holidays.
- [x] Use this link to link "local Vendors" to the forest's site: https://www.fs.usda.gov/detail/giffordpinchot/passes-permits/forestproducts/?cid=fsbdev3_005072
- [x] Address for Mt Adams Ranger District should be 2455 Highway 141 (not 12455).
- [x] The forest is missing "National" in its title: Visit [Gifford Pinchot](https://www.fs.usda.gov/giffordpinchot/) National Forest for more information.
- [x] ALT Text and Tags added to images (provided by POC)

- [x] Forest POC has been informed of updates.
- [x] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested with forest

**Comment by lisamcmichael** [comment]
@ASprinkle

**Comment by carlsonem** [comment]
@mtlaney ready for development

**Comment by ASprinkle** [comment]
@mtlaney 

This is looking really good. 
Can we stick the line under "Identifying Tree Species" just like the one underneath  "Helpful Cutting Tips"
![image](https://user-images.githubusercontent.com/33435621/64649064-0bbbe680-d3d1-11e9-8bc9-7dd7c2848adb.png)

Also, I "Inspected" the tree species images for Alt Text and am showing a screen shot of what I was looking for. Is it correct to assume that if it says something next to "alt:" in this screen shot, that it is the "alt text" provided for the image?
![image](https://user-images.githubusercontent.com/33435621/64649169-39089480-d3d1-11e9-962a-7ff122889121.png)

**Comment by mtlaney** [comment]
@ASprinkle not sure why your line isn't there. Maybe try hard refreshing your browser? I can see the line on my end in staging and dev.

<img width="1226" alt="Screen Shot 2019-09-11 at 6 58 00 AM" src="https://user-images.githubusercontent.com/18233188/64691873-b976d600-d461-11e9-86df-3183bad023f8.png">

**Comment by lisamcmichael** [comment]
@ASprinkle and @mtlaney  we could make this a bit more explicit with 
alt: "Noble Fir photo"

**Comment by ASprinkle** [comment]
@mtlaney What page where you on when you viewed it? 

When I looked this morning I deleted all my history, files and refreshed my browser etc. Had to sign back in to staging even..

I am able to see the line in staging under Identifying Tree Species on the Arapaho Roosevelt, Deschutes, Flathead, Fremont-Winema, Rogue River-Siskiyou, Shoshone,

I do not see a line under Identifying Tree Species for the Gifford Pinchot, Mt. Hood, Umatilla, and Willamette.

For the Okanogan-Wenatchee and Mt. Baker-Snoqualmie, the line is present under Identifying Tree Species, but missing under Helpful Cutting Tips.

If this isn't an easy 5min find/fix, we can create a story to address it. Just LMK.

**Comment by mtlaney** [comment]
@ASprinkle that's really wierd. I'm just at https://open-forest-staging.app.cloud.gov/christmas-trees/forests/giffordpinchot and can see the line

**Comment by ASprinkle** [comment]
Ok. perhaps it's an odd issue only on my end.

**Comment by ASprinkle** [comment]
@mtlaney lets push this to Prod so that we can so small pushes at a time in case there are any issues.
