### ISSUE TITLE
As the Fremont-Winema Open Forest POC, I want to approve Christmas tree permit content before it goes live to the public.

### ISSUE THREAD

**Issue by lisamcmichael** [USDAForestService/fs-open-forest-platform#807]
## Notes
See EPIC #799

## Acceptance Criteria
- [ ] Reviewed and approved "MVP" website content
- [ ] Approved backlog content (for next season) 

## Tasks
- [ ] Complete a demo with the forest, captured input
- [ ] Review findings with PO
- [ ] Implement changes
- [ ] Forest approved
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested with forest

**Comment by lisamcmichael** [comment]
@carlsonem @ASprinkle **Started scheduling the forest.**

**Comment by lisamcmichael** [comment]
@ASprinkle The content review was completed with Seana and Annette, and it's marked that way above. I am setting this to In Progress.

**Comment by lisamcmichael** [comment]
Started making updates to the forest's content.

**Comment by ASprinkle** [comment]
@lisamcmichael when you say "started making content updates" do you mean in Staging? or in a word doc for the dev team? I want to make sure we follow a process for review before we push changes to staging for review, and then to Production.

**Comment by lisamcmichael** [comment]
I started making updates (above under Implement Changes) and to the Word doc. Updates are still underway.

**Comment by lisamcmichael** [comment]
Annette and Seana mentioned pets not on a leash can pose problems. @ASprinkle is this more "forest" content than "Open Forest" content?

**Comment by lisamcmichael** [comment]
All content revisions added; several follow-ups with the Forest are note w/in Tasks. Contacted the Forest, Annette and Seana.

**Comment by ASprinkle** [comment]
> Annette and Seana mentioned pets not on a leash can pose problems. @ASprinkle is this more "forest" content than "Open Forest" content?

Yes, that is more a forest concern. we're not going to put that kind of content on the Open Forest site at this time. Forest visitors should be able to find other general information about visiting national forest lands on other websites. good call.

**Comment by lisamcmichael** [comment]
Moved to Blocked, waiting on Forest for followups

**Comment by lisamcmichael** [comment]
Forest will have the missing information soon. Updated tree species, and cutting area maps.

**Comment by lisamcmichael** [comment]
*The Forest provided Christmas Tree info flyer* - making updates to the above follow- ups.

Box/Pinyon: https://usfs.box.com/s/d89fj1fdrzx5ml15d2zu346yzpboukp2

**Comment by lisamcmichael** [comment]
@ASprinkle, the forest has a _max. tree height of 20 feet on its flyer_. I recall that anything over 12 feet is not a Christmas Tree product/permit/FLREA. _So, I set the tree height at 12 feet for Fre-Win._ 
Let me know if that needs changing. Thx!

**Comment by ASprinkle** [comment]
@lisamcmichael WAHOO! we have their info!  We will put onto Open Forest anything the forest tells us to.  I agree 20' feet is far and above what the regional standard is for a "Christmas tree" but that is not our decision. I will inform them that the Region's definition of a Christmas tree is 15 feet max.
I will include you on the email for awareness.

**Comment by lisamcmichael** [comment]
Changed tree height to "15" feet

**Comment by lisamcmichael** [comment]
@ASprinkle This is ready for development.
