### ISSUE TITLE
As an Open Forest Researcher, I want to summarize R6 Christmas Tree Permitting Kickoff Workshop findings so that we can make informed decisions about feature enhancements for Open Forest.

### ISSUE THREAD

**Issue by lisamcmichael** [USDAForestService/fs-open-forest-platform#809]
## Acceptance Criteria
- [x] Forests' hopes/fears, sails/anchors and priorities are organized, and prioritized.
- [x] Forests' maps are analyzed and any unique findings documented.
- [x] Key findings are shared with the PO.

## Tasks
- [x] Summarize findings, and highlight anything new, along with patterns 
- [x] Meet with PO and PM to review and determine what, if any, new cards need creating.
- [] Create new cards - if needed

## Definition of Done
- [ ] Enhancements for 2019 season are implemented.
- [ ] Backlog items for next season are included or not included, and then prioritized.

**Comment by lisamcmichael** [comment]
[ Open Forest R6 Workshop - Product Backlog, Findings - 08.13.19.xlsx](https://github.com/USDAForestService/fs-open-forest-platform/files/3517013/Open.Forest.R6.Workshop.-.Product.Backlog.Findings.-.08.13.19.xlsx)

@amber I will find time with you later this week to go over these.

**Comment by lisamcmichael** [comment]
During content reviews, explore each of these if applicable. 

- Service First: responsibility shared with BLM (RogueRS, Willamette) (FS lands and BLM lands might share neighboring boundaries, so the idea is to make it easier for the public to get permits that could be shared between forests)
- Unique Tree sizes, two different sizes, two different costs (Open Forest isn't going to include multiple sizes/costs, but need to capture that info). Over sized trees may not fall w/in REC.
- Sharing permits between forests (vs. land managers); are there expectations that a permit will be valid across more than 1 forest?

**Comment by ASprinkle** [comment]
@lisamcmichael I think this story is done, do you agree?

**Comment by lisamcmichael** [comment]
Hi @ASprinkle - I followed up w/ Willamette, and Christian said that the new permitting process clears up his "pain point" issuing permits to vendors.
