### ISSUE TITLE
As an Open Forest team member, I am onboarding to the FS laptop so that I can use it to work on OF.

### ISSUE THREAD

**Issue by lisamcmichael** [USDAForestService/fs-open-forest-platform#810]
## Notes
* Nothing specific to note *

## Acceptance Criteria
- [ ] *setup FS laptop for USDA emails, meetings and for...*
- [ ] ... Github and Zenhub access
- [ ] ... Pinyon access
- [ ] ... storing and accessing Open Forest files
- [ ] ... collaborating on Teams, Skype and Slack
- [ ] ... storing key information such as passwords to FS accounts

## Tasks
- [ ] Finish acceptance criteria by 8/23

## Definition of Done
- [ ] Using FS laptop for the above

**Comment by carlsonem** [comment]
Move to program board
