### ISSUE TITLE
As a christmas tree hunter on the Flathead NF I want to be informed about prohibited species so that I can follow the rules.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#812]
## Notes
* What are things we should consider when making this story *
From Michelle Owens: "I was asked if we could list White Pine and Western White Pine to the do not harvest list for the Flathead? They are both 5 needle pines and our Silviculturist has asked that they both be listed as do not cut. "

## Acceptance Criteria
- [ ] White Pine is listed as a "prohibited" species in the Identifying Tree Species Section
- [ ] Western White Pine is listed as a "prohibited" species in the Identifying Tree Species Section

## Tasks
- [ ] Obtain photo of pines
- [ ] Add photo to the Identifying Tree Species section
- [ ] Verify the identifying description with the Forest Silviculturist
- [ ] Add the description texts to the corresponding photos
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
![image](https://user-images.githubusercontent.com/33435621/63448563-07646500-c3f3-11e9-9486-721fc2461fae.png)

**Comment by ASprinkle** [comment]
![image](https://user-images.githubusercontent.com/33435621/65909767-235a0f80-e37e-11e9-8793-72fb914f388c.png)
![image](https://user-images.githubusercontent.com/33435621/65909773-26550000-e37e-11e9-9059-4a3b5a08d3ae.png)
![image](https://user-images.githubusercontent.com/33435621/65909780-2a811d80-e37e-11e9-9a37-2606091ea1aa.png)
