### ISSUE TITLE
BUG As a FS administrator I want to know that when I my season dates don't change in Production unless I am updating it in Production.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#813]
## Notes
* What are things we should consider when making this story *
The Mt. Hood, Arapaho and Roosevelt, and Flathead National Forests had their season dates open from 2018-2021 with the buy permit button actionable on the production site. I went in and updated the season dates for 2018, so that it was closed. 
I generated a report to verify no permits had been issued. 

I checked again on the morning of 8/21, and the same forests were open again 2018-2021 (Mt. Hood, Flathead, ARP).  I generated a report to verify no permits had been issued.  

I checked again on the morning of 8/22 and they were all open again.  

Also some forests have season start dates in 2019, and season end dates in 2018 showing on the production page.

Screen shot examples of workflow provided in the comments.

## Acceptance Criteria
- [x] All forests show that "Christmas tree season is closed and online permits are not available."
- [x] All forests show "Dates not yet available" in the green season dates box on the info page.
- [x] For multiple days in a row, the "Buy Permit" button is not actionable on the Production Site.
- [x] Any fixes have been made if needed.

## Tasks
- [x] tasks list needs dev team refinement for this story
- [x]  Turn off the midnight recycle... Temporarily disable the midnight re-build until we can pinpoint the issue.
- [x] Test the production site to make sure the "buy permit" button isn't renabled.
- [x] Reinstate the landing page once the bug has been fixed.
- [x] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
Blocked - waiting to see if the issue presents itself again after today.

**Comment by ASprinkle** [comment]
**On Production, Arapaho and Roosevelt forest page with buy permit button actionable:**
![image](https://user-images.githubusercontent.com/33435621/63525471-9c7a6300-c4b2-11e9-902b-7d041b72a997.png)

Logged in as Admin in Production to check/change season dates:
![image](https://user-images.githubusercontent.com/33435621/63525501-ab611580-c4b2-11e9-8a95-aa3ff60b91f7.png)
![image](https://user-images.githubusercontent.com/33435621/63525518-b0be6000-c4b2-11e9-8e7d-bdd8fa93cef0.png)
![image](https://user-images.githubusercontent.com/33435621/63525532-b5831400-c4b2-11e9-9ff9-fc50cd357b04.png)

Verified on Production that the ARP season dates are updated on the site:
![image](https://user-images.githubusercontent.com/33435621/63525557-c2a00300-c4b2-11e9-9fca-e29483f8b74e.png)

Verified in production that no permits had been issued recently for the ARP, Flathead, or Mt. Hood
![image](https://user-images.githubusercontent.com/33435621/63525592-cf245b80-c4b2-11e9-94ea-6dee139266ff.png)
![image](https://user-images.githubusercontent.com/33435621/63525748-0c88e900-c4b3-11e9-8460-860e9c0988ee.png)
![image](https://user-images.githubusercontent.com/33435621/63525761-127eca00-c4b3-11e9-87e0-ec4c0edbf5d7.png)

**Comment by ASprinkle** [comment]
@mtlaney I reviewed the seeder file code changes and approved the #815

**Comment by ASprinkle** [comment]
@mtlaney I checked again this evening (10pm PST) and the ARP, Mt. Hood, and Flathead had the buy permit button activated again in PROD through 2021.  I went in through PROD Admin and updated the season dates to show the season is closed. Ran a report to ensure no permits had been issued. Here are my screen shots. 
[2021 Season Dates Bug 8232019 10pm.docx](https://github.com/USDAForestService/fs-open-forest-platform/files/3536883/2021.Season.Dates.Bug.8232019.10pm.docx)

**Comment by ASprinkle** [comment]
@mtlaney @abdul1234e It looks like this issue hasn't been fixed over the weekend. A permit was issued from the production site for the Arapaho Roosevelt. Have all of the reviews and approvals been completed? Was this story pushed through? Is there an issue with the pull requests?

**Comment by ASprinkle** [comment]
Update 9/3: Update on bug fix / recycle job. This morning Abdul manually ran recycle on PROD, with success, the dates did not revert. After than I added a recycle job to staging just to verify, that recycle job ran at 1:30PM with no dates reverted. We have now pushed to PROD, our next recycle job will run at 4:30PM and should complete by 4:35PM. Assuming it goes as planned, and dates do not revert, I will change the recycle job to return to it's original time, and publish a release to capture these changes

**Comment by ASprinkle** [comment]
[1:38 PM] Laney, Michael - FS
    Recycle has ran successfully at 4:30. PROD Dates did not revert. We are g2g

**Comment by ASprinkle** [comment]
@mtlaney this is great news! I updated the tasks to add "Reinstate the landing page once the bug has been fixed".  once that is done, I think we can call this wrapped up. Agreed?

**Comment by mtlaney** [comment]
@ASprinkle agreed, moving to awaiting acceptance, it's on prod already, so once you verify you are happy with the status we can move to done
