### ISSUE TITLE
As a forest service administrator I do not want Christmas tree permits active for purchase outside of the season so that people aren't confused about when they can get a Christmas tree.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#817]
## Notes
* What are things we should consider when making this story *

The purpose of this story is to inactivate the production site to the public facing user while the site is under construction.

## Acceptance Criteria
- [x] The public cannot access information about Christmas trees while the site is under construction.
- [x] The public cannot access the buy permit button while the site is under construction.
- [x] The public is informed that "The site is under construction in preparation for the coming holiday season".
- [x] We have an understanding of why the BUG story 813 fixes were not successful.

## Tasks
- [x]  A final test on 9/3 to verify Circle recycle jobs are good to go. For now they are still disabled until the final test is done.
- [x] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by abdul1234e** [comment]
@ASprinkle @mtlaney Please perform the validation in production and staging. and review if the dates are still showing incorrect.

**Comment by ASprinkle** [comment]
@abdul1234e 
In staging - I had set the dates for 2024 in my last review. I checked the ARP, Mt Hood and Flathead. All sites still show 2024, which means that dates are not reverting in staging.
![image](https://user-images.githubusercontent.com/33435621/63992793-6afd2b00-caa2-11e9-8685-38ea673fb40f.png)
![image](https://user-images.githubusercontent.com/33435621/63992799-6e90b200-caa2-11e9-8c4f-45fe0cd0dcf1.png)
![image](https://user-images.githubusercontent.com/33435621/63992801-72bccf80-caa2-11e9-87c1-8be4f5971f09.png)

When I checked in PROD:
The dates have not reverted for all three forests. The "buy permit" button is not active the pages.
I checked the landing pages (screen shots below), and the change season dates pages.
![image](https://user-images.githubusercontent.com/33435621/63992943-202fe300-caa3-11e9-970c-d751bad46560.png)
![image](https://user-images.githubusercontent.com/33435621/63992948-24f49700-caa3-11e9-9ef3-d89ec21ce5c3.png)
![image](https://user-images.githubusercontent.com/33435621/63992956-29b94b00-caa3-11e9-985d-1d08d3d924e7.png)

**Comment by abdul1234e** [comment]
@ASprinkle Thank you amber for validating this.

**Comment by mwreiss** [comment]
Notes from the security/eng./dev meeting 8/30/19:  This is to address the nightly Circle environment recycle job.  

@ASprinkle @aaronburk  The team is going to do a final test on Tuesday to verify Circle recycle jobs are good to go.  For now they are still disabled until the final  test is done.

![image](https://user-images.githubusercontent.com/50459930/64036725-78a1c780-cb19-11e9-9709-9e028e0478b1.png)

**Comment by ASprinkle** [comment]
@mwreiss thanks for the update on this!
