### ISSUE TITLE
Change forest selector bg color to green *USDA Pipeline Demo*

### ISSUE THREAD

**Issue by mtlaney** [USDAForestService/fs-open-forest-platform#836]
## Notes
As a customer, I would like to see the forest selector in a green color instead of brown to properly indicate christmas

## Acceptance Criteria
- [x] USA-Hero changed from brown to green

## Tasks
- [x] Update SCSS files

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested
