### ISSUE TITLE
As an OF Admin for a forest I want to be added so that I can do admin things in staging and in production.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#839]
## Notes

*Ideally we can add these individuals using the new user management tool we're building in Open Forest* 

Through more discussions with pilot forests, the following individuals also need to be added to the Open Forest system as an Admin

Add Jason Page jason.page@usda.gov back in to the system for the Mt. Hood NF (Read/Write: Generate Reports/Set Season Dates)

Add Leonardo Silva leonardo.silva@usda.gov as an admin for the Okanogan-Wenatchee (Read: Generate Reports)

Add Chamise Kramer chamise.kramer@usda.gov as an admin for Rogue River-Siskiyou NF (Read: Generate Reports)

Add Charlotte Kennymore charlotte.kennymore@usda.gov as a Regional admin for the Arapaho and Roosevelt and Shoshone NFs (Read/Write: Generate Reports/Set Season Dates)

## Acceptance Criteria
- [x] Chamise is added as an admin
- [x] Jason is added as an admin
- [x] Leo is added as an admin
- [x] Charlotte is added as an admin
- [] We know the admin access levels for all other white listed admins
- [] We have created follow up tasks if needed to update admin access permissions.

## Tasks
- [] Meet with team to review admin access levels for all white listed admins.
- [x] Add Chamise as an admin for RRS (generate reports)
- [x] Inform Chamise she's been added and request her to verify access
- [x] Add Jason as an admin for MTH (generate reports change season dates)
- [x] Inform Jason he's been added and request him to verify access
- [x] Add Leo as an admin for  Oka-Wen (generate reports)
- [x] Inform Leo he's been added and request him to verify access
- [x] Add Charlotte as an admin for R2 (ARP and SHO) (generate reports change season dates)
- [x] Inform Charlotte, she's been added and request her to verify access
- [x] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
@abdul1234e this story and the program board stories 138 and 139 (adding Dylan and Rebekah) should all be done at the same time.  @carlsonem

**Comment by abdul1234e** [comment]
they are added in production including rebeeka and dylan.

**Comment by ASprinkle** [comment]
Thanks @abdul1234e I will contact the forest POCs to inform them, and ask them to test their access.

**Comment by ASprinkle** [comment]
Both Leo and Charlotte checked their access to https://openforest.fs.usda.gov/admin/christmas-trees/reports and they receive  a white blank page.
![AdminBlankPage](https://user-images.githubusercontent.com/33435621/68145602-09669c00-feeb-11e9-952f-890bb17414d9.png)

**Comment by ASprinkle** [comment]
Confirmed that Chamise Kramer has access : "Seems to work for me, Amber!"

**Comment by ASprinkle** [comment]
Charlotte needed to download and access admin via Chrome.  Admin access via IE (and removing usda.gov compatibility view settings) resulted in this view. 
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/33435621/68236781-aba18500-ffba-11e9-8363-5d23e8c07772.png)

**Comment by ASprinkle** [comment]
Hello @abdul1234e Charlotte Kennymore tested her admin functions, and this is what she sees when she logs in as an admin.  No forests are listed.  Is there a bug with trying to assign multiple forests to one person?
She should see the Arapaho and Roosevelt and the Shoshone National Forest, which are both Region 2 forests.
![AdminNoForests](https://user-images.githubusercontent.com/33435621/68402101-a7e33f00-012f-11ea-91f5-b17a06864d67.png)

**Comment by abdul1234e** [comment]
{
          "admin_username": "CHARLOTTE_KENNYMORE",
          "forests": [
            "region2"
          ]
        },

yes it seems to be a bug because in her admin right, she has multiple forest. i tried adding her with commas first that didn't work then adding individual forest with her name even that didn't work.

Then finally i added her with region2 as you suggested.

**Comment by ASprinkle** [comment]
Ahh... ok, well, I am going to guess that since "Region 2" does not exist in the system, that it won't work... Since we determined we are not currently able to specify certain forests, can we add her to all forests then?  Should I create a new story for that?

**Comment by abdul1234e** [comment]
yes amber. i was going to suggest you the same to add her in all forests.

sounds good.

**Comment by ASprinkle** [comment]
Created story #1031 to address multi-forest admins
