### ISSUE TITLE
As an Open Forest Super Admin I would like a way to review submitted feedback within the Open Forest system so that I can access the information easily.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#840]
## Notes

This story has to do with being able to see and review the feedback has been received.

## Acceptance Criteria
- [x] Feedback received from public and internal forests are displayed by super admin

## Tasks
- [x] Design feedback screen
- [x] Store data from the public feedback
- [x] Store data from the internal FS users
- [x] Code to be able to display feedback from public
- [x] Code to be able to display feedback from internal FS users
- [x] Be able to export reports to excel spreadsheet (use report generated code as applicable)
- [] Conduct usability testing
- [x] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [] Usability tested

**Comment by lisaredux** [comment]
@ASprinkle this is ready for your review https://xd.adobe.com/view/a4f7b920-6330-4f2a-6cdc-3a0fcd11a431-d2c6/screen/d0efead3-c42b-4411-ab88-621ca3528237/STORY-776-INTRO-1?fullscreen

**Comment by ASprinkle** [comment]
@briandavidson I see this story in Awaiting Acceptance, but I when I check staging, I do not see anything. I will check again tomorrow morning. Thanks

**Comment by briandavidson** [comment]
@ASprinkle hi Amber, this is and the related user feedback stories are ready for you to checkout on staging.

**Comment by ASprinkle** [comment]
@briandavidson are you available to meet up at the moment?

**Comment by ASprinkle** [comment]
@briandavidson  It looks like the text is not wrapping in the table. Can we get the dates to read across one line, and get the text to wrap?
![image](https://user-images.githubusercontent.com/33435621/67816217-7e0e8600-fa66-11e9-8b76-5cfa2149d121.png)

It looks like I have to zoom out to 33% in order to see the full extent of the table while in Open Forest 
![image](https://user-images.githubusercontent.com/33435621/67816257-9e3e4500-fa66-11e9-96b0-af025deda203.png)

**Comment by ASprinkle** [comment]
![image](https://user-images.githubusercontent.com/33435621/67901949-4a466580-fb25-11e9-95e3-5d56483d7ebc.png) 
Looks really great!! @briandavidson @mtlaney
