### ISSUE TITLE
SPIKE Research and Contacts to add the Ochoco NF to the Open Forest System

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#841]
## Notes
* What are things we should consider when making this story *
This story captures the work to be completed before adding the Ochoco NF to the Open Forest system

## Acceptance Criteria
- [x] We have support from the Forest Supervisor.
- [x] We have support from WO.
- [x] We have support from RO.
- [x] We have an understanding of what we need to add the Ochoco to the system.
- [x] We have created and prioritized the adding the Ochoco if supported.

## Tasks
- [x] Confirm with WO leadership that this addition is supported given our time constraints.
- [x] Confirm with RO leadership that this addition is supported given our time constraints.
- [x] Confirm with Forest-level leadership that this is something they indeed want.
- [x] Obtain a list of contacts for the Ochoco.
- [x] Know whom should be added as an administrator to the Ochoco.
- [x] Reach out to Todd Harbin to confirm lift for adding another Forest to POSS for Open Forest.
- [x] PO approved.

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
Hi Amber,
From Brian Tandy: 8/30/2019
They are managed together in that they are virtually identical with the same (cutting rules and specifications, etc.).  We use the same “Guidelines for collecting your Christmas tree” flyer that contains cutting rules and specs, etc. for both Forests (see attached).  I think you could copy the Deschutes Open Forest webpage and use it intact, with some minor changes (Office addresses and phone numbers) for the Ochoco NF.   I am the point of contact for both Forests as I am the Forest Products Program Manager (that includes timber and SPF) for both Forests.   Also, we don’t use maps but rely on the flyer on where folks can cut their trees.  If a particular unit does use a map they are generalized maps on where folks can find particular species of trees to cut.

[Guidelines for collecting your Christmas tree - Deschutes & Ochoco National Forests.pdf](https://github.com/USDAForestService/fs-open-forest-platform/files/3576588/Guidelines.for.collecting.your.Christmas.tree.-.Deschutes.Ochoco.National.Forests.pdf)

**Comment by ASprinkle** [comment]
From Amber to Brian Tandy:
I have connected with our WO and RO leads regarding the request to add the Ochoco National Forest. We would like to see a message from the Ochoco National Forest’s Forest Supervisor stating that the Forest would like to be added to Open Forest for this coming pilot. Preferably this message would include the forest’s NR staff, Rec staff and Public Affairs staff at minimum, and other points of contact.

Given the information you provided about the content required for the Ochoco NF Christmas tree program, and considerations, I believe our Open Forest team should be able to add the Ochoco National Forest as an option in the Open Forest system within our timeframe.  That said, if we were to identify a significant risk or blocker to the ability to add it to the system, we would not add it, and we would certainly communicate that to you all in a timely manner.

Once we receive that message from the Ochoco NF Forest Supervisor I will coordinate a meeting with the Ochoco NF staff to bring folks up to speed, provide a demonstration of the site, and begin working with our developers to add the Ochoco NF.

**Comment by ASprinkle** [comment]
Open Forest POC for Ochoco NF:

Brian Tandy - Forest Products and Silv Program Lead brian.tandy@usda.gov
Kevin Keown - Natural Resources Staff Officer kevin.keown@usda.gov
Chris Joosen - Recreation Staff Officer christopher.joosen@usda.gov
Beccie Sakraida - Resource Specialist rebecca.sakraida@usda.gov

**Comment by ASprinkle** [comment]
Waiting on email from the OCH forest sup

**Comment by ASprinkle** [comment]
[Fwd_ Adding Ochoco to Open Forest pilot.pdf](https://github.com/USDAForestService/fs-open-forest-platform/files/3596719/Fwd_.Adding.Ochoco.to.Open.Forest.pilot.pdf)
