### ISSUE TITLE
As the Ochoco NF Open Forest POC, I want to review and have Christmas tree permit content updated so that I know the information is correct before the season starts.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#842]
## Notes
See EPIC #799
[Ochoco National Forest](https://www.fs.usda.gov/main/ochoco/home) home page

## Acceptance Criteria
- [x] POC reviewed and approved content
- [x] POC approved any backlog content ( if there is any for next season)
- [x] The Forest's content has been updated based on Forest POC review.

## Tasks
- [x] Copy the finalized content from the Deschutes POC review story #808.
- [x] Receive support message from the Ochoco NF Forest Supervisor/Leadership
- [x] Add Ochoco NF to drop down box once support message is received.
- [x] Research and add the Ochoco NF specific Contact Us information - this is different from the 
- [x]  Org Code 060607
- [x] POSS Item ID Code is Ochoco National Forest – 999900016
Deschutes Page
- [x] Add Contact Us information:

_Ochoco National Forest_
3160 NE Third Street
Prineville, Oregon 97754
(541) 416-6500

_Crooked River National Grassland_
274 SW 4th Street
Madras, Oregon 97741
(541) 416-6640
- [x] Confirm Contact Us information with Forest
- [] Design the Permit to say that it is valid on the "Deschutes and Ochoco National Forests" instead of only the Ochoco National Forest.
- [x] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
From Todd Harbin: Regarding adding the Ochoco item, once the item is created, it will get the following accounting:
Transaction type: MP
Revenue Source: 105

•	Ochoco National Forest – **Item Number TBD**
o	5% FDDS36 0627, 95% FDDS36 0607

**Comment by lisamcmichael** [comment]
@ASprinkle, this is what I understand to be the plan 
- "copy Deschutes" and change the "contact info"
- when Ochoco is on staging, send a note to Brian and Jeremy to review it

@carlsonem, including you for "fyi"

**Comment by ASprinkle** [comment]
@lisamcmichael Yes!  We'll want to copy the Deschutes page once the edits from the POC review have been completed, so that we don't have to make the same changes twice.

**Comment by lisamcmichael** [comment]
@mtlaney When you have "5" grab time with me, Amber and Lisa S.

**Comment by lisamcmichael** [comment]
@ASprinkle, @mtlaney  and @carlsonem, this could be moved out of blocked and to "in progress". I'll send a meeting invitation for a content review with Ochoco (Brian, Jeremy right?) to capture the updates for its Open Forest site. After that, Mike and/or Brian will update Ochoco's OF site, and we'll follow-up with the Forest by email. Make sense?

**Comment by lisamcmichael** [comment]
@ASprinkle, is this a developer task?
Copy the finalized content from the Deschutes POC review story #808.

**Comment by ASprinkle** [comment]
@lisamcmichael yes. a developer task. We should provide the new contact us information since that is the only change.

**Comment by lisamcmichael** [comment]
@ASprinkle Brian/Jeremy confirmed the Contact Us info.

**Comment by lisamcmichael** [comment]
@carlsonem I wasn't sure if it was clear, this is ready for development to start on the first task:  _Copy the finalized content from the Deschutes POC review story #808._

**Comment by ASprinkle** [comment]
Thanks @lisamcmichael I moved it to ready

**Comment by ASprinkle** [comment]
Waiting on the POSS Item number to develop the forest's seeder file.

**Comment by ASprinkle** [comment]
@carlsonem can you help us track down a POSS code for the Ochoco? I emailed Todd Harbin and Jamin Bhatt today asking for it.

**Comment by carlsonem** [comment]
@ASprinkle certainly! I'll also ask if they were able to verify the test permits that we ran.

**Comment by carlsonem** [comment]
I chatted with Jamin and he will get the items done this week.

**Comment by ASprinkle** [comment]
From Jamin 9/24:

•	Deschutes National Forest - 999900008
•	Rogue River-Siskiyou National Forest - 999900009
•	Mt. Baker/Snoqualmie National Forest - 999900010
•	Okanogan-Wenatchee National Forest - 999900011
•	Willamette National Forest - 999900012
•	Umatilla National Forest - 999900013
•	Gifford Pinchot National Forest - 999900014
•	Fremont-Winema National Forest – 999900015
•	Ochoco National Forest – 999900016

**Comment by briandavidson** [comment]
@ASprinkle would it be alright if we addressed having the permits display both Deschutes and Ochoco in a follow up issue? 

As it is right now each forest will display their own name like the permits for every other forest. This change would be to the permit printing service which seems to me like a different task than adding the forest.

**Comment by briandavidson** [comment]
^ confirmed with amber that permit task will be handled in this follow up issue: https://github.com/USDAForestService/fs-open-forest-platform/issues/843

**Comment by ASprinkle** [comment]
@briandavidson I don't see Ochoco as a selection option yet.. but maybe it's going to take another minute to update on staging?

**Comment by briandavidson** [comment]
After we merge the branch back into dev, the CircleCI workflow begins. Part of that workflow includes the job to deploy the code to the staging environment.

You can see that job's progress here: https://circleci.com/workflow-run/539e9df9-6c33-4f28-8d05-f4d3f68cd1ef

Once that finishes, you should see Ochoco as an option.

**Comment by briandavidson** [comment]
@ASprinkle oh but I did move it to awaiting acceptance too soon then -- I should have waited for that to complete, apologies!
