### ISSUE TITLE
As a Deschutes NF employee I want to be sure that the Christmas tree permit is valid for the Deschutes and the Ochoco NFs so that forest visitors continue to have a good experience.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#843]
## Notes
* What are things we should consider when making this story *

The Deschutes and Ochoco NFs operate their Christmas tree programs in a similar way, managed by the same individual. Their visiting public expect their Christmas tree permits to be applicable across the Deschutes and the Ochoco no matter which forest's office the permit is purchased from.

The Open Forest printed permit should list both forest's names on it instead of one or the other.

## Acceptance Criteria
- [x] A permit printed from the Deschutes page purchase process reads: "Deschutes and Ochoco National Forests" on it.
- [x] A permit printed from the Ochoco page purchase process reads: "Deschutes and Ochoco National Forests" on it.

## Tasks
- [x] Design permit
- [x] Update code to allow permit to display multiple forest names on the printed permit as applicable
- [x] Test to ensure permits are displaying name correctly
- [x] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by lisaredux** [comment]
@ASprinkle Here is the permit updated to show what it would look like: [Permit-Open Forest-Descutes-Ochoco-Story843.pdf](https://github.com/USDAForestService/fs-open-forest-platform/files/3602087/Permit-Open.Forest-Descutes-Ochoco-Story843.pdf)

Let me know if this misses the intent of this story, and I will refactor.
<img width="486" alt="Screenshot 2019-09-11 13 51 06" src="https://user-images.githubusercontent.com/26801590/64721841-438f6080-d49b-11e9-930f-e27a375e0c02.png">

**Comment by lisamcmichael** [comment]
@lisaredux See related story 842; basically Mike's going to 'copy' Deschutes to make the Ochoco site; after that we'll update the Contact Us info. That's about it, especially because the Permit is designed! No need to regroup.

**Comment by ASprinkle** [comment]
Awesome. One tweak @mtlaney can we put an "s" at the end of "FOREST" so that it reads "Deschutes and Ochoco National Forests"?
Once we do that, we'll be set to move to master! :)
Version from the Deschutes - looks great!
![image](https://user-images.githubusercontent.com/33435621/66516035-09fb4680-ea95-11e9-9379-803ef8685f5d.png)

Version from the Ochoco - Looks great!
![image](https://user-images.githubusercontent.com/33435621/66516041-0c5da080-ea95-11e9-905f-92314b026774.png)

**Comment by ASprinkle** [comment]
![image](https://user-images.githubusercontent.com/33435621/66593095-2c4f9b80-eb4b-11e9-83aa-fa3e261892a7.png)
Awesome!
