### ISSUE TITLE
Change Selector BG Color **CIO CI/CD DEMO**

### ISSUE THREAD

**Issue by mtlaney** [USDAForestService/fs-open-forest-platform#845]
## Notes
With the upcoming christmas season, I would like to see the Forest Selector BG color on the home page be green instead of brown.

## Acceptance Criteria
- [x] Selector BG color is now Green

## Tasks
- [x] Change Color
- [x] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested
