### ISSUE TITLE
As an OF Admin I want the rules section to specify that a permit is not replaceable so that people understand the permit limitations

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#850]
## Notes

![image.png](https://images.zenhubusercontent.com/5a00e34b8a75884b90864b6f/094b69e2-32c9-4ba1-875e-32bc6c3abae2)

Change "Is non-transferrable and non-refundable". 

TO 

"Is non-transferrable, non-replaceable, non-refundable".

Per POC reviews during R6 Scale Up

## Acceptance Criteria
- [x] The rules and guidelines specific to the permit have been updated to reflect the non-replaceable language.

## Tasks
- [x]  Update the Permit specific rules so that the information is updated for each forest.
- [x] PO approved

## Definition of Done
- [x] Pull requests meet technical definition of done
- [x] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
![image](https://user-images.githubusercontent.com/33435621/68315501-b74d8400-006c-11ea-9ad9-2609057859cc.png)
