### ISSUE TITLE
As an OF Admin I would like to test the Generate Report function to see how it works, so that I know what to expect prior to the season starting.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#852]
## Notes
* What are things we should consider when making this story *

Only 5 of the forest's "Generate Reports" tab seems to be working (Mt Hood, Flathead, Shoshone, ARP, and MBS).  When I try to generate a report for all of the other Forests in staging, this is the page I am taken to:
![image.png](https://images.zenhubusercontent.com/5a00e34b8a75884b90864b6f/e290cbd2-09ab-4509-8c46-82e5f7552fdb)

## Acceptance Criteria
- [x] All forest's Generate Reports pages work in staging
- [x] The report generated correctly reflects "staging site issued" permits 

## Tasks
- [x] Diagnose the reason a report can't be run in staging
- [x] Fix the issue
- [x] Test the issue
- [x] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by carlsonem** [comment]
Hasn't worked since the new forests were added to the system

**Comment by ASprinkle** [comment]
## Generate Report by date range Attempts Successful for:
Arapaho and Roosevelt
Flathead
Mt. Hood
Shoshone

## Generate Report by date range Attempts Failed for:
Gifford Pinchot
Fremont-Winema
Mt. Baker-Snoqualmie
Deschutes
Willamette
Rogue River-Skiskiyou
Okanogan-Wenatchee
Umatilla
Ochoco (Before purchasing a test permit, I generated a report, and the page successfully loaded informing me that no permits had been issued. When I completed a purchase for the Ochoco in staging, and tried to generate a report showing that purchase, I received a 404 Page not found error - I continued to receive this error after multiple date range attempts).
All Forests

## Generate Report by permit number Successful Attempts (only some are listed. I did not test all the way back into August.
Ochoco 00000495 9/30/2019
Rogue River-Siskiyou 00000494 9/30/2019
Rogue River-Siskiyou 00000490 9/27/2019
Fremont-Winema 00000492 9/27/2019
Flathead 00000492 9/30/2019
Umatilla 00000491 9/27/2019
Oka-Wen 00000489 9/27/2019
 00000488 Not Found
 00000487 Not Found
Flathead 00000486 9/26/2019
Arapaho and Roosevelt 00000485 9/26/2019
 00000484 Not Found
Arapaho and Roosevelt 00000483 9/26/2019
Mt. Baker Snoqualmie 00000482 9/25/2019
Arapaho and Roosevelt 00000481 9/24/2019
Willamette 00000480 9/24/2019
Willamette 00000479 9/24/2019
Mt. Baker Snoqualmie 00000478 9/19/2019
Gifford Pinchot 00000477 9/19/2019
Mt. Baker Snoqualmie 00000476 9/19/2019
Mt. Baker Snoqualmie 00000475 9/18/2019
Mt. Baker Snoqualmie 00000474 9/18/2019
00000473 Not Found
Mt. Baker Snoqualmie 00000472 9/18/2019
Willamette 00000471 9/16/2019
Shoshone 00000470 9/16/2019

**Comment by ASprinkle** [comment]
@briandavidson In PROD running a report by date range for ALL Forests is working.
![image](https://user-images.githubusercontent.com/33435621/66152885-47f8f600-e5cf-11e9-8795-fc5a9fc48802.png)

It looks like a few forests are working correctly.. I didn't test all of them
![image](https://user-images.githubusercontent.com/33435621/66152979-7971c180-e5cf-11e9-8f92-76a280c0db03.png)

BUT in Staging, running a report prior to a permit being issued was working (given the Ochoco example)... I would be curious to know if I were to purchase a permit in PROD with real money, I wonder if the report feature would work in PROD, or if it would reflect the bug that occurs in staging...

**Comment by briandavidson** [comment]
Hi @ASprinkle this should be good to go now, ready for you to take a look at on staging.

**Comment by ASprinkle** [comment]
@briandavidson awesome!
![image](https://user-images.githubusercontent.com/33435621/66354430-a8629d00-e919-11e9-89eb-2efe3592d8da.png)
