### ISSUE TITLE
As the Open Forest researcher, I want to recruit and schedule usability test participants to determine if Admin Roles can perform admin functions based on access level.

### ISSUE THREAD

**Issue by lisamcmichael** [USDAForestService/fs-open-forest-platform#856]
## Notes
* What are things we should consider when making this story *

_See #855_
- What are our sources for recruiting participants? Internal only? 
- This will need support from the PO to identify who to recruit.

## Acceptance Criteria
- [ ] 

## Tasks
- [ ] Recruit / schedule
   - [ ] Meet with PO for recruitment, get contact names from PO  
   - [ ] Create Recruitment email and Consent form
          - [ ] PO approval (consent form and recruitment email)
   - [ ] Designer(s) create a Calendly account   
   - [ ] PO/Designer(s) send Recruitment email with Consent form
   - [ ] Set up participant scheduling/confirmation Tracker (Excel file)
   - [ ] Confirm participants' test dates
           - [ ] Receive signed consent form
   - [ ] Send reminder email to participants (day before test) 
   - [ ] Update Tracker when a test is completed, rescheduled, or no-show (upload to Pinyon Research folder

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by lisamcmichael** [comment]
@lisaredux I've added you as back-up in case I need some help, and to join the planning meeting w/ Amber.

**Comment by ASprinkle** [comment]
For the Shoshone:
Paul Rau paul.rau@usda.gov
Kristie Salzmann kristie.l.salzmann@usda.gov

For the Arapaho Roosevelt:
Tammy Williams tammy.j.williams@usda.gov
Laura Schaffer laura.c.shaffer@usda.gov
Jodi King jodi.king@usda.gov

**Comment by ASprinkle** [comment]
Update 9/27
requires approval of the test plan 
may require staging site being ready. some testing could occur using mock ups.

**Comment by lisaredux** [comment]
I'm currently working on the prototype to test #689 with Admins. For testing, it will be implemented into Invision

**Comment by ASprinkle** [comment]
Closing based on results of SPIKE story #922 - Open Forest will not house a unique admin user management system.
