### ISSUE TITLE
As a forest visitor I want see the same information on the Rules and Guidelines page as what I read on the Forest's Information page so that I am not confused about what is required.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#861]
## Notes
* What are things we should consider when making this story *

We need to verify that the content updates from the general information page for each forest are also correctly reflected in the Rules and Guidelines page that the permit holder agrees to prior to purchasing a permit, AND that they are correctly reflected in the Rules and Guidelines page that is available for printing/emailed to them at the end of their purchase.

## Acceptance Criteria
- [x] Stories for Rules and Guidelines have been created so that they mirrors the rules and guidelines that are provided on the information page.  
- [x] The information is verified as correct by Open Forest team member, OR a story has been created to remedy a found inconsistency.

## Tasks
- [x] Compare Rules and Guidelines page and Information Page for the Gifford Pinchot
    - [x] Amber
- [x] Compare Rules and Guidelines page and Information Page for the Umatilla
    - [x] Lisa S / See #868  (has the updated Rules and Guidelines for developers)
- [x] Compare Rules and Guidelines page and Information Page for the Oka-Wen
    - [x] Lisa S / See #870 (has the updated Rules and Guidelines for developers)
- [x] Compare Rules and Guidelines page and Information Page for the MBS
    - [x] Lisa S / See #871 (has the updated Rules and Guidelines for developers)
- [x] Compare Rules and Guidelines page and Information Page for the Willamette
     - [x] Lisa M / See #864 (has the updated Rules and Guidelines for developers)
- [x] Compare Rules and Guidelines page and Information Page for the RRS
     - [x] Lisa M / See #866 (has the updated Rules and Guidelines for developers)
- [x] Compare Rules and Guidelines page and Information Page for the Fre-Win
     - [x] Lisa M / See #875 
- [x] Compare Rules and Guidelines page and Information Page for the Deschutes
     - [x] Lisa M / See #873  (has the updated Rules and Guidelines for developers)
- [x] Compare Rules and Guidelines page and Information Page for the Ochoco
     - [x] Lisa M/ See #874 (has the updated Rules and Guidelines for developers)
- [x] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
Using the Gifford Pinchot pages as an example:
The information page shows the following rules and guidelines:
![image](https://user-images.githubusercontent.com/33435621/65076344-a5ddda80-d94d-11e9-9c51-9efaace7c5a3.png)
![image](https://user-images.githubusercontent.com/33435621/65076349-a9716180-d94d-11e9-822e-741d9b8884dd.png)

The Rules and Guidelines page is shows this information specific to Christmas tree cutting:
![image](https://user-images.githubusercontent.com/33435621/65076445-d9b90000-d94d-11e9-819a-96eee2562518.png)

The GP rules and guidelines page need the following updates:
Add: "Your tree must be equal to or less than 12 feet in height."
Add: "No cutting or removing trees within:
- Congressionally designated Wilderness Areas.
- Mount St. Helens National Volcanic Monument.
- Experimental forests.
- Developed campgrounds.
- Administrative sites.
- Within 300 feet of streams.
- On private or state-owned lands within national forest boundaries.
- In any other posted area.
Add: "A Washington Sno-Park Permit is required for parking at designated Sno-Parks."
Add: "A valid [Recreation Pass](https://www.fs.usda.gov/main/giffordpinchot/passes-permits/recreation) is required at designated recreation fee sites."
Remove "Cutting is prohibited in plantations, previously thinned stands of trees, timber sale areas, or areas posted as closed to Christmas tree cutting."
Remove "You must choose a tree at least 200 feet away from main roads, recreation sites and campgrounds, and 300 feet away from streams, rivers or lakes."
Remove "Do not remove Whitebark Pine trees."

**Comment by ASprinkle** [comment]
Another example from the MBS: “Where to cut your tree” it shows “within 150 feet” but when you print the rules after purchasing the permit shows “within 200 feet”

**Comment by ASprinkle** [comment]
What is a Rule/Guideline:
saved to Pinyon Content folder: https://usfs.box.com/s/jvb2krshkj71ak006fc1e1tnkzmkptro
[What is a Rule.docx](https://github.com/USDAForestService/fs-open-forest-platform/files/3628438/What.is.a.Rule.docx)

**Comment by lisamcmichael** [comment]
@lisaredux and @ASprinkle As for a status, it looks like _GP is finished_ (Amber) and added to _story #863_.  Also, I set this story to In Progress.

NEXT:
I am taking Willamette. I'll create a "rules and guidelines" story (based on the GP example #863).

**Comment by lisaredux** [comment]
Thanks @lisamcmichael - I am working on Umatilla

**Comment by ASprinkle** [comment]
Awesome!!  @lisamcmichael @lisaredux I think screen shots would be helpful too. I'd also note that not all of the content review updates have gone through staging yet, so the information on the staging site won't be POC approved necessarily.  We may just need to create Rules and Guidelines stories for each forest that pair with the content updates... :/

**Comment by lisaredux** [comment]
@ASprinkle great idea. I'm collecting the differences on a Word doc with screenshots etc in the meantime.

**Comment by lisamcmichael** [comment]
So @ASprinkle and @lisaredux  I went through the forest's R/G content and cleaned up a few typos. They're ready for Amber to review them for consistency.
