### ISSUE TITLE
Add an Ability to Re-issue Lost Permits

### ISSUE THREAD

**Issue by carlsonem** [USDAForestService/fs-open-forest-platform#862]
## Notes
* What are things we should consider when making this story *

## Acceptance Criteria
- [ ]

## Tasks
- [ ] Confirm PII Rules
- [ ] Research method to recover a lost permit
- [ ] Implement code to be able to recover a lost permit
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by smahmudFS** [comment]
@ericsorenson @briandavidson Hi - Based on our discussion, can we SMTP the permits to our inbox given that there are no PII on this.

**Comment by ASprinkle** [comment]
What is "SMTP"? ^

**Comment by lisamcmichael** [comment]
> What is "SMTP"? ^

Nothing fancy

Short for Simple Mail Transfer Protocol, a **protocol for sending e-mail messages between servers**. Most e-mail systems that send mail over the Internet use SMTP to send messages from one server to another; the messages can then be retrieved with an e-mail client using either POP or IMAP.
