### ISSUE TITLE
As a GP admin I want to see the correct Rules and Guidelines info on the rules and guidelines page.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#863]
## Notes

As a follow up to story #806 per POC review the information on the rules and guidelines page does not match the updated content.

## Acceptance Criteria
- [ ] The Information Page rules and guidelines match the Rules and Guidelines page
- [ ] The Rules and Guidelines page that is emailed also matches accordingly.

## Tasks
- [ ] Compare pages.
- [ ] Note differences.
- [ ] Make updates to the Rules and Guidelines sections so that it matches in the information page.
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
The information page shows the following rules and guidelines:
![image](https://user-images.githubusercontent.com/33435621/65076344-a5ddda80-d94d-11e9-9c51-9efaace7c5a3.png)
![image](https://user-images.githubusercontent.com/33435621/65076349-a9716180-d94d-11e9-822e-741d9b8884dd.png)

The Rules and Guidelines page does not match the information presented on the main GP page, showing this:
![image](https://user-images.githubusercontent.com/33435621/65076445-d9b90000-d94d-11e9-819a-96eee2562518.png)

The GP rules and guidelines page need the following updates:
Add: "Your tree must be equal to or less than 12 feet in height."
Add: "No cutting or removing trees within:
- Congressionally designated Wilderness Areas.
- Mount St. Helens National Volcanic Monument.
- Experimental forests.
- Developed campgrounds.
- Administrative sites.
- Within 300 feet of streams.
- On private or state-owned lands within national forest boundaries.
- In any other posted area.

Add: "A Washington Sno-Park Permit is required for parking at designated Sno-Parks."
Add: "A valid [Recreation Pass](https://www.fs.usda.gov/main/giffordpinchot/passes-permits/recreation) is required at designated recreation fee sites."
Remove: "Cutting is prohibited in plantations, previously thinned stands of trees, timber sale areas, or areas posted as closed to Christmas tree cutting."
Remove: "You must choose a tree at least 200 feet away from main roads, recreation sites and campgrounds, and 300 feet away from streams, rivers or lakes."
Remove: "Do not remove Whitebark Pine trees."

**Comment by ASprinkle** [comment]
The Rules and Guidelines page appears to be up to date in staging now! :)
![image](https://user-images.githubusercontent.com/33435621/65260477-43a2e800-dabb-11e9-8b13-425b45555398.png)
