### ISSUE TITLE
As a WILLAMETTE admin I want to see the correct Rules and Guidelines info on the rules and guidelines page.

### ISSUE THREAD

**Issue by lisamcmichael** [USDAForestService/fs-open-forest-platform#864]
## Notes
As a follow up to story #800 (per POC review) the information on the rules and guidelines page does not match the updated content.

## Acceptance Criteria
- [x] The Information Page rules and guidelines match the Rules and Guidelines page
- [x] The Rules and Guidelines page that is emailed also matches accordingly.

## Tasks
- [x] Compare pages

*Implement content (under Christmas tree cutting section) as follows*
- [x] Do not cut five-needle pines (sugar and white pines) or Pacific yew.
- [x] You must leave a stump of 6 inches in height or less.
- [x] Your tree must be less than 12 feet in height.
- [x] Tree-topping is prohibited. Cut down the whole tree.
- [x] Cut the leftover branches from the stump and scatter them.
- [x] Clear branches and debris from road banks and ditches.
- [x] Choose a tree that has another three within 8 feet of the one you're cutting.
- [x] Only cut trees within the national forest boundary.
- [x] An Oregon Sno-Park permit is required for parking at designated Sno-Parks

*Implement content (under Christmas tree cutting/Do not cut trees within: section) as follows*
- [x] 50 feet of trails and paved roads,
- [x] 300 feet of campgrounds,
- [x] 100 feet of streams,
- [x] Areas posted “Christmas Tree Cutting Prohibited",
- [x] Botanical areas and fenced plantations,
- [x] Congressionally designated wilderness areas, 
- [x] Research natural areas,
- [x] Scenic areas,
- [x] Areas with rare, threatened or endangered plants.

- [x] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by lisaredux** [comment]
Currently on staging:

![Screenshot 2019-09-19 16 35 33](https://user-images.githubusercontent.com/26801590/65279260-d06d9600-dafb-11e9-9109-d434e02b19e6.png)
![Screenshot 2019-09-19 16 35 52](https://user-images.githubusercontent.com/26801590/65279267-d4011d00-dafb-11e9-85fb-2c329f4c895d.png)


![Umatilla-Rules](https://user-images.githubusercontent.com/26801590/65279029-50dfc700-dafb-11e9-9dd4-e5999c8a40d2.png)

**Comment by ASprinkle** [comment]
@lisa this looks great! I made one change. I removed the check box for :
- [] Choose a tree from a dense forested area. 
I did this because of the other rule about making sure there is one w/in so many feet.

**Comment by ASprinkle** [comment]
committed to dev a small typo fix where tree height was indicated in inches vs. feet 
![image](https://user-images.githubusercontent.com/33435621/65538883-26a45580-debd-11e9-98bf-be611337f64f.png)
