### ISSUE TITLE
As a RR - SISKIYOU admin I want to see the correct Rules and Guidelines info on the rules and guidelines page.

### ISSUE THREAD

**Issue by lisamcmichael** [USDAForestService/fs-open-forest-platform#866]
## Notes
As a follow up to story #803 (per POC review) the information on the rules and guidelines page does not match the updated content.

## Acceptance Criteria
- [x] The Information Page rules and guidelines match the Rules and Guidelines page
- [x] The Rules and Guidelines page that is emailed also matches accordingly.

## Tasks
- [x] Compare pages
- [x] Add *Christmas tree cutting* header as bold

* Implement content (under *Christmas tree cutting section*) as follows:
- [x] You must leave a stump of 12 inches in height or less.
- [x] Your tree must be less than 12 feet in height.
- [x] Tree-topping is prohibited. Cut down the whole tree.
- [x] Cut the leftover branches from the stump and scatter them.
- [x] Only cut trees within the national forest boundary.
- [x] Choose a tree that has another tree within 12 feet of the one you're cutting.
- [x] An Oregon Sno-Park permit is required for parking at designated Sno-Parks. 

- [x] Remove title: Measuring your tree. Replace with *Do not cut trees within:* as bold header
Implement content (under *Do not cut trees within*) as follows:
- [x] Wilderness Areas or Wild and Scenic River Corridors,
- [x] National monuments,
- [x] Research Natural Areas,
- [x] Areas currently closed for public health and safety,
- [x] 150 feet of state highways,
- [x] 300 feet of streams and bodies of water,
- [x] Posted young tree plantations,
- [x] Private property,
- [x] Areas with trees marked with paint.

- [x] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
Removed "Choose a tree from a dense forested area."

**Comment by ASprinkle** [comment]
![image](https://user-images.githubusercontent.com/33435621/65799994-41c7cd00-e12a-11e9-9efa-3f7b9fdbc117.png)
![image](https://user-images.githubusercontent.com/33435621/65799998-455b5400-e12a-11e9-9f52-18fffefb38a3.png)

**Comment by ASprinkle** [comment]
These updates look good.
![image](https://user-images.githubusercontent.com/33435621/65910681-0e7e7b80-e380-11e9-8d67-7740b76094d1.png)
![image](https://user-images.githubusercontent.com/33435621/65910688-12120280-e380-11e9-9039-ccdb2fef2c66.png)
![image](https://user-images.githubusercontent.com/33435621/65910698-15a58980-e380-11e9-8c4a-bd7ab7904514.png)
![image](https://user-images.githubusercontent.com/33435621/65910710-19d1a700-e380-11e9-8a35-5ba894cc15bd.png)
![image](https://user-images.githubusercontent.com/33435621/65910721-1d652e00-e380-11e9-90ed-6e1115a470b5.png)
![image](https://user-images.githubusercontent.com/33435621/65910730-21914b80-e380-11e9-8399-7356d87020f0.png)
