### ISSUE TITLE
As a UMATILLA admin I want to see the correct Rules and Guidelines info on the rules and guidelines page.

### ISSUE THREAD

**Issue by lisaredux** [USDAForestService/fs-open-forest-platform#868]
## Notes
As a follow up to story #800 (per POC review) the information on the rules and guidelines page does not match the updated content.

## Acceptance Criteria
- [ ] The Information Page rules and guidelines match the Rules and Guidelines page
- [ ] The Rules and Guidelines page that is emailed also matches accordingly.

## Tasks
- [x] Compare pages

*Implement content (under Christmas tree cutting section) as follows*
- [ ] Cut trees only within the national forest boundary and respect surrounding private property.
- [ ] No cutting or removing trees within:
- 200 feet of Bluewood or Spout Springs Ski Areas, summer home sites, Tollgate Work Center, or Forest Service Guard Stations.
- These specific areas of the Pomeroy Ranger District:
– Park and Cook Ridges
– Lick Creek area, including Sheep Creek, Cabin, Capehorn and Mud Springs ridges.
- [ ] Choose a tree from a dense forested area.
- [ ] Choose a tree that has another three within 8 feet of the one your cutting.
- [ ] You must leave a stump of 10 inches in height or less.
- [ ] Your tree must be less than 14 feet in height.
- [ ] Tree-topping is prohibited. Cut down the whole tree.
- [ ] Cut the leftover branches from the stump and scatter them.
- [ ] Keep road ditches functioning and debris off of, and away from, roadways (at least 50 feet).

*Implement content (under Christmas tree cutting/Do not cut trees within: section) as follows*
- [ ] 50 feet of trails and paved roads,
- [ ] 300 feet of campgrounds, 
- [ ] 100 feet of streams,
- [ ] Areas posted "Christmas Tree Cutting Prohibited", 
- [ ] Botanical areas and fenced plantations,
- [ ] Research natural areas,
- [ ] Scenic areas,
- [ ] Congressionally designated Wilderness Areas,
- [ ] Areas with rare, threatened or endangered plants.

- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by lisaredux** [comment]
Currently on staging:

![Screenshot 2019-09-19 16 35 33](https://user-images.githubusercontent.com/26801590/65279260-d06d9600-dafb-11e9-9109-d434e02b19e6.png)
![Screenshot 2019-09-19 16 35 52](https://user-images.githubusercontent.com/26801590/65279267-d4011d00-dafb-11e9-85fb-2c329f4c895d.png)


![Umatilla-Rules](https://user-images.githubusercontent.com/26801590/65279029-50dfc700-dafb-11e9-9dd4-e5999c8a40d2.png)

**Comment by ASprinkle** [comment]
![image](https://user-images.githubusercontent.com/33435621/65801350-bd774900-e12d-11e9-8e24-1379a8f3bb0a.png)
![image](https://user-images.githubusercontent.com/33435621/65801363-c2d49380-e12d-11e9-8283-bc0a89e87a21.png)

![image](https://user-images.githubusercontent.com/33435621/65801369-c5cf8400-e12d-11e9-9d6a-a187394768fe.png)



![image](https://user-images.githubusercontent.com/33435621/65801246-86a13300-e12d-11e9-8b74-fa258137f1cd.png)
![image](https://user-images.githubusercontent.com/33435621/65801250-89038d00-e12d-11e9-9fc5-7baf69e483f5.png)
![image](https://user-images.githubusercontent.com/33435621/65801257-8d2faa80-e12d-11e9-827f-7945db63e6ae.png)
