### ISSUE TITLE
As a OKANOGAN-WENATCHEE admin I want to see the correct Rules and Guidelines info on the rules and guidelines page.

### ISSUE THREAD

**Issue by lisaredux** [USDAForestService/fs-open-forest-platform#870]
## Notes
As a follow up to story #804 (per POC review) the information on the rules and guidelines page does not match the updated content.

## Acceptance Criteria
- [x] The Information Page rules and guidelines match the Rules and Guidelines page
- [x] The Rules and Guidelines page that is emailed also matches accordingly.

## Tasks
- [x] Compare pages

*Implement content (under Christmas tree cutting section) as follows*
- [x] You must leave a stump of 6 inches in height or less.
- [x] Your tree must be less than 15 feet in height.
- [x] Tree-topping is prohibited. Cut down the whole tree.
- [x] Choose a tree that has another tree within 8 feet of the one your cutting.
- [x] Cut the leftover branches from the stump and scatter them
- [x] A Washington Sno-Park permit is required for parking at designated Sno-Parks.
- [x] A valid Recreation Pass is required at designated recreation fee sites.

*Implement content under Christmas tree cutting section (Do not cut trees within:) as follows*
- [x] 200 feet of the following roads:
* Naches District—along Highway 410, Highway 12, and Forest Service Roads #1200, #1800, and #1900
* The Entiat Valley Road (Entiat Ranger District)
* Interstate 90 and Highway 97 (Cle Elum District)
* Highway 20 over Loup Loup Pass between Twisp and Okanogan-Wenatchee (Methow Valley Ranger District)  
* Along Harts Pass road #5400. Along North Cascades Scenic Highway between east and west scenic highway portal signs, including all side roads (Methow Valley Ranger District).
- [x] Private property
- [x] No cutting or removing trees within 150 feet of any stream, lake, pond, or wetland area.
- [x] Active timber sale areas
- [x] Private or state-owned lands within national forest boundaries,
- [x] Tree plantations.
- [x] Campgrounds
- [x] Administrative site.
- [x] Any posted area.

- [x] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by lisaredux** [comment]
Currently on staging: 

![Screenshot 2019-09-20 11 06 13](https://user-images.githubusercontent.com/26801590/65337799-dfeded00-db96-11e9-940f-d3d3c8894599.png)
![Screenshot 2019-09-20 11 06 45](https://user-images.githubusercontent.com/26801590/65337804-e2e8dd80-db96-11e9-9d20-cb776fc0c61a.png)
![OKA-WEN-Rules](https://user-images.githubusercontent.com/26801590/65337659-930a1680-db96-11e9-9b04-45cbaf9b5893.png)

**Comment by ASprinkle** [comment]
![image](https://user-images.githubusercontent.com/33435621/65799645-7f782600-e129-11e9-8edc-561f54df38fd.png)

![image](https://user-images.githubusercontent.com/33435621/65799651-82731680-e129-11e9-9e7c-79c457b4999f.png)

![image](https://user-images.githubusercontent.com/33435621/65799656-8737ca80-e129-11e9-8261-2d6d3a1f31a1.png)
