### ISSUE TITLE
As a MT. BAKER-SNOQUALMIE admin, I want to see the correct Rules and Guidelines info on the rules and guidelines page

### ISSUE THREAD

**Issue by lisaredux** [USDAForestService/fs-open-forest-platform#871]
## Notes
As a follow up to story #805  (per POC review) the information on the rules and guidelines page does not match the updated content.

## Acceptance Criteria
- [x] The Information Page rules and guidelines match the Rules and Guidelines page
- [x] The Rules and Guidelines page that is emailed also matches accordingly.

## Tasks
- [x] Compare pages

*Implement content (under Christmas tree cutting section) as follows*
- [x] Ensure that the "Christmas tree cutting" header is bold
- [x] You must leave a stump of 12 inches in height or less.
- [x] Your tree must be less than 15 feet in height.
- [x] Tree-topping is prohibited. Cut down the whole tree.
- [x] Cut the leftover branches from the stump and scatter them.
- [x] A Washington Sno-Park permit is required for parking at designated Sno-Parks.
- [x] A valid Recreation Pass is required at designated recreation fee sites.

*Implement content under Christmas tree cutting (Do not cut trees within: section) as follows*
- [x] Create a bold header for "Do not cut trees within:" if one does not exist.
- [x] Developed campgrounds and picnic areas.
- [x] Trail heads.
- [x] Administrative sites.
- [x] Designated wilderness areas.
- [x] 150 feet of any stream, lakes, ponds or wetland areas.
- [x] Private or state-owned lands within national forest boundaries.
- [x] Any posted area.

- [x] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
I will review this story once the content for the MBS is updated on Staging- reflecting the correct 15-foot tree height, vs. previous 12-feet.
![image](https://user-images.githubusercontent.com/33435621/65802227-e13b8e80-e12f-11e9-91e6-3aff038456d5.png)

**Comment by ASprinkle** [comment]
![image](https://user-images.githubusercontent.com/33435621/65985286-595aca80-e436-11e9-804c-68808c03b3a2.png)
![image](https://user-images.githubusercontent.com/33435621/65985296-5bbd2480-e436-11e9-9b12-dd4133e6258f.png)
![image](https://user-images.githubusercontent.com/33435621/65985309-5eb81500-e436-11e9-8dc4-2c62e673e83e.png)
![image](https://user-images.githubusercontent.com/33435621/65985317-624b9c00-e436-11e9-85e2-7a71467f3091.png)
![image](https://user-images.githubusercontent.com/33435621/65985326-65df2300-e436-11e9-92e5-9f250b65734c.png)
![image](https://user-images.githubusercontent.com/33435621/65985343-6a0b4080-e436-11e9-9536-def686408bc0.png)
