### ISSUE TITLE
As a forest admin I want to see my updated season dates shown so that people know when the season opens.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#872]
## Notes
* What are things we should consider when making this story *

The MTH end season date is December 24, 2019 (currently showing as Dec. 23 in Prod)
The MTH season start date is Nov. 14, 2019 (currently showing as Nov. 13 in Prod)
The ARP end season date is Jan 6, 2020 (currently showing as Jan. 5 in Prod)
The RRS start season date is Nov. 9, 2019 (currently showing as Nov. 8 in Prod)
The Flathead end date is Dec. 31, 2019 (currently showing as Dec. 30 in Prod)
The Shoshone end date Dec. 31, 2019  (currently showing as Dec. 29 in Prod)

## Acceptance Criteria
- [x] The MTH season end date has been updated to Dec 24, 2019
- [x] The MTH season start date has been updated to Nov. 14, 2019
- [x] The ARP season end date has been updated to Jan 6, 2020
- [x] The RRS season start date has been updated to Nov. 9, 2019
- [x] The Flathead end date has been updated to Dec. 31, 2019 
- [x] The Shoshone end date has been updated to Dec. 30, 2019 

## Tasks
- [x] Update seeder files.
- [x] PO approved.

## Definition of Done
- [ ] Pull requests meet technical definition of done

**Comment by ASprinkle** [comment]
Season Date verification progress is being tracked in Pinyon here under the Content 2019 file https://usfs.box.com/s/tur5z2q202fmawawl2896z4qgwpxa8en

**Comment by ASprinkle** [comment]
Current Prod Screen Shots for forest dates that need to be updated:
![image](https://user-images.githubusercontent.com/33435621/66156899-75e23880-e5d7-11e9-8159-337c6abf2107.png)
![image](https://user-images.githubusercontent.com/33435621/66156906-7a0e5600-e5d7-11e9-88a9-edff5da82f1d.png)
![image](https://user-images.githubusercontent.com/33435621/66156912-7e3a7380-e5d7-11e9-9051-88db3900f14c.png)
![image](https://user-images.githubusercontent.com/33435621/66156921-82669100-e5d7-11e9-918d-0e3c0036e270.png)
![image](https://user-images.githubusercontent.com/33435621/66156930-85fa1800-e5d7-11e9-964d-254228dbcb53.png)

**Comment by ASprinkle** [comment]
Used admin in PROD to update the MTH dates.... 
![image](https://user-images.githubusercontent.com/33435621/66157934-af1ba800-e5d9-11e9-881e-ed434c0c430a.png)

**Comment by ASprinkle** [comment]
@mtlaney one fix: RRS shows Nov. 8 still vs. Nov. 9.
![image](https://user-images.githubusercontent.com/33435621/66341438-22842900-e8fc-11e9-945a-6429a45f4b5b.png)

**Comment by mtlaney** [comment]
@ASprinkle do you happen to know RRS end date as well, is it the 25th or the 24th?

**Comment by mtlaney** [comment]
> @ASprinkle do you happen to know RRS end date as well, is it the 25th or the 24th?

nvm, i found the word doc, updating all seattle tz's to match as well

**Comment by ASprinkle** [comment]
Oh gosh, I didn't catch that. Glad you've got eyes on he doc in Pinyon. RRS seas start date is Nov. 9. Season end date is Dec 25

**Comment by ASprinkle** [comment]
@mtlaney awesome!! :) 
![image](https://user-images.githubusercontent.com/33435621/66357120-87527a00-e922-11e9-994e-505796502290.png)

**Comment by ASprinkle** [comment]
The Season Dates Word Doc Pinyon file has been updated to an Excel file, and is available in the same Product Owner folder, here's the link to All Forest Season Dates: https://usfs.box.com/s/6n8130crzvivssgrqt4jpn569vwam0mu
