### ISSUE TITLE
As a DESCHUTES admin I want to see the correct Rules and Guidelines info on the rules and guidelines page.

### ISSUE THREAD

**Issue by lisamcmichael** [USDAForestService/fs-open-forest-platform#873]
## Notes
As a follow up to story #808 (per POC review) the information on the rules and guidelines page does not match the updated content.

## Acceptance Criteria
- [x] The Information Page rules and guidelines match the Rules and Guidelines page
- [x] The Rules and Guidelines page that is emailed also matches accordingly.

## Tasks
- [x] Compare pages

Implement content (under Christmas tree cutting section) as follows:
- [x] Only cut trees within the national forest boundary.
- [x] Choose a tree that has another tree within 20 feet of the one you're cutting.
- [x] You must leave a stump of 6 inches in height or less.
- [x] Your tree must be less than 12 feet in height.
- [x] Tree-topping is prohibited. Cut down the whole tree.
- [x] Cut the leftover branches from the stump and scatter them.
- [x] An Oregon Sno-Park permit is required for parking at designated Sno-Parks.

Implement content (under Christmas tree cutting/Do not cut trees within: section). 
- [x] add subtitle in bold font "Do not cut trees within:" 
Underneath this section, Include as follows:
- [x] Private property,
- [x] Wilderness areas or the Newberry National Volcanic Monument,
- [x] Forest Service nurseries and plantations (nursery grown seedlings planted for future forests),
- [x] 300 feet of streams,
- [x] 150 feet of state highways, picnic areas, campgrounds and other developed areas.

- [x] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
@mtlaney I created a pull request to add text to the main info page about making sure another tree is within 20 feet of the one being cut.  that was the only difference between the pages, and I missed it in creating the original content story.  once that is approved we can move this to Ready for Master.
![image](https://user-images.githubusercontent.com/33435621/65986284-64aef580-e438-11e9-84ce-da9ec088bcac.png)
![image](https://user-images.githubusercontent.com/33435621/65986295-67a9e600-e438-11e9-802a-6614d2be3c9b.png)
![image](https://user-images.githubusercontent.com/33435621/65986304-6d073080-e438-11e9-827b-eb9fab1be90c.png)
![image](https://user-images.githubusercontent.com/33435621/65986311-71334e00-e438-11e9-92f4-36a8617ad045.png)
![image](https://user-images.githubusercontent.com/33435621/65986323-742e3e80-e438-11e9-8b44-497378ee2734.png)
![image](https://user-images.githubusercontent.com/33435621/65986328-785a5c00-e438-11e9-9461-f8df2e8f0887.png)
![image](https://user-images.githubusercontent.com/33435621/65986337-7c867980-e438-11e9-912e-952506d9937c.png)
