### ISSUE TITLE
As the Open Forest researcher, I want to conduct usability testing to determine if the public can provide feedback about their Christmas Tree permit experience, so that we know what is working for them and which enhancements are needed.

### ISSUE THREAD

**Issue by lisamcmichael** [USDAForestService/fs-open-forest-platform#876]
The Open Forest program needs to capture the public's feedback so that we can continue to improve the user experience over time. 

Considerations: Will this simple survey encourage feedback. It's possible the design and wording may need refinement over time to create the right "CTA".

The team should refer to #676 for additional background.

## Acceptance Criteria
- [ ] PO okays usability test plan
- [ ] PO receives test findings
- [ ] Researcher reviews findings with PO and the "team"

## Tasks
- [ ] Create research plan draft (includes goal, methodology, test script, test targets with any links)
- [ ] Review plan with PO and modify if needed
- [ ] Add research plan to Pinyon (Research folder)
- [ ] Conduct tests with participants
- [ ] Update Research folder with findings once synthesized
- [ ] Review test findings with PO, designer and Devs
- [ ] Make design changes if needed
- [ ] Create follow-on research stories if appropriate 

## Definition of Done
- [ ] Completed research study and findings
- [ ] Updated User Admin screens/Lisa S and Developers if needed
- [ ] Approved by PO

**Comment by lisamcmichael** [comment]
For now I'm closing this. The feedback form is very simple, so testing it later, once we see if it's being used, will be better timing and use of resources.
