### ISSUE TITLE
SPIKE compile dev related scale up considerations

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#887]
## Notes

Throughout the R6 scale up there have been discussions and mentions of some inefficiencies for building.
Regarding MVP 2018 - the process was sufficient. 
As we begin to add more content for multiple forests with different needs, we have noticed areas where efficiencies could be gained (i.e., seeder file process, circle ci one-at-a-time updates) even for reaching MVP.

## Acceptance Criteria
- [x] We have an understanding of what changes would be needed from a technical stand point in order to facilitate smooth larger-scale scale up efforts.
- [x] We have information documented in a shared file space.
- [x] We have begun to develop stories in the backlog to address these needs.
- [x] We have an understanding of how we can improve our DEV management for future.

## Tasks
- [x] PO to meet with Dev team to discuss technical considerations from the 2019 R6 scale up.
- [x] Shadat will set up a meeting between Eric, Amber, Matt to review observations from front end and back end retro sessions.
- [x] Develop action plan(s) based on front end and back end input.
- [x] Create a shared Pinyon notes document
- [x] Identify the work that needs to be done for test cases to be up-to-date with the most recent code
- [x] PO approved

## Definition of Done
- [x] Meeting completed.
- [x] A/C Met.

**Comment by ASprinkle** [comment]
#890  notes regarding Sequelize may be helpful here too

**Comment by smahmudFS** [comment]
Thanks @ASprinkle.  Should we setup a meeting with @ericsorenson, you, I @mwreiss to review your observations and thoughts first then we put action plans?  I can set it up.  Thanks.

**Comment by ASprinkle** [comment]
@carlsonem I just removed all assignee names from this story. no one should be currently assigned to this story, as this is in the backlog and should not be actively worked right now.

**Comment by ASprinkle** [comment]
A note regarding Circle-Ci failures, and fixes w/o code changes:
"There was a CircleCI failure during the end to end tests that ran on your pull request. I went ahead and re-ran the workflow and it was successful this time so we should be good to merge this.
I'm starting to wonder why we're occasionally seeing these failures. It's a little odd to me that we are resolving them without making any code changes."

**Comment by lisamcmichael** [comment]
Amber and I talked about this story, and we will include Lisa S. and/or me in the "retro" because we assume there could be design considerations too.

**Comment by ASprinkle** [comment]
https://usfs.box.com/s/88ci1a86f4z63tdgb1vmiz045grd71m5

**Comment by ASprinkle** [comment]
Invites sent for Front End Dev Retro: 1/9 0930-1030 PST
Invites sent for Back End Dev Retro: 1/9 1030-1100 PST

**Comment by ASprinkle** [comment]
Dev retro notes saved here https://usfs.box.com/s/4kccoctxvmp4w8r1v58h8py2lsm97sh6 with prepped stories drafted
