### ISSUE TITLE
As the Forest Service Project Manager, I want a discovery plan to guide us on scaling up Open Forest Christmas Tree in 2020, so that adding new forests is successful.

### ISSUE THREAD

**Issue by lisamcmichael** [USDAForestService/fs-open-forest-platform#888]
## Notes
* What are things we should consider when making this story *

- We've discovered from contacting Washington office recreation and Forest products staff, the data they're capturing on tree sales is not accurate.

- Amber provided a draft survey: https://drive.google.com/file/d/1L1xKYdAecqyoQezxcXlc4lt-5UuRDXwO/view?usp=sharing

See closed story #107 for initial notes and activities

DRAFT!
## Acceptance Criteria
- [ ] PM approves discovery plan

## **Tasks**
- [x] Write discovery plan draft
- [x] Review plan with team
- [x] Put plan draft in the Icebox  

## Definition of Done
- [ ] The PM and PO have a plan to guide them to scale-up Open Forest 2020.

**Comment by lisamcmichael** [comment]
Initial analysis of per unit tree fees per forest and region (from Aaron)
[Christmas Trees sold -FY 2015_with_potential cost - AB.xlsx](https://github.com/USDAForestService/fs-open-forest-platform/files/3663053/Christmas.Trees.sold.-FY.2015_with_potential.cost.-.AB.xlsx)

**Comment by ASprinkle** [comment]
@lisamcmichael I found this draft document that I made in Dec 2018.  It's got a lot of granularity to it, but may be helpful to refer to for higher-level considerations. Its a draft brainstorm there are things in here that suggest we're going to "select forests" etc. which we know is beyond the scope of the Open Forest team's decision space. https://usfs.box.com/s/lr46rc2wbs5jyiymz4a3piqmx9mldai0

**Comment by lisamcmichael** [comment]
UPDATE: met with @aaronburk and Amber and Lisa S. and the plan is on hold for now.

**Comment by lisamcmichael** [comment]
> @lisamcmichael I found this draft document that I made in Dec 2018. It's got a lot of granularity to it, but may be helpful to refer to for higher-level considerations. Its a draft brainstorm there are things in here that suggest we're going to "select forests" etc. which we know is beyond the scope of the Open Forest team's decision space. https://usfs.box.com/s/lr46rc2wbs5jyiymz4a3piqmx9mldai0

@ASprinkle  Thx for getting this to me! I'll circle back with you as I make updates to the "2020" discovery research plan.

**Comment by lisamcmichael** [comment]
@ASprinkle, @aaronburk and @lisaredux I've made updates based on our meeting, and Amber's draft doc.

https://usfs.box.com/s/iyw1aezk0e5b4wibl0v6pfegic4igkl0

**Comment by ASprinkle** [comment]
A plan is drafted, and still in draft form. Closing for now.
