### ISSUE TITLE
** SPIKE Research on Run Seeder File Updates so that forest content updates can be completed.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#890]
## Notes
* What are things we should consider when making this story *

## Acceptance Criteria
- [x] seeder file updates have been successfully completed
- [x]  any issues are documented and fully resolved.

## Tasks
- [ ] Run seeder file at an obscure time to minimize risk
- [ ] After seeder file update is complete, check each forest page on the production site to ensure the "buy permit" button is not active.  If active, resolve issue.
- [ ] PO approved

## Definition of Done
- [ ] tasks and a/c are complete.

**Comment by ASprinkle** [comment]
@abdul1234e @briandavidson FYI as a follow up from Teams Chat today - I created this story to track our work related to this. Any updates needed to the tasks - please make them.

**Comment by ASprinkle** [comment]
2019 season dates https://usfs.box.com/s/tur5z2q202fmawawl2896z4qgwpxa8en
