### ISSUE TITLE
As a forest visitor i'd like to see consistent sources for photos in tree ID section so that I am not confused.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#891]
## Notes

The Deschutes page currently shows a source different from the NRCS database:
![image.png](https://images.zenhubusercontent.com/5a00e34b8a75884b90864b6f/b539a065-1f9a-4886-bcea-62a6ceb5cf38)

## Acceptance Criteria
- [x] The white fir photo is updated with one from the NRCS database.
- [x] The update is reflected on all forests that have White Fir in their "Identifying tree species" section.

## Tasks
- [ ] Update the photo with this one from the NRCS database: https://plants.usda.gov/java/largeImage?imageID=abco_018_ahp.jpg
![image.png](https://images.zenhubusercontent.com/5a00e34b8a75884b90864b6f/8177302b-27a5-4f7c-ae61-b0eab5c94b67)
- [x] PO approved

## Definition of Done
- [x] Tasks are completed
- [x]  A/C is met
