### ISSUE TITLE
As an OF User I would like to read in the Wiki about how Feedback and User Management tools are handled, so that I can understand the system.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#892]
## Notes
* What are things we should consider when making this story *
Update documentation for 
Feedback tool use
User Management tool use.

## Acceptance Criteria
- [ ] Our documentation is updated regarding process for using User Management and Feedback tools

## Tasks
- [ ] Ensure that instructions for users submitting feedback and how it is handled are updated in the wiki here - https://github.com/USDAForestService/fs-open-forest/wiki/2018-Christmas-Tree-Email-Response-Protocol
- [ ] Ensure that instructions for user management and how it is handled are updated in the wiki. A new page may need to be created as this is a new feature.
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
This is already a task in each story., Closing.
