### ISSUE TITLE
As an FS admin on a forest I want to know that Open Forest transactions have been tested with real money so that we know funds are being correctly allocated.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#893]
## Notes

Open Forest transactions need to occur with real money prior to Nov. 1 launch.

## Acceptance Criteria
- [x] Open Forest has been tested with real money on all new forests.
- [x]  We know whether or not the funds are being correctly allocated.
- [x] We have created stories to address the need to fix issues, if necessary.

## Tasks
- [x] We know whether or not we have a real card we can use to charge to so that we don't have to use personal funds.
- [x] Coordinate with team when team will test this
- [x] Change season dates in PROD to test in PROD with real money prior to season start.
- [x] Put season dates back immediately after test is complete so that the public cannot get a permit early.
- [x] PO approved

## Definition of Done
- [x]  Tasks are done.
- [x] A/C is met.

**Comment by ASprinkle** [comment]
Moving to Blocked pending hearing back from Jaimin as noted in this email below

Sent: Thursday, October 10, 2019 3:09 PM
To: Carlson, Eric - FS <eric.carlson@usda.gov>
Cc: Brown, Dena-Kay - FS <dena-kay.brown@usda.gov>; Cha, Daniel S -FS <daniel.cha@usda.gov>; Key, Robin Y -FS <robin.key@usda.gov>; Burk, Aaron E -FS <aaron.burk@usda.gov>; Sprinkle, Amber D -FS <amber.sprinkle@usda.gov>
Subject: RE: Open Forest Test Transactions FMMI file
Importance: High

Hello Eric,

We were expecting that you will first notify us to get the new items and their necessary accounting setup in PROD. We will setup these items and let you know. Please hold off on doing live test transactions in PROD until you hear back from us.

Thanks,

Jaimin

**Comment by ASprinkle** [comment]
Email from Jaimin 10/15: "Hi Aaron & Eric,

The items are now setup in PROD. Please go ahead with your “live” test transactions and provide us the transaction details so we can look for it at settlement."

**Comment by ASprinkle** [comment]
Update: Deschutes and Okanogan were tested with real money 10/16.

Within Open Forest PROD Admin, reports generated feature is working great!
![image](https://user-images.githubusercontent.com/33435621/66932848-17608580-efed-11e9-8ad5-a10318839458.png)
![image](https://user-images.githubusercontent.com/33435621/66932858-1a5b7600-efed-11e9-845c-f23c5b99a9ee.png)

**Comment by ASprinkle** [comment]
All Forests tested
![image](https://user-images.githubusercontent.com/33435621/67120460-32bec280-f19e-11e9-8a56-5ab0d055427e.png)

**Comment by ASprinkle** [comment]
First two tested forests had hit POSS correctly. Waiting to hear from Jamin RE 95/5% split confirmation in FMMI

**Comment by carlsonem** [comment]
@carlsonem Ping Jaimin

**Comment by ASprinkle** [comment]
[Test RealMoney Transactions Confirmation 20191024.xlsx](https://github.com/USDAForestService/fs-open-forest-platform/files/3768882/Test.RealMoney.Transactions.Confirmation.20191024.xlsx)

Not all FMMI document numbers are populated. Jamin will send an updated spreadsheet with the remaining FMMI numbers.  The spreadhseet clearly shows the 95/5 split/allocation to forest and region.  Based on this information we can confirm that the funds from each transaction are correctly being allocated. I am moving this to Awaiting Acceptance.
@carlsonem
