### ISSUE TITLE
As a Christmas tree permit customer, I want to have the rules and guidelines included by default when printing or downloading my permit so that I can have everything in one PDF

### ISSUE THREAD

**Issue by lisaredux** [USDAForestService/fs-open-forest-platform#899]
## Notes
*Currently, there is a checkbox on the Christmas tree permit confirmation page that is unchecked by default. In case the customer is scanning the text and not paying close attention, we believe it's better for them to get the rules and guidelines by accident rather than to overlook the opportunity to get them by default.

## Acceptance Criteria
- [x] PO understands the purpose for checkbox being checked by default
- [x] Screenshot of the default design added to story
- [x] The checkbox is automatically checked for people.

## Tasks
- [x] Present the case and the justification to have Rules and Guidelines checkbox "checked" as the default state
- [x] Dev - make the checkbox automatically/pre-checked for "include a copy of the Christmas tree cutting rules and guidelines"
- [x] PO approved

## Definition of Done
- [x] Pull requests meet technical definition of done
- [x] Compare finished design with mockup

Default:
<img width="860" alt="Screenshot 2019-09-26 15 00 33" src="https://user-images.githubusercontent.com/26801590/65718369-614eef00-e071-11e9-8a4d-4e3cdde8a1d3.png">

After user action:
<img width="918" alt="Screenshot 2019-09-26 15 00 22" src="https://user-images.githubusercontent.com/26801590/65718370-614eef00-e071-11e9-9244-bb1af103e1b2.png">

**Comment by lisaredux** [comment]
@lisamcmichael here is the new issue I was mentioning today. 

@ASprinkle — Lisa McMichael and I were talking about this, and we strongly recommend the checkbox to be checked by default in case either the customer doesn't get the email or doesn't read all the text in the page

**Comment by ASprinkle** [comment]
Thanks @lisaredux to be clear the idea would be the box is Checked by default with the option to uncheck if they don't want to include them in printing, knowing that they have been emailed to them?

Thanks for this insight!

**Comment by lisamcmichael** [comment]
Morning @lisaredux! I've added 2 criteria to the acceptance criteria, and 1 task (checked as done). Feel free to adjust based on Amber's initial ok of the story.

**Comment by lisaredux** [comment]
> Thanks @lisaredux to be clear the idea would be the box is Checked by default with the option to uncheck if they don't want to include them in printing, knowing that they have been emailed to them?
> 
@ASprinkle — yes, exactly. The box would be checked by default. 

Hopefully an easy lift for development.

**Comment by lisamcmichael** [comment]
@lisaredux and @ASprinkle Any sense of whether or not this could be included in dev work for 2019 season?

**Comment by ASprinkle** [comment]
Hmm. It's a possibility for next sprint. 10/13-10/26

**Comment by ASprinkle** [comment]
More background is available under closed story #630 (closed due to redundancy)

**Comment by ASprinkle** [comment]
Awesome! it was pre-checked, and all the stuff was there!
![image](https://user-images.githubusercontent.com/33435621/68443359-7fd3fa00-0188-11ea-8286-46b4a7b6239d.png)
![image](https://user-images.githubusercontent.com/33435621/68443367-82ceea80-0188-11ea-9aeb-95f0b9fda72a.png)
