### ISSUE TITLE
WIL tree height change from 12 to 15 feet

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#902]
## Notes
* What are things we should consider when making this story *
Email 9/27 

"...the Willamette will be permitting the 15’ Christmas tree rule. 
Amber, could we have the website reflect the change?"

## Acceptance Criteria
- [ ] tree height is updated to 15 feet.

## Tasks
- [ ] update tree height for the Willamette to 15 feet.
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
Created #910 in place of this and moved to Blocked pending more info from Christian.
