### ISSUE TITLE
As a Fre-Win admin I'd like to see an updated Start Date to Nov. 1 and rules and guidelines info.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#903]
## Notes
* What are things we should consider when making this story *

## Acceptance Criteria
- [x] The updates completed.

## Tasks
- [x] update start date to November 1
- [x] add a bullet at the end of the list of the rules and guidelines "Christmas tree cutting" section that reads: "Do not cut cedar trees within the Chemult, Chiloquin, and Klamath Ranger Districts"
- [x] PO approved

## Definition of Done
- [ ] AC and tasks are met/completed.

**Comment by ASprinkle** [comment]
The forest is still ironing out their start date. I informed them to confirm before Oct 4.

**Comment by ASprinkle** [comment]
Their email for reference is saved in the Content 2019 folder: https://usfs.box.com/s/ocsom6vyfwd2gzfrcjvtbv8ohpityfov

**Comment by ASprinkle** [comment]
![image](https://user-images.githubusercontent.com/33435621/65986712-4a294c00-e439-11e9-9a11-c6e5bc579535.png)
![image](https://user-images.githubusercontent.com/33435621/65986715-4d243c80-e439-11e9-806b-1111fabec09d.png)
![image](https://user-images.githubusercontent.com/33435621/65986725-50b7c380-e439-11e9-8008-34d1aa6d9817.png)

**Comment by ASprinkle** [comment]
@mtlaney @briandavidson ^^ the changes for the Fre-Win are no longer showing on staging or prod. their POC informed me that the updates are not showing. 
Here are screen shots showing what's up on Staging and Prod:
![image](https://user-images.githubusercontent.com/33435621/66688028-b83ff100-ec39-11e9-9468-311a70916ba9.png)
![image](https://user-images.githubusercontent.com/33435621/66688047-c8f06700-ec39-11e9-9e20-fd6490207950.png)

**Comment by ASprinkle** [comment]
@mtlaney Looks good!
