### ISSUE TITLE
As a WIL NF POC I would like to implement final changes to content so that the site is fully updated prior to launch.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#910]
## Notes
* What are things we should consider when making this story *

The Region came out with a new tree height maximum. The Forest would like to match this new maximum prior to the start of the season. In order to do this, the Forest will be updating their maps and sending us new maps.

## Acceptance Criteria
- [x] Tree height is shown as 15 feet on the information page, rules and guidelines page, and the permit.
- [x] New maps have been uploaded (either as PDF or .png or both)

## Tasks
- [x] Update tree height
- [x] find out if we can upload maps as PDFs (preferred file type by POC).
- [x] upload the maps as an option to download as a PDF file.
- [x] Upload new maps.
- [x] Remove the "Printer Friendly PDF version of Willamette National Forest" PDF link and Map.
- [x] PO approved

## Definition of Done
- [x]  tasks are completed
- [x] AC is met

**Comment by ASprinkle** [comment]
All tasks for this story are blocked until we receive new maps from the Willamette

**Comment by ASprinkle** [comment]
Per email - We will receive the updated maps before COB Monday 10/7.  We can anticipate putting this story into in progress by Tuesday 10/8.

**Comment by ASprinkle** [comment]
Updated Willamette PDF maps are stored here: https://usfs.box.com/s/5pob82vpl9ubokbmahnzb3v1wkbdcd2i

**Comment by ASprinkle** [comment]
Looks great! thank you for being able to get those maps up as PDFs. ![image](https://user-images.githubusercontent.com/33435621/66960635-b901ca00-f021-11e9-8d40-809e4e1366b9.png)
![image](https://user-images.githubusercontent.com/33435621/66960636-bbfcba80-f021-11e9-9ecc-a859b0f44276.png)
