### ISSUE TITLE
As the Open Forest researcher, I want a Pilot Test in preparation for Admin Role usability testing so that we can understand more about user management.

### ISSUE THREAD

**Issue by lisamcmichael** [USDAForestService/fs-open-forest-platform#912]
## Notes
- This is a Pilot test to make any needed modifications to the research plan #855. 
- #855 (closed issue on 9/30)

## Acceptance Criteria
- [ ] PO included in Pilot Tests
- [ ] PO approved prototype flows for testing User Roles Management #689
- [ ] All tasks completed

## Tasks
- [x] Lisa S. creates prototype with updated flows for testing
     - [ ] Review prototype with PO and Lisa M.
     - [ ] If needed, revise the prototype
- [ ] If needed, revise test plan (#855) 
- [ ] Pick dates to conduct both pilot tests 
     - [ ] Contact and Schedule separate Pilot Tests with Dana Croll and Fara Humphrey
- [ ] Run a Pilot Test with each participant 
- [ ] Synthesize findings
- [ ] Share findings with PO and Lisa S
     - [ ] If needed, revise the test plan #855
     - [ ] If needed, revise the prototype
- [ ] Pick dates to conduct Usability Testing
     - [ ] Create a new story for Usability Testing

## Definition of Done
- [ ] Completed 2 Pilot Tests
- [ ] Test findings accepted by PO
- [ ] Research Plan #855 is ready for Usability Testing

**Comment by lisamcmichael** [comment]
The above story has what I think are the necessary details, but @lisaredux and @ASprinkle feel free to adjust as needed.

**Comment by ASprinkle** [comment]
Closing based on results of SPIKE story #922 - Open Forest will not house a unique admin user management system.
