### ISSUE TITLE
As a Fre-Win admin I want to see my forest's name spelled correctly on the permit so that I feel good about the product.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#921]
## Notes
* What are things we should consider when making this story *
The forest name is spelled incorrectly on the printed permit, as "Freemont-Winema". It should be spelled as "Fremont-Winema" with only one "e" in "Fremont"
![image.png](https://images.zenhubusercontent.com/5a00e34b8a75884b90864b6f/80389bbb-21ef-47b9-9c94-1629e4c1623d)

## Acceptance Criteria
- [x] The forest name is spelled correctly on the printed permit.

## Tasks
- [x] Update the forest name to "Fremont-Winema" on the printed permit.
- [x] Check to verify it is not spelled incorrectly elsewhere.
- [x] Edit forest name errors if present elsewhere.
- [x] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
![image](https://user-images.githubusercontent.com/33435621/66342540-80b20b80-e8fe-11e9-93c9-81cee2cda84d.png)
