### ISSUE TITLE
*** SPIKE ICAM overview to inform User Management interface for Open Forest

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#922]
## Notes
* What are things we should consider when making this story *

## Acceptance Criteria
- [x] the team has met to gain an understanding of how ICAM and Open Forest admin User Management are related
- [x] the team received an overview of ICAM
- [x] Current Admin User Management related stories are updated/managed/prioritized as a result of the meeting

## Tasks
- [x] The team meets
- [x] Notes are captured in a shareable location
- [x] Additional follow up stories are developed if needed.
- [x] Update/managed/prioritize existing user management related stories ( #856 #912 #689 #753 )
- [x] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by JonathanLerner54** [comment]
ICAM  Identity, Credential, and Access Management

**Comment by ASprinkle** [comment]
[ICAM Service Overview no demos.pptx](https://github.com/USDAForestService/fs-open-forest-platform/files/3683128/ICAM.Service.Overview.no.demos.pptx)
