### ISSUE TITLE
** SPIKE Dev Research for ICAM/EEMS integration needs (User Management)

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#926]
## Notes
* What are things we should consider when making this story *
This is a follow up to SPIKE #922 where we were learning about ICAM
This is also somewhat connected to #689 where we initially started to build a User Management application within Open Forest -but stopped work on that due to the direction to integrate with the automated ICAM/EEMS systems.

The purpose of this story is to gain an understanding of what we need to do to integrate Open Forest with the ICAM/EEMS system, while meeting our user management goals.

This story is DEV specific, and in tandem with Program-level considerations being captured on the Program Board story 170 https://code.fs.usda.gov/forest-service/Open-Forest-Program/issues/170#issue-20719

## Acceptance Criteria
- [x] We have an understanding of what we need to do in order to integrate with ICAM/EEMS for Open Forest admin user management.
- [x] We have begun to develop dev-related user stories for next steps/integration.

## Tasks
- [x] research requirements for ICAM/EEMS integration.
- [x] document findings in a shareable location (Pinyon Link to User Management Folder: https://usfs.box.com/s/axc60zuazso8ec1xadrm7sbd5he092s9 )
- [x] have a meeting with team to share findings
- [x] develop additional user stories in order to accomplish the dev related work to integrate.
- [ ] PO approved

## Definition of Done
- [x] AC and Tasks are met.

**Comment by ASprinkle** [comment]
@carlsonem can you create a folder called "User Management" nested under Open Forest directly? that would house all of this research? That way we all have appropriate access/permissions.

**Comment by ASprinkle** [comment]
Here is the pinyon folder for us to house all EEMS/ICAM User Management related documentation https://usfs.box.com/s/axc60zuazso8ec1xadrm7sbd5he092s9 @carlsonem @smahmudFS

**Comment by smahmudFS** [comment]
@briandavidson @mtlaney Let's figure out what are the attributes required to manage a user in Open Forest platform for authorization.  Please use the data catalog on box for reference to EEMS/ICAM attributes:  https://usfs.app.box.com/file/591416099738
fyi....@mwreiss @JonathanLerner54

**Comment by ASprinkle** [comment]
Shadat is updating

**Comment by smahmudFS** [comment]
Reference Documents for EEMS are updated on Pinyon including USDA EEMS (Enterprise Entitlement Management System) integration artifacts such as ISA agreement, Data Catalog, Roles etc.  Artifacts can be found under the following folder:
https://usfs.app.box.com/folder/98692211229

In addition, future user stories are needed to be established:
1. Integration with USDA EEMS, validate additional authorization attributes coming from eAuth.
2. Ability to parse authorization attributes from eAuth.
3. Ability to use authorization attributes for access to Open Forest.
4. Training on EEMS administration page for authorized Open Forest security role manager(s)
5. Internal reporting for last log-in on end users (open forest internal security requirement).
6. Ability to add/remove users in EEMS and see reflective impacts/results in Open Forest.
7. EEMS report on user management (open forest internal security requirement).
8. Remove white listing functionality from Open Forest.
9. Establish and document process for new user or modifying existing user profile in Open Forest via EEMS.   Must update information on security controls.
10. Establish and document, exercise formal communication for users in Open Forest.

**Comment by ASprinkle** [comment]
@ASprinkle  will review. @carlsonem @mwreiss @smahmudFS will meet up and develop user stories for the Platform board based on the results of the spike.
