### ISSUE TITLE
As an admin I would like to have the Request a Content Change tab/option hidden so that I am not confused by it.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#927]
## Notes
* What are things we should consider when making this story *

## Acceptance Criteria
- [x] The "Request a Content Change" tab is not visible (not able to be seen or selected)

## Tasks
- [x] Capture screen shots or a copy of the content change request google form, and save it in a shareable location.
- [x] Deactivate the "Request a Content Change" google form feature from the Open Forest platform. 
- [x] PO approved

## Definition of Done
- [x] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
Thank you for taking those screen shots @briandavidson - this looks great!
![image](https://user-images.githubusercontent.com/33435621/66961047-a5a32e80-f022-11e9-946b-13fe4f597e40.png)
