### ISSUE TITLE
As a Umatilla NF admin I want to see Lodgepole Pine added as a species so that folks in the eastzone know what to trees they may see.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#928]
## Notes
* What are things we should consider when making this story *

The Umatilla NF has two zones - East and West.
The East zone has less subalpine fir and more Lodgepole. It is important to the Umatialla NF to represent the most popular species across the whole forest.
![image.png](https://images.zenhubusercontent.com/5a00e34b8a75884b90864b6f/fdeb2e89-46a2-404c-853f-fe259648ca11)

## Acceptance Criteria
- [x] Lodgepole pine is added in the "Identify your tree" section

## Tasks
- [x] Add the Lodgepole pine species photo and description as it appears on the Flathead NF page.
- [x] PO approved

## Definition of Done
- [x] Pull requests meet technical definition of done
- [x] Compare finished design with mockup
- [x] Usability tested

**Comment by ASprinkle** [comment]
looks great!
