### ISSUE TITLE
SPIKE verify Org Codes for all forests

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#937]
## Notes
* What are things we should consider when making this story *

## Acceptance Criteria
- [x] Org Codes are verified and correct

## Tasks
- [x] Gather org codes into a doc share
- [x] PO approved

## Definition of Done
- [x] Pull requests meet technical definition of done
- [x] Compare finished design with mockup
- [x] Usability tested

**Comment by ASprinkle** [comment]
I am housing the info in this document in the Content folder in Pinyon https://usfs.box.com/s/1gjpwx0w708xik84ql62ztrelhel66re

Still updating...

**Comment by ASprinkle** [comment]
All Org Codes for all Forests in the FS are housed in this spreadsheet. They are set up by Region/Forest/District.  For Open Forest, we are more interested in the Region/Forest breakdown.   I have the spreadsheet saved with the Filter set for our Open Forest pilot forests.
https://usfs.box.com/s/clo3lael67ntg6fs8svk7drf90gdw4ng
- Flathead: 0110
- Shoshone: 0214
- Arapaho Roosevelt: 0210
- Deschutes: 0601
- Fremont-Winema: 0602
- Gifford Pinchot: 0603
- Mt. Hood: 0606
- Ochoco: 0607
- Rogue River-Siskiyou: 0610
- Umatilla: 0614
- Okanogan-Wenatchee: 0617
- Willamette: 0618

**Comment by ASprinkle** [comment]
@mtlaney ^ org codes!

**Comment by mtlaney** [comment]
> @mtlaney ^ org codes! can you verify that we have these correct in our systems? or let me know if there is some inconsistency? once we verify - we can move to awaiting acceptance.

I'll check them out!

**Comment by mtlaney** [comment]
@ASprinkle currently they are set like this in open forest, including our pilot forests from last year. Let me know if this format looks correct:

Arapaho Roosevelt: 11-02-10 as opposed to 0210

**Comment by ASprinkle** [comment]
@mtlaney I believe they should all start with "11" correct?

**Comment by mtlaney** [comment]
@ASprinkle perfect. Any luck finding MBS, or am I totally missing it somehow?

**Comment by ASprinkle** [comment]
AH!! MBS is 0605.

**Comment by ASprinkle** [comment]
@mtlaney All the org codes have an "11" preceding them in your files, correct?

**Comment by mtlaney** [comment]
@ASprinkle all org codes have an 11 now
