### ISSUE TITLE
As an Oka-Wen NF POC I would like to implement final changes to Rules content so that the site is fully updated prior to launch

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#940]
## Notes
* What are things we should consider when making this story *

## Acceptance Criteria
- [x] Update typos in the Prohibited areas on info page
- [x] Update typos in the Rules page

## Tasks
Update typo under the 
- [x] “No cutting or removing trees within:” Prohibited areas section: 
- [x] Rules and Guidelines section.

Under the Methow Valley District section, there should be a period after the word Okanogan (the –Wenatchee needs to be removed).  so that it reads: "Methow Valley District–along Highway 20 over Loup Loup Pass between Twisp and Okanogan.”
- [x] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
![image](https://user-images.githubusercontent.com/33435621/66497670-ab70a100-ea71-11e9-8d2e-72772f6e1925.png)
![image](https://user-images.githubusercontent.com/33435621/66497678-ae6b9180-ea71-11e9-9a16-aa8c7b5385ed.png)
