### ISSUE TITLE
As an Oka-Wen NF POC I would like to implement final changes to MAPS so that the site is fully updated prior to launch

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#941]
## Notes
* What are things we should consider when making this story *

New Maps are saved in Pinyon here https://usfs.box.com/s/8sdqnqmt5xn9jgzidc8f3anivy1tmfcx

## Acceptance Criteria
- [x] The new maps are shown on the Open Forest site
- [x] A link is associated with each map so that a user can view a larger image and download it to device.

## East Cle Elum Christmas tree cutting area 
- [x] Add Map 
[XmasTreeCutting2015_East-CleElum.pdf](https://github.com/USDAForestService/fs-open-forest-platform/files/3704659/XmasTreeCutting2015_East-CleElum.pdf)
- [x] Add Alt Text: "Christmas tree cutting areas are shown as green shaded areas. No cutting areas are illustrated with crosshatch marks. Recreation sites, main roads, and main water bodies are also illustrated on the map. Map scale is 1in=2mi,"

## North Cle Elum Christmas tree cutting area
- [x] Add Map [XmasTreeCutting2015_North-CleElum.pdf](https://github.com/USDAForestService/fs-open-forest-platform/files/3704624/XmasTreeCutting2015_North-CleElum.pdf)
- [x] Add Alt Text: "Christmas tree cutting areas are shown as green shaded areas. No cutting areas are illustrated with crosshatch marks. Recreation sites, main roads, and main water bodies are also illustrated on the map. Map scale is 1in=2mi,"

## South Cle Elum Christmas tree cutting area
- [x] Add Map: 
[XmasTreeCutting2015_south-Cleelum.pdf](https://github.com/USDAForestService/fs-open-forest-platform/files/3704633/XmasTreeCutting2015_south-Cleelum.pdf)
- [x] Add Alt Text: "Christmas tree cutting areas are shown as green shaded areas. No cutting areas are illustrated with crosshatch marks. Recreation sites, main roads, and main water bodies are also illustrated on the map. Map scale is 1in=2mi,"

## West Cle Elum Christmas tree cutting area
- [x] Add Map
[XmasTreeCutting2015_West-CleElum.pdf](https://github.com/USDAForestService/fs-open-forest-platform/files/3704635/XmasTreeCutting2015_West-CleElum.pdf)
- [x] Add Alt Text: "Christmas tree cutting areas are shown as green shaded areas. No cutting areas are illustrated with crosshatch marks. Recreation sites, main roads, and main water bodies are also illustrated on the map. Map scale is 1in=2mi,"

## Chelan Christmas tree cutting area
- [x] Add Map 
[XmasTreeCuttingMapChelanRD_2019_Eng&Span.pdf](https://github.com/USDAForestService/fs-open-forest-platform/files/3704639/XmasTreeCuttingMapChelanRD_2019_Eng.Span.pdf)
- [x] Add Alt Text:  "Christmas tree cutting areas are shown as green shaded areas. Recreation sites, towns, main roads, and main water bodies are also illustrated on the map."

## Entiat Christmas tree cutting area
- [x] Add Map: 
[XmasTreeCuttingMapEntiatRD_2019_Eng&Span.pdf](https://github.com/USDAForestService/fs-open-forest-platform/files/3704646/XmasTreeCuttingMapEntiatRD_2019_Eng.Span.pdf)
- [x] Add Alt Text:  "Christmas tree cutting areas are shown as green shaded areas. Recreation sites, towns, main roads, and main water bodies are also illustrated on the map."

## Leavenworth Christmas tree cutting area
- [x] Add Map 
[XmasTreeCuttingMapLeavenworthArea_2019_Eng&Span.pdf](https://github.com/USDAForestService/fs-open-forest-platform/files/3704650/XmasTreeCuttingMapLeavenworthArea_2019_Eng.Span.pdf)
- [x] Add Alt Text:  "Christmas tree cutting areas are shown as green shaded areas. Recreation sites, towns, main roads, and main water bodies are also illustrated on the map."

## Wenatchee Christmas tree cutting area
- [x] Add Map 
[XmasTreeCuttingMapWenatcheeArea_2019_Eng&Span.pdf](https://github.com/USDAForestService/fs-open-forest-platform/files/3704652/XmasTreeCuttingMapWenatcheeArea_2019_Eng.Span.pdf)
- [x] Add Alt Text: "Christmas tree cutting areas are shown as green shaded areas. Recreation sites, towns, main roads, and main water bodies are also illustrated on the map."

## Tasks
- [x] Remove all existing maps
- [x] Add new maps and new alt text
- [x] PO approved

## Definition of Done
- [x] Pull requests meet technical definition of done
- [x] Compare finished design with mockup

**Comment by ASprinkle** [comment]
@mtlaney It looks like this is in Awaiting acceptance, but when I go in to review the updates on Staging, It doesn't look like anything has changed yet. All I see are the same 3 maps. Do you see anything different on staging? 
![image](https://user-images.githubusercontent.com/33435621/66684219-65ad0780-ec2e-11e9-85bd-fa6fc072d88c.png)

**Comment by mtlaney** [comment]
hmmm, that's wierd I'm seeing the same thing. I'm going to try to re-run the deployment

**Comment by mtlaney** [comment]
@ASprinkle Should be correctly displaying the maps now

**Comment by ASprinkle** [comment]
![image](https://user-images.githubusercontent.com/33435621/66846473-bd958800-ef26-11e9-9294-d6219348251c.png)
![image](https://user-images.githubusercontent.com/33435621/66846483-c0907880-ef26-11e9-8305-e1cf81475af2.png)
![image](https://user-images.githubusercontent.com/33435621/66846511-c8501d00-ef26-11e9-885d-94a68301ef1a.png)

![image](https://user-images.githubusercontent.com/33435621/66846501-c5552c80-ef26-11e9-9ac9-a16a65667568.png)
