### ISSUE TITLE
As a researcher, I need to review Icebox stories, so that I can identify any design opportunities for in particular MBS.

### ISSUE THREAD

**Issue by lisamcmichael** [USDAForestService/fs-open-forest-platform#945]
## Notes
*Now that MVP Pilot 2019 is mostly complete, the team is ready to identify and prioritize Open Forest enhancements for the upcoming 2020 season.*

## Acceptance Criteria
- [x] Created task list from Icebox stories

## Tasks
- [x] Review Icebox
- [x] Create initial raw list w/ notes; add comments to stories (if relevant)
- [x] Identify any design opportunities
- [x] Create task list
- [x] Review task list with PO 
- [x] Create any new stories if needed
- [x] Update existing stories with new status

## Definition of Done
- [x] New stories created
- [x] Existing stories assigned to an updated status

**Comment by lisamcmichael** [comment]
**Base list of all icebox stories with crib notes** 

ADMIN MANAGEMENT STORIES
	• 659 - "request change content" -  now TBD on new Admin Tool
	• 904 -  "free use products, to get other permits" (need clarification)
	• 678 - "admin workflow" - (ask Amber, still relevant?)
	• 618 - "manage multiple admins" (ask Amber, still relevant?)
	• 259 - "message should be sent to support team about submit-to-subs error" - when apps are not submitted
	• 061 - "MBS, informed of NRM shut downs" 
	• 748 - "Reporting" - validate that reporting info is useful to Forest admins


CUSTOMER/USER STORIES
	• 835 - "add Sno-park logo" (XMAS)
	• 563 - "calendar selector" - usability findings suggest selector is easier to use
	• 467 - "PII consent checkbox"  
	• 371 - "Apply now button, Navigation confusing" Login.gov
	• 530 - "application completion time" content - seems ready to go back into development
	• 670 - "bug/issue user feedback" - Lisa S. created a link in the footer "For help or feedback…" - will that resolve this story?
	• 393 - "purchase 2 or more permits" - it's not clear if the goal is a "multi-item selector" or something else
	• 348 - "temp outfitters+ guides need cost estimates" 
	• 532 - "save my live application" - users want to come back and finish it later - needs "PII" decision 
	• 261 - "communicate file upload status to applicants" - Confirmation message or an Error message needed
	• 566 - "MBS form, add required fields" 
	• 531 - "MBS applicants need upfront info about the app process" - wireframe + design completed; A/B testing, new story created #565, referenced #627 and #530. Comment from PO about usability testing/July 3 - was ready for dev
	• 400 - "issue entering name and email into permit application" - unclear what is the issue (see scale up RFP)
	• 399 - "notification of permit approval" - not clear if this is an email notification or SMS
	• 534 - "applicant's receive what's next info - initial designs attempt to resolve insufficient details; this story has more than one issue w/in it; see 538
	• 354 - "link facility rental permitting to Open Forest permitting" - unclear if this is feasible
	• 620 - see below under engineering- potential UI design for how message displays
	• 395 - "EPIC about usability concerns" - not one specific story except for reference to #563 (calendar selector)


ENGINEERNG
	• 280 - "obtain non-comm / temp outfitter permit" - an engineering task 
	• 406 - "past due apps are showing on the expired permit applications page" - design started for MBS, appears to be a "bug"
	• 551 - "issue accessing staging" - bug noted by Eric / Mike
	• 152 - "SUDS" issue
	• 559 - "log in issue for developers"
	• 344 - "file format refactoring"
	• 620 - "form field errors" - if user enters info incorrectly, or skips over, platform alerts h/her
	• 679 - "SUDS" issue
	• 411 - "SUDS" issue
	• 820 - "test alt text" Dev story 
	• 768 - "Chrome" dev story

NOT A DESIGN MATTER - 888 - "discovery research plan 2020"

**Comment by lisamcmichael** [comment]
**Base list is organized to indicate stories with UX design.**
On Box now: https://usfs.box.com/s/pyvoabpw06lc3b39vj2g391mc8rsvukb

**Comment by lisamcmichael** [comment]
I've organized the stories a bit more, so we can see how they may relate to each other. @ASprinkle they're ready for review. And, I moved our meeting to 730 a.m. PT.

On Box now: https://usfs.box.com/s/pyvoabpw06lc3b39vj2g391mc8rsvukb

**Comment by lisamcmichael** [comment]
@ASprinkle  and @lisaredux  The updated Icebox story statuses are now on Box. Amber, we have one more meeting to review the remaining stories and add actions/decisions. I am free most of today and tomorrow. 

The list of stories is on Pinyon: https://usfs.box.com/s/pyvoabpw06lc3b39vj2g391mc8rsvukb

**Comment by lisamcmichael** [comment]
@carlsonem,  I met with Amber, and we need one more meeting to finish reviewing all Icebox stories. Also, we identified 2 new stories, put in the icebox for now.

**Comment by lisamcmichael** [comment]
@carlsonem  Amber is out today, so we cannot have the final meeting to close this story. I'm moving it to blocked until next Thursday when we are meeting.

**Comment by lisamcmichael** [comment]
I've updated a 'master list' of Icebox Stories with actions and next steps, @ASprinkle and @lisaredux. 
https://usfs.app.box.com/file/537998513989

**Comment by ASprinkle** [comment]
Hey @lisamcmichael I am going to move this to Done... so that I can capture it as an item in my summary next week
