### ISSUE TITLE
As a researcher, I need to review previous research and work on Special Use permitting, so I am acquainted with that work.

### ISSUE THREAD

**Issue by lisamcmichael** [USDAForestService/fs-open-forest-platform#948]
## Notes
The team is ready to identify and prioritize Open Forest enhancements for the upcoming 2020 season starting with MBS.

## Acceptance Criteria
- [ ] Created list of notes to review with Lisa S. and PO

## Tasks
- [x] Review past work and research findings
- [x] Create notes or spike stories
- [x] Identify any design opportunities 

## Definition of Done
- [ ] Outline of next steps

**Comment by lisamcmichael** [comment]
@carlsonem I've been reviewing previous research and discovery on special permits on Pinyon. You mentioned specific user stories to me, what are those? Thx!
