### ISSUE TITLE
As an RRS admin, I'd like to see the correct season start date.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#950]
## Notes
* What are things we should consider when making this story *

 The RRS Start Date should be November 8, 2019.  
The Season Dates document in pinyon had an error, and showed Nov. 9, which is incorrect - per the RRS POC.

## Acceptance Criteria
- [x] The start date is Nov. 8, 2019.

## Tasks
- [x] Update the start date to November 8, 2019
- [x] PO approved

## Definition of Done
- [x] Pull requests meet technical definition of done
- [x] Compare finished design with mockup
- [ ] Usability tested

**Comment by aaronburk** [comment]
What is an RRS?

**Comment by ASprinkle** [comment]
![image](https://user-images.githubusercontent.com/33435621/66664946-616af500-ec02-11e9-8bee-e1b067584d61.png)
Looks Great!

**Comment by ASprinkle** [comment]
> What is an RRS? Aha Rogue River Siskiyou!

@aaronburk Rogue River-Siskiyou (RRS) National Forest.
