### ISSUE TITLE
As an Admin for the ARP I would like to see some final changes so that the site is updated for this season.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#954]
## Notes
* What are things we should consider when making this story *
Final POC reviews resulted in the following needs for change:

The POC also requested to remove the "When to cut your tree" title above the Season Dates green box.
I do not know if we can do this.
I shared with the POC that "For awareness and transparency, this may seem like a simple ask, however we may not be able to remove this based on the current design for consistency, menu options, and overall structure of the pages. We may need to replace this with some other text. Or it may need to remain the way it is for this pilot year – with any changes to this feature implemented next season. I will check in with our development and design team to see what our options may be here."

## Acceptance Criteria
- [x] The tasks are completed, and the cutting area dates are updated.

## Tasks
- [x] Elk Creek special cutting area Cutting Dates: "Dec 1, 2019 – Dec 8, 2019 from 9:00 AM – 4:00 PM. The last car will be allowed in at 2:00 PM"
- [x] Red Feather special cutting area Cutting Dates: "Dec 7, 2019 – Dec 15, 2019 from 8:30 AM and 2:30 PM. For safety reasons, leave the area by 4:00 PM"
- [x] The paragraph following the Canyon Lakes Ranger District contact information should read:
"Permits are available for purchase in person at the Canyon Lakes office Nov. 25 - Dec. 13, 2019. The office is closed on Wednesdays. Permits for the Red Feather cutting area are also available on-site the first two weekends in December."
- [x] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by mtlaney** [comment]
@ASprinkle with the following example, where do they want me to add 'the last car will be allowed in at 2:00 PM"?

<img width="692" alt="Screen Shot 2019-10-16 at 11 47 31 AM" src="https://user-images.githubusercontent.com/18233188/66935883-ca8ba780-f00a-11e9-9748-d7664e70ff1b.png">


Elk Creek special cutting area Cutting Dates: "Dec 1, 2019 – Dec 8, 2019 from 9:00 AM – 4:00 PM. The last car will be allowed in at 2:00 PM"

**Comment by mtlaney** [comment]
@ASprinkle 

I think I have this done correctly. I've updated the cutting area dates, and changed the text in cutting area rules and the contact us section. 

The first request I did not complete since it's part of the core template of the forest pages, the removing 'When to cut your tree'. It 'can' be done, but the level of effort is higher than the reward possibly. Let me know if you'd like me to move forward with it.

**Comment by ASprinkle** [comment]
> @ASprinkle
> 
> I think I have this done correctly. I've updated the cutting area dates, and changed the text in cutting area rules and the contact us section.
> 
> The first request I did not complete since it's part of the core template of the forest pages, the removing 'When to cut your tree'. It 'can' be done, but the level of effort is higher than the reward possibly. Let me know if you'd like me to move forward with it.

@mtlaney Thank you for working on those updates for cutting areas.  At this time please do not work on editing the "When to cut your tree' title. I think we'll have to address this after this pilot is over. Thanks for the background/info on this.

**Comment by mtlaney** [comment]
@ASprinkle 
<img width="919" alt="Screen Shot 2019-10-16 at 2 01 26 PM" src="https://user-images.githubusercontent.com/18233188/66945710-8229b500-f01d-11e9-8a4a-e070ff239093.png">

**Comment by ASprinkle** [comment]
Let's go with it!  For the empty cell - maybe we should add "no notes" or something so people know they aren't missing something

**Comment by ASprinkle** [comment]
This looks really great, thank you for your work on this @mtlaney! 
![image](https://user-images.githubusercontent.com/33435621/66960329-1a756900-f021-11e9-8b44-a6659c324d6c.png)
![image](https://user-images.githubusercontent.com/33435621/66960336-1d705980-f021-11e9-80ff-a4297acc1a30.png)

**Comment by ASprinkle** [comment]
@mtlaney I created story #979  it looks like the cutting area times are off by 2 hours in the system in PROD.
