### ISSUE TITLE
As a researcher, I need to discuss special permit usability test findings with Lisa S., so that we can identify new design opportunities.

### ISSUE THREAD

**Issue by lisamcmichael** [USDAForestService/fs-open-forest-platform#965]
## Notes
Two usability studies were conducted in June 2019 to evaluate content flow strategies and designs. It's not clear if all of the refinements/recommendations have been included in the MBS Special Permits site.

## Acceptance Criteria
- [x] Lisa S. reviewed research with Lisa M.

## Tasks
- [x] Review 2 "content flow strategy studies" June 2019
- [x] Create list of design opportunities
- [x] Review list with PO
- [x] Mock-up designs if needed
- [x] Determine if usability research is needed

## Definition of Done
- [x] identified design opportunities

**Comment by lisamcmichael** [comment]
I found a series of **prototype user stories** on Pinyon (June 2019). Some of those stories have been implemented in the Special Permit MBS pilot, but some have not:
https://usfs.app.box.com/file/480467318419

**Comment by lisamcmichael** [comment]
@lisaredux I'll find some time on our calendars for early next week to chat about this.
