### ISSUE TITLE
As a Special Permit applicant, I want to return to the MBS homepage, so that I do not have to use the browser back button. 

### ISSUE THREAD

**Issue by lisamcmichael** [USDAForestService/fs-open-forest-platform#966]
## Notes

If an applicant “abandons” the application process, or if they have finished checking the status of the application, they cannot return to the MBS homepage without using the browser back button.

## Acceptance Criteria
- [ ] Users are able to access previous pages from their current page anywhere in the SU application process without having to use their browser back button.

## Tasks
- [] Mock-up: Add return link to MBS special permits homepage (see both screenshots below)
- [] Mock-up: Revise link language:  Visit Mt. Baker-Snoqualmie Open Forest homepage
NEW: 
- [x] Mock up Learn More Page breadcrumb (for both non-comm and temp OG): Mt. Baker-Snoqualmie special use permits / Learn more 
- [x] Mock up the edit to the Help Me Find a Permit page breadcrumb: Mt. Baker-Snoqualmie special use permits / Help me find a permit 
- [x] Mock up Temporary Outfitting and Guiding application page breadcrumb: Mt. Baker-Snoqualmie special use permits / Application
- [x] Mock up Non-commercial group use application page breadcrumb: Mt. Baker-Snoqualmie special use permits / Application
- [x] Mock up View Applications page breadcrumb: Mt. Baker-Snoqualmie special use permits / View applications
- [x] Mock up Application Details page breadcrumb: Mt. Baker-Snoqualmie special use permits / View Applications / Application details
- [x] Hand off with Dev.
- [x] Build the breadcrumbs the MBS homepage that have been mocked up.
- [x] PO approved

## Definition of Done
- [x] Compare finished design with mockup
- [ ] UX tested

![966](https://user-images.githubusercontent.com/52501060/66930113-1e45c300-f002-11e9-864f-50bb0c26f80d.JPG)

![Permit status](https://user-images.githubusercontent.com/52501060/67595980-bdbb3200-f735-11e9-96eb-a4c2c29681b8.JPG)

**Comment by lisamcmichael** [comment]
@ASprinkle >  **New story created**

**Comment by ASprinkle** [comment]
@lisaredux  we will also want a way to get back to the home page from the page where the applicant can view the details of their previously submitted application.
![image](https://user-images.githubusercontent.com/33435621/68802234-66accc80-0612-11ea-9c0a-13c47bfa60a2.png)

**Comment by lisaredux** [comment]
@ASprinkle here are some updates:

on previously submitted application page... "return to home"

 ![966-home-button-inprocess](https://user-images.githubusercontent.com/26801590/68979370-568c1d00-07cb-11ea-9266-bf6da080280f.png)

and on the feedback page:

"return to previous page" because we won't know where they came from exactly, and previous page seems more catch-all than saying _return home_

<img width="742" alt="Screenshot 2019-11-15 17 08 00" src="https://user-images.githubusercontent.com/26801590/68979403-74f21880-07cb-11ea-8cf3-5dd00444ce82.png">

Let me know your thoughts. I'll keep working on the other pages.

**Comment by ASprinkle** [comment]
@lisaredux I think that "return to previous page" option for the feedback tool is great! Do we know if that is something that dev can do?

For the "non profits r us" screen shot. Where would "Return to home" take the customer who logged in to view the details of their application? I think we would want them to easily "Return to view applications", here:  
![image](https://user-images.githubusercontent.com/33435621/68980201-9dbae380-07b4-11ea-9db2-648107710979.png)

Or we could offer a breadcrumb trail at the top of the page, that would show the Mt. Baker-Snoqualmie Permits > View Applications > Application details

On the customer's "View applications" page, we could do the same bread crumb at the top: Mt. Baker-Snoqualmie Permits > View Applications
![image](https://user-images.githubusercontent.com/33435621/68980271-dd81cb00-07b4-11ea-952f-b603f9ee93c5.png)

**Comment by lisaredux** [comment]
@ASprinkle Here's the update: 

1- Mock up Learn More Page breadcrumb (for both non-comm and temp OG): 
_Mt. Baker-Snoqualmie special use permits / Learn more_
https://open-forest-staging.app.cloud.gov/mbs/applications/noncommercial-group-use/learn-more
https://open-forest-staging.app.cloud.gov/mbs/applications/temp-outfitters/learn-more

<img width="1153" alt="Screenshot 2019-11-19 10 55 08" src="https://user-images.githubusercontent.com/26801590/69185268-73cf2d00-0ae4-11ea-8a68-c90292f1946e.png">

<img width="1133" alt="Screenshot 2019-11-19 10 56 14" src="https://user-images.githubusercontent.com/26801590/69185278-7af63b00-0ae4-11ea-8439-72ac77aed7c7.png">


2- Mock up the edit to the Help Me Find a Permit page breadcrumb: 
_Mt. Baker-Snoqualmie special use permits / Help me find a permit_
https://open-forest-staging.app.cloud.gov/mbs/help-me-pick/1

<img width="1080" alt="Screenshot 2019-11-19 11 18 06" src="https://user-images.githubusercontent.com/26801590/69186088-dd037000-0ae5-11ea-9475-930779965d8c.png">


3- Mock up Temporary Outfitting and Guiding application page breadcrumb: 
_Mt. Baker-Snoqualmie special use permits / Application_
https://open-forest-staging.app.cloud.gov/mbs/applications/temp-outfitters/new

<img width="1198" alt="Screenshot 2019-11-19 13 42 24" src="https://user-images.githubusercontent.com/26801590/69186229-25bb2900-0ae6-11ea-9558-c179f78419ee.png">


4- Mock up Non-commercial group use application page breadcrumb: 
_Mt. Baker-Snoqualmie special use permits / Application_
https://open-forest-staging.app.cloud.gov/mbs/applications/noncommercial-group-use/new

<img width="1064" alt="Screenshot 2019-11-19 13 38 56" src="https://user-images.githubusercontent.com/26801590/69186486-95c9af00-0ae6-11ea-991b-227a7899d341.png">


5- Mock up View Applications page breadcrumb: 
_Mt. Baker-Snoqualmie special use permits / View applications_
https://open-forest-staging.app.cloud.gov/user/applications
(I have an alternate text-align to the left for this one, but it looks weird)

<img width="1156" alt="Screenshot 2019-11-19 11 39 29" src="https://user-images.githubusercontent.com/26801590/69186572-b72a9b00-0ae6-11ea-8292-166924b5953b.png">




6- Mock up Application Details page breadcrumb: 
_Mt. Baker-Snoqualmie special use permits / View Applications / Application details_
![68802263-75937f00-0612-11ea-8a99-a9b2ed239589](https://user-images.githubusercontent.com/26801590/69186651-eb9e5700-0ae6-11ea-8b5d-720cf2a85efb.png)

7- Redesign the Return Home option on the Give Feedback page
https://open-forest-staging.app.cloud.gov/feedback

<img width="742" alt="68979403-74f21880-07cb-11ea-8cf3-5dd00444ce82" src="https://user-images.githubusercontent.com/26801590/69186942-8bf47b80-0ae7-11ea-980c-3f42d9a191f4.png">

**Comment by ASprinkle** [comment]
@lisaredux  those mock ups look great! thanks!! this is ready for dev now.

**Comment by ASprinkle** [comment]
@ASprinkle  will create a separate story to capture the tasks related to the Return Home/Previous Page function on the feedback screen.

**Comment by ASprinkle** [comment]
@mtlaney I have some comments related to my review of this story. It looks like there are some places where the breadcrumb is missing...

**Comment by ASprinkle** [comment]
Thanks @mtlaney the breadcrumbs look good. Great work navigating the admin and user view applications pages!
![image](https://user-images.githubusercontent.com/33435621/70251877-377f0c00-1735-11ea-9677-fb0c424aff51.png)
