### ISSUE TITLE
As a Special Permit applicant viewing the status of my pending permit, I want to return to the MBS homepage without using the browser back button, so that my experience is efficient.

### ISSUE THREAD

**Issue by lisamcmichael** [USDAForestService/fs-open-forest-platform#967]
## Notes
* If an applicant has viewed her Application Status (on that page), there isn’t an efficient way to return to the MBS homepage, only the browser back button is available.*

## Acceptance Criteria
- [ ] Design updates are completed.
- [ ] Link to homepage works (tested)

## Tasks
- [ ] Mock-up: Add a return link to MBS special permits homepage
- [ ] Mock-up: Revise link language to:  Visit Mt. Baker-Snoqualmie Open Forest homepage
- [ ] Engineer the link to the MBS homepage
- [ ] PO approved

## Definition of Done
- [ ] Compare finished design with mock-up
- [ ] Usability tested

![967](https://user-images.githubusercontent.com/52501060/66929883-c73fee00-f001-11e9-8b1a-d5adca0610a6.JPG)

**Comment by lisamcmichael** [comment]
@ASprinkle Added new story.
