### ISSUE TITLE
As an Open Forest admin, I don't want to be confused by a google form when trying to contact the OF team so that I know I am in the right place.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#978]
## Notes
* What are things we should consider when making this story *

We removed the "Request a Content Change Tab" in story #927 but we still have some "request access" links on the admin-only pages that take the user to the google form.

We need to replace the request access link, with the shared customer support email address.

## Acceptance Criteria
- [x] The google form is no longer accessible
- [x] Admins know where to go if they have questions.

## Tasks
- [x] Mock design for new language/email
- [x] On the Generate Reports page, replace "please request access" with "please email SM.FS.OpnFrstCsSup@usda.gov"
- [x] On the Change Season Dates page, replace "please request access" with "please email SM.FS.OpnFrstCsSup@usda.gov"
- [x] On the Change Cutting Area Dates page, replace "please submit a request" with "please email SM.FS.OpnFrstCsSup@usda.gov"
- [x] On the Change Cutting Area Dates page, remove all of the following text: "To update , remove, or create a new area please submit a request"
- [x] PO approved

## Definition of Done
- [x] Pull requests meet technical definition of done
- [x] Compare finished design with mockup

**Comment by lisaredux** [comment]
@ASprinkle The update is implemented into the design for your approval to move forward: 

On the Generate Reports page —

<img width="504" alt="Screenshot 2019-10-22 11 30 34" src="https://user-images.githubusercontent.com/26801590/67304957-9dd00800-f4c2-11e9-8c02-7fdc83883de0.png">

On the Change Season Dates page —

<img width="564" alt="Screenshot 2019-10-22 11 36 41" src="https://user-images.githubusercontent.com/26801590/67304977-a9233380-f4c2-11e9-8083-36b3368f3585.png">

On the Change Cutting Area Dates page —

<img width="655" alt="Screenshot 2019-10-22 11 50 59" src="https://user-images.githubusercontent.com/26801590/67305068-cbb54c80-f4c2-11e9-8c40-11afdb806cd4.png">

**Comment by ASprinkle** [comment]
Thank you @lisaredux .  that looks good!

**Comment by ASprinkle** [comment]
@mtlaney I updated the tasks. It looks like there was another text piece in the change cutting area dates section. I missed that on the initial review...

![image](https://user-images.githubusercontent.com/33435621/67803222-d1261000-fa49-11e9-9c05-1e0ce4d3f36f.png)

**Comment by mtlaney** [comment]
@ASprinkle Should be good to test again
