### ISSUE TITLE
As an ARP administrator, I would like to see the Cutting Area Times accurately reflected in PROD before Nov. 1

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#979]
## Notes
* What are things we should consider when making this story *

The ARP Cutting Area Times are not correctly shown. they appear to be 2 hours off, showing:
Elk Creek 6:00 AM - 1:00 PM
Red Feather 5:30 AM - 11:30 AM

One of the ARP Admins went in and used the Admin Change Cutting Area Dates feature to manually update the times.  The Admin did this on Friday, and today, Monday, the times have reverted back.

This is what PROD is currently showing 10/21:
![image](https://user-images.githubusercontent.com/33435621/67217394-82d59900-f3d9-11e9-8768-b038e2fbe1b9.png)

On Friday 10/18 an ARP admin went in and updated the times.  The times are no
![image](https://user-images.githubusercontent.com/33435621/67217448-97b22c80-f3d9-11e9-8a9a-1dc2f9ab086b.png)

## Acceptance Criteria
- [x] The times are accurately shown on staging
- [x] The times are accurately shown on Prod.
- [x] We have an understanding (documented in the comments below) of why the ARP admin's manual change did not stay reflected on the page.

## Tasks
- [x] Update ARP Cutting Area Times for Elk Creek to show 9:00 AM - 4:00 PM
- [x] Update ARP Cutting Area Times for Red Feather 8:30 AM - 2:30 PM
- [x] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done

**Comment by ASprinkle** [comment]
@mtlaney @briandavidson Perhaps this was a bug in the recent push to Prod. The ARP opens on Nov. 1. Can we get this issue fixed and pushed to prod right away?

**Comment by briandavidson** [comment]
> @mtlaney @briandavidson Perhaps this was a bug in the recent push to Prod. The ARP opens on Nov. 1. Can we get this issue fixed and pushed to prod right away?

@ASprinkle I'll make sure this gets fixed by immediately and coordinate with @mtlaney to see it gets through to prod.

**Comment by mtlaney** [comment]
@ASprinkle this one is now complete. After we push to prod I will have to change the season dates there as well. I have turned off the seeder to prevent reverting dates now that we have all dates complete.

**Comment by ASprinkle** [comment]
@mtlaney it looks like Red Feather is still updating on staging? 
![image](https://user-images.githubusercontent.com/33435621/67315329-35315d00-f4bb-11e9-8ae0-27ee4cf681ea.png)

**Comment by mtlaney** [comment]
@ASprinkle here's what I'm showing on staging 
@briandavidson can you check your staging site?

<img width="1104" alt="Screen Shot 2019-10-22 at 2 04 11 PM" src="https://user-images.githubusercontent.com/18233188/67315641-fad4b980-f4d4-11e9-8b08-a18c5cfcf2b6.png">

**Comment by briandavidson** [comment]
![image](https://user-images.githubusercontent.com/5187168/67316859-340e2900-f4d7-11e9-96ac-334699691ed8.png)

**Comment by ASprinkle** [comment]
Wow, this is odd. I am still seeing the 5:30-11:30 time frame for Red Feather....

**Comment by ASprinkle** [comment]
[ARP RE_ Confirming Open Forest site content 10292019.pdf](https://github.com/USDAForestService/fs-open-forest-platform/files/3784780/ARP.RE_.Confirming.Open.Forest.site.content.10292019.pdf)

**Comment by ASprinkle** [comment]
When we updated Prod today, I had to log into PROD as an Admin and update the ARP cutting area times again.. @mtlaney
