### ISSUE TITLE
As an OF Admin, I would like to see season dates consistently displayed in the Change Season Dates section so that I am not confused.

### ISSUE THREAD

**Issue by Rebekah-Hernandez** [USDAForestService/fs-open-forest-platform#980]
## Notes
Inside of the staging platform, when changing the season dates, the end date will automatically add an extra day to whatever the input is. For example, if the input end date is 12/31/2019, upon saving and refreshing, the date will now show as being 01/01/2020. As exhibited in screenshots of Arapaho-Roosevelt: 

![Arapaho_Roosevelt_before.PNG](https://images.zenhubusercontent.com/5d93a772c8e4d80001227a95/9af44741-c281-4165-923c-b70e594e45da)

Then this happens once "Update season dates" has been submitted and the page has been refreshed:

![Arapaho_Roosevelt_after.PNG](https://images.zenhubusercontent.com/5d93a772c8e4d80001227a95/1e12e092-7add-4a48-9288-7f7ab2c9c445)

## Acceptance Criteria
- [x] All forests have the correct end date listed
- [x] Text about midnight is removed

## Tasks
- [x] Update code so that dates show consisntely
- [x] Remove text "The time on the season start date and end date will be set to midnight."
- [x] PO approved

## Definition of Done
- [x] Pull requests meet technical definition of done
- [] Compare finished design with mockup
- [x] Usability tested

**Comment by ASprinkle** [comment]
@briandavidson Let's meet up and talk about this one.

When I tested this for the Shoshone NF. I set the season date for Jan 29 through Jan 30. Then, when I went to Change Season dates, it showed me Jan 28 and Jan 29 as the preset for  me to change.  It does not look like the season dates are consistently being populated.
![image](https://user-images.githubusercontent.com/33435621/73385794-9fa82500-4282-11ea-8aac-210ceaebc049.png)
![image](https://user-images.githubusercontent.com/33435621/73385803-a46cd900-4282-11ea-9753-0341530a517b.png)

I also noticed some text that I hadn't noticed before: "the tie on the season start date and end date will be set to midnight." 
![image](https://user-images.githubusercontent.com/33435621/73385814-aafb5080-4282-11ea-8ef3-abdb1cc73c47.png)
this isn't necessarily what we want to share, given that the season start date would not be midnight, it would be 12:01 AM of the start date, and 12:59 PM of the end date.
For example season start would be 12:01 AM Jan 29  and season end would be 12:59 PM Jan 30.  If it was set to mid night, then, Season start would be Midnight Jan 29...meaning  the buy permit button wouldn't be available until the end of Jan 29, which is not what we want.

**Comment by ASprinkle** [comment]
In testing this some more, I determined, that the update is working correctly for all forests except the Arapaho and Roosevelt, Flathead, and Shoshone.

**Comment by ASprinkle** [comment]
@briandavidson  let's confirm that the tests that you did in staging with Dylan and Rebekah included the ARP, FLT, and SHO forests.  If so, let's move this to awaiting acceptance.

**Comment by ASprinkle** [comment]
It looks like this is working! I checked for ARP, FLT, SHO, MTH, and UMA.
Here is a screen shot of what I saw when reviewing the ARP, and after refreshing etc.
![image](https://user-images.githubusercontent.com/33435621/74485197-0fb3cf00-4e6f-11ea-9ece-d8eb7617b2d7.png)
![image](https://user-images.githubusercontent.com/33435621/74485205-14788300-4e6f-11ea-9f01-63911dd796e9.png)

Good Stuff!

**Comment by briandavidson** [comment]
Thank you very much for the assistance on this one @mtlaney ! You rock!

**Comment by mtlaney** [comment]
blocked by #1196
