### ISSUE TITLE
SPIKE Research 508 compliant capability for Calendar Pop-up MBS Special Uses

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#981]
## Notes
**See Story #563 and #508** 

## Acceptance Criteria
- [x] Determine if there is an existing 508 compliant calendar that the Open Forest Team can utilize

## Tasks
- [x] Research 508 calendars (Lisa M)
      - [ ] Create short-list of 2 options to start with for Brian/Mike to consider
      - [ ] Meet with Developers to decide next steps: more research to find one, use one that Lisa provided, or modify one.
- [x] Document findings.
- [] Mock-up calendar if we can make one
- [x] PO approved

## Definition of Done
- [x] Tasks are completed, and A/C is informed.

**Comment by lisamcmichael** [comment]
@ASprinkle I wonder if this one could be closed because Story 563 includes the "508 accessibility" requirement?

**Comment by ASprinkle** [comment]
@lisamcmichael The result of this story research spike would inform the tasks and the A/C for #563.  Currently, #563 is blocked by this story.

**Comment by lisamcmichael** [comment]
@briandavidson @mtlaney @smahmudFS , FYI:

- Deque University’s Date Picker (referenced by W3C.org)
https://www.w3.org/blog/wai-components-gallery/widget/datepicker/

https://dequeuniversity.com/library/aria/date-pickers/sf-date-picker

- http://eureka2.github.io/ab-datepicker/

Here are a few calendars tools which claim to be accessible, but we have not tested yet:
•	http://mootools.net/forge/p/accessible_datepicker
•	https://www.joedolson.com/my-calendar/sample-calendar/
•	http://accessibility.athena-ict.com/aria/examples/datepicker2.shtml
•	http://amsul.ca/pickadate.js/ (does not claim to be accessible, but has some accessibility tools built in like labels and extra titles that can be added).
Tools & Resources
•	Accessible Web Design Calendar
-------------
Examples of Success Criterion 2.1.2
(to avoid keyboard traps)
 
•	A calendar widget
A calendar widget allows users to add, remove or update items in their calendar using the keyboard. The controls in the widget are part of the tab order within the Web page, allowing users to tab through the controls in the widget as well as to any links or controls that follow.

**Comment by lisamcmichael** [comment]
@briandavidson and @mtlaney, take a look at the "before" video, and the then "Demo" video. Big difference in the experience. 

**Making a Better Calendar**
https://www.24a11y.com/2018/a-new-day-making-a-better-calendar/

**Comment by ASprinkle** [comment]
@lisamcmichael the .24a11y.com  link didn't seem to work for me.. maybe it worked for Mike and Brian! :)

**Comment by lisamcmichael** [comment]
@ASprinkle, I ran test of sorts and discovered that the _FS VPN is "blocking" it._  When I turned off VPN, the site loaded.  You could try the site from another computer.

**Comment by lisamcmichael** [comment]
@briandavidson @mtlaney Should I do more digging for 508-styled calendars and/or date pickers?

**Comment by lisamcmichael** [comment]
@ASprinkle there are several resources I posted for Mike and/or Brian to consider. I set this to In Progress because research has started on date pickers and/or calendars; and, I took my name off the story.

**Comment by lisamcmichael** [comment]
@mtlaney , I couldn't hear what you said on today's standup (poor audio). Let me know what you came up with. Thx!

**Comment by ASprinkle** [comment]
Primary issue with existing tools research is that We are able to find compliant calendars in the wrong language (java script not angular/type script), or we can find non-compliant calendars in the correct language.
Time to build: We can build - but would need to rewrite many lines of code (~1k) in order to add it.
https://www.w3.org/blog/wai-components-gallery/widget/datepicker/
Same as above: https://dequeuniversity.com/library/aria/date-pickers/sf-date-picker
Brief review – not in type script: http://eureka2.github.io/ab-datepicker/
976 lines of code would need to be rewritten: http://mootools.net/forge/p/accessible_datepicker
Demo only, no downloadable viewable code. Also more of an event calendar vs. date picker: https://www.joedolson.com/my-calendar/sample-calendar/
Not a 508 compliant option, and not correct language: http://amsul.ca/pickadate.js/ 
Revisit again in 3-6 months to see if options have evolved.

There is a program that can be purchased Kendo UI by Pelerik both angular/type script and 508 compliant ($$$$).
