### ISSUE TITLE
As a user I would like to understand more about how my Feedback is applied so that I can feel good about providing feedback.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#984]
## Notes
* What are things we should consider when making this story *

We have heard from a few people that when someone submits "feedback" they may expect a response from the team.  We will need to add some informational text to the feedback page so that people know that submitting feedback does not result in a response, and that if they have a question, they should contact customer support.

## Acceptance Criteria
- [x] Information on how feedback is submitted, reviewed, applied is available in an appropriate **place on the Wiki** (follow up from story #676)
- [x]  We have a design that informs users that their feedback submission will not result in a response from the team.
- [x] We have a design that informs users that if they need help, or have technical questions, they will need to contact customer support.

## Tasks
- [x] Determine informative language to add to the Feedback pages.
- [x] Mock the design
- [x] Create a Feedback Information link in the Wiki
- [x] Draft process-related information about user feedback
- [x] Review information, and approve for posting
- [x] Add the information about user feedback to the wiki
- [x] PO approved

## Definition of Done
- [x] Tasks are completed and A/C is met.

**Comment by lisamcmichael** [comment]
Hi @ASprinkle, if I recall we are using the same Feedback feature for Special Use permits. If that's right, we can tack-on the label Special Uses and let @lisaredux know. Make sense?

**Comment by ASprinkle** [comment]
If it's xmas and SU, then we can use the platform label. :)

**Comment by ASprinkle** [comment]
@Rebekah-Hernandez here is a document that I started for a brainstorm around what our feedback information on our wiki could include. it's some disorganized thoughts around the feedback tool. I think you can help with refining this a bit. https://usfs.box.com/s/c6gr6p9thei3agy4aw3ruya6xjojc1tk
@lisaredux  there might also be some ideas here on text to add to the feedback pages so that people have an understanding of what to expect.

**Comment by lisamcmichael** [comment]
@Rebekah-Hernandez @lisaredux no rush on my side, but let's grab some time to kick ideas around.

**Comment by ASprinkle** [comment]
@lisamcmichael I also started a pinyon doc with some ideas/phrases, link ^

**Comment by Rebekah-Hernandez** [comment]
@ASprinkle @lisamcmichael @lisaredux  I updated the pinyon folder linked above ^ with a rough outline of the flow and direction of the wiki page and what I thought might be the necessary information to include on the feedback link itself. Please review when you get a chance and let me know if that direction is okay and if you'd like to start flushing it out - or if there is anything else needed.

**Comment by lisamcmichael** [comment]
@Rebekah-Hernandez I've been looking at your notes, getting my thoughts together on it. I have time after standup to chat about it.

**Comment by lisamcmichael** [comment]
I'm not sure @Rebekah-Hernandez if I'm on the right track with the input I left on the pinyon doc. I'll look at the story again early next week. Cheers.

**Comment by lisamcmichael** [comment]
@Rebekah-Hernandez  Could you get us together this week for a check-in meeting? Thx!

**Comment by Rebekah-Hernandez** [comment]
@lisamcmichael we can do a check-in meeting. I'm not sure how to check schedules and see when the best time is. Is that on Outlook? 

@ASprinkle I also added a couple more notes to the pinyon doc and using the outline I had created, flushed out a bit more of what could go in the wiki. Both of you are welcome to take a look at that.

**Comment by lisamcmichael** [comment]
@Rebekah-Hernandez The "scheduling assistant" part of Outlook should show our availability.  Maybe Thr. or Friday? I'll take a look at the updates. Thx!

**Comment by lisamcmichael** [comment]
@Rebekah-Hernandez Replied to your input...see you all tomorrow!

**Comment by lisaredux** [comment]
Thanks for the meeting @Rebekah-Hernandez @ASprinkle @lisamcmichael. 
Here are the updates for review:

**FEEDBACK FORM**
https://open-forest-staging.app.cloud.gov/feedback

Modified h1-sub: _Tell us what you like about the website 
or what we can be doing better._

New hint text:  _Your feedback is anonymous. If you have questions, or would like a response, email us at SM.FS.OpnFrstCsSup@usda.gov._

![Screenshot 2019-11-22 13 34 24](https://user-images.githubusercontent.com/26801590/69451973-a53b3900-0d2e-11ea-943a-56a8293308a1.png)





**POST-FEEDBACK SECTION**
Modified usa-alert-info section: _Thank you for sharing your feedback. 
For help or technical questions, email us at SM.FS.OpnFrstCsSup@usda.gov._

![Screenshot 2019-11-22 13 40 17](https://user-images.githubusercontent.com/26801590/69452161-0c58ed80-0d2f-11ea-8b9b-0789571d44b4.png)

**Comment by ASprinkle** [comment]
@lisaredux Those mock ups looks great! thanks all for the meeting today. I consider these updates ready for Dev. I will create a separate story specific to the dev piece for updating the feedback page.

**Comment by lisaredux** [comment]
@mtlaney @briandavidson This is ready for DEV. See mockups above

**Comment by lisamcmichael** [comment]
@Rebekah-Hernandez asked if @briandavidson could jump on these soon. The feedback content on the feedback form page seems like a low lift, and can start on it. The other notification (blue banner) has a link which might require HTML; that will be a larger lift.

**Comment by ASprinkle** [comment]
@lisamcmichael @lisaredux @mtlaney @briandavidson >>>> created #1080 a separate story specific to the dev piece for updating the feedback page.  

The rest of this story has to do with writing up information and putting it on the Wiki - as described in the tasks list.

**Comment by ASprinkle** [comment]
@Rebekah-Hernandez can you help post the following information on the Wiki? I updated the Pinyon doc too (everything pasted here is highlighted yellow in the pinyon doc). We can title it Feedback Tool, and nest it under the How We Work menu option.

_At Open Forest, we are always looking for ways to improve our work. The Open Forest team developed the feedback tool so that people using the site could anonymously provide their input. It is an easy way for customers to share their experiences without expecting a direct response from the Open Forest Team but knowing that their feedback is taken into consideration. 

The feedback tool is voluntary to everyone who uses Open Forest. It is not required, but is appreciated when filled out.  Since the feedback is anonymous the team is not asking for contact information such as name and email address. People who submit feedback will not receive a response from the team after submitting your feedback.

People who have the ability to view submitted feedback include Open Forest team members, and any Forest Service staff member who has been granted administrator privileges for the site. 

If someone needs technical help or has a question they would like a response to, they should reaching out to the Open Forest Customer Support Team at: SM.FS.OpnFrstCsSup@usda.gov. The Customer Support Team is always ready to help answer questions and resolve issues experienced from the Open Forest website._

**Comment by ASprinkle** [comment]
@Rebekah-Hernandez I reviewed the write up in the Wiki at this link. I made a few edits. Can you build the menu option for Feedback Tool under How We Work, and make it live?

**Comment by ASprinkle** [comment]
Live on the Wiki https://github.com/USDAForestService/fs-open-forest/wiki/Feedback-Tool
