### ISSUE TITLE
As a non-commercial applicant, I want to see a left-side menu on the online application form like I see it on the temporary outfitters application so that I can see my progress

### ISSUE THREAD

**Issue by lisaredux** [USDAForestService/fs-open-forest-platform#986]
## Notes

Add left menu navigation to the NCGU Application Page with the following actionable menu items: "Application Process", "Applicant Information", "Event Details", and "Signature".
Make sure the menu functions with validation and errors 

Currently there is no menu and the page looks like this:
![image](https://user-images.githubusercontent.com/33435621/69367803-d0019080-0c4d-11ea-9750-a9771dce9236.png)

Meanwhile the Temporary Outfitting and Guiding Application page looks like this, with a menu:
![image](https://user-images.githubusercontent.com/33435621/69367886-f0c9e600-0c4d-11ea-8b74-6e82f1951f55.png)

## Acceptance Criteria
- [x] There is a navigation menu on the NCGU application page.
- [x] The navigation menu provides validation and error symbols as the application is completed.
- [x] The navigation menu is actionable. 

## Tasks
- [x] Create mock-up of the navigation menu  for the NCGU application Page
- [x] Research old code, and reuse it if possible
- [x] Build the NCGU application page navigation menu, with validation confirmation/errors.
- [x] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Functions on mobile
- [ ] UX team tested

**Comment by lisamcmichael** [comment]
Thx Lisa!

**Comment by ASprinkle** [comment]
@lisaredux  will update this with some images to help with describing the issue.

**Comment by lisaredux** [comment]
@ASprinkle for your review: 
<img width="1100" alt="Screenshot 2019-12-02 19 09 26" src="https://user-images.githubusercontent.com/26801590/70005599-3208a280-1538-11ea-9855-303b77ef2006.png">

**Comment by ASprinkle** [comment]
Thanks Lisa, Can we remove Application Process from the menu? It's not really a "step" even though it is a header. If we remove Application process, then it will look like your NCGU application can be completed in three easy steps.  What are your thoughts there?

Also, can you include what the check marks and error symbols should appear as for both individual and organization applicants?

**Comment by lisaredux** [comment]
@ASprinkle Three steps makes sense. I was debating it myself and removed the Application process from the sidebar in this updated design.

Unfortunately, it's too hard to show the validation in the sidebar the way I have it set up. However, all the validation is already embedded in the DEV's code so it should be foolproof moving forward.

<img width="1064" alt="Screenshot 2019-12-03 10 39 54" src="https://user-images.githubusercontent.com/26801590/70066932-7ee18d00-15bb-11ea-87b7-963e6f17d388.png">

**Comment by ASprinkle** [comment]
Thanks Lisa, this is good to go for Dev. I updated the Tasks above to specify building the menu with "validation confirmation/errors".

**Comment by ASprinkle** [comment]
@briandavidson I saw your virtual stand up update. Good call on taking liberties to fix the awkward interactions on the TOG menu.  I looked at what is on staging for the NCGU 
I was able to populate the exclamation mark error notes in the menu when trying to submit an application with incomplete information.
![image](https://user-images.githubusercontent.com/33435621/70758940-63802b80-1cf9-11ea-97d6-4273897fc4ee.png)

WHen I tested it for complete information validation, the green check mark only appears for Step 3. here's a screen shot:
![image](https://user-images.githubusercontent.com/33435621/70758997-a4784000-1cf9-11ea-8fd7-1562ae6c18ec.png)

Can we fix this so that the green check mark appears when all of the required fields for each step are completed?

**Comment by ASprinkle** [comment]
@briandavidson The menu looks great!
![image](https://user-images.githubusercontent.com/33435621/71129408-396cb480-21a4-11ea-803f-3ffbf85488b4.png)

There appears to be an odd occurance with the check mark when required fields are satisfied. It is not keeping anyone from submitting an application - so we can address the "check mark" display in another story.  This is considered PO approved and ready! thank you for your work on this! 
![image](https://user-images.githubusercontent.com/33435621/71129477-615c1800-21a4-11ea-83c5-28ed537dd5a3.png)

**Comment by briandavidson** [comment]
Hi @ASprinkle - I attached a gif of what I'm experiencing on staging currently.
![green_checkmark](https://user-images.githubusercontent.com/5187168/71131861-edca0300-21c3-11ea-868d-70c4a7321fa9.gif)

I'm not sure why we're seeing different things here. If we can pair up when you have some time I'm sure we can quickly hash out what's going on.

**Comment by ASprinkle** [comment]
@briandavidson it looks like it is working for me now! :) not sure why the issues earlier! thanks! 
![image](https://user-images.githubusercontent.com/33435621/71586421-080eb580-2acf-11ea-8f2e-e55d2d1c6caa.png)
