### ISSUE TITLE
Prep for Nov 1. As an Oka-Wen admin, I would like to updated to Id Tree Species so that the public isn't confused.

### ISSUE THREAD

**Issue by ASprinkle** [USDAForestService/fs-open-forest-platform#987]
## Notes
* What are things we should consider when making this story *

## Acceptance Criteria
- [x] The tree species section is updated so that people can be informed that some species are at higher elevations.

## Tasks
- [x]  Add a line of text to the introduction to this section that says “Noble Fir, Sub Alpine Fir and Pacific Silver Fir trees are found at higher elevations. Higher elevations typically receive snow early in the season and may not be easily accessible.”
- [x] Rearrange the order of the tree species so that Douglas-fir and Grand Fir are shown as the first two tree species options in the list.. followed by Noble, Silver, and Alpine.

- [x] PO approved

## Definition of Done
- [x] Pull requests meet technical definition of done
- [x] Compare finished design with mockup
- [x] Usability tested

**Comment by ASprinkle** [comment]
@mtlaney @briandavidson this just in.. do you think we can get this one in before Nov. 1 as well?  I was going to go in and make some of the text changes but I did not see the ID tree species section in the front end content option for the oka-wen...

**Comment by mtlaney** [comment]
@ASprinkle will do

**Comment by ASprinkle** [comment]
Looks good!
![image](https://user-images.githubusercontent.com/33435621/67621848-ada06280-f7c8-11e9-8e0b-eb9a1b7914d0.png)
![image](https://user-images.githubusercontent.com/33435621/67621849-b1cc8000-f7c8-11e9-8488-ac42ccec4640.png)
