### ISSUE TITLE
As a researcher, I want to draft a research road map so that the Product Owner can decide what features need evaluation for 2019/2020.

### ISSUE THREAD

**Issue by lisamcmichael** [USDAForestService/fs-open-forest-platform#992]
## Notes
There are proposed Special Use and Xmas tree permitting enhancements that necessitate evaluation. 

## Acceptance Criteria
- [x] PO reviewed research "roadmap"
- [x] PO added comments to "roadmap"

## Tasks
- [x] Review past research
- [x] Review stories on the platform board (icebox, backlog, new issues)
- [x] Create list of research opportunities from those stories
       - [x] Review list with PO and UX design lead
       - [x] Identify and prioritize research as a "roadmap" for MBS MVP and not MVP

## Definition of Done
- [x] Tentative research roadmap in Awaiting Acceptance

**Comment by lisamcmichael** [comment]
Met with @lisaredux to review list of research targets.

**Comment by ASprinkle** [comment]
@lisamcmichael can you please put the link here to the document that we reviewed? I went into Discover>kick off user research> where I thought we were before when reviewing it.. and I don't see it..

**Comment by lisamcmichael** [comment]
Here it is @ASprinkle 

**https://usfs.app.box.com/file/547591796267**
