### ISSUE TITLE
As a special use applicant, I want to be able to clearly read the feedback button on the authenticated side so that I know what my options are

### ISSUE THREAD

**Issue by lisaredux** [USDAForestService/fs-open-forest-platform#994]
## Notes
*The feedback button is positioned in a way that it may overlap with existing header elements for Special uses — noticeable in authentication with email address gsa.lisashenouda@gmail.com - other users mentioned that they didn't see the same issue, so it might be a bug that appears with certain email character lengths*

## Acceptance Criteria
- [ ] Able to read feedback button even when a long name is used

## Tasks
- [ ] Update the code so the feedback button remains visible when a long email is used
- [ ] Test with a long email address
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] UX team tested

![Screenshot 2019-10-28 13 42 18](https://user-images.githubusercontent.com/26801590/67702890-e5ee9f00-f988-11e9-9ad4-e7641ebb5d56.png)
![Screenshot 2019-10-28 13 43 00](https://user-images.githubusercontent.com/26801590/67702889-e5ee9f00-f988-11e9-9b4e-8d89b5be2693.png)

**Comment by lisaredux** [comment]
@ASprinkle  - I went ahead and created this issue, because upon further investigation of the CSS, it seems like the way Feedback is implemented is not compatible with the rest of the header elements

@mtlaney @briandavidson looks like the #give-feedback CSS attributes for the header need to be modified so there isn't potential overlap of text
![Screenshot 2019-10-28 14 21 35](https://user-images.githubusercontent.com/26801590/67706327-f0139c00-f98e-11e9-8433-35780706d36c.png)

**Comment by ASprinkle** [comment]
@briandavidson @lisaredux Do we know if #840 resolved this?

**Comment by lisaredux** [comment]
@ASprinkle @briandavidson This one looks resolved to me

**Comment by ASprinkle** [comment]
@lisaredux Can you include a screen shot of what you see when you log in? This way we can compare it with the previous one above.  Thanks!

**Comment by briandavidson** [comment]
This issue was created while work was still underway. Once the work was completed the problem was resolved so we can probably just close this one out.

@carlsonem / @ASprinkle

**Comment by ASprinkle** [comment]
Closing based on Lisa and Brian's comments. I also have not been able to recreate the bug,.
