### ISSUE TITLE
Platform api Dev Crashed - Troubleshoot

### ISSUE THREAD

**Issue by mwreiss** [USDAForestService/fs-open-forest-platform#996]
## Notes
The logs in cloud.gov show that open-forest-platform-api-dev has crashed.  After discussions with the team it appears api connectivity to postgresql database has been lost.

## Acceptance Criteria
- [x] Postgresql database connectivity is back in place as expected

## Tasks
- [x] Research why postgresql database isn't connecting
- [x] Resolve dependencies
- [x] Verify staging and prod will not be affected
- [x] Document resolution

## Definition of Done
- [x] Postgresql database connectivity is re-established
- [x] Eng. satisfied with resolution
- [x] Dev. satisfied with resolution
- [x] Arch. satisfied with resolution

**Comment by mwreiss** [comment]
Current logs supplied by @aqureshi :

Data' GROUP BY i.relname, ix.indexrelid, ix.indisprimary, ix.indisunique, ix.indkey ORDER BY i.relname;
2019-10-28T10:51:50.43-0400 [APP/PROC/WEB/0] OUT 2019-10-28T14:51:50.434Z info: SEQUELIZE: Executing (default): SELECT "name" FROM "SequelizeData" AS "SequelizeMeta" ORDER BY "SequelizeMeta"."name" ASC;
2019-10-28T10:51:50.46-0400 [APP/PROC/WEB/0] ERR ERROR: Unable to find migration: 02-users.js
2019-10-28T10:51:50.47-0400 [APP/PROC/WEB/0] ERR npm ERR! code ELIFECYCLE
2019-10-28T10:51:50.47-0400 [APP/PROC/WEB/0] ERR npm ERR! errno 1
2019-10-28T10:51:50.47-0400 [APP/PROC/WEB/0] ERR npm ERR! fs-open-forest-platform@0.0.1 undoAllSeed: sequelize db:seed:undo:all
2019-10-28T10:51:50.47-0400 [APP/PROC/WEB/0] ERR npm ERR! Exit status 1
2019-10-28T10:51:50.47-0400 [APP/PROC/WEB/0] ERR npm ERR!
2019-10-28T10:51:50.47-0400 [APP/PROC/WEB/0] ERR npm ERR! Failed at the fs-open-forest-platform@0.0.1 undoAllSeed script.
2019-10-28T10:51:50.47-0400 [APP/PROC/WEB/0] ERR npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2019-10-28T10:51:50.49-0400 [APP/PROC/WEB/0] ERR npm ERR! A complete log of this run can be found in:
2019-10-28T10:51:50.49-0400 [APP/PROC/WEB/0] ERR npm ERR! /home/vcap/app/.npm/_logs/2019-10-28T14_51_50_473Z-debug.log
2019-10-28T10:51:50.55-0400 [APP/PROC/WEB/0] OUT Exit status 1

**Comment by mwreiss** [comment]
Manual deployment from dev branch was successful.  Database connectivity is restored.

Abdul is seeing a 403, he’s looking into now.

**Comment by mwreiss** [comment]
After some discussion with the team we would like to see the dev environment brought into the CICD process.  Dev was originally put together as a standalone manual process by GSA.  

I will create a new issue to track those activities.

**Comment by abdul1234e** [comment]
We were still seeing 403 error which got fixed today. Dev is back online. The issue is the script had more missing modules. Updated missing modules and ran npm run dist-dev and deployed in platform-dev.

**Comment by mwreiss** [comment]
Thanks @abdul1234e !!
